<?php
ini_set('display_errors','0');error_reporting(E_ALL);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');$ROOT=__DIR__.'/..';require "$ROOT/lib/Db.php";require "$ROOT/lib/Jwt.php";require "$ROOT/lib/Http.php";require "$ROOT/lib/LineImageCompressor.php";$CONFIG=require "$ROOT/config.php";
function ll_out($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function ll_fail($m,$s=400){ll_out(['error'=>$m],$s);}
function ll_user(){global $CONFIG;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))ll_fail('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$CONFIG['jwt_secret']);if(!$p)ll_fail('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.level,r.is_admin FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?",[$p['sub']]);if(!$u||!$u['is_active'])ll_fail('کاربر نامعتبر',401);$dt=$p['dt']??'web';$sess=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$unlimited=in_array($u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);if(!$sess||$sess['revoked_at']||(!$unlimited&&$sess['device_id']!==($p['device_id']??'')))ll_fail('نشست منقضی یا باطل شده است',401);return $u;}
function ll_schema(){Db::run("CREATE TABLE IF NOT EXISTS line_location_permissions (id INT AUTO_INCREMENT PRIMARY KEY, role_id INT NOT NULL, can_capture TINYINT(1) NOT NULL DEFAULT 0, can_view TINYINT(1) NOT NULL DEFAULT 0, can_manage TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_llp_role(role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");Db::run("CREATE TABLE IF NOT EXISTS line_station_locations (id BIGINT AUTO_INCREMENT PRIMARY KEY, line_id INT NOT NULL, station_name VARCHAR(190) NULL, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, accuracy_m DECIMAL(10,2) NULL, location_photo_path VARCHAR(500) NULL, sign_photo_path VARCHAR(500) NULL, captured_by INT NOT NULL, captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_lsl_line(line_id), INDEX idx_lsl_captured(captured_by,captured_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");foreach(['latitude DECIMAL(10,7) NULL','longitude DECIMAL(10,7) NULL','location_accuracy_m DECIMAL(10,2) NULL','location_photo_path VARCHAR(500) NULL','station_sign_photo_path VARCHAR(500) NULL','station_name VARCHAR(190) NULL','location_updated_by INT NULL','location_updated_at DATETIME NULL'] as $def){$col=strtok($def,' ');$n=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='lines' AND COLUMN_NAME=?",[$col]);if(!(int)($n['c']??0))Db::run("ALTER TABLE `lines` ADD COLUMN `$col` ".substr($def,strlen($col)));}}
function ll_is_unlimited($u){return !empty($u['is_admin'])||in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);}
function ll_line_ids($u){if(ll_is_unlimited($u))return null;try{$rows=Db::all("SELECT line_id FROM user_lines WHERE user_id=?",[$u['id']]);return array_map('intval',array_column($rows,'line_id'));}catch(Throwable $e){return null;}}
function ll_app_item_allowed($u){if(ll_is_unlimited($u))return true;$row=Db::one("SELECT value FROM app_settings WHERE `key`='role_app_items'");$cfg=$row?json_decode($row['value'],true):[];$rid=(string)($u['role_id']??'');if(!is_array($cfg)||!array_key_exists($rid,$cfg))return true;if(!is_array($cfg[$rid]))return false;return in_array('LineLocation',$cfg[$rid],true);}
function ll_can($u,$what){if($what==='can_capture'||$what==='can_view')return ll_app_item_allowed($u);return false;}
function ll_store_jpeg($binary,$prefix){if(!is_string($binary)||$binary==='')return null;if(strlen($binary)>8*1024*1024)ll_fail('حجم تصویر بیش از ۸ مگابایت است');if(@getimagesizefromstring($binary)===false)ll_fail('محتوای تصویر نامعتبر است');$rel='/uploads/line-locations/'.date('Y/m').'/';$dir=__DIR__.$rel;@mkdir($dir,0775,true);$name=$prefix.'_'.bin2hex(random_bytes(8)).'.jpg';$absolute=$dir.$name;if(!LineImageCompressor::fromBinary($binary,$absolute)){@unlink($absolute);ll_fail('فشرده‌سازی تصویر JPEG روی سرور در دسترس نیست',500);}return $rel.$name;}
function ll_upload($field,$prefix){if(empty($_FILES[$field])||($_FILES[$field]['error']??1)!==UPLOAD_ERR_OK)return null;$f=$_FILES[$field];if($f['size']>8*1024*1024)ll_fail('حجم تصویر بیش از ۸ مگابایت است');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))ll_fail('فرمت تصویر مجاز نیست');return ll_store_jpeg(@file_get_contents($f['tmp_name']),$prefix);}
function ll_json($v,$prefix){if(!$v||!preg_match('#^data:image/(jpeg|png|webp);base64,#i',$v))return null;$raw=substr($v,strpos($v,',')+1);$bin=base64_decode($raw,true);if($bin===false)return null;return ll_store_jpeg($bin,$prefix);}
$u=ll_user();ll_schema();$op=$_GET['op']??$_POST['op']??'permission';
if($op==='permission')ll_out(['allowed'=>ll_can($u,'can_capture'),'can_view'=>ll_can($u,'can_view'),'can_manage'=>ll_can($u,'can_manage'),'role_id'=>(int)$u['role_id'],'max_accuracy_m'=>20]);
if($op==='lines'){if(!ll_can($u,'can_capture')&&!ll_can($u,'can_view'))ll_fail('دسترسی ثبت موقعیت خطوط ندارید',403);$ids=ll_line_ids($u);$where='';$args=[];if(is_array($ids)){if(!$ids)ll_out([]);$in=implode(',',array_fill(0,count($ids),'?'));$where=" WHERE l.id IN($in)";$args=$ids;}ll_out(Db::all("SELECT l.id,l.code,l.origin,l.destination,l.status,l.latitude,l.longitude,l.location_accuracy_m,l.station_name,l.location_photo_path,l.station_sign_photo_path,l.location_updated_at FROM `lines` l $where ORDER BY l.code",$args));}
if($op==='roles')ll_fail('این تنظیمات حذف شده است',404);
if($op==='save-role')ll_fail('این تنظیمات حذف شده است',404);
if($op==='capture'){if(!ll_can($u,'can_capture'))ll_fail('دسترسی ثبت موقعیت خطوط ندارید',403);$b=json_decode(file_get_contents('php://input'),true)?:$_POST;$lineId=(int)($b['line_id']??0);$line=Db::one("SELECT id,code FROM `lines` WHERE id=?",[$lineId]);if(!$line)ll_fail('خط انتخاب‌شده وجود ندارد',404);$ids=ll_line_ids($u);if(is_array($ids)&&!in_array($lineId,$ids,true))ll_fail('این خط در محدوده دسترسی شما نیست',403);$lat=$b['latitude']??null;$lng=$b['longitude']??null;if(!is_numeric($lat)||!is_numeric($lng)||$lat<-90||$lat>90||$lng<-180||$lng>180)ll_fail('مختصات نامعتبر است');$acc=is_numeric($b['accuracy_m']??null)?(float)$b['accuracy_m']:null;if($acc===null)ll_fail('دقت GPS دریافت نشده است');if($acc<0||$acc>20)ll_fail('دقت GPS برای ثبت ایستگاه کافی نیست؛ دقت باید حداکثر ۲۰ متر باشد',422);$photo=ll_upload('location_photo','line')?:ll_json($b['location_photo']??null,'line');$sign=ll_upload('sign_photo','sign')?:ll_json($b['sign_photo']??null,'sign');if(!$photo||!$sign)ll_fail('هر دو تصویر محل خط و تابلو ایستگاه الزامی است');$station=trim((string)($b['station_name']??''));$now=date('Y-m-d H:i:s');Db::run("INSERT INTO line_station_locations(line_id,station_name,latitude,longitude,accuracy_m,location_photo_path,sign_photo_path,captured_by,captured_at) VALUES(?,?,?,?,?,?,?,?,?)",[$lineId,$station?:null,$lat,$lng,$acc,$photo,$sign,$u['id'],$now]);Db::run("UPDATE `lines` SET latitude=?,longitude=?,location_accuracy_m=?,location_photo_path=?,station_sign_photo_path=?,station_name=?,location_updated_by=?,location_updated_at=? WHERE id=?",[$lat,$lng,$acc,$photo,$sign,$station?:null,$u['id'],$now,$lineId]);ll_out(['ok'=>true,'line_id'=>$lineId,'line_code'=>$line['code'],'station_name'=>$station,'latitude'=>(float)$lat,'longitude'=>(float)$lng,'accuracy_m'=>$acc,'location_photo'=>$photo,'sign_photo'=>$sign,'image_format'=>'jpg','image_compression'=>LineImageCompressor::settings(),'updated_at'=>$now]);}
if(strpos($op,'history&line_id=')===0){parse_str(substr($op,8),$q);$_GET['line_id']=(int)($q['line_id']??0);$op='history';}
if($op==='history'){if(!ll_can($u,'can_view'))ll_fail('دسترسی مشاهده موقعیت خطوط ندارید',403);$lineId=(int)($_GET['line_id']??0);$ids=ll_line_ids($u);if(is_array($ids)&&!in_array($lineId,$ids,true))ll_fail('این خط در محدوده دسترسی شما نیست',403);ll_out(Db::all("SELECT s.*,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) captured_by_name FROM line_station_locations s LEFT JOIN users u ON u.id=s.captured_by WHERE s.line_id=? ORDER BY s.captured_at DESC LIMIT 100",[$lineId]));}
ll_fail('عملیات نامعتبر است',404);
