<?php
ini_set('display_errors','0');error_reporting(E_ALL);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$R=__DIR__.'/..';require "$R/lib/Db.php";require "$R/lib/Jwt.php";require "$R/lib/LineImageCompressor.php";$CFG=require "$R/config.php";
function so($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function sf($m,$s=400){so(['error'=>$m],$s);}function usr(){global $CFG;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))sf('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$CFG['jwt_secret']);if(!$p)sf('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.is_admin FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?",[$p['sub']]);if(!$u||!$u['is_active'])sf('کاربر نامعتبر',401);return $u;}
function admin($u){return !empty($u['is_admin'])||in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);}function ids($u){if(admin($u))return null;try{$r=Db::all('SELECT line_id FROM user_lines WHERE user_id=?',[$u['id']]);return array_map('intval',array_column($r,'line_id'));}catch(Throwable $e){return null;}}
function schema(){Db::run("CREATE TABLE IF NOT EXISTS station_sign_types(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(80) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_sst_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");foreach(["station_code VARCHAR(80) NULL","station_status VARCHAR(30) NOT NULL DEFAULT 'registered'"] as $d){$c=strtok($d,' ');$n=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='line_station_locations' AND COLUMN_NAME=?",[$c]);if(!(int)($n['c']??0))Db::run("ALTER TABLE line_station_locations ADD COLUMN `$c` ".substr($d,strlen($c)));}Db::run("CREATE TABLE IF NOT EXISTS line_station_signs(id BIGINT AUTO_INCREMENT PRIMARY KEY,station_location_id BIGINT NOT NULL,sign_type_id INT NOT NULL,photo_path VARCHAR(500) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_station(station_location_id),INDEX idx_type(sign_type_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$ds=[['تابلو ایستگاه تاکسی ساده','simple',1],['تابلو ایستگاه تاکسی دارای بارکرد','barcard',2],['تابلو ایستگاه تاکسی حمل با جرثقیل','crane',3],['تابلو ایستگاه دارای دوربین نظارتی پلیس','police_camera',4]];foreach($ds as $d)Db::run('INSERT IGNORE INTO station_sign_types(title,code,is_active,sort_order) VALUES(?,?,1,?)',[$d[0],$d[1],$d[2]]);}
function store($v,$pre){if(!is_string($v)||$v==='')return null;if(strpos($v,'base64,')!==false){$v=substr($v,strpos($v,',')+1);$v=base64_decode($v,true);}if(!is_string($v)||strlen($v)>8*1024*1024||@getimagesizefromstring($v)===false)sf('تصویر نامعتبر یا بزرگ‌تر از ۸ مگابایت است');$rel='/uploads/line-locations/'.date('Y/m').'/';$dir=__DIR__.$rel;@mkdir($dir,0775,true);$p=$dir.$pre.'_'.bin2hex(random_bytes(8)).'.jpg';if(!LineImageCompressor::fromBinary($v,$p))sf('فشرده‌سازی تصویر در دسترس نیست',500);return $rel.basename($p);}
$u=usr();schema();$op=$_GET['op']??$_POST['op']??'permission';
if($op==='permission')so(['allowed'=>true,'can_manage'=>admin($u)]);
if($op==='lines'){$is=ids($u);$w='';$a=[];if(is_array($is)){if(!$is)so([]);$w=' WHERE l.id IN('.implode(',',array_fill(0,count($is),'?')).')';$a=$is;}so(Db::all("SELECT l.id,l.code,l.origin,l.destination FROM `lines` l$w ORDER BY l.code",$a));}
if($op==='sign-types')so(Db::all('SELECT id,title,code FROM station_sign_types WHERE is_active=1 ORDER BY sort_order,title'));
if($op==='save-sign-type'){if(!admin($u))sf('دسترسی مدیریت نوع تابلو ندارید',403);$b=json_decode(file_get_contents('php://input'),true)?:$_POST;$id=(int)($b['id']??0);$t=trim((string)($b['title']??''));$c=trim((string)($b['code']??''));if(!$t)sf('عنوان نوع تابلو الزامی است');if($id)Db::run('UPDATE station_sign_types SET title=?,code=?,is_active=? WHERE id=?',[$t,$c?:null,!empty($b['is_active'])?1:0,$id]);else Db::run('INSERT INTO station_sign_types(title,code,is_active,sort_order) VALUES(?,?,?,999)',[$t,$c?:null,!empty($b['is_active'])?1:0]);so(['ok'=>true]);}
if($op==='delete-sign-type'){if(!admin($u))sf('دسترسی مدیریت نوع تابلو ندارید',403);Db::run('UPDATE station_sign_types SET is_active=0 WHERE id=?',[(int)($_GET['id']??$_POST['id']??0)]);so(['ok'=>true]);}
if($op==='nearest'){$lat=(float)($_GET['lat']??0);$lng=(float)($_GET['lng']??0);$rad=min(2000,max(50,(float)($_GET['radius']??500)));if($lat<-90||$lat>90||$lng<-180||$lng>180)sf('مختصات نامعتبر است');$is=ids($u);$w='';$a=[];if(is_array($is)){if(!$is)so(['stations'=>[]]);$w=' AND s.line_id IN('.implode(',',array_fill(0,count($is),'?')).')';$a=$is;}$rows=Db::all("SELECT s.id,s.line_id,s.station_code,s.station_name,s.station_status,s.latitude,s.longitude,l.code line_code,l.origin,l.destination FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE s.latitude IS NOT NULL AND s.longitude IS NOT NULL$w ORDER BY s.captured_at DESC",$a);$seen=[];$out=[];foreach($rows as $r){$key=($r['station_code']?:'id'.$r['id']).'|'.$r['line_id'];if(isset($seen[$key]))continue;$seen[$key]=1;$d=6371000*2*asin(sqrt(pow(sin(deg2rad(((float)$r['latitude']-$lat)/2)),2)+cos(deg2rad($lat))*cos(deg2rad((float)$r['latitude']))*pow(sin(deg2rad(((float)$r['longitude']-$lng)/2)),2)));if($d<=$rad){$r['distance_m']=round($d,1);$out[]=$r;}}usort($out,function($x,$y){return $x['distance_m']==$y['distance_m']?0:($x['distance_m']<$y['distance_m']?-1:1);});so(['stations'=>array_slice($out,0,20),'radius_m'=>$rad]);}
if($op==='search'){$q=trim((string)($_GET['q']??''));if($q==='')so([]);$is=ids($u);$w='';$a=[];if(is_array($is)){if(!$is)so([]);$w=' AND s.line_id IN('.implode(',',array_fill(0,count($is),'?')).')';$a=$is;}$l='%'.$q.'%';so(Db::all("SELECT s.id,s.line_id,s.station_code,s.station_name,s.station_status,s.latitude,s.longitude,l.code line_code FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE (s.station_code LIKE ? OR s.station_name LIKE ? OR l.code LIKE ?)$w ORDER BY s.station_code LIMIT 50",array_merge([$l,$l,$l],$a)));}
if($op==='history'){$id=(int)($_GET['station_id']??0);so(Db::all("SELECT s.*, (SELECT COUNT(*) FROM line_station_signs z WHERE z.station_location_id=s.id) sign_count FROM line_station_locations s WHERE s.id=? OR (s.station_code IS NOT NULL AND s.station_code=(SELECT station_code FROM line_station_locations WHERE id=?)) ORDER BY s.captured_at DESC LIMIT 100",[$id,$id]));}
if($op==='capture'){$b=json_decode(file_get_contents('php://input'),true)?:$_POST;$lid=(int)($b['line_id']??0);$line=Db::one('SELECT id,code FROM `lines` WHERE id=?',[$lid]);if(!$line)sf('خط انتخاب‌شده وجود ندارد',404);$is=ids($u);if(is_array($is)&&!in_array($lid,$is,true))sf('این خط در محدوده دسترسی شما نیست',403);$lat=$b['latitude']??null;$lng=$b['longitude']??null;$acc=$b['accuracy_m']??null;if(!is_numeric($lat)||!is_numeric($lng)||!is_numeric($acc)||$lat<-90||$lat>90||$lng<-180||$lng>180||$acc<0)sf('مختصات یا دقت GPS نامعتبر است');if((float)$acc>20)sf('دقت GPS باید حداکثر ۲۰ متر باشد',422);$st=($b['station_status']??'registered')==='missing'?'missing':'registered';$code=trim((string)($b['station_code']??''));$name=trim((string)($b['station_name']??''));if($st==='registered'&&!$code)sf('شماره ایستگاه الزامی است');$ss=$b['signs']??[];if(!is_array($ss)||!count($ss))sf('حداقل یک تابلو الزامی است');$now=date('Y-m-d H:i:s');Db::run('INSERT INTO line_station_locations(line_id,station_code,station_status,station_name,latitude,longitude,accuracy_m,captured_by,captured_at) VALUES(?,?,?,?,?,?,?,?,?)',[$lid,$code?:null,$st,$name?:null,$lat,$lng,$acc,$u['id'],$now]);$sid=(int)Db::lastId();foreach($ss as $x){$tid=(int)($x['type_id']??0);if(!Db::one('SELECT id FROM station_sign_types WHERE id=? AND is_active=1',[$tid]))sf('نوع تابلو نامعتبر است');$p=store($x['photo']??null,'station-sign');if(!$p)sf('تصویر تابلو الزامی است');Db::run('INSERT INTO line_station_signs(station_location_id,sign_type_id,photo_path) VALUES(?,?,?)',[$sid,$tid,$p]);}Db::run('UPDATE `lines` SET latitude=?,longitude=?,location_accuracy_m=?,station_name=?,location_updated_by=?,location_updated_at=? WHERE id=?',[$lat,$lng,$acc,$name?:null,$u['id'],$now,$lid]);so(['ok'=>true,'id'=>$sid,'line_code'=>$line['code'],'station_code'=>$code?:null,'station_status'=>$st,'updated_at'=>$now]);}
if($op==='sign-report'){if(!admin($u))sf('دسترسی گزارش تابلوها ندارید',403);$t=(int)($_GET['type_id']??0);so(Db::all("SELECT s.id,s.station_code,s.station_status,s.station_name,s.latitude,s.longitude,s.accuracy_m,s.captured_at,l.code line_code,l.origin,l.destination,t.title sign_type,sg.photo_path,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) captured_by FROM line_station_signs sg JOIN line_station_locations s ON s.id=sg.station_location_id JOIN station_sign_types t ON t.id=sg.sign_type_id JOIN `lines` l ON l.id=s.line_id LEFT JOIN users u ON u.id=s.captured_by WHERE (?=0 OR t.id=?) ORDER BY s.captured_at DESC",[$t,$t]));}
sf('عملیات نامعتبر است',404);
