<?php
ini_set('display_errors','0');
$ROOT=__DIR__.'/..';require "$ROOT/lib/Db.php";require "$ROOT/lib/Jwt.php";require "$ROOT/lib/Http.php";$CONFIG=require "$ROOT/config.php";
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store,max-age=0');header('X-Content-Type-Options:nosniff');header('Permissions-Policy:microphone=(self)');
function rj($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function re($m,$s=400){rj(['ok'=>false,'error'=>$m],$s);}function rb(){ $x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:$_POST;}
function te($t){static $c=[];if(isset($c[$t]))return$c[$t];$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);return$c[$t]=(int)($r['c']??0)>0;}function ce($t,$c){static$x=[];$k="$t.$c";if(isset($x[$k]))return$x[$k];$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$t,$c]);return$x[$k]=(int)($r['c']??0)>0;}
// راه‌اندازی ایمن و idempotent ساختار پایگاه‌دادهٔ بی‌سیم — این بخش در نسخهٔ v1 (radio-api.php) وجود
// داشت ولی هنگام بازنویسی به v2 (افزودن قابلیت محدودسازی بر اساس منطقه/سمت/کاربر) به‌اشتباه حذف شده بود؛
// نبود آن باعث می‌شد در هر نصب/سروری که migration دستی radio*.sql روی آن اجرا نشده باشد، جدول‌های
// بی‌سیم اصلاً وجود نداشته باشند و «کانال صوتی» برای همیشه خالی/خطا نمایش داده شود، بدون هیچ سرنخی.
function radio_schema(){try{
 Db::run("CREATE TABLE IF NOT EXISTS radio_channels(id INT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,code VARCHAR(50) NOT NULL,description VARCHAR(255) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,current_speaker_id INT NULL,lock_until DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_radio_channels_code(code),KEY idx_radio_channels_active(is_active),KEY idx_radio_channels_speaker(current_speaker_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 foreach([['channel_type',"VARCHAR(20) NOT NULL DEFAULT 'custom'"],['match_mode',"VARCHAR(3) NOT NULL DEFAULT 'OR'"],['max_talk_ms','INT UNSIGNED NOT NULL DEFAULT 25000'],['priority','INT NOT NULL DEFAULT 0']] as $x){if(!ce('radio_channels',$x[0]))Db::run("ALTER TABLE radio_channels ADD COLUMN {$x[0]} {$x[1]}");}
 Db::run("CREATE TABLE IF NOT EXISTS radio_messages(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NOT NULL,sender_id INT NOT NULL,sender_name VARCHAR(190) NOT NULL,audio_path VARCHAR(255) NOT NULL,mime_type VARCHAR(80) NOT NULL DEFAULT 'audio/mp4',duration_ms INT UNSIGNED NOT NULL DEFAULT 0,bytes_size INT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_radio_messages_channel_id(channel_id,id),KEY idx_radio_messages_sender(sender_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_user_settings(user_id INT NOT NULL PRIMARY KEY,enabled TINYINT(1) NOT NULL DEFAULT 1,channel_id INT UNSIGNED NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_radio_user_channel(channel_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_channel_regions(channel_id INT UNSIGNED NOT NULL,region_id INT NOT NULL,PRIMARY KEY(channel_id,region_id),KEY(region_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_channel_users(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,PRIMARY KEY(channel_id,user_id),KEY(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_channel_roles(channel_id INT UNSIGNED NOT NULL,role_id INT NOT NULL,PRIMARY KEY(channel_id,role_id),KEY(role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_presence(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(channel_id,user_id),KEY(channel_id,last_seen_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 Db::run("CREATE TABLE IF NOT EXISTS radio_logs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NULL,user_id INT NULL,event_type VARCHAR(40) NOT NULL,meta_json TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY(channel_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $cnt=Db::one('SELECT COUNT(*) c FROM radio_channels'); if((int)($cnt['c']??0)===0){foreach([['عمومی','general','کانال عمومی ارتباط خطیار'],['مدیریت','management','ارتباط مدیریت و مسئولین'],['بازرسی','inspection','ارتباط واحد بازرسی'],['عملیات خطوط','field','ارتباط عملیات میدانی خطوط']] as $c)Db::run("INSERT INTO radio_channels(name,code,description) VALUES(?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),is_active=1",$c);}
}catch(Throwable $e){error_log('radio_schema bootstrap failed: '.$e->getMessage());}}
function au(){global$CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))re('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.*,r.title role_title,r.level,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])re('کاربر نامعتبر است',401);if(te('user_sessions')){$dt=$p['dt']??'web';$s=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$admin=!empty($u['is_admin'])||in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);if(!$s||$s['revoked_at']||(!$admin&&(string)$s['device_id']!==(string)($p['device_id']??'')))re('نشست منقضی یا باطل شده است',401);}return$u;}
function ch($id){$c=Db::one('SELECT * FROM radio_channels WHERE id=? AND is_active=1',[(int)$id]);if(!$c)re('کانال بی‌سیم یافت نشد',404);return$c;}
function rules($id){$a=['regions'=>[],'users'=>[],'roles'=>[]];foreach($a as$k=>$_){$t=['regions'=>'radio_channel_regions','users'=>'radio_channel_users','roles'=>'radio_channel_roles'][$k];if(te($t)){$col=$k==='regions'?'region_id':($k==='users'?'user_id':'role_id');$a[$k]=array_map('intval',array_column(Db::all("SELECT $col v FROM $t WHERE channel_id=?",[$id]),'v'));}}return$a;}
function uregion($u){foreach(['region_id','area_id','zone_id','district_id']as$c)if(ce('users',$c)&&!empty($u[$c]))return(int)$u[$c];foreach(['user_regions','user_region']as$t)if(te($t)&&ce($t,'user_id'))foreach(['region_id','area_id','zone_id']as$c)if(ce($t,$c)){ $r=Db::one("SELECT $c v FROM $t WHERE user_id=? LIMIT 1",[$u['id']]);if($r&&$r['v']!==null)return(int)$r['v'];}return 0;}
function okch($c,$u){$r=rules($c['id']);$g=[];if($r['regions'])$g[]=in_array(uregion($u),$r['regions'],true);if($r['roles'])$g[]=in_array((int)$u['role_id'],$r['roles'],true);if($r['users'])$g[]=in_array((int)$u['id'],$r['users'],true);if(!$g)return true;return($c['match_mode']??'OR')==='AND'?!in_array(false,$g,true):in_array(true,$g,true);}
function ec($id,$u){$c=ch($id);if(!okch($c,$u))re('شما عضو این کانال نیستید',403);return$c;}function logx($cid,$uid,$ev,$m=[]){if(te('radio_logs'))try{Db::run('INSERT INTO radio_logs(channel_id,user_id,event_type,meta_json) VALUES(?,?,?,?)',[$cid,$uid,$ev,json_encode($m,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable$e){}}
$u=au();radio_schema();$op=$_GET['op']??$_POST['op']??'state';$method=$_SERVER['REQUEST_METHOD']??'GET';
if($op==='channels'&&$method==='GET'){ $rows=Db::all('SELECT * FROM radio_channels WHERE is_active=1 ORDER BY priority DESC,id');$o=[];foreach($rows as$c)if(okch($c,$u)){$lm=Db::one('SELECT MAX(id) m FROM radio_messages WHERE channel_id=?',[$c['id']]);$o[]=['id'=>(int)$c['id'],'name'=>$c['name'],'code'=>$c['code'],'description'=>$c['description'],'channel_type'=>$c['channel_type']??'custom','max_talk_ms'=>(int)($c['max_talk_ms']??25000),'priority'=>(int)($c['priority']??0),'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null,'last_message_id'=>(int)($lm['m']??0)];}$s=Db::one('SELECT enabled,channel_id FROM radio_user_settings WHERE user_id=?',[$u['id']]);$cid=(int)($s['channel_id']??($o[0]['id']??0));rj(['ok'=>true,'channels'=>$o,'enabled'=>$s?(bool)$s['enabled']:true,'channel_id'=>$cid]);}
if($op==='state'&&$method==='GET'){ $s=Db::one('SELECT enabled,channel_id FROM radio_user_settings WHERE user_id=?',[$u['id']]);$cid=(int)($s['channel_id']??0);$c=$cid?ec($cid,$u):null;rj(['ok'=>true,'enabled'=>$s?(bool)$s['enabled']:true,'channel'=>$c?['id'=>(int)$c['id'],'name'=>$c['name'],'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null]:null]);}
if($op==='presence'&&$method==='POST'){ $cid=(int)(rb()['channel_id']??0);$c=ec($cid,$u);if(te('radio_presence'))Db::run('INSERT INTO radio_presence(channel_id,user_id,last_seen_at) VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE last_seen_at=NOW()',[$cid,$u['id']]);rj(['ok'=>true]);}
if($op==='settings'&&$method==='POST'){ $b=rb();$cid=(int)($b['channel_id']??0);if($cid)ec($cid,$u);$en=!empty($b['enabled'])?1:0;Db::run('INSERT INTO radio_user_settings(user_id,enabled,channel_id) VALUES(?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),channel_id=VALUES(channel_id)',[$u['id'],$en,$cid?:null]);rj(['ok'=>true,'enabled'=>(bool)$en,'channel_id'=>$cid]);}
if($op==='take'&&$method==='POST'){ $cid=(int)(rb()['channel_id']??0);$c=ec($cid,$u);$pdo=Db::pdo();$pdo->beginTransaction();try{$row=Db::one('SELECT current_speaker_id,lock_until FROM radio_channels WHERE id=? FOR UPDATE',[$cid]);if(!empty($row['current_speaker_id'])&&strtotime((string)$row['lock_until'])>time()&&(int)$row['current_speaker_id']!==(int)$u['id']){$pdo->rollBack();re('کانال در حال استفاده است',409);}$ms=max(5000,min(120000,(int)($c['max_talk_ms']??25000)));Db::run('UPDATE radio_channels SET current_speaker_id=?,lock_until=DATE_ADD(NOW(),INTERVAL ? SECOND) WHERE id=?',[$u['id'],ceil($ms/1000),$cid]);$pdo->commit();logx($cid,$u['id'],'take',['max_talk_ms'=>$ms]);$name=trim(($u['first_name']??'').' '.($u['last_name']??''))?:($u['username']??'کاربر');rj(['ok'=>true,'channel_id'=>$cid,'speaker_id'=>(int)$u['id'],'speaker_name'=>$name,'lease_ms'=>$ms]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();re('گرفتن کانال ناموفق بود',500);}}
if($op==='release'&&$method==='POST'){ $cid=(int)(rb()['channel_id']??0);ec($cid,$u);Db::run('UPDATE radio_channels SET current_speaker_id=NULL,lock_until=NULL WHERE id=? AND current_speaker_id=?',[$cid,$u['id']]);logx($cid,$u['id'],'release');rj(['ok'=>true]);}
if($op==='send'&&$method==='POST'){ $cid=(int)($_POST['channel_id']??0);$c=ec($cid,$u);$row=Db::one('SELECT current_speaker_id,lock_until FROM radio_channels WHERE id=?',[$cid]);if((int)($row['current_speaker_id']??0)!==(int)$u['id']||strtotime((string)($row['lock_until']??''))<=time())re('مجوز صحبت شما منقضی شده است',409);$max=(int)($c['max_talk_ms']??25000);$duration=max(0,min($max,(int)($_POST['duration_ms']??0)));if(empty($_FILES['audio']['tmp_name']))re('فایل صوتی ارسال نشده است');$f=$_FILES['audio'];if((int)$f['size']>160000)re('فایل صوتی بیش از حد مجاز است',413);$mime=(string)($f['type']??'audio/mp4');if(!preg_match('~^(audio/(mp4|m4a|aac|webm|mpeg)|video/mp4)$~i',$mime))re('فرمت صوتی مجاز نیست',415);$dir=__DIR__.'/uploads/radio';if(!is_dir($dir)&&!@mkdir($dir,0750,true))re('فضای ذخیره بی‌سیم قابل ایجاد نیست',500);$n=Db::one('SELECT COALESCE(MAX(id),0)+1 n FROM radio_messages');$id=(int)$n['n'];$path=$dir.'/'.$id.'.m4a';if(!@move_uploaded_file($f['tmp_name'],$path))re('ذخیره فایل صوتی ناموفق بود',500);$name=trim(($u['first_name']??'').' '.($u['last_name']??''))?:($u['username']??'کاربر');Db::run('INSERT INTO radio_messages(id,channel_id,sender_id,sender_name,audio_path,mime_type,duration_ms,bytes_size) VALUES(?,?,?,?,?,?,?,?)',[$id,$cid,$u['id'],$name,'uploads/radio/'.$id.'.m4a',$mime,$duration,(int)$f['size']]);Db::run('UPDATE radio_channels SET current_speaker_id=NULL,lock_until=NULL WHERE id=? AND current_speaker_id=?',[$cid,$u['id']]);logx($cid,$u['id'],'send',['message_id'=>$id,'duration_ms'=>$duration]);rj(['ok'=>true,'message'=>['id'=>$id,'channel_id'=>$cid,'sender_id'=>(int)$u['id'],'sender_name'=>$name,'duration_ms'=>$duration,'audio_url'=>'/api/radio-api-v2.php?op=audio&id='.$id]]);}
if($op==='poll'&&$method==='GET'){ $cid=(int)($_GET['channel_id']??0);$after=(int)($_GET['after']??0);$c=ec($cid,$u);$rows=Db::all('SELECT id,channel_id,sender_id,sender_name,duration_ms,bytes_size,created_at FROM radio_messages WHERE channel_id=? AND id>? ORDER BY id ASC LIMIT 10',[$cid,$after]);foreach($rows as&$r)$r['audio_url']='/api/radio-api-v2.php?op=audio&id='.(int)$r['id'];unset($r);$speakerName=null;$speakerRole=null;if(!empty($c['current_speaker_id'])){if((int)$c['current_speaker_id']===(int)$u['id']){$speakerName='شما';$speakerRole=$u['role_title']??'';}else{$su=Db::one('SELECT u.first_name,u.last_name,u.username,r.title role_title FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1',[$c['current_speaker_id']]);$speakerName=$su?(trim(($su['first_name']??'').' '.($su['last_name']??''))?:($su['username']??'کاربر')):'کاربر';$speakerRole=$su['role_title']??'';}}rj(['ok'=>true,'messages'=>$rows,'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null,'speaker_name'=>$speakerName,'speaker_role'=>$speakerRole]);}
if($op==='responsible-recent'&&$method==='GET'){ $cid=(int)($_GET['channel_id']??0);$c=ec($cid,$u);$roles=['مدیر کل','معاونت نظارت و بازرسی','معاونت اداره بازرسی','رییس اداره بازرسی','رئیس اداره بازرسی','سربازرس ارشد','سربازرس','نیروی اداری ارشد'];$where=[];$params=[];foreach($roles as $role){$where[]='r.title=?';$params[]=$role;}$sql='SELECT m.id,m.channel_id,m.sender_id,m.sender_name,m.duration_ms,m.bytes_size,m.created_at,r.title role_title FROM radio_messages m JOIN users su ON su.id=m.sender_id LEFT JOIN roles r ON r.id=su.role_id WHERE m.channel_id=? AND (su.is_admin=1 OR ('.implode(' OR ',$where).')) ORDER BY m.id DESC LIMIT 3';$rows=Db::all($sql,array_merge([$cid],$params));foreach($rows as&$r)$r['audio_url']='/api/radio-api-v2.php?op=audio&id='.(int)$r['id'];unset($r);rj(['ok'=>true,'messages'=>$rows]);}
if($op==='audio'&&$method==='GET'){ $id=(int)($_GET['id']??0);$m=Db::one('SELECT m.*,c.is_active FROM radio_messages m JOIN radio_channels c ON c.id=m.channel_id WHERE m.id=?',[$id]);if(!$m||!(int)$m['is_active'])re('پیام صوتی یافت نشد',404);ec($m['channel_id'],$u);$p=__DIR__.'/'.$m['audio_path'];if(!is_file($p))re('فایل صوتی یافت نشد',404);header('Content-Type: '.($m['mime_type']?:'audio/mp4'));header('Content-Length:'.filesize($p));header('Content-Disposition:inline; filename="radio-'.$id.'.m4a"');readfile($p);exit;}
re('عملیات بی‌سیم نامعتبر است',404);
