<?php
ini_set('display_errors','0');$ROOT=__DIR__.'/..';require "$ROOT/lib/Db.php";require "$ROOT/lib/Jwt.php";require "$ROOT/lib/Http.php";$CONFIG=require "$ROOT/config.php";header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store,max-age=0');
function j($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function e($m,$s=400){j(['ok'=>false,'error'=>$m],$s);}function b(){ $x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:$_POST;}
function te($t){$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);return(int)($r['c']??0)>0;}function ce($t,$c){$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$t,$c]);return(int)($r['c']??0)>0;}
function load_user(){global$CONFIG;$p=($t=Http::bearer())?Jwt::verify($t,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))e('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.*,r.title role_title,r.level,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])e('کاربر نامعتبر است',401);return$u;}
function is_super_admin($u){return!empty($u['is_admin'])||in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);}
function has_radio_permission($u){if(is_super_admin($u))return true;try{$r=Db::one("SELECT value FROM app_settings WHERE `key`='role_perms' LIMIT 1");$cfg=$r?json_decode((string)$r['value'],true):[];$rid=(string)($u['role_id']??'');if(!is_array($cfg)||!array_key_exists($rid,$cfg))return false;$items=is_array($cfg[$rid])?$cfg[$rid]:[];return in_array('radiocenter',$items,true)||in_array('radio',$items,true);}catch(Throwable$e){return false;}}
function has_radio_listen_permission($u){return has_radio_permission($u);}
function auth(){ $u=load_user();if(!has_radio_listen_permission($u))e('این سمت مجوز دسترسی به بی‌سیم را ندارد',403);return$u;}
function require_admin_op($u){if(!has_radio_permission($u))e('این سمت مجوز مدیریت بی‌سیم را ندارد',403);}
function ensure_settings(){try{if(!te('app_settings'))Db::run("CREATE TABLE IF NOT EXISTS app_settings(`key` VARCHAR(190) NOT NULL PRIMARY KEY,value LONGTEXT NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}catch(Throwable $e){}}
function retention_hours(){ensure_settings();try{$r=Db::one("SELECT value FROM app_settings WHERE `key`='radio_archive_retention_hours' LIMIT 1");$v=(int)($r['value']??0);if($v>0)return max(1,min(87600,$v));$r=Db::one("SELECT value FROM app_settings WHERE `key`='radio_archive_retention_days' LIMIT 1");$d=(int)($r['value']??0);if($d>0)return max(1,min(87600,$d*24));}catch(Throwable$e){}return 24;}
function retention_days(){return max(1,(int)ceil(retention_hours()/24));}
function audio_sig($id,$exp,$dl=0){global$CONFIG;return hash_hmac('sha256',((int)$id).'|'.((int)$exp).'|'.((int)$dl),(string)$CONFIG['jwt_secret']);}
function audio_url($id,$dl=0){$exp=time()+900;$u='/api/radio-admin-api.php?op=monitor-audio&id='.(int)$id.'&exp='.$exp.'&sig='.audio_sig($id,$exp,$dl);if($dl)$u.='&dl=1';return $u;}
function verify_audio(){ $id=(int)($_GET['id']??0);$exp=(int)($_GET['exp']??0);$sig=(string)($_GET['sig']??'');$dl=(int)($_GET['dl']??0);if(!$id||$exp<time()||!$sig||!hash_equals(audio_sig($id,$exp,$dl),$sig))e('لینک صوتی نامعتبر یا منقضی است',401);return$id;}
function ensure_radio_runtime_tables(){
  Db::run("CREATE TABLE IF NOT EXISTS radio_messages(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NOT NULL,sender_id INT NOT NULL,sender_name VARCHAR(190) NOT NULL,audio_path VARCHAR(255) NOT NULL,mime_type VARCHAR(80) NOT NULL DEFAULT 'audio/mp4',duration_ms INT UNSIGNED NOT NULL DEFAULT 0,bytes_size INT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_radio_messages_channel_id(channel_id,id),KEY idx_radio_messages_sender(sender_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  Db::run("CREATE TABLE IF NOT EXISTS radio_user_settings(user_id INT NOT NULL PRIMARY KEY,enabled TINYINT(1) NOT NULL DEFAULT 1,channel_id INT UNSIGNED NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_radio_user_channel(channel_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function setup(){try{ensure_radio_runtime_tables();Db::run("CREATE TABLE IF NOT EXISTS radio_channels(id INT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,code VARCHAR(50) NOT NULL,description VARCHAR(255) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,current_speaker_id INT NULL,lock_until DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_radio_channels_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");foreach([['channel_type',"VARCHAR(20) NOT NULL DEFAULT 'custom'"],['match_mode',"VARCHAR(3) NOT NULL DEFAULT 'OR'"],['max_talk_ms','INT UNSIGNED NOT NULL DEFAULT 25000'],['priority','INT NOT NULL DEFAULT 0']]as$x){if(!ce('radio_channels',$x[0]))Db::run("ALTER TABLE radio_channels ADD COLUMN {$x[0]} {$x[1]}");}foreach(['radio_channel_regions'=>"CREATE TABLE IF NOT EXISTS radio_channel_regions(channel_id INT UNSIGNED NOT NULL,region_id INT NOT NULL,PRIMARY KEY(channel_id,region_id),KEY(region_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'radio_channel_users'=>"CREATE TABLE IF NOT EXISTS radio_channel_users(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,PRIMARY KEY(channel_id,user_id),KEY(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'radio_channel_roles'=>"CREATE TABLE IF NOT EXISTS radio_channel_roles(channel_id INT UNSIGNED NOT NULL,role_id INT NOT NULL,PRIMARY KEY(channel_id,role_id),KEY(role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'radio_presence'=>"CREATE TABLE IF NOT EXISTS radio_presence(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(channel_id,user_id),KEY(channel_id,last_seen_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'radio_logs'=>"CREATE TABLE IF NOT EXISTS radio_logs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NULL,user_id INT NULL,event_type VARCHAR(40) NOT NULL,meta_json TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY(channel_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"]as$t=>$sql)if(!te($t))Db::run($sql);ensure_settings();}catch(Throwable$ex){e('راه‌اندازی ساختار مدیریت بی‌سیم ناموفق بود',500);}}
function region_source(){foreach(['regions','areas','geographic_regions','districts']as$t)if(te($t))foreach(['name','title','region_name','area_name']as$n)if(ce($t,$n))return[$t,$n];return null;}function regions(){ $s=region_source();if(!$s)return[];[$t,$n]=$s;$rows=Db::all("SELECT id,$n name FROM $t ORDER BY $n");return array_map(fn($r)=>['id'=>(int)$r['id'],'name'=>(string)$r['name']],$rows);}function uregion($u){foreach(['region_id','area_id','zone_id','district_id']as$c)if(ce('users',$c)&&!empty($u[$c]))return(int)$u[$c];return 0;}
function allowed($c,$u){$rid=uregion($u);$rg=Db::all('SELECT region_id FROM radio_channel_regions WHERE channel_id=?',[$c['id']]);$us=Db::all('SELECT user_id FROM radio_channel_users WHERE channel_id=?',[$c['id']]);$ro=Db::all('SELECT role_id FROM radio_channel_roles WHERE channel_id=?',[$c['id']]);$groups=[];if($rg)$groups[]=in_array($rid,array_map(fn($x)=>(int)$x['region_id'],$rg),true);if($ro)$groups[]=in_array((int)$u['role_id'],array_map(fn($x)=>(int)$x['role_id'],$ro),true);if($us)$groups[]=in_array((int)$u['id'],array_map(fn($x)=>(int)$x['user_id'],$us),true);if(!$groups)return true;return(($c['match_mode']??'OR')==='AND')?!in_array(false,$groups,true):in_array(true,$groups,true);}
setup();$op=$_GET['op']??$_POST['op']??'bootstrap';$method=$_SERVER['REQUEST_METHOD']??'GET';
if($op==='monitor-audio'&&$method==='GET'){ $id=verify_audio();$dl=(int)($_GET['dl']??0);$m=Db::one('SELECT audio_path,mime_type,sender_name,created_at FROM radio_messages WHERE id=?',[$id]);if(!$m)e('فایل صوتی یافت نشد',404);$p=__DIR__.'/'.$m['audio_path'];if(!is_file($p))e('فایل صوتی یافت نشد',404);header('Content-Type: '.($m['mime_type']?:'audio/mp4'));header('Content-Length:'.filesize($p));if($dl){$ext=(strpos((string)$m['mime_type'],'mpeg')!==false)?'mp3':'m4a';$safeName=preg_replace('/[^\p{L}\p{N}_-]+/u','-',(string)($m['sender_name']?:'radio'));$fname='bisim-'.$safeName.'-'.preg_replace('/[^0-9]/','',(string)$m['created_at']).'-'.$id.'.'.$ext;header('Content-Disposition: attachment; filename="'.$fname.'"');}else{header('Content-Disposition:inline; filename="radio-'.$id.'.m4a"');}readfile($p);exit;}
$me=auth();
if($op==='channel-list'&&$method==='GET'){ $chs=Db::all('SELECT c.id,c.name,c.code,(SELECT COALESCE(MAX(m.id),0) FROM radio_messages m WHERE m.channel_id=c.id) last_message_id FROM radio_channels c WHERE c.is_active=1 ORDER BY c.priority DESC,c.name');j(['ok'=>true,'channels'=>array_map(fn($c)=>['id'=>(int)$c['id'],'name'=>$c['name'],'code'=>$c['code'],'last_message_id'=>(int)$c['last_message_id']],$chs)]);}
if($op==='monitor'&&$method==='GET'){ $cid=(int)($_GET['channel_id']??0);$after=(int)($_GET['after']??0);$c=Db::one('SELECT id,is_active FROM radio_channels WHERE id=?',[$cid]);if(!$c||!(int)$c['is_active'])e('کانال یافت نشد',404);$rows=Db::all('SELECT id,channel_id,sender_id,sender_name,duration_ms,created_at FROM radio_messages WHERE channel_id=? AND id>? ORDER BY id ASC LIMIT 20',[$cid,$after]);foreach($rows as&$r){$r['id']=(int)$r['id'];$r['audio_url']=audio_url($r['id']);$r['download_url']=audio_url($r['id'],1);}unset($r);Db::run('INSERT INTO radio_logs(channel_id,user_id,event_type,meta_json) VALUES(?,?,?,?)',[$cid,$me['id'],'monitor',null]);j(['ok'=>true,'messages'=>$rows]);}
if($op==='archive'&&$method==='GET'){ $cid=(int)($_GET['channel_id']??0);$hours=max(1,min(720,(int)($_GET['hours']??24)));$before=(int)($_GET['before']??PHP_INT_MAX);$limit=max(1,min(500,(int)($_GET['limit']??200)));$rows=Db::all('SELECT id,channel_id,sender_id,sender_name,duration_ms,created_at FROM radio_messages WHERE id<? AND created_at>=DATE_SUB(NOW(),INTERVAL ? HOUR) AND (?=0 OR channel_id=?) ORDER BY id DESC LIMIT '.$limit,[$before,$hours,$cid,$cid]);foreach($rows as&$r){$r['id']=(int)$r['id'];$r['audio_url']=audio_url($r['id']);$r['download_url']=audio_url($r['id'],1);}unset($r);j(['ok'=>true,'messages'=>$rows,'hours'=>$hours,'retention_days'=>retention_days(),'retention_hours'=>retention_hours()]);}
if($op==='retention-get'&&$method==='GET')j(['ok'=>true,'retention_days'=>retention_days(),'retention_hours'=>retention_hours()]);
if($op==='retention-set'&&$method==='POST'){require_admin_op($me);$x=b();$hours=max(1,min(87600,(int)($x['retention_hours']??(($x['retention_days']??1)*24))));ensure_settings();Db::run("INSERT INTO app_settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)",['radio_archive_retention_hours',(string)$hours]);Db::run("INSERT INTO app_settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)",['radio_archive_retention_days',(string)max(1,(int)ceil($hours/24))]);Db::run('INSERT INTO radio_logs(channel_id,user_id,event_type,meta_json) VALUES(NULL,?,?,?)',[$me['id'],'archive_retention',json_encode(['hours'=>$hours,'days'=>max(1,(int)ceil($hours/24))],JSON_UNESCAPED_UNICODE)]);j(['ok'=>true,'retention_days'=>max(1,(int)ceil($hours/24)),'retention_hours'=>$hours]);}
if($op==='access'&&$method==='GET')j(['ok'=>true,'allowed'=>true,'role_id'=>(int)$me['role_id'],'can_manage'=>has_radio_permission($me)]);
if($op==='bootstrap'&&$method==='GET'){ require_admin_op($me);$chs=Db::all('SELECT id,name,code,description,is_active,channel_type,match_mode,max_talk_ms,priority,current_speaker_id,lock_until FROM radio_channels ORDER BY priority DESC,id');foreach($chs as&$c){$c['id']=(int)$c['id'];$c['is_active']=(bool)$c['is_active'];$c['max_talk_ms']=(int)$c['max_talk_ms'];$c['priority']=(int)$c['priority'];$c['rules']=['regions'=>array_map('intval',array_column(Db::all('SELECT region_id FROM radio_channel_regions WHERE channel_id=?',[$c['id']]),'region_id')),'users'=>array_map('intval',array_column(Db::all('SELECT user_id FROM radio_channel_users WHERE channel_id=?',[$c['id']]),'user_id')),'roles'=>array_map('intval',array_column(Db::all('SELECT role_id FROM radio_channel_roles WHERE channel_id=?',[$c['id']]),'role_id'))];$c['online_count']=(int)(Db::one('SELECT COUNT(*) n FROM radio_presence WHERE channel_id=? AND last_seen_at>=DATE_SUB(NOW(),INTERVAL 90 SECOND)',[$c['id']])['n']??0);}unset($c);j(['ok'=>true,'channels'=>$chs,'regions'=>regions(),'retention_hours'=>retention_hours(),'retention_days'=>retention_days()]);}

// --- مدیریت کانال‌ها ---
if($op==='save'&&$method==='POST'){
  require_admin_op($me);$x=b();
  $id=(int)($x['id']??0);$name=trim((string)($x['name']??''));$code=preg_replace('/[^a-zA-Z0-9_-]/','',trim((string)($x['code']??'')));
  $desc=trim((string)($x['description']??''));$type=(string)($x['channel_type']??'custom');$mode=strtoupper((string)($x['match_mode']??'OR'));
  $max=max(5000,min(120000,(int)($x['max_talk_ms']??25000)));$priority=max(-100,min(100,(int)($x['priority']??0)));$active=!empty($x['is_active'])?1:0;
  if($name==='')e('نام کانال الزامی است',422);if($code==='')e('کد یکتا الزامی است',422);
  if(!in_array($type,['region','users','roles','custom'],true))e('نوع کانال نامعتبر است',422);
  if(!in_array($mode,['OR','AND'],true))e('منطق ترکیب شروط نامعتبر است',422);
  $rules=$x['rules']??[];$regions=array_values(array_unique(array_map('intval',is_array($rules['regions']??null)?$rules['regions']:[])));$users=array_values(array_unique(array_map('intval',is_array($rules['users']??null)?$rules['users']:[])));$roles=array_values(array_unique(array_map('intval',is_array($rules['roles']??null)?$rules['roles']:[])));
  if($type==='region'&&!$regions)e('برای کانال منطقه‌ای حداقل یک منطقه انتخاب کنید',422);
  if($type==='users'&&!$users)e('برای کانال اعضای انتخابی حداقل یک عضو انتخاب کنید',422);
  if($type==='roles'&&!$roles)e('برای کانال سمت‌محور حداقل یک سمت انتخاب کنید',422);
  $dup=Db::one("SELECT id FROM radio_channels WHERE code=? AND id<>? LIMIT 1",[$code,$id]);if($dup)e('کد کانال قبلاً استفاده شده است',409);
  $pdo=Db::pdo();$pdo->beginTransaction();
  try{
    if($id){
      if(!Db::one("SELECT id FROM radio_channels WHERE id=?",[$id]))throw new RuntimeException('کانال یافت نشد');
      Db::run("UPDATE radio_channels SET name=?,code=?,description=?,is_active=?,channel_type=?,match_mode=?,max_talk_ms=?,priority=? WHERE id=?",[$name,$code,$desc?:null,$active,$type,$mode,$max,$priority,$id]);
    }else{
      Db::run("INSERT INTO radio_channels(name,code,description,is_active,channel_type,match_mode,max_talk_ms,priority) VALUES(?,?,?,?,?,?,?,?)",[$name,$code,$desc?:null,$active,$type,$mode,$max,$priority]);$id=(int)$pdo->lastInsertId();
    }
    Db::run("DELETE FROM radio_channel_regions WHERE channel_id=?",[$id]);Db::run("DELETE FROM radio_channel_users WHERE channel_id=?",[$id]);Db::run("DELETE FROM radio_channel_roles WHERE channel_id=?",[$id]);
    foreach($regions as $v)Db::run("INSERT IGNORE INTO radio_channel_regions(channel_id,region_id) VALUES(?,?)",[$id,$v]);
    foreach($users as $v)Db::run("INSERT IGNORE INTO radio_channel_users(channel_id,user_id) VALUES(?,?)",[$id,$v]);
    foreach($roles as $v)Db::run("INSERT IGNORE INTO radio_channel_roles(channel_id,role_id) VALUES(?,?)",[$id,$v]);
    $pdo->commit();j(['ok'=>true,'id'=>$id]);
  }catch(Throwable$ex){if($pdo->inTransaction())$pdo->rollBack();e('ذخیره کانال ناموفق بود',500);}
}
if($op==='delete'&&$method==='POST'){
  require_admin_op($me);$id=(int)(b()['id']??0);if(!$id)e('شناسه کانال نامعتبر است',422);
  if(!Db::one("SELECT id FROM radio_channels WHERE id=?",[$id]))e('کانال یافت نشد',404);
  Db::run("UPDATE radio_channels SET is_active=0,current_speaker_id=NULL,lock_until=NULL WHERE id=?",[$id]);
  j(['ok'=>true]);
}
if($op==='members'&&$method==='GET'){
  require_admin_op($me);$id=(int)($_GET['channel_id']??0);if(!$id)e('شناسه کانال نامعتبر است',422);if(!Db::one("SELECT id FROM radio_channels WHERE id=?",[$id]))e('کانال یافت نشد',404);
  $rg=Db::all("SELECT region_id FROM radio_channel_regions WHERE channel_id=?",[$id]);$us=Db::all("SELECT user_id FROM radio_channel_users WHERE channel_id=?",[$id]);$ro=Db::all("SELECT role_id FROM radio_channel_roles WHERE channel_id=?",[$id]);
  $members=[];foreach($us as $x)$members[]=['type'=>'user','id'=>(int)$x['user_id']];foreach($ro as $x)$members[]=['type'=>'role','id'=>(int)$x['role_id']];foreach($rg as $x)$members[]=['type'=>'region','id'=>(int)$x['region_id']];j(['ok'=>true,'members'=>$members,'counts'=>['users'=>count($us),'roles'=>count($ro),'regions'=>count($rg)]]);
}
if($op==='logs'&&$method==='GET'){
  require_admin_op($me);$id=(int)($_GET['channel_id']??0);if(!$id)e('شناسه کانال نامعتبر است',422);$limit=max(1,min(200,(int)($_GET['limit']??100)));
  $rows=Db::all("SELECT l.id,l.channel_id,l.user_id,l.event_type,l.meta_json,l.created_at,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) user_name FROM radio_logs l LEFT JOIN users u ON u.id=l.user_id WHERE l.channel_id=? ORDER BY l.id DESC LIMIT ".$limit,[$id]);
  j(['ok'=>true,'logs'=>$rows]);
}
