<?php
ini_set('display_errors','0');
$ROOT=__DIR__.'/..';require "$ROOT/lib/Db.php";require "$ROOT/lib/Jwt.php";require "$ROOT/lib/Http.php";$CONFIG=require "$ROOT/config.php";
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store,max-age=0');header('X-Content-Type-Options:nosniff');header('Permissions-Policy:microphone=(self)');
function rj($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function re($m,$s=400){rj(['ok'=>false,'error'=>$m],$s);}function rb(){ $x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:$_POST;}
function te($t){static $c=[];if(isset($c[$t]))return$c[$t];$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);return$c[$t]=(int)($r['c']??0)>0;}function ce($t,$c){static$x=[];$k="$t.$c";if(isset($x[$k]))return$x[$k];$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$t,$c]);return$x[$k]=(int)($r['c']??0)>0;}
function radio_schema(){static $ready=null;if($ready===true)return true;try{
 $creates=[
 "radio_channels"=>"CREATE TABLE IF NOT EXISTS radio_channels(id INT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,code VARCHAR(50) NOT NULL,description VARCHAR(255) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,current_speaker_id INT NULL,lock_until DATETIME NULL,channel_type VARCHAR(20) NOT NULL DEFAULT 'custom',match_mode VARCHAR(3) NOT NULL DEFAULT 'OR',max_talk_ms INT UNSIGNED NOT NULL DEFAULT 25000,priority INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_radio_channels_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_messages"=>"CREATE TABLE IF NOT EXISTS radio_messages(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NOT NULL,sender_id INT NOT NULL,sender_name VARCHAR(190) NOT NULL,audio_path VARCHAR(255) NOT NULL,mime_type VARCHAR(80) NOT NULL DEFAULT 'audio/mp4',duration_ms INT UNSIGNED NOT NULL DEFAULT 0,bytes_size INT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_user_settings"=>"CREATE TABLE IF NOT EXISTS radio_user_settings(user_id INT NOT NULL PRIMARY KEY,enabled TINYINT(1) NOT NULL DEFAULT 1,channel_id INT UNSIGNED NULL,listen_all TINYINT(1) NOT NULL DEFAULT 0,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_channel_regions"=>"CREATE TABLE IF NOT EXISTS radio_channel_regions(channel_id INT UNSIGNED NOT NULL,region_id INT NOT NULL,PRIMARY KEY(channel_id,region_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_channel_users"=>"CREATE TABLE IF NOT EXISTS radio_channel_users(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,PRIMARY KEY(channel_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_channel_roles"=>"CREATE TABLE IF NOT EXISTS radio_channel_roles(channel_id INT UNSIGNED NOT NULL,role_id INT NOT NULL,PRIMARY KEY(channel_id,role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_presence"=>"CREATE TABLE IF NOT EXISTS radio_presence(channel_id INT UNSIGNED NOT NULL,user_id INT NOT NULL,last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(channel_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "radio_logs"=>"CREATE TABLE IF NOT EXISTS radio_logs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id INT UNSIGNED NULL,user_id INT NULL,event_type VARCHAR(40) NOT NULL,meta_json TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
 ];
 foreach($creates as $q)Db::run($q);
 $ensure=function($table,$column,$definition){if(!ce($table,$column))Db::run("ALTER TABLE ".$table." ADD COLUMN ".$column." ".$definition);};
 foreach([
 ['radio_channels','name','VARCHAR(100) NOT NULL'],['radio_channels','code','VARCHAR(50) NOT NULL'],['radio_channels','description','VARCHAR(255) NULL'],['radio_channels','is_active','TINYINT(1) NOT NULL DEFAULT 1'],['radio_channels','current_speaker_id','INT NULL'],['radio_channels','lock_until','DATETIME NULL'],['radio_channels','channel_type',"VARCHAR(20) NOT NULL DEFAULT 'custom'"],['radio_channels','match_mode',"VARCHAR(3) NOT NULL DEFAULT 'OR'"],['radio_channels','max_talk_ms','INT UNSIGNED NOT NULL DEFAULT 25000'],['radio_channels','priority','INT NOT NULL DEFAULT 0'],['radio_channels','created_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'],['radio_channels','updated_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
 ['radio_messages','channel_id','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_messages','sender_id','INT NOT NULL DEFAULT 0'],['radio_messages','sender_name',"VARCHAR(190) NOT NULL DEFAULT 'کاربر'"],['radio_messages','audio_path',"VARCHAR(255) NOT NULL DEFAULT ''"],['radio_messages','mime_type',"VARCHAR(80) NOT NULL DEFAULT 'audio/mp4'"],['radio_messages','duration_ms','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_messages','bytes_size','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_messages','created_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 ['radio_user_settings','enabled','TINYINT(1) NOT NULL DEFAULT 1'],['radio_user_settings','channel_id','INT UNSIGNED NULL'],['radio_user_settings','listen_all','TINYINT(1) NOT NULL DEFAULT 0'],['radio_user_settings','updated_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
 ['radio_channel_regions','channel_id','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_channel_regions','region_id','INT NOT NULL DEFAULT 0'],['radio_channel_users','channel_id','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_channel_users','user_id','INT NOT NULL DEFAULT 0'],['radio_channel_roles','channel_id','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_channel_roles','role_id','INT NOT NULL DEFAULT 0'],
 ['radio_presence','channel_id','INT UNSIGNED NOT NULL DEFAULT 0'],['radio_presence','user_id','INT NOT NULL DEFAULT 0'],['radio_presence','last_seen_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'],
 ['radio_logs','channel_id','INT UNSIGNED NULL'],['radio_logs','user_id','INT NULL'],['radio_logs','event_type',"VARCHAR(40) NOT NULL DEFAULT 'event'"],['radio_logs','meta_json','TEXT NULL'],['radio_logs','created_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']
 ] as $x){$ensure($x[0],$x[1],$x[2]);}
 $cnt=Db::one('SELECT COUNT(*) c FROM radio_channels');if((int)($cnt['c']??0)===0){foreach([['عمومی','general','کانال عمومی ارتباط خطیار'],['مدیریت','management','ارتباط مدیریت و مسئولین'],['بازرسی','inspection','ارتباط واحد بازرسی'],['عملیات خطوط','field','ارتباط عملیات میدانی خطوط']] as $ch)Db::run("INSERT INTO radio_channels(name,code,description) VALUES(?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),is_active=1",$ch);}
 $ready=true;return true;
}catch(Throwable $e){$ready=false;error_log('radio_schema bootstrap failed: '.$e->getMessage());return false;}}
function ensure_radio_auth_schema(){
  try{
    if(!te('user_sessions')) Db::run("CREATE TABLE user_sessions(
      id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,device_type VARCHAR(20) NOT NULL DEFAULT 'web',
      device_id VARCHAR(255) NOT NULL DEFAULT '',device_model VARCHAR(255) NULL,revoked_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_user_type(user_id,device_type),
      KEY idx_user_sessions_revoked(revoked_at,created_at),KEY idx_user_sessions_device(device_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $ensure=function($table,$column,$definition){if(!ce($table,$column))Db::run("ALTER TABLE ".$table." ADD COLUMN ".$column." ".$definition);};
    $ensure('user_sessions','user_id','INT NOT NULL DEFAULT 0');
    $ensure('user_sessions','device_type',"VARCHAR(20) NOT NULL DEFAULT 'web'");
    $ensure('user_sessions','device_id',"VARCHAR(255) NOT NULL DEFAULT ''");
    $ensure('user_sessions','device_model','VARCHAR(255) NULL');
    $ensure('user_sessions','revoked_at','DATETIME NULL');
    $ensure('user_sessions','created_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP');
    if(te('roles')&&!ce('roles','is_admin'))Db::run("ALTER TABLE roles ADD COLUMN is_admin TINYINT(1) NOT NULL DEFAULT 0");
    return true;
  }catch(Throwable $e){error_log('radio auth schema bootstrap failed: '.$e->getMessage());return false;}
}
function au(){global$CONFIG;if(!ensure_radio_auth_schema())re('ساختار احراز هویت بیسیم آماده نیست',503);$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))re('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.*,r.title role_title,r.level,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])re('کاربر نامعتبر است',401);if(te('user_sessions')){$dt=$p['dt']??'web';$s=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$admin=!empty($u['is_admin'])||in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);if(!$s||$s['revoked_at']||(!$admin&&(string)$s['device_id']!==(string)($p['device_id']??'')))re('نشست منقضی یا باطل شده است',401);}return$u;}
function ch($id){$c=Db::one('SELECT * FROM radio_channels WHERE id=? AND is_active=1',[(int)$id]);if(!$c)re('کانال بی‌سیم یافت نشد',404);return$c;}
function rules($id){$a=['regions'=>[],'users'=>[],'roles'=>[]];foreach($a as$k=>$_){$t=['regions'=>'radio_channel_regions','users'=>'radio_channel_users','roles'=>'radio_channel_roles'][$k];if(te($t)){$col=$k==='regions'?'region_id':($k==='users'?'user_id':'role_id');$a[$k]=array_map('intval',array_column(Db::all("SELECT $col v FROM $t WHERE channel_id=?",[$id]),'v'));}}return$a;}
function uregion($u){foreach(['region_id','area_id','zone_id','district_id']as$c)if(ce('users',$c)&&!empty($u[$c]))return(int)$u[$c];foreach(['user_regions','user_region']as$t)if(te($t)&&ce($t,'user_id'))foreach(['region_id','area_id','zone_id']as$c)if(ce($t,$c)){$r=Db::one("SELECT $c v FROM $t WHERE user_id=? LIMIT 1",[$u['id']]);if($r&&$r['v']!==null)return(int)$r['v'];}return 0;}
function okch($c,$u){$r=rules($c['id']);$g=[];if($r['regions'])$g[]=in_array(uregion($u),$r['regions'],true);if($r['roles'])$g[]=in_array((int)$u['role_id'],$r['roles'],true);if($r['users'])$g[]=in_array((int)$u['id'],$r['users'],true);if(!$g)return true;return($c['match_mode']??'OR')==='AND'?!in_array(false,$g,true):in_array(true,$g,true);}
function ec($id,$u){$c=ch($id);if(!okch($c,$u))re('شما عضو این کانال نیستید',403);return$c;}function logx($cid,$uid,$ev,$m=[]){if(te('radio_logs'))try{Db::run('INSERT INTO radio_logs(channel_id,user_id,event_type,meta_json) VALUES(?,?,?,?)',[$cid,$uid,$ev,json_encode($m,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable$e){}}
function canListenAll($u){$level=(int)($u['level']??0);return $level>=1&&$level<=4;}
function requireListenAll($u){if(!canListenAll($u))re('این قابلیت فقط برای سمت‌های سطح ۱ تا ۴ فعال است',403);}
function radio_audio_sig($id,$exp,$uid){global $CONFIG;return hash_hmac('sha256',((int)$id).'|'.((int)$exp).'|'.((int)$uid),(string)$CONFIG['jwt_secret']);}
function radio_audio_url($id,$uid){$exp=time()+900;return '/api/radio-api-v2.php?op=audio&id='.(int)$id.'&exp='.$exp.'&uid='.(int)$uid.'&sig='.radio_audio_sig($id,$exp,$uid);}
function radio_audio_signed_user(){global $CONFIG;$id=(int)($_GET['id']??0);$exp=(int)($_GET['exp']??0);$uid=(int)($_GET['uid']??0);$sig=(string)($_GET['sig']??'');if(!$id||!$uid||$exp<time()||!$sig||!hash_equals(radio_audio_sig($id,$exp,$uid),$sig))re('لینک صوتی نامعتبر یا منقضی است',401);$u=Db::one("SELECT u.*,r.title role_title,r.level,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$uid]);if(!$u||!(int)$u['is_active'])re('کاربر نامعتبر است',401);return $u;}
$u=au();if(!radio_schema())re('ساختار پایگاه‌داده بی‌سیم آماده نیست؛ لطفاً Migrationهای بی‌سیم را بررسی کنید.',500);$op=$_GET['op']??$_POST['op']??'state';$method=$_SERVER['REQUEST_METHOD']??'GET';
if($op==='channels'&&$method==='GET'){$rows=Db::all('SELECT * FROM radio_channels WHERE is_active=1 ORDER BY priority DESC,id');$o=[];foreach($rows as$c)if(okch($c,$u)){$lm=Db::one('SELECT MAX(id) m FROM radio_messages WHERE channel_id=?',[$c['id']]);$o[]=['id'=>(int)$c['id'],'name'=>$c['name'],'code'=>$c['code'],'description'=>$c['description'],'channel_type'=>$c['channel_type']??'custom','max_talk_ms'=>(int)($c['max_talk_ms']??25000),'priority'=>(int)($c['priority']??0),'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null,'last_message_id'=>(int)($lm['m']??0)];}$s=Db::one('SELECT enabled,channel_id,listen_all FROM radio_user_settings WHERE user_id=?',[$u['id']]);$wanted=(int)($s['channel_id']??0);$allowedIds=array_map('intval',array_column($o,'id'));$cid=in_array($wanted,$allowedIds,true)?$wanted:(int)($o[0]['id']??0);$allowed=canListenAll($u);$listenAll=$allowed&&$s&&!empty($s['listen_all']);$allMax=0;if($allowed){$x=Db::one('SELECT MAX(m.id) m FROM radio_messages m JOIN radio_channels c ON c.id=m.channel_id WHERE c.is_active=1');$allMax=(int)($x['m']??0);}rj(['ok'=>true,'channels'=>$o,'enabled'=>$s?(bool)$s['enabled']:true,'channel_id'=>$cid,'listen_all_allowed'=>$allowed,'listen_all'=>$listenAll,'listen_all_last_message_id'=>$allMax]);}
if($op==='state'&&$method==='GET'){$s=Db::one('SELECT enabled,channel_id FROM radio_user_settings WHERE user_id=?',[$u['id']]);$cid=(int)($s['channel_id']??0);$c=$cid?ec($cid,$u):null;rj(['ok'=>true,'enabled'=>$s?(bool)$s['enabled']:true,'channel'=>$c?['id'=>(int)$c['id'],'name'=>$c['name'],'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null]:null]);}
if($op==='presence'&&$method==='POST'){$cid=(int)(rb()['channel_id']??0);ec($cid,$u);if(te('radio_presence'))Db::run('INSERT INTO radio_presence(channel_id,user_id,last_seen_at) VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE last_seen_at=NOW()',[$cid,$u['id']]);rj(['ok'=>true]);}
if($op==='settings'&&$method==='POST'){$b=rb();$cid=(int)($b['channel_id']??0);if($cid)ec($cid,$u);$en=!empty($b['enabled'])?1:0;if(!empty($b['listen_all']))requireListenAll($u);$la=(!empty($b['listen_all'])&&canListenAll($u))?1:0;Db::run('INSERT INTO radio_user_settings(user_id,enabled,channel_id,listen_all) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),channel_id=VALUES(channel_id),listen_all=VALUES(listen_all)',[$u['id'],$en,$cid?:null,$la]);rj(['ok'=>true,'enabled'=>(bool)$en,'channel_id'=>$cid,'listen_all'=>(bool)$la]);}
if($op==='take'&&$method==='POST'){$cid=(int)(rb()['channel_id']??0);$c=ec($cid,$u);$pdo=Db::pdo();$pdo->beginTransaction();try{$row=Db::one('SELECT current_speaker_id,lock_until FROM radio_channels WHERE id=? FOR UPDATE',[$cid]);if(!empty($row['current_speaker_id'])&&strtotime((string)$row['lock_until'])>time()&&(int)$row['current_speaker_id']!==(int)$u['id']){$pdo->rollBack();re('کانال در حال استفاده است',409);}$ms=max(5000,min(120000,(int)($c['max_talk_ms']??25000)));$leaseSeconds=max(1,(int)ceil($ms/1000));Db::run('UPDATE radio_channels SET current_speaker_id=?,lock_until=DATE_ADD(NOW(), INTERVAL '.$leaseSeconds.' SECOND) WHERE id=?',[$u['id'],$cid]);$pdo->commit();logx($cid,$u['id'],'take',['max_talk_ms'=>$ms]);$name=trim(($u['first_name']??'').' '.($u['last_name']??''))?:($u['username']??'کاربر');rj(['ok'=>true,'channel_id'=>$cid,'speaker_id'=>(int)$u['id'],'speaker_name'=>$name,'lease_ms'=>$ms]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();re('گرفتن کانال ناموفق بود',500);}}
if($op==='release'&&$method==='POST'){$cid=(int)(rb()['channel_id']??0);ec($cid,$u);Db::run('UPDATE radio_channels SET current_speaker_id=NULL,lock_until=NULL WHERE id=? AND current_speaker_id=?',[$cid,$u['id']]);logx($cid,$u['id'],'release');rj(['ok'=>true]);}
if($op==='send'&&$method==='POST'){
 $cid=(int)($_POST['channel_id']??0);$c=ec($cid,$u);$row=Db::one('SELECT current_speaker_id,lock_until FROM radio_channels WHERE id=?',[$cid]);
 if((int)($row['current_speaker_id']??0)!==(int)$u['id']||strtotime((string)($row['lock_until']??''))<=time()-30)re('مجوز صحبت شما منقضی شده است',409);
 $max=(int)($c['max_talk_ms']??25000);$duration=(int)($_POST['duration_ms']??0);
 if($duration<1000||$duration>$max)re('مدت پیام صوتی نامعتبر است',422);
 $f=$_FILES['audio']??null;if(!$f||($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||empty($f['tmp_name'])||!is_uploaded_file($f['tmp_name']))re('فایل صوتی ارسال نشده است',422);
 if((int)$f['size']>160000)re('فایل صوتی بیش از حد مجاز است',413);
 $clientMime=strtolower(trim((string)($f['type']??'')));$allowed=['audio/mp4','audio/m4a','audio/x-m4a','video/mp4','audio/aac'];
 $detected='';
 if(class_exists('finfo')){$fi=new finfo(FILEINFO_MIME_TYPE);$detected=strtolower(trim((string)$fi->file($f['tmp_name'])));}
 if($clientMime!==''&&!in_array($clientMime,$allowed,true))re('فرمت صوتی مجاز نیست',415);
 if($detected!==''&&!in_array($detected,$allowed,true))re('محتوای فایل صوتی معتبر نیست',415);
 $mime=$detected!==''?$detected:($clientMime?:'audio/mp4');
 $dir=__DIR__.'/uploads/radio';if(!is_dir($dir)&&!@mkdir($dir,0750,true))re('فضای ذخیره بی‌سیم قابل ایجاد نیست',500);
 $tmpName='.upload_'.bin2hex(random_bytes(12)).'.tmp';$tmpPath=$dir.'/'.$tmpName;$finalPath=null;$pdo=Db::pdo();
 if(!@move_uploaded_file($f['tmp_name'],$tmpPath))re('ذخیره فایل صوتی ناموفق بود',500);
 try{
   $pdo->beginTransaction();
   $name=trim(($u['first_name']??'').' '.($u['last_name']??''))?:($u['username']??'کاربر');
   Db::run('INSERT INTO radio_messages(channel_id,sender_id,sender_name,audio_path,mime_type,duration_ms,bytes_size) VALUES(?,?,?,?,?,?,?)',[$cid,$u['id'],$name,'uploads/radio/'.$tmpName,$mime,$duration,(int)$f['size']]);
   $id=(int)$pdo->lastInsertId();if($id<=0)throw new RuntimeException('شناسه پیام صوتی ایجاد نشد.');
   $finalName=$id.'.m4a';$finalPath=$dir.'/'.$finalName;
   if(!@rename($tmpPath,$finalPath))throw new RuntimeException('انتقال فایل صوتی ناموفق بود.');
   $realSize=(int)(@filesize($finalPath)?:0);if($realSize<=0)throw new RuntimeException('فایل صوتی ذخیره‌شده خالی است.');
   Db::run('UPDATE radio_messages SET audio_path=?,mime_type=?,bytes_size=? WHERE id=?',['uploads/radio/'.$finalName,$mime,$realSize,$id]);
   Db::run('UPDATE radio_channels SET current_speaker_id=NULL,lock_until=NULL WHERE id=? AND current_speaker_id=?',[$cid,$u['id']]);
   $pdo->commit();
   logx($cid,$u['id'],'send',['message_id'=>$id,'duration_ms'=>$duration,'bytes_size'=>$realSize]);
   rj(['ok'=>true,'message'=>['id'=>$id,'channel_id'=>$cid,'sender_id'=>(int)$u['id'],'sender_name'=>$name,'duration_ms'=>$duration,'audio_url'=>radio_audio_url($id,(int)$u['id'])]]);
 }catch(Throwable $e){
   if($pdo->inTransaction())$pdo->rollBack();
   @unlink($tmpPath);if($finalPath)@unlink($finalPath);
   try{Db::run('UPDATE radio_channels SET current_speaker_id=NULL,lock_until=NULL WHERE id=? AND current_speaker_id=?',[$cid,$u['id']]);}catch(Throwable $ignored){}
   re('ارسال پیام صوتی ناموفق بود',500);
 }
}
if($op==='poll-all'&&$method==='GET'){requireListenAll($u);$after=(int)($_GET['after']??0);$rows=Db::all('SELECT * FROM radio_channels WHERE is_active=1');$ids=[];$names=[];foreach($rows as$c){if(!okch($c,$u))continue;$ids[]=(int)$c['id'];$names[(int)$c['id']]=$c['name'];}if(!$ids)rj(['ok'=>true,'messages'=>[]]);$ph=implode(',',array_fill(0,count($ids),'?'));$params=$ids;$params[]=$after;$msgs=Db::all("SELECT id,channel_id,sender_id,sender_name,duration_ms,bytes_size,created_at FROM radio_messages WHERE channel_id IN ($ph) AND id>? ORDER BY id ASC LIMIT 30",$params);foreach($msgs as&$r){$r['audio_url']=radio_audio_url((int)$r['id'],(int)$u['id']);$r['channel_name']=$names[(int)$r['channel_id']]??'';}unset($r);rj(['ok'=>true,'messages'=>$msgs]);}
if($op==='archive'&&$method==='GET'){$cid=(int)($_GET['channel_id']??0);ec($cid,$u);$hours=max(1,min(720,(int)($_GET['hours']??24)));$before=(int)($_GET['before']??PHP_INT_MAX);$limit=max(1,min(300,(int)($_GET['limit']??100)));$rows=Db::all('SELECT id,channel_id,sender_id,sender_name,duration_ms,bytes_size,created_at FROM radio_messages WHERE channel_id=? AND id<? AND created_at>=DATE_SUB(NOW(),INTERVAL ? HOUR) ORDER BY id DESC LIMIT '.$limit,[$cid,$before,$hours]);foreach($rows as&$r)$r['audio_url']=radio_audio_url((int)$r['id'],(int)$u['id']);unset($r);rj(['ok'=>true,'messages'=>$rows,'hours'=>$hours]);}
if($op==='poll'&&$method==='GET'){$cid=(int)($_GET['channel_id']??0);$after=(int)($_GET['after']??0);$c=ec($cid,$u);$rows=Db::all('SELECT id,channel_id,sender_id,sender_name,duration_ms,bytes_size,created_at FROM radio_messages WHERE channel_id=? AND id>? ORDER BY id ASC LIMIT 10',[$cid,$after]);foreach($rows as&$r)$r['audio_url']=radio_audio_url((int)$r['id'],(int)$u['id']);unset($r);$speakerName=null;$speakerRole=null;if(!empty($c['current_speaker_id'])){if((int)$c['current_speaker_id']===(int)$u['id']){$speakerName='شما';$speakerRole=$u['role_title']??'';}else{$su=Db::one('SELECT u.first_name,u.last_name,u.username,r.title role_title FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1',[$c['current_speaker_id']]);$speakerName=$su?(trim(($su['first_name']??'').' '.($su['last_name']??''))?:($su['username']??'کاربر')):'کاربر';$speakerRole=$su['role_title']??'';}}rj(['ok'=>true,'messages'=>$rows,'busy'=>!empty($c['current_speaker_id'])&&strtotime((string)$c['lock_until'])>time(),'speaker_id'=>$c['current_speaker_id']?(int)$c['current_speaker_id']:null,'speaker_name'=>$speakerName,'speaker_role'=>$speakerRole]);}
if($op==='responsible-recent'&&$method==='GET'){$cid=(int)($_GET['channel_id']??0);ec($cid,$u);$sql='SELECT m.id,m.channel_id,m.sender_id,m.sender_name,m.duration_ms,m.bytes_size,m.created_at,r.title role_title,r.level role_level FROM radio_messages m INNER JOIN users su ON su.id=m.sender_id INNER JOIN roles r ON r.id=su.role_id WHERE m.channel_id=? AND r.level BETWEEN 1 AND 5 ORDER BY m.created_at DESC,m.id DESC LIMIT 3';$rows=Db::all($sql,[$cid]);foreach($rows as&$r){$r['role_level']=(int)$r['role_level'];$r['audio_url']=radio_audio_url((int)$r['id'],(int)$u['id']);}unset($r);rj(['ok'=>true,'messages'=>$rows]);}
if($op==='latest-three'&&$method==='GET'){$cid=(int)($_GET['channel_id']??0);ec($cid,$u);$sql='SELECT m.id,m.channel_id,m.sender_id,m.sender_name,m.duration_ms,m.bytes_size,m.created_at,r.title role_title FROM radio_messages m LEFT JOIN users su ON su.id=m.sender_id LEFT JOIN roles r ON r.id=su.role_id WHERE m.channel_id=? ORDER BY m.created_at DESC,m.id DESC LIMIT 3';$rows=Db::all($sql,[$cid]);foreach($rows as&$r)$r['audio_url']=radio_audio_url((int)$r['id'],(int)$u['id']);unset($r);rj(['ok'=>true,'messages'=>$rows]);}
if($op==='audio'&&$method==='GET'){if(isset($_GET['sig'])){$u=radio_audio_signed_user();} $id=(int)($_GET['id']??0);$m=Db::one('SELECT m.*,c.is_active FROM radio_messages m JOIN radio_channels c ON c.id=m.channel_id WHERE m.id=?',[$id]);if(!$m||!(int)$m['is_active'])re('پیام صوتی یافت نشد',404);if(canListenAll($u))ch($m['channel_id']);else ec($m['channel_id'],$u);$p=__DIR__.'/'.$m['audio_path'];if(!is_file($p))re('فایل صوتی یافت نشد',404);header('Content-Type: '.($m['mime_type']?:'audio/mp4'));header('Content-Length:'.filesize($p));header('Content-Disposition:inline; filename="radio-'.$id.'.m4a"');readfile($p);exit;}
re('عملیات بی‌سیم نامعتبر است',404);