<?php
ini_set('display_errors','0'); error_reporting(E_ALL);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store');
$R=__DIR__.'/..'; require "$R/lib/Db.php"; require "$R/lib/Jwt.php"; require "$R/lib/LineImageCompressor.php"; $C=require "$R/config.php";
function sw_json($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function sw_err($m,$s=400){sw_json(['error'=>$m],$s);}
function sw_user(){global $C;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))sw_err('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$C['jwt_secret']);if(!$p)sw_err('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.is_admin FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?",[$p['sub']]);if(!$u||!$u['is_active'])sw_err('کاربر نامعتبر است',401);return $u;}
function sw_admin($u){return !empty($u['is_admin'])||in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);}
function sw_okline($u,$id){if(sw_admin($u))return true;return !!Db::one('SELECT 1 FROM user_lines WHERE user_id=? AND line_id=?',[$u['id'],$id]);}
function sw_dist($a,$b,$c,$d){$p=M_PI/180;$x=sin(($c-$a)*$p/2)**2+cos($a*$p)*cos($c*$p)*sin(($d-$b)*$p/2)**2;return 6371000*2*asin(min(1,sqrt($x)));}
function sw_col($table,$col,$def){$q=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$table,$col]);if(!(int)($q['c']??0))Db::run("ALTER TABLE `$table` ADD COLUMN `$col` ".$def);}
function sw_schema(){
  Db::run("CREATE TABLE IF NOT EXISTS line_station_locations (id BIGINT AUTO_INCREMENT PRIMARY KEY,line_id INT NOT NULL,station_code VARCHAR(80) NULL,station_status VARCHAR(30) NOT NULL DEFAULT 'registered',station_name VARCHAR(190) NULL,latitude DECIMAL(10,7) NOT NULL,longitude DECIMAL(10,7) NOT NULL,accuracy_m DECIMAL(10,2) NULL,physical_address TEXT NULL,street VARCHAR(190) NULL,location_photo_path VARCHAR(500) NULL,captured_by INT NOT NULL,captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_lsl_line(line_id),INDEX idx_lsl_captured(captured_by,captured_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  foreach([['station_code','VARCHAR(80) NULL'],['station_status',"VARCHAR(30) NOT NULL DEFAULT 'registered'"],['physical_address','TEXT NULL'],['street','VARCHAR(190) NULL'],['updated_at','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP']] as $x)sw_col('line_station_locations',$x[0],$x[1]);
  Db::run("CREATE TABLE IF NOT EXISTS line_station_signs (id BIGINT AUTO_INCREMENT PRIMARY KEY,station_location_id BIGINT NOT NULL,sign_type_id INT NOT NULL,photo_path VARCHAR(500) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_lss_station(station_location_id),INDEX idx_lss_type(sign_type_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  foreach([['station_location_id','BIGINT NULL'],['station_code','VARCHAR(80) NULL'],['station_status',"VARCHAR(30) NOT NULL DEFAULT 'registered'"],['physical_address','TEXT NULL'],['street','VARCHAR(190) NULL']] as $x)sw_col('line_station_locations',$x[0],$x[1]);
  foreach([['latitude','DECIMAL(10,7) NULL'],['longitude','DECIMAL(10,7) NULL'],['location_accuracy_m','DECIMAL(10,2) NULL'],['station_name','VARCHAR(190) NULL'],['location_photo_path','VARCHAR(500) NULL'],['location_updated_by','INT NULL'],['location_updated_at','DATETIME NULL'],['station_location_id','BIGINT NULL'],['station_physical_address','TEXT NULL'],['station_street','VARCHAR(190) NULL']] as $x)sw_col('lines',$x[0],$x[1]);
  Db::run("CREATE TABLE IF NOT EXISTS geofences(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,line_id BIGINT NOT NULL,type VARCHAR(30) NOT NULL DEFAULT 'circle',center_lat DECIMAL(10,7) NULL,center_lng DECIMAL(10,7) NULL,radius_m INT NOT NULL DEFAULT 100,polygon LONGTEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_geo_line(line_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  foreach([['station_location_id','BIGINT NULL'],['station_code','VARCHAR(80) NULL'],['purpose',"VARCHAR(40) NOT NULL DEFAULT 'station_attendance'"],['base_radius_m','INT NOT NULL DEFAULT 100'],['edge_tolerance_m','INT NOT NULL DEFAULT 0']] as $x)sw_col('geofences',$x[0],$x[1]);
}
function sw_pic($v,$p){if(!$v)return null;if(strpos($v,'base64,')!==false)$v=base64_decode(substr($v,strpos($v,',')+1),true);if(!$v||strlen($v)>8*1024*1024||@getimagesizefromstring($v)===false)sw_err('تصویر نامعتبر یا بزرگ است');$r='/uploads/line-locations/'.date('Y/m').'/';$d=__DIR__.$r;@mkdir($d,0775,true);$f=$d.$p.'_'.bin2hex(random_bytes(7)).'.jpg';if(!LineImageCompressor::fromBinary($v,$f))sw_err('ذخیره تصویر ناموفق بود',500);return $r.basename($f);}
function sw_edge(){try{$r=Db::one("SELECT value FROM app_settings WHERE `key`='checkin_error_radius_m'");return max(0,(int)($r['value']??0));}catch(Throwable $e){return 0;}}
function sw_sync_geo($lineId,$stationId,$code,$name,$lat,$lng){try{Db::run("DELETE FROM geofences WHERE line_id=? AND purpose='station_attendance'",[$lineId]);}catch(Throwable $e){}$edge=sw_edge();Db::run("INSERT INTO geofences(name,line_id,type,center_lat,center_lng,radius_m,polygon,station_location_id,station_code,purpose,base_radius_m,edge_tolerance_m) VALUES(?,?,'circle',?,?,100,NULL,?,?,?,100,?)",[$name!==''?$name:($code!==''?'ایستگاه '.$code:'ایستگاه'),$lineId,$lat,$lng,$stationId,$code!==''?$code:null,'station_attendance',$edge]);return (int)Db::lastId();}
$u=sw_user();sw_schema();$op=$_GET['op']??'types';
if($op==='types')sw_json(Db::all('SELECT id,title,code FROM station_sign_types WHERE is_active=1 ORDER BY sort_order,title'));
if($op==='lines'){$r=Db::all("SELECT l.id,l.code,l.origin,l.destination,l.status,l.latitude,l.longitude,l.location_accuracy_m,l.station_name,l.station_location_id,l.station_physical_address,l.station_street,(SELECT s.station_code FROM line_station_locations s WHERE s.line_id=l.id ORDER BY s.id DESC LIMIT 1) station_code,(SELECT s.station_status FROM line_station_locations s WHERE s.line_id=l.id ORDER BY s.id DESC LIMIT 1) station_status FROM `lines` l ORDER BY l.code");if(!sw_admin($u)){$ids=array_map('intval',array_column(Db::all('SELECT line_id FROM user_lines WHERE user_id=?',[$u['id']]),'line_id'));$r=array_values(array_filter($r,fn($x)=>in_array((int)$x['id'],$ids,true)));}sw_json($r);}
if($op==='nearest-line'){$lat=(float)($_GET['lat']??0);$lng=(float)($_GET['lng']??0);$best=null;$bd=INF;foreach(Db::all('SELECT id,code,origin,destination,status,latitude,longitude,station_name FROM `lines` WHERE latitude IS NOT NULL AND longitude IS NOT NULL') as $r){if(!sw_okline($u,$r['id']))continue;$d=sw_dist($lat,$lng,$r['latitude'],$r['longitude']);if($d<$bd){$bd=$d;$best=$r;$best['distance_m']=round($d,1);}}sw_json(['line'=>$best]);}
if($op==='mine'){$r=Db::all("SELECT s.*,l.code line_code,l.origin,l.destination,(SELECT COUNT(*) FROM line_station_signs z WHERE z.station_location_id=s.id) sign_count FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE s.captured_by=? ORDER BY s.updated_at DESC,s.id DESC",[$u['id']]);sw_json($r);}
if($op==='detail'){$id=(int)($_GET['id']??0);$s=Db::one('SELECT s.*,l.code line_code,l.origin,l.destination FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE s.id=?',[$id]);if(!$s)sw_err('ایستگاه یافت نشد',404);if((int)$s['captured_by']!==(int)$u['id']&&!sw_admin($u))sw_err('دسترسی ندارید',403);$s['signs']=Db::all('SELECT z.id,z.sign_type_id,t.title,z.photo_path FROM line_station_signs z JOIN station_sign_types t ON t.id=z.sign_type_id WHERE z.station_location_id=? ORDER BY z.id',[$id]);sw_json($s);}
if($op==='save'){
  $b=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($b['station_id']??0);$lid=(int)($b['line_id']??0);if(!$lid)sw_err('خط انتخاب نشده است');if(!sw_okline($u,$lid))sw_err('خط در محدوده دسترسی شما نیست',403);
  $lat=$b['latitude']??null;$lng=$b['longitude']??null;$method=($b['location_method']??'gps')==='manual'?'manual':'gps';$acc=$b['accuracy_m']??null;if(!is_numeric($lat)||!is_numeric($lng)||$lat<-90||$lat>90||$lng<-180||$lng>180)sw_err('مختصات نامعتبر است');if($method==='gps'&&(!is_numeric($acc)||$acc<0||$acc>20))sw_err('دقت GPS باید حداکثر ۲۰ متر باشد',422);if($method==='manual')$acc=null;
  $existing=$id?Db::one('SELECT * FROM line_station_locations WHERE id=?',[$id]):Db::one('SELECT * FROM line_station_locations WHERE line_id=? ORDER BY id DESC LIMIT 1',[$lid]);if($existing){$id=(int)$existing['id'];if((int)$existing['line_id']!==$lid)sw_err('ایستگاه انتخاب‌شده متعلق به این خط نیست',409);if((int)$existing['captured_by']!==(int)$u['id']&&!sw_admin($u))sw_err('فقط ثبت‌کننده می‌تواند ایستگاه را ویرایش کند',403);}
  $status=($b['station_status']??'registered')==='missing'?'missing':'registered';$code=trim((string)($b['station_code']??''));$name=trim((string)($b['station_name']??''));$address=trim((string)($b['physical_address']??''));$street=trim((string)($b['street']??''));if($existing&&$code==='')$code=trim((string)($existing['station_code']??''));if($status==='registered'&&!$code){$code=(string)$lid;}if($status==='registered'&&!preg_match('/^\d+$/',$code))sw_err('شناسه عددی ایستگاه نامعتبر است');
  $signs=$b['signs']??[];if(!is_array($signs)||!count($signs))sw_err('حداقل یک تابلو ثبت کنید');$now=date('Y-m-d H:i:s');$lp=sw_pic($b['location_photo']??null,'station-location');if($existing){if(!$lp)$lp=$existing['location_photo_path']??null;Db::run('UPDATE line_station_locations SET line_id=?,station_code=?,station_status=?,station_name=?,latitude=?,longitude=?,accuracy_m=?,physical_address=?,street=?,location_photo_path=?,updated_at=? WHERE id=?',[$lid,$code?:null,$status,$name?:null,$lat,$lng,$acc,$address?:null,$street?:null,$lp,$now,$id]);$sid=$id;Db::run('DELETE FROM line_station_signs WHERE station_location_id=?',[$sid]);}else{Db::run('INSERT INTO line_station_locations(line_id,station_code,station_status,station_name,latitude,longitude,accuracy_m,physical_address,street,location_photo_path,captured_by,captured_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[$lid,$code?:null,$status,$name?:null,$lat,$lng,$acc,$address?:null,$street?:null,$lp,$u['id'],$now,$now]);$sid=(int)Db::lastId();}
  foreach($signs as $sg){$tid=(int)($sg['type_id']??0);if(!Db::one('SELECT id FROM station_sign_types WHERE id=? AND is_active=1',[$tid]))sw_err('نوع تابلو نامعتبر است');$p=sw_pic($sg['photo']??null,'station-sign');if(!$p)$p=trim((string)($sg['photo_path']??''));if(!$p)sw_err('تصویر تابلو الزامی است');Db::run('INSERT INTO line_station_signs(station_location_id,sign_type_id,photo_path) VALUES(?,?,?)',[$sid,$tid,$p]);}
  $geo=sw_sync_geo($lid,$sid,$code,$name,$lat,$lng);Db::run('UPDATE `lines` SET latitude=?,longitude=?,location_accuracy_m=?,station_name=?,location_updated_by=?,location_updated_at=?,station_location_id=?,station_physical_address=?,station_street=? WHERE id=?',[$lat,$lng,$acc,$name?:null,$u['id'],$now,$sid,$address?:null,$street?:null,$lid]);$g=Db::one('SELECT base_radius_m,edge_tolerance_m FROM geofences WHERE id=?',[$geo])?:['base_radius_m'=>100,'edge_tolerance_m'=>0];$line=Db::one('SELECT code FROM `lines` WHERE id=?',[$lid]);sw_json(['ok'=>true,'id'=>$sid,'line_id'=>$lid,'line_code'=>$line['code']??'','station_code'=>$code,'location_method'=>$method,'geofence_id'=>$geo,'geofence_base_radius_m'=>(int)$g['base_radius_m'],'geofence_edge_tolerance_m'=>(int)$g['edge_tolerance_m'],'effective_max_distance_m'=>(int)$g['base_radius_m']+(int)$g['edge_tolerance_m'],'updated_at'=>$now]);
}
sw_err('عملیات نامعتبر است',404);
