<?php
ini_set('display_errors','0');error_reporting(E_ALL);date_default_timezone_set('Asia/Tehran');header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$R=__DIR__.'/..';require "$R/lib/Db.php";require "$R/lib/Jwt.php";$CFG=require "$R/config.php";
function scr_json($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function scr_err($m,$s=400){scr_json(['error'=>$m],$s);}
function scr_user(){global $CFG;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))scr_err('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$CFG['jwt_secret']);if(!$p)scr_err('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.is_admin FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?",[$p['sub']]);if(!$u||!$u['is_active'])scr_err('کاربر نامعتبر است',401);return $u;}
function scr_admin($u){return !empty($u['is_admin'])||in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);}
function jal($dt){try{$d=new DateTime($dt,new DateTimeZone('Asia/Tehran'));$gy=(int)$d->format('Y')-1600;$gm=(int)$d->format('n')-1;$gd=(int)$d->format('j')-1;$md=[31,28,31,30,31,30,31,31,30,31,30,31];$y=$gy+1600;$md[1]=((($y%4===0)&&($y%100!==0))||$y%400===0)?29:28;$gdn=365*$gy+intdiv($gy+3,4)-intdiv($gy+99,100)+intdiv($gy+399,400);for($i=0;$i<$gm;$i++)$gdn+=$md[$i];$gdn+=$gd;$jdn=$gdn-79;$jnp=intdiv($jdn,12053);$jdn%=12053;$jy=979+33*$jnp+4*intdiv($jdn,1461);$jdn%=1461;if($jdn>=366){$jy+=intdiv($jdn-1,365);$jdn=($jdn-1)%365;}$jm=$jdn<186?1+intdiv($jdn,31):7+intdiv($jdn-186,30);$jd=1+($jdn<186?$jdn%31:($jdn-186)%30);return sprintf('%04d/%02d/%02d %s',$jy,$jm,$jd,$d->format('H:i:s'));}catch(Throwable $e){return $dt;}}
$u=scr_user();if(!scr_admin($u))scr_err('دسترسی گزارش ایستگاه‌ها ندارید',403);$op=trim((string)($_GET['op']??'rows'));
if($op==='detail'){$id=(int)($_GET['station_id']??0);if(!$id)scr_err('شناسه ایستگاه نامعتبر است');$s=Db::one("SELECT s.id,s.line_id,s.station_status,s.latitude,s.longitude,s.accuracy_m,s.physical_address,s.location_photo_path,s.captured_at,l.code line_code,l.origin,l.destination,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) captured_by FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id LEFT JOIN users u ON u.id=s.captured_by WHERE s.id=?",[$id]);if(!$s)scr_err('ایستگاه یافت نشد',404);$s['captured_at_jalali']=jal($s['captured_at']);$s['signs']=Db::all("SELECT z.id,z.sign_type_id,t.title,z.photo_path FROM line_station_signs z JOIN station_sign_types t ON t.id=z.sign_type_id WHERE z.station_location_id=? ORDER BY z.id",[$id]);scr_json($s);}
if($op==='map'){try{$rows=Db::all("SELECT l.id line_id,l.code line_code,l.origin,l.destination,l.status line_status,l.latitude line_latitude,l.longitude line_longitude,s.id station_id,s.latitude station_latitude,s.longitude station_longitude,s.accuracy_m,s.physical_address,s.location_photo_path,s.captured_at,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) captured_by,(SELECT COUNT(*) FROM line_station_signs sx WHERE sx.station_location_id=s.id) sign_count FROM `lines` l LEFT JOIN line_station_locations s ON s.id=(SELECT MAX(s2.id) FROM line_station_locations s2 WHERE s2.line_id=l.id) LEFT JOIN users u ON u.id=s.captured_by ORDER BY l.code,l.id");foreach($rows as &$r){$r['registered']=!empty($r['station_id']);$r['latitude']=$r['station_id']!==null?$r['station_latitude']:$r['line_latitude'];$r['longitude']=$r['station_id']!==null?$r['station_longitude']:$r['line_longitude'];$r['status_color']=$r['registered']?'green':'red';$r['captured_at_jalali']=$r['captured_at']?jal($r['captured_at']):null;}scr_json($rows);}catch(Throwable $e){scr_err('خطا در نقشه خطوط: '.$e->getMessage(),500);}}
$status=trim((string)($_GET['station_status']??''));$type=(int)($_GET['type_id']??0);$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$where=[];$args=[];if($status!==''){$where[]='s.station_status=?';$args[]=$status;}if($type>0){$where[]='sg.sign_type_id=?';$args[]=$type;}if($from!==''){$where[]='DATE(s.captured_at)>=?';$args[]=$from;}if($to!==''){$where[]='DATE(s.captured_at)<=?';$args[]=$to;}$w=$where?' WHERE '.implode(' AND ',$where):'';try{$rows=Db::all("SELECT s.id,s.line_id,s.station_code,s.station_status,s.station_name,s.latitude,s.longitude,s.accuracy_m,s.physical_address,s.location_photo_path,s.captured_at,l.code line_code,l.origin,l.destination,t.id sign_type_id,t.title sign_type,sg.photo_path,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) captured_by,(SELECT COUNT(*) FROM line_station_signs sx WHERE sx.station_location_id=s.id) sign_count FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id LEFT JOIN line_station_signs sg ON sg.station_location_id=s.id LEFT JOIN station_sign_types t ON t.id=sg.sign_type_id LEFT JOIN users u ON u.id=s.captured_by $w ORDER BY s.captured_at DESC,sg.id ASC",$args);foreach($rows as &$r)$r['captured_at_jalali']=jal($r['captured_at']);scr_json($rows);}catch(Throwable $e){scr_err('خطا در گزارش ثبت‌های ایستگاه: '.$e->getMessage(),500);}
