<?php
ini_set('display_errors','0');error_reporting(E_ALL);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$R=__DIR__.'/..';require "$R/lib/Db.php";require "$R/lib/Jwt.php";require "$R/lib/LineImageCompressor.php";$C=require "$R/config.php";
function o($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function e($m,$s=400){o(['error'=>$m],$s);}function u(){global $C;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))e('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$C['jwt_secret']);if(!$p)e('توکن منقضی است',401);$x=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.is_admin FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?",[$p['sub']]);if(!$x||!$x['is_active'])e('کاربر نامعتبر است',401);return $x;}function adm($u){return !empty($u['is_admin'])||in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);}function okline($u,$id){if(adm($u))return true;return !!Db::one('SELECT 1 FROM user_lines WHERE user_id=? AND line_id=?',[$u['id'],$id]);}function pic($v,$p){if(!$v)return null;if(strpos($v,'base64,')!==false)$v=base64_decode(substr($v,strpos($v,',')+1),true);if(!$v||strlen($v)>8*1024*1024||@getimagesizefromstring($v)===false)e('تصویر نامعتبر یا بزرگ است');$r='/uploads/line-locations/'.date('Y/m').'/';$d=__DIR__.$r;@mkdir($d,0775,true);$f=$d.$p.'_'.bin2hex(random_bytes(7)).'.jpg';if(!LineImageCompressor::fromBinary($v,$f))e('ذخیره تصویر ناموفق بود',500);return $r.basename($f);}function hd($a,$b,$c,$d){$p=M_PI/180;$x=sin(($c-$a)*$p/2)**2+cos($a*$p)*cos($c*$p)*sin(($d-$b)*$p/2)**2;return 6371000*2*asin(min(1,sqrt($x)));}
function schema(){foreach(["physical_address TEXT NULL","street VARCHAR(190) NULL","location_photo_path VARCHAR(500) NULL"] as $d){$c=strtok($d,' ');$n=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='line_station_locations' AND COLUMN_NAME=?",[$c]);if(!(int)($n['c']??0))Db::run("ALTER TABLE line_station_locations ADD COLUMN `$c` ".substr($d,strlen($c)));}}
$u=u();schema();$op=$_GET['op']??'types';
if($op==='types')o(Db::all('SELECT id,title,code FROM station_sign_types WHERE is_active=1 ORDER BY sort_order,title'));
if($op==='lines'){$r=Db::all('SELECT id,code,origin,destination,status,latitude,longitude,station_name FROM `lines` ORDER BY code');if(!adm($u)){$ids=array_column(Db::all('SELECT line_id FROM user_lines WHERE user_id=?',[$u['id']]),'line_id');$r=array_values(array_filter($r,fn($x)=>in_array($x['id'],$ids)));}o($r);}
if($op==='nearest-line'){$lat=(float)($_GET['lat']??0);$lng=(float)($_GET['lng']??0);$best=null;$bd=INF;foreach(Db::all('SELECT id,code,origin,destination,status,latitude,longitude FROM `lines` WHERE latitude IS NOT NULL AND longitude IS NOT NULL') as $r){if(!okline($u,$r['id']))continue;$d=hd($lat,$lng,$r['latitude'],$r['longitude']);if($d<$bd){$bd=$d;$best=$r;$best['distance_m']=round($d,1);}}o(['line'=>$best]);}
if($op==='mine')o(Db::all("SELECT s.*,l.code line_code,l.origin,l.destination,(SELECT COUNT(*) FROM line_station_signs z WHERE z.station_location_id=s.id) sign_count FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE s.captured_by=? ORDER BY s.captured_at DESC",[$u['id']]));
if($op==='detail'){$id=(int)($_GET['id']??0);$s=Db::one('SELECT s.*,l.code line_code,l.origin,l.destination FROM line_station_locations s JOIN `lines` l ON l.id=s.line_id WHERE s.id=?',[$id]);if(!$s)e('ایستگاه یافت نشد',404);if((int)$s['captured_by']!==(int)$u['id']&&!adm($u))e('دسترسی ندارید',403);$s['signs']=Db::all('SELECT z.id,z.sign_type_id,t.title,z.photo_path FROM line_station_signs z JOIN station_sign_types t ON t.id=z.sign_type_id WHERE z.station_location_id=?',[$id]);o($s);}
if($op==='save'){$b=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($b['station_id']??0);$lid=(int)($b['line_id']??0);if(!okline($u,$lid))e('خط در محدوده دسترسی شما نیست',403);$lat=$b['latitude']??null;$lng=$b['longitude']??null;$method=($b['location_method']??'gps')==='manual'?'manual':'gps';$acc=$b['accuracy_m']??null;if(!is_numeric($lat)||!is_numeric($lng)||$lat<-90||$lat>90||$lng<-180||$lng>180)e('مختصات نامعتبر است');if($method==='gps'&&(!is_numeric($acc)||$acc<0||$acc>20))e('دقت GPS باید حداکثر ۲۰ متر باشد',422);if($method==='manual')$acc=null;$status=($b['station_status']??'registered')==='missing'?'missing':'registered';$code=trim((string)($b['station_code']??''));$name=trim((string)($b['station_name']??''));$address=trim((string)($b['physical_address']??''));$street=trim((string)($b['street']??''));if($id){$old=Db::one('SELECT * FROM line_station_locations WHERE id=?',[$id]);if(!$old)e('ایستگاه یافت نشد',404);if((int)$old['captured_by']!==(int)$u['id']&&!adm($u))e('فقط ثبت کننده می‌تواند ویرایش کند',403);if($code==='')$code=trim((string)($old['station_code']??''));}if($status==='registered'&&!$code){$r=Db::one("SELECT MAX(CAST(station_code AS UNSIGNED)) m FROM line_station_locations WHERE line_id=? AND station_code REGEXP '^[0-9]+$'",[$lid]);$code=(string)(((int)($r['m']??0))+1);}if($status==='registered'&&!preg_match('/^\d+$/',$code))e('شناسه عددی ایستگاه نامعتبر است');$signs=$b['signs']??[];if(!is_array($signs)||!count($signs))e('حداقل یک تابلو ثبت کنید');$now=date('Y-m-d H:i:s');$lp=pic($b['location_photo']??null,'station-location');if($id){Db::run('UPDATE line_station_locations SET line_id=?,station_code=?,station_status=?,station_name=?,latitude=?,longitude=?,accuracy_m=?,physical_address=?,street=?,location_photo_path=COALESCE(?,location_photo_path),captured_at=? WHERE id=?',[$lid,$code?:null,$status,$name?:null,$lat,$lng,$acc,$address?:null,$street?:null,$lp,$now,$id]);$sid=$id;Db::run('DELETE FROM line_station_signs WHERE station_location_id=?',[$id]);}else{Db::run('INSERT INTO line_station_locations(line_id,station_code,station_status,station_name,latitude,longitude,accuracy_m,physical_address,street,location_photo_path,captured_by,captured_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[$lid,$code?:null,$status,$name?:null,$lat,$lng,$acc,$address?:null,$street?:null,$lp,$u['id'],$now]);$sid=(int)Db::lastId();}foreach($signs as $sg){$tid=(int)($sg['type_id']??0);if(!Db::one('SELECT id FROM station_sign_types WHERE id=? AND is_active=1',[$tid]))e('نوع تابلو نامعتبر است');$p=pic($sg['photo']??null,'station-sign');if(!$p){if(!empty($sg['photo_path']))$p=$sg['photo_path'];else e('تصویر تابلو الزامی است');}Db::run('INSERT INTO line_station_signs(station_location_id,sign_type_id,photo_path) VALUES(?,?,?)',[$sid,$tid,$p]);}o(['ok'=>true,'id'=>$sid,'line_id'=>$lid,'line_code'=>Db::one('SELECT code FROM `lines` WHERE id=?',[$lid])['code'],'station_code'=>$code,'location_method'=>$method,'updated_at'=>$now]);}
e('عملیات نامعتبر است',404);
