<?php
ini_set('display_errors','0');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
require __DIR__.'/../lib/Db.php'; require __DIR__.'/../lib/Jwt.php';
$C=require __DIR__.'/../config.php';
function sa4_json($x,$status=200){http_response_code($status);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function sa4_auth(){global $C;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))sa4_json(['error'=>'توکن نامعتبر است'],401);$p=Jwt::verify(trim($m[1]),$C['jwt_secret']);if(!$p||empty($p['sub']))sa4_json(['error'=>'توکن منقضی یا نامعتبر است'],401);$u=Db::one("SELECT u.id,u.role_id,u.is_active,r.title role_title,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])sa4_json(['error'=>'کاربر نامعتبر است'],401);return $u;}
function sa4_admin($u){return !empty($u['is_admin'])||in_array((string)($u['role_title']??''),['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);}
function sa4_schema(){Db::run("CREATE TABLE IF NOT EXISTS station_sign_types (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,code VARCHAR(80) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_sst_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
function sa4_image_url($kind,$id){$id=(int)$id;if(!$id)return null;return '/api/station-image.php?'.($kind==='sign'?'sign_id':'station_id').'='.$id;}
$u=sa4_auth();if(!sa4_admin($u))sa4_json(['error'=>'دسترسی غیرمجاز'],403);sa4_schema();$op=$_GET['op']??'map';
if($op==='types'){sa4_json(['success'=>true,'types'=>Db::all('SELECT id,title,code,is_active,sort_order FROM station_sign_types ORDER BY sort_order,title,id')]);}
if($op==='save-type'){$b=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($b['id']??0);$title=trim((string)($b['title']??''));$code=trim((string)($b['code']??''));$active=!empty($b['is_active'])?1:0;$sort=(int)($b['sort_order']??0);if($title==='')sa4_json(['error'=>'عنوان نوع تابلو الزامی است'],422);if($id)Db::run('UPDATE station_sign_types SET title=?,code=?,is_active=?,sort_order=? WHERE id=?',[$title,$code?:null,$active,$sort,$id]);else{Db::run('INSERT INTO station_sign_types(title,code,is_active,sort_order) VALUES(?,?,?,?)',[$title,$code?:null,$active,$sort]);$id=(int)Db::lastId();}sa4_json(['success'=>true,'id'=>$id]);}
if($op==='delete-type'){$id=(int)($_POST['id']??$_GET['id']??0);if(!$id)sa4_json(['error'=>'شناسه نامعتبر است'],422);$n=Db::one('SELECT COUNT(*) c FROM line_station_signs WHERE sign_type_id=?',[$id]);if((int)($n['c']??0)>0){Db::run('UPDATE station_sign_types SET is_active=0 WHERE id=?',[$id]);sa4_json(['success'=>true,'deactivated'=>true]);}Db::run('DELETE FROM station_sign_types WHERE id=?',[$id]);sa4_json(['success'=>true]);}
if($op==='map'){$rows=Db::all("SELECT l.id,l.code,l.origin,l.destination,l.status,l.latitude,l.longitude,l.location_updated_at,l.location_updated_by,s.id station_id,s.station_status,s.accuracy_m,s.physical_address,s.location_photo_path,s.captured_by,s.captured_at,s.updated_at,CONCAT(COALESCE(cu.first_name,''),' ',COALESCE(cu.last_name,'')) captured_by_name,CONCAT(COALESCE(uu.first_name,''),' ',COALESCE(uu.last_name,'')) updated_by_name FROM `lines` l LEFT JOIN line_station_locations s ON s.id=l.station_location_id LEFT JOIN users cu ON cu.id=s.captured_by LEFT JOIN users uu ON uu.id=l.location_updated_by ORDER BY l.code");$registered=0;foreach($rows as &$r){$r['registered']=!empty($r['station_id']);if($r['registered'])$registered++;$r['location_photo_url']=sa4_image_url('station',$r['station_id']);$r['signs']=$r['station_id']?Db::all('SELECT z.id,z.sign_type_id,t.title,t.code,z.photo_path,z.created_at,z.updated_at FROM line_station_signs z JOIN station_sign_types t ON t.id=z.sign_type_id WHERE z.station_location_id=? ORDER BY z.id',[$r['station_id']]):[];foreach($r['signs'] as &$z)$z['photo_url']=sa4_image_url('sign',$z['id']);unset($z);}unset($r);sa4_json(['success'=>true,'stats'=>['total'=>count($rows),'registered'=>$registered,'unregistered'=>count($rows)-$registered],'lines'=>$rows]);}
sa4_json(['error'=>'عملیات نامعتبر است'],400);
