<?php
/* خطیار — درج امن و idempotent تعطیلات رسمی مرجع */
ini_set('display_errors','0');
date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../';
require_once "$ROOT/lib/Db.php";
require_once "$ROOT/lib/Jwt.php";
require_once "$ROOT/lib/Http.php";
require_once "$ROOT/lib/IranCalendar.php";
$CONFIG=require "$ROOT/config.php";
function hs_json($v,$s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('Pragma: no-cache');echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function hs_digits($v){return strtr((string)$v,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);}
function hs_table_cols($table){static $cache=[];$key=strtolower($table);if(isset($cache[$key]))return$cache[$key];$rows=Db::all('SHOW COLUMNS FROM `'.$table.'`');$out=[];foreach($rows as $r)$out[strtolower((string)$r['Field'])]=true;return$cache[$key]=$out;}
function hs_auth(){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))hs_json(['error'=>'توکن نامعتبر یا منقضی است'],401);$uc=hs_table_cols('users');$rc=hs_table_cols('roles');$select=['u.id','u.is_active'];if(!empty($uc['is_admin']))$select[]='u.is_admin';if(!empty($rc['is_admin']))$select[]='r.is_admin AS role_is_admin';if(!empty($rc['title']))$select[]='r.title AS role_title';$sql='SELECT '.implode(',',$select).' FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1';$u=Db::one($sql,[$p['sub']]);if(!$u||!(int)$u['is_active'])hs_json(['error'=>'کاربر نامعتبر است'],401);$title=(string)($u['role_title']??'');$allowed=!empty($u['is_admin'])||!empty($u['role_is_admin'])||in_array($title,['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);if(!$allowed)hs_json(['error'=>'دسترسی مدیریتی لازم است'],403);return$u;}
function hs_cols(){static $c=null;if($c!==null)return$c;$rows=Db::all('SHOW COLUMNS FROM holidays');$c=[];foreach($rows as $r)$c[strtolower((string)$r['Field'])]=true;return$c;}
function hs_ensure_table(){Db::query("CREATE TABLE IF NOT EXISTS holidays (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,jdate VARCHAR(10) NOT NULL,title VARCHAR(500) NOT NULL,source VARCHAR(40) NULL,is_official TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_holidays_jdate(jdate)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$c=hs_cols();if(empty($c['jdate']))Db::query("ALTER TABLE holidays ADD COLUMN jdate VARCHAR(10) NULL");if(empty($c['title']))Db::query("ALTER TABLE holidays ADD COLUMN title VARCHAR(500) NULL");$c=hs_cols();if(empty($c['source'])){try{Db::query("ALTER TABLE holidays ADD COLUMN source VARCHAR(40) NULL");}catch(Throwable $e){}}if(empty($c['is_official'])){try{Db::query("ALTER TABLE holidays ADD COLUMN is_official TINYINT(1) NOT NULL DEFAULT 0");}catch(Throwable $e){}}$c=hs_cols();if(empty($c['jdate'])||empty($c['title']))throw new RuntimeException('ساختار جدول holidays قابل استفاده نیست (jdate/title)');}
$stage='شروع';
try{$stage='احراز هویت مدیریتی';hs_auth();$stage='تعیین سال';$y=(int)hs_digits($_GET['year']??$_POST['year']??'');if($y<1390||$y>1500)$y=(int)date('Y')-621;$stage='آماده‌سازی جدول تعطیلات';hs_ensure_table();$stage='دریافت تعطیلات رسمی سال '.$y;$events=IranCalendar::events($y);$official=[];foreach($events as $j=>$e)if(!empty($e['is_holiday']))$official[$j]=trim((string)($e['title']??'تعطیل رسمی'));if(!$official)hs_json(['ok'=>false,'error'=>'فهرست تعطیلات رسمی برای این سال موجود نیست','year'=>$y],422);$cols=hs_cols();$sourceCol=!empty($cols['source'])?'source':null;$officialCol=!empty($cols['is_official'])?'is_official':(!empty($cols['official'])?'official':null);$inserted=0;$updated=0;$existing=0;$details=[];foreach($official as $j=>$title){$stage='بررسی '.$j;$old=Db::one('SELECT id,title'.($sourceCol?',source':'').($officialCol?',`'.$officialCol.'`':'').' FROM holidays WHERE jdate IN (?,?) ORDER BY id LIMIT 1',[$j,str_replace('-','/',$j)]);if($old){$existing++;$oldTitle=trim((string)($old['title']??''));$newTitle=$oldTitle===''?$title:$oldTitle;if($oldTitle!==''&&mb_strpos($oldTitle,$title,0,'UTF-8')===false)$newTitle=$oldTitle.' | '.$title;$set=[];$args=[];if($newTitle!==$oldTitle){$set[]='title=?';$args[]=$newTitle;}if($sourceCol){$set[]='`'.$sourceCol.'`=?';$args[]='official';}if($officialCol){$set[]='`'.$officialCol.'`=?';$args[]=1;}if($set){$args[]=$old['id'];Db::query('UPDATE holidays SET '.implode(',',$set).' WHERE id=?',$args);$updated++;}$details[]=['jdate'=>$j,'status'=>'existing','title'=>$newTitle];}else{$fields=['jdate','title'];$vals=[$j,$title];if($sourceCol){$fields[]=$sourceCol;$vals[]='official';}if($officialCol){$fields[]=$officialCol;$vals[]=1;}$qs=implode(',',array_fill(0,count($vals),'?'));Db::query('INSERT INTO holidays (`'.implode('`,`',$fields).'`) VALUES ('.$qs.')',$vals);$inserted++;$details[]=['jdate'=>$j,'status'=>'inserted','title'=>$title];}}hs_json(['ok'=>true,'year'=>$y,'total'=>count($official),'inserted'=>$inserted,'updated'=>$updated,'existing'=>$existing,'details'=>$details]);}catch(Throwable $e){error_log('admin-holiday-seed: stage='.$stage.' '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());$detail=$e->getMessage();if($detail==='')$detail=get_class($e);hs_json(['ok'=>false,'error'=>'خطای داخلی در درج تعطیلات رسمی','stage'=>$stage,'detail'=>$detail],500);}
