<?php
/* خطیار — گزارش تردد Production-safe v3 */
ini_set('display_errors','0');
date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../';
require "$ROOT/lib/Db.php";
require "$ROOT/lib/Jwt.php";
require "$ROOT/lib/Http.php";
require "$ROOT/lib/ShiftCalc.php";
require "$ROOT/lib/IranCalendar.php";
$CONFIG=require "$ROOT/config.php";
require "$ROOT/lib/routes.php";
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

function afv_json($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function afv_error($m,$s=400){afv_json(['error'=>$m],$s);}
function afv_digits($s){return strtr((string)$s,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);}
function afv_table($name){static $c=[];$name=(string)$name;if(array_key_exists($name,$c))return$c[$name];try{$r=Db::one('SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$name]);return$c[$name]=((int)($r['c']??0)>0);}catch(Throwable $e){return$c[$name]=false;}}
function afv_col($table,$col){static $c=[];$k=$table.'.'.$col;if(array_key_exists($k,$c))return$c[$k];if(!afv_table($table))return$c[$k]=false;try{$r=Db::one('SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?',[$table,$col]);return$c[$k]=((int)($r['c']??0)>0);}catch(Throwable $e){return$c[$k]=false;}}
function afv_auth(){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))afv_error('توکن منقضی یا نامعتبر است',401);$roleJoin=afv_table('roles')?' JOIN roles r ON r.id=u.role_id ':'';$roleTitle=$roleJoin?'r.title role_title':"'' role_title";$sql="SELECT u.id,u.is_active,u.is_admin,$roleTitle FROM users u".$roleJoin." WHERE u.id=? LIMIT 1";$u=Db::one($sql,[$p['sub']]);if(!$u||!(int)($u['is_active']??0))afv_error('کاربر نامعتبر',401);$dt=$p['dt']??'web';if(afv_table('user_sessions')){try{$sess=Db::one('SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1',[$u['id'],$dt]);$unlimited=in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);if(!$sess||$sess['revoked_at']||(!$unlimited&&($sess['device_id']??'')!==($p['device_id']??'')))afv_error('نشست منقضی یا باطل شده است',401);}catch(Throwable $e){error_log('attendance-report-safe-v3 session: '.$e->getMessage());}}if(empty($u['is_admin']))afv_error('دسترسی مدیریتی لازم است',403);return$u;}
function afv_j2g($jy,$jm,$jd){$jy=(int)$jy-979;$jm=(int)$jm-1;$jd=(int)$jd-1;$jdn=365*$jy+intdiv($jy,33)*8+intdiv(($jy%33+3),4);$md=[31,31,31,31,31,31,30,30,30,30,30,29];for($i=0;$i<$jm;$i++)$jdn+=$md[$i];$jdn+=$jd;$g=$jdn+79;$gy=1600+400*intdiv($g,146097);$g%=146097;$leap=true;if($g>=36525){$g--; $gy+=100*intdiv($g,36524);$g%=36524;if($g>=365)$g++;else$leap=false;}$gy+=4*intdiv($g,1461);$g%=1461;if($g>=366){$leap=false;$g--; $gy+=intdiv($g,365);$g%=365;}$gd=[31,$leap?29:28,31,30,31,30,31,31,30,31,30,31];$gm=0;for(;$gm<12&&$g>=$gd[$gm];$gm++)$g-=$gd[$gm];return[$gy,$gm+1,$g+1];}
function afv_g2j($gy,$gm,$gd){$gdm=[0,31,59,90,120,151,181,212,243,273,304,334];$gy2=$gy-1600;$gm2=$gm-1;$gd2=$gd-1;$gdn=365*$gy2+intdiv($gy2+3,4)-intdiv($gy2+99,100)+intdiv($gy2+399,400)+$gdm[$gm2]+$gd2;if($gm2>1&&(($gy%4==0&&$gy%100!=0)||($gy%400==0)))$gdn++;$jdn=$gdn-79;$jy=979+33*intdiv($jdn,12053);$jdn%=12053;$jy+=4*intdiv($jdn,1461);$jdn%=1461;if($jdn>=366){$jy+=intdiv($jdn-1,365);$jdn=($jdn-1)%365;}$jm=$jdn<186?1+intdiv($jdn,31):7+intdiv($jdn-186,30);$jd=1+($jdn<186?$jdn%31:($jdn-186)%30);return[$jy,$jm,$jd];}
function afv_jts($j){$j=str_replace(['/','.'],'-',afv_digits(trim((string)$j)));if(!preg_match('/^(\d{4})-(\d{1,2})-(\d{1,2})$/',$j,$m))return null;[$gy,$gm,$gd]=afv_j2g($m[1],$m[2],$m[3]);return mktime(0,0,0,$gm,$gd,$gy);}
function afv_jdate($ts){[$y,$m,$d]=afv_g2j((int)date('Y',$ts),(int)date('n',$ts),(int)date('j',$ts));return sprintf('%04d-%02d-%02d',$y,$m,$d);}
function afv_hm($m){$m=max(0,(int)$m);return sprintf('%02d:%02d',intdiv($m,60),$m%60);}
function afv_weekday($j){$names=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];try{$i=ShiftCalc::jweekday($j);return $names[(int)$i]??'';}catch(Throwable $e){$ts=afv_jts($j);if($ts===null)return '';return $names[((int)date('w',$ts)+1)%7]??'';}}
function afv_shift($uid,$j){if(!afv_table('user_shifts')||!afv_table('shifts'))return null;try{$rows=Db::all('SELECT us.shift_id,us.from_jdate,us.to_jdate,s.* FROM user_shifts us JOIN shifts s ON s.id=us.shift_id WHERE us.user_id=? AND s.is_active=1 ORDER BY us.id DESC',[$uid]);foreach($rows as $r){$f=!empty($r['from_jdate'])?str_replace('/','-',(string)$r['from_jdate']):null;$t=!empty($r['to_jdate'])?str_replace('/','-',(string)$r['to_jdate']):null;if($f&&strcmp($j,$f)<0)continue;if($t&&strcmp($j,$t)>0)continue;return$r;}}catch(Throwable $e){error_log('attendance-report-safe-v3 shift: '.$e->getMessage());}return null;}
function afv_shift_day($shift,$j){if(!$shift||($shift['type']??'')!=='advanced'||!afv_table('shift_days'))return null;$sid=(int)($shift['shift_id']??$shift['id']??0);if(!$sid)return null;try{return Db::one("SELECT shift_id,jdate,segments,is_off,day_config FROM shift_days WHERE shift_id=? AND REPLACE(jdate,'/','-')=? LIMIT 1",[$sid,str_replace('/','-',$j)]);}catch(Throwable $e){return null;}}
function afv_simple($j,$rows,$expected=0,$holiday=false,$friday=false){$work=0;$first=null;$last=null;$sessions=[];$p=[];foreach($rows as $r){$in=!empty($r['check_in'])?strtotime($r['check_in']):false;$out=!empty($r['check_out'])?strtotime($r['check_out']):null;if(!$in)continue;$out=$out?:time();$work+=max(0,(int)floor(($out-$in)/60));$first=$first===null?$in:min($first,$in);$last=$last===null?$out:max($last,$out);$p[]=['id'=>(int)$r['id'],'in'=>date('H:i',$in),'out'=>$r['check_out']?date('H:i',$out):null,'in_full'=>$r['check_in']??null,'out_full'=>$r['check_out']??null,'in_lat'=>$r['in_lat']??null,'in_lng'=>$r['in_lng']??null,'out_lat'=>$r['out_lat']??null,'out_lng'=>$r['out_lng']??null,'method'=>$r['method']??null,'in_station'=>$r['in_station']??null,'out_station'=>$r['out_station']??null];$sessions[]=['in'=>$in,'out'=>$out,'clip_start'=>afv_jts($j),'clip_end'=>afv_jts($j)+86400];}
$expected=max(0,(int)$expected);$short=max(0,$expected-min($work,$expected));$ot=max(0,$work-$expected);if($holiday||$friday)$short=0;return[$work,$short,$ot,$first,$last,$p,$sessions];}

try{
 afv_auth();
 $uid=(int)($_GET['user_id']??0);$from=str_replace('/','-',afv_digits(trim($_GET['from']??'')));$to=str_replace('/','-',afv_digits(trim($_GET['to']??'')));if(!$uid||!$from||!$to)afv_error('پرسنل و بازهٔ تاریخ را مشخص کنید',400);$fts=afv_jts($from);$tts=afv_jts($to);if($fts===null||$tts===null||$fts>$tts)afv_error('بازهٔ تاریخ نامعتبر است',400);$daysCount=(int)floor(($tts-$fts)/86400)+1;if($daysCount>366)afv_error('حداکثر بازهٔ مجاز گزارش ۳۶۶ روز است',400);
 if(!afv_table('staff_attendance'))afv_error('جدول تردد پرسنل وجود ندارد',500);
 $nameFirst=afv_col('users','first_name')?'COALESCE(first_name,\'\')':'\'\'';$nameLast=afv_col('users','last_name')?'COALESCE(last_name,\'\')':'\'\'';$device=afv_col('users','device_model')?'device_model':'NULL';$policy=afv_col('users','work_policy_id')?'work_policy_id':'NULL';$usr=Db::one("SELECT id,TRIM(CONCAT($nameFirst,' ',$nameLast)) name,$device device_model,$policy work_policy_id FROM users WHERE id=? LIMIT 1",[$uid]);if(!$usr)afv_error('پرسنل یافت نشد',404);
 $start=date('Y-m-d 00:00:00',$fts);$end=date('Y-m-d 00:00:00',$tts+86400);
 $attCols=['id','check_in','check_out'];foreach(['method','in_lat','in_lng','out_lat','out_lng','in_station','out_station'] as $c)if(afv_col('staff_attendance',$c))$attCols[]=$c;foreach(['method','in_lat','in_lng','out_lat','out_lng','in_station','out_station'] as $c)if(!in_array($c,$attCols,true))$attCols[]='NULL AS '.$c;
 $att=Db::all('SELECT '.implode(',',$attCols).' FROM staff_attendance WHERE user_id=? AND check_in < ? AND (check_out IS NULL OR check_out > ?) ORDER BY check_in',[$uid,$end,$start]);
 $byDay=[];foreach($att as $r){$in=strtotime((string)$r['check_in']);if(!$in)continue;$out=!empty($r['check_out'])?strtotime($r['check_out']):time();$a=max($fts,(int)floor($in/86400)*86400);$b=min($tts+86399,$out);for($d=$a;$d<=$b;$d+=86400){if($in<$d+86400&&$out>$d){$j=afv_jdate($d);if($j)$byDay[$j][]=$r;}}}
 $days=[];$lastShift=null;
 for($ts=$fts;$ts<=$tts;$ts+=86400){$j=afv_jdate($ts);$rows=$byDay[$j]??[];$shift=afv_shift($uid,$j);if($shift)$lastShift=$shift;$dayRow=afv_shift_day($shift,$j);$cal=['is_official_holiday'=>false,'is_manual_holiday'=>false,'is_holiday'=>false,'title'=>'','source'=>'calculated'];try{$cal=IranCalendar::day($j);}catch(Throwable $e){}$isHol=!empty($cal['is_holiday']);$isFri=ShiftCalc::isFriday($j);$expected=0;if($shift){try{$expected=(int)ShiftCalc::expectedMinutes($shift,$j,$dayRow);}catch(Throwable $e){$expected=0;}}
  [$worked,$short,$ot,$first,$last,$punches,$sessions]=afv_simple($j,$rows,$expected,$isHol,$isFri);
  if($shift){try{$w=ShiftCalc::dayWork($shift,$j,$dayRow,$sessions,$isHol);$worked=(int)($w['worked']??$worked);$short=(int)($w['shortage']??$short);$ot=(int)($w['overtime']??$ot);$expected=(int)($w['expected']??$expected);$first=$w['in']?$first:$first;$last=$w['out']?$last:$last;}catch(Throwable $e){error_log('attendance-report-safe-v3 day '.$j.': '.$e->getMessage());}}
  $days[]=['jdate'=>str_replace('-','/',$j),'weekday'=>afv_weekday($j),'is_friday'=>$isFri,'is_official_holiday'=>(bool)($cal['is_official_holiday']??false),'is_manual_holiday'=>(bool)($cal['is_manual_holiday']??false),'is_holiday'=>$isHol,'holiday_title'=>$cal['title']??'','holiday_source'=>$cal['source']??'','punches'=>$punches,'in_shift'=>afv_hm($worked),'worked'=>afv_hm($worked),'expected'=>afv_hm($expected),'late_in'=>'00:00','early_out'=>'00:00','shortage'=>afv_hm($short),'night'=>'00:00','overtime'=>afv_hm($ot),'surplus'=>'00:00','adjusted_ot'=>'00:00','friday_work'=>afv_hm($isFri?$worked:0),'holiday_work'=>afv_hm($isHol&&!$isFri?$worked:0),'absent'=>(!$punches&&!$isHol&&!$isFri)?1:0,'first_in'=>$first?date('H:i',$first):null,'last_out'=>$last?date('H:i',$last):null,'mission'=>'00:00','annual_leave'=>'00:00','sick_leave'=>'00:00','unpaid_leave'=>'00:00'];
 }
 afv_json(['user'=>$usr,'shift'=>$lastShift?['title'=>$lastShift['title']??'']:null,'from'=>str_replace('-','/',$from),'to'=>str_replace('-','/',$to),'days'=>$days,'fast_report'=>true,'read_only'=>true,'schema_compatible'=>true,'implementation'=>'production-safe-v3']);
}catch(Throwable $e){error_log('attendance-report-safe-v3: '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());afv_error('خطای داخلی گزارش تردد؛ جزئیات در گزارش خطای سرور ثبت شد.',500);}
