<?php
/* خطیار — گزارش تردد امن v2: بدون وابستگی به helperهای اختیاری */
ini_set('display_errors','0');
date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../';
require "$ROOT/lib/Db.php";
require "$ROOT/lib/Jwt.php";
require "$ROOT/lib/Http.php";
require "$ROOT/lib/ShiftCalc.php";
require "$ROOT/lib/IranCalendar.php";
$CONFIG=require "$ROOT/config.php";
require "$ROOT/lib/routes.php";
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

function afs_json($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function afs_error($m,$s=400){afs_json(['error'=>$m],$s);}
function afs_digits($s){return strtr((string)$s,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);}
function afs_table($name){static $c=[];if(isset($c[$name]))return$c[$name];try{$r=Db::one("SELECT 1 x FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1",[$name]);}catch(Throwable $e){$r=null;}return$c[$name]=($r!==null);}
function afs_col($table,$col){static $c=[];$k=$table.'.'.$col;if(isset($c[$k]))return$c[$k];if(!afs_table($table))return$c[$k]=false;try{$r=Db::one("SELECT 1 x FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=? LIMIT 1",[$table,$col]);}catch(Throwable $e){$r=null;}return$c[$k]=($r!==null);}
function afs_auth(){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))afs_error('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.is_active,u.is_admin,r.level,r.title role_title FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])afs_error('کاربر نامعتبر',401);$dt=$p['dt']??'web';$sess=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$unlimited=in_array($u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);if(!$sess||$sess['revoked_at']||(!$unlimited&&$sess['device_id']!==($p['device_id']??'')))afs_error('نشست منقضی یا باطل شده است',401);if(empty($u['is_admin']))afs_error('دسترسی مدیریتی لازم است',403);return$u;}
function afs_jts($j){$j=preg_replace('/[\/-]/','-',afs_digits(trim((string)$j)));if(!preg_match('/^(\d{4})-(\d{1,2})-(\d{1,2})$/',$j,$m))return null;if(!function_exists('jalali_to_gregorian'))return null;[$gy,$gm,$gd]=jalali_to_gregorian((int)$m[1],(int)$m[2],(int)$m[3]);return mktime(0,0,0,$gm,$gd,$gy);}
function afs_jdate($ts){if(function_exists('gregorian_to_jalali')){$j=gregorian_to_jalali((int)date('Y',$ts),(int)date('n',$ts),(int)date('j',$ts));return sprintf('%04d-%02d-%02d',(int)$j[0],(int)$j[1],(int)$j[2]);}return null;}
function afs_hm($m){$m=max(0,(int)$m);return sprintf('%02d:%02d',intdiv($m,60),$m%60);}
function afs_weekday($j){try{$w=ShiftCalc::jweekday($j);$names=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];return $names[(int)$w]??'';}catch(Throwable $e){return '';}}
function afs_shift_for($uid,$jdate){if(!afs_table('user_shifts')||!afs_table('shifts'))return null;try{$rows=Db::all("SELECT us.user_id,us.shift_id,us.from_jdate,us.to_jdate,s.* FROM user_shifts us JOIN shifts s ON s.id=us.shift_id WHERE us.user_id=? AND s.is_active=1 ORDER BY us.id DESC",[$uid]);foreach($rows as $r){$from=!empty($r['from_jdate'])?str_replace('/','-',(string)$r['from_jdate']):null;$to=!empty($r['to_jdate'])?str_replace('/','-',(string)$r['to_jdate']):null;if($from&&strcmp($jdate,$from)<0)continue;if($to&&strcmp($jdate,$to)>0)continue;return$r;}}catch(Throwable $e){error_log('attendance-report-safe-v2 shift: '.$e->getMessage());}return null;}
function afs_shift_day($shift,$jdate){if(!$shift||($shift['type']??'')!=='advanced'||!afs_table('shift_days'))return null;$sid=(int)($shift['shift_id']??$shift['id']??0);if(!$sid)return null;try{return Db::one("SELECT shift_id,jdate,segments,is_off,day_config FROM shift_days WHERE shift_id=? AND REPLACE(jdate,'/','-')=? LIMIT 1",[$sid,str_replace('/','-', $jdate)]);}catch(Throwable $e){return null;}}
function afs_requests($uid,$from,$to){$out=[];if(!afs_table('requests'))return$out;$cols=['type','unit','from_jdate','to_jdate','the_date','from_time','to_time','minutes'];foreach($cols as $c)if(!afs_col('requests',$c))return$out;try{$rows=Db::all("SELECT type,unit,from_jdate,to_jdate,the_date,from_time,to_time,minutes FROM requests WHERE user_id=? AND status='approved' ORDER BY id",[$uid]);foreach($rows as $r){$f=str_replace('/','-',trim((string)($r['from_jdate']?:$r['the_date'])));$t=str_replace('/','-',trim((string)($r['to_jdate']?:$r['the_date']?:$r['from_jdate'])));$fts=afs_jts($f);$tts=afs_jts($t);if($fts===null||$tts===null||$fts>$tts)continue;$type=(string)$r['type'];$mins=(int)($r['minutes']??0);if(($r['unit']??'')==='hourly'){$a=explode(':',(string)($r['from_time']??'0:0'));$b=explode(':',(string)($r['to_time']??'0:0'));$mins=max(0,((int)($b[0]??0)*60+(int)($b[1]??0))-((int)($a[0]??0)*60+(int)($a[1]??0)));if($mins<=0)$mins=(int)($r['minutes']??0);$k=afs_jdate($fts);if($k&&$k>=$from&&$k<=$to)$out[$k][$type]=($out[$k][$type]??0)+$mins;continue;}$days=max(1,(int)(($tts-$fts)/86400)+1);if($mins<=0)$mins=$days*480;$per=max(0,intdiv($mins,$days));for($d=$fts;$d<=$tts;$d+=86400){$k=afs_jdate($d);if($k&&$k>=$from&&$k<=$to)$out[$k][$type]=($out[$k][$type]??0)+$per;}}}catch(Throwable $e){error_log('attendance-report-safe-v2 requests: '.$e->getMessage());}return$out;}

try{
 afs_auth();
 $uid=(int)($_GET['user_id']??0);$from=str_replace('/','-',afs_digits(trim($_GET['from']??'')));$to=str_replace('/','-',afs_digits(trim($_GET['to']??'')));
 if(!$uid||!$from||!$to)afs_error('پرسنل و بازهٔ تاریخ را مشخص کنید',400);
 $fts=afs_jts($from);$tts=afs_jts($to);if($fts===null||$tts===null||$fts>$tts)afs_error('بازهٔ تاریخ نامعتبر است',400);if((int)floor(($tts-$fts)/86400)+1>366)afs_error('حداکثر بازهٔ مجاز گزارش ۳۶۶ روز است',400);
 $usrNameFirst=afs_col('users','first_name')?'COALESCE(u.first_name,\'\')':'\'\'';$usrNameLast=afs_col('users','last_name')?'COALESCE(u.last_name,\'\')':'\'\'';$device=afs_col('users','device_model')?'u.device_model':'NULL';$policy=afs_col('users','work_policy_id')?'u.work_policy_id':'NULL';
 $usr=Db::one("SELECT u.id,TRIM(CONCAT($usrNameFirst,' ',$usrNameLast)) name,$device device_model,$policy work_policy_id FROM users u WHERE u.id=? LIMIT 1",[$uid]);if(!$usr)afs_error('پرسنل یافت نشد',404);
 $start=date('Y-m-d 00:00:00',$fts);$end=date('Y-m-d 00:00:00',$tts+86400);
 if(!afs_table('staff_attendance'))afs_error('جدول تردد پرسنل در پایگاه داده وجود ندارد',500);
 $inSt=afs_col('staff_attendance','in_station')?'in_station':'NULL';$outSt=afs_col('staff_attendance','out_station')?'out_station':'NULL';
 $att=Db::all("SELECT id,check_in,check_out,method,in_lat,in_lng,out_lat,out_lng,$inSt in_station,$outSt out_station FROM staff_attendance WHERE user_id=? AND check_in < ? AND (check_out IS NULL OR check_out > ?) ORDER BY check_in",[$uid,$end,$start]);
 $byDay=[];foreach($att as $r){$in=strtotime((string)$r['check_in']);if(!$in)continue;$out=!empty($r['check_out'])?strtotime($r['check_out']):time();$a=max($fts,(int)floor($in/86400)*86400);$b=min($tts+86399,$out);for($d=$a;$d<=$b;$d+=86400)if($in<$d+86400&&$out>$d){$k=afs_jdate($d);if($k)$byDay[$k][]=$r;}}
 $days=[];$lastShift=null;$approvedRequests=null;
 for($ts=$fts;$ts<=$tts;$ts+=86400){$j=afs_jdate($ts);if(!$j)continue;$rows=$byDay[$j]??[];$punches=[];$sessions=[];foreach($rows as $r){$punches[]=['id'=>$r['id'],'in'=>!empty($r['check_in'])?date('H:i',strtotime($r['check_in'])):null,'out'=>!empty($r['check_out'])?date('H:i',strtotime($r['check_out'])):null,'in_full'=>$r['check_in']??null,'out_full'=>$r['check_out']??null,'in_station'=>$r['in_station']??null,'out_station'=>$r['out_station']??null,'method'=>$r['method']??null,'device'=>$usr['device_model']??null,'in_lat'=>$r['in_lat']??null,'in_lng'=>$r['in_lng']??null,'out_lat'=>$r['out_lat']??null,'out_lng'=>$r['out_lng']??null];$sessions[]=['in'=>strtotime($r['check_in']??''),'out'=>!empty($r['check_out'])?strtotime($r['check_out']):null,'clip_start'=>$ts,'clip_end'=>$ts+86400];}
  $shift=afs_shift_for($uid,$j);if($shift)$lastShift=$shift;$dayRow=afs_shift_day($shift,$j);$cal=['is_official_holiday'=>false,'is_manual_holiday'=>false,'is_holiday'=>false,'title'=>'','source'=>''];try{$cal=IranCalendar::day($j);}catch(Throwable $e){}$isHol=!empty($cal['is_holiday']);$isFri=ShiftCalc::isFriday($j);$w=['worked'=>0,'in_shift'=>0,'expected'=>0,'overtime'=>0,'shortage'=>0,'night'=>0,'late_in'=>0,'early_out'=>0,'surplus'=>0,'friday_work'=>0,'holiday_work'=>0,'in'=>null,'out'=>null];if($shift){try{$w=ShiftCalc::dayWork($shift,$j,$dayRow,$sessions,$isHol);}catch(Throwable $e){error_log('attendance-report-safe-v2 day '.$j.': '.$e->getMessage());}}
  if($approvedRequests===null)$approvedRequests=afs_requests($uid,$from,$to);$rq=$approvedRequests[$j]??[];$annual=(int)($rq['annual']??0);$sick=(int)($rq['sick']??0);$unpaid=(int)($rq['unpaid']??0);$mission=(int)($rq['mission']??0);$exempt=min((int)($w['expected']??0),$annual+$sick+$unpaid+$mission);$short=max(0,(int)($w['shortage']??0)-$exempt);
  $days[]=['jdate'=>str_replace('-','/',$j),'weekday'=>afs_weekday($j),'is_friday'=>$isFri,'is_official_holiday'=>(bool)($cal['is_official_holiday']??false),'is_manual_holiday'=>(bool)($cal['is_manual_holiday']??false),'is_holiday'=>$isHol,'holiday_title'=>$cal['title']??'','holiday_source'=>$cal['source']??'','punches'=>$punches,'in_shift'=>afs_hm($w['in_shift']??$w['worked']??0),'worked'=>afs_hm($w['worked']??0),'expected'=>afs_hm($w['expected']??0),'late_in'=>afs_hm($w['late_in']??0),'early_out'=>afs_hm($w['early_out']??0),'shortage'=>afs_hm($short),'night'=>afs_hm($w['night']??0),'overtime'=>afs_hm($w['overtime']??0),'surplus'=>afs_hm($w['surplus']??0),'adjusted_ot'=>afs_hm($w['adjusted_ot']??0),'friday_work'=>afs_hm($w['friday_work']??$w['friday']??0),'holiday_work'=>afs_hm($w['holiday_work']??$w['holiday']??0),'absent'=>(!$punches&&!$isHol&&!$isFri&&$exempt<=0)?1:0,'first_in'=>$w['in']??null,'last_out'=>$w['out']??null,'mission'=>afs_hm($mission),'annual_leave'=>afs_hm($annual),'sick_leave'=>afs_hm($sick),'unpaid_leave'=>afs_hm($unpaid)];
 }
 afs_json(['user'=>$usr,'shift'=>$lastShift?['title'=>$lastShift['title']??'']:null,'from'=>str_replace('-','/',$from),'to'=>str_replace('-','/',$to),'days'=>$days,'fast_report'=>true,'read_only'=>true,'schema_compatible'=>true]);
}catch(Throwable $e){error_log('attendance-report-safe-v2: '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());afs_error('خطای داخلی گزارش تردد؛ جزئیات در گزارش خطای سرور ثبت شد.',500);}
