<?php
ini_set('display_errors','0');
date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../';
require "$ROOT/lib/Db.php"; require "$ROOT/lib/Jwt.php"; require "$ROOT/lib/Http.php"; require "$ROOT/lib/Sms.php";
$CONFIG=require "$ROOT/config.php";
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
function crs_json($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function crs_error($m,$s=400){crs_json(['error'=>$m],$s);}
function crs_digits($v){return preg_replace('/\D+/','',strtr((string)$v,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']));}
function crs_table($t){static $c=[];$t=(string)$t;if(array_key_exists($t,$c))return$c[$t];try{$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);}catch(Throwable $e){$r=null;}return$c[$t]=((int)($r['c']??0)>0);}
function crs_col($t,$c){static $x=[];$k=$t.'.'.$c;if(array_key_exists($k,$x))return$x[$k];if(!crs_table($t))return$x[$k]=false;try{$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$t,$c]);}catch(Throwable $e){$r=null;}return$x[$k]=((int)($r['c']??0)>0);}
function crs_auth($admin=false){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))crs_error('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.is_active,u.is_admin,r.level,r.title role_title FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])crs_error('کاربر نامعتبر است',401);$dt=$p['dt']??'web';$sess=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=?",[$u['id'],$dt]);$unlimited=in_array($u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true);if(!$sess||$sess['revoked_at']||(!$unlimited&&$sess['device_id']!==($p['device_id']??'')))crs_error('نشست منقضی یا باطل شده است',401);if($admin&&empty($u['is_admin']))crs_error('دسترسی مدیریتی لازم است',403);return $u;}
function crs_driver($nid){$nid=crs_digits($nid);if(strlen($nid)!==10)crs_error('کد ملی راننده باید ۱۰ رقم باشد',422);if(!crs_table('drivers'))crs_error('جدول رانندگان در پایگاه داده موجود نیست',500);$fa=strtr($nid,['0'=>'۰','1'=>'۱','2'=>'۲','3'=>'۳','4'=>'۴','5'=>'۵','6'=>'۶','7'=>'۷','8'=>'۸','9'=>'۹']);$parts=[];$args=[];foreach(['national_id','national_code'] as $col){if(crs_col('drivers',$col)){$parts[]="REPLACE(REPLACE(COALESCE(d.`$col`,''),'-',''),' ','') IN (?,?)";array_push($args,$nid,$fa);}}if(!$parts)crs_error('ستون کد ملی رانندگان در پایگاه داده موجود نیست',500);$first=crs_col('drivers','first_name')?'d.`first_name`':'\'\'';$last=crs_col('drivers','last_name')?'d.`last_name`':'\'\'';$nationalId=crs_col('drivers','national_id')?'d.`national_id`':'NULL';$nationalCode=crs_col('drivers','national_code')?'d.`national_code`':'NULL';$mobile=crs_col('drivers','mobile')?'d.`mobile`':'NULL';$d=Db::one("SELECT d.id,$first first_name,$last last_name,$nationalId national_id,$nationalCode national_code,$mobile mobile FROM drivers d WHERE ".implode(' OR ',$parts)." LIMIT 1",$args);if(!$d)crs_error('راننده‌ای با این کد ملی یافت نشد',404);$vehicles=[];try{if(crs_table('vehicle_drivers')&&crs_table('vehicles')){$vcols=['id','plate','model_name','model_year'];$sel=[];foreach($vcols as $c)$sel[]=crs_col('vehicles',$c)?"v.`$c`":'NULL';$vehicles=Db::all("SELECT DISTINCT ".implode(',',$sel)." FROM vehicle_drivers vd JOIN vehicles v ON v.id=vd.vehicle_id WHERE vd.driver_id=? ORDER BY v.id DESC LIMIT 10",[$d['id']]);}}catch(Throwable $e){}return ['id'=>(int)$d['id'],'first_name'=>$d['first_name']??'','last_name'=>$d['last_name']??'','name'=>trim(($d['first_name']??'').' '.($d['last_name']??'')),'national_id'=>$d['national_id']?:($d['national_code']??$nid),'mobile'=>$d['mobile']??'','vehicles'=>$vehicles];}
function crs_settings(){ $out=[];try{$rows=Db::all("SELECT setting_key,setting_value FROM company_request_settings WHERE setting_key IN ('notify_document_submission_sms_enabled','notify_document_submission_sms_mobile')");foreach($rows as $r){$v=json_decode($r['setting_value'],true);$out[$r['setting_key']]=json_last_error()===JSON_ERROR_NONE?$v:$r['setting_value'];}}catch(Throwable $e){}return $out;}
$op=trim((string)($_GET['op']??''));
if($op==='driver-search'){crs_auth(false);crs_json(['ok'=>true,'driver'=>crs_driver($_GET['national_id']??'')]);}
if($op==='admin-drivers'){crs_auth(true);$ids=[];foreach(explode(',',(string)($_GET['ids']??'')) as $x){$x=(int)$x;if($x>0)$ids[$x]=$x;}if(!$ids)crs_json(['ok'=>true,'drivers'=>[]]);$in=implode(',',array_fill(0,count($ids),'?'));$rows=Db::all("SELECT d.id,d.first_name,d.last_name,d.national_id,d.national_code,d.mobile FROM drivers d WHERE d.id IN ($in)",array_values($ids));$out=[];foreach($rows as $d){$out[(string)$d['id']]=['id'=>(int)$d['id'],'name'=>trim(($d['first_name']??'').' '.($d['last_name']??'')),'national_id'=>$d['national_id']?:($d['national_code']??''),'mobile'=>$d['mobile']??''];}crs_json(['ok'=>true,'drivers'=>$out]);}
if($op==='notify-new'){$u=crs_auth(false);$body=json_decode(file_get_contents('php://input'),true);$requestId=(int)($body['request_id']??$_POST['request_id']??0);if(!$requestId)crs_error('شناسه درخواست الزامی است',422);$req=Db::one("SELECT cr.*,crt.title request_type_title,d.first_name driver_first_name,d.last_name driver_last_name,d.national_id driver_national_id FROM company_requests cr JOIN company_request_types crt ON crt.id=cr.request_type_id LEFT JOIN drivers d ON d.id=cr.driver_id WHERE cr.id=? LIMIT 1",[$requestId]);if(!$req)crs_error('درخواست یافت نشد',404);if((int)$req['user_id']!==(int)$u['id'])crs_error('دسترسی مجاز نیست',403);$s=crs_settings();$enabled=!empty($s['notify_document_submission_sms_enabled']);$mobile=crs_digits($s['notify_document_submission_sms_mobile']??'');if(!$enabled||strlen($mobile)<10)crs_json(['ok'=>true,'sent'=>false,'skipped'=>true]);$dup=Db::one("SELECT id FROM company_request_logs WHERE request_id=? AND action='document_submission_sms_notified' LIMIT 1",[$requestId]);if($dup)crs_json(['ok'=>true,'sent'=>false,'duplicate'=>true]);$msg='درخواست جدید ارسال مدارک شرکت در خطیار ثبت شد.\nکد رهگیری: '.($req['tracking_code']??'').'\nخدمت: '.($req['request_type_title']??'');$dn=trim(($req['driver_first_name']??'').' '.($req['driver_last_name']??''));if($dn!=='')$msg.='\nراننده: '.$dn.(!empty($req['driver_national_id'])?' - کد ملی: '.$req['driver_national_id']:'');try{$res=Sms::send([$mobile],$msg,'company_request_new',(int)$u['id']);if(empty($res['ok']))crs_error($res['error']??'ارسال پیامک ناموفق بود',502);Db::exec("INSERT INTO company_request_logs(request_id,user_id,action,description,meta) VALUES(?,?,?,?,?)",[$requestId,(int)$u['id'],'document_submission_sms_notified','اعلان پیامکی درخواست جدید ارسال شد',json_encode(['mobile'=>$mobile],JSON_UNESCAPED_UNICODE)]);crs_json(['ok'=>true,'sent'=>true]);}catch(Throwable $e){crs_error('ارسال پیامک ناموفق بود: '.$e->getMessage(),502);}}
crs_error('عملیات نامعتبر است',404);
