<?php
/* خطیار — API خودرو/موتورسیکلت پرسنل، بدون تغییر ساختار دیتابیس در زمان درخواست */
declare(strict_types=1);
ini_set('display_errors','0');
date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../';
require "$ROOT/lib/Db.php";
require "$ROOT/lib/Jwt.php";
require "$ROOT/lib/Http.php";
require "$ROOT/lib/XlsxWriter.php";
$CONFIG=require "$ROOT/config.php";

function pvas_json($data,int $status=200): void { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function pvas_fail(string $message,int $status=400): void { pvas_json(['ok'=>false,'error'=>$message],$status); }
function pvas_body(): array { static $body=null; if($body===null){$raw=file_get_contents('php://input');$body=json_decode($raw?:'',true);if(!is_array($body))$body=[];} return $body; }
function pvas_norm($value): string { $s=trim((string)$value); $s=strtr($s,['ي'=>'ی','ى'=>'ی','ك'=>'ک','ۀ'=>'ه','ة'=>'ه','۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']); $s=preg_replace('/\s+/u',' ',$s)??$s; return trim($s); }
function pvas_table(string $table): bool { static $cache=[]; if(isset($cache[$table])) return $cache[$table]; try{$r=Db::one("SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1",[$table]);}catch(Throwable $e){$r=null;} return $cache[$table]=($r!==null); }
function pvas_col(string $table,string $column): bool { static $cache=[]; $key=$table.'.'.$column; if(isset($cache[$key])) return $cache[$key]; if(!pvas_table($table)) return $cache[$key]=false; try{$r=Db::one("SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=? LIMIT 1",[$table,$column]);}catch(Throwable $e){$r=null;} return $cache[$key]=($r!==null); }
function pvas_require_schema(): void { foreach(['personnel_vehicle_assets','personnel_vehicle_asset_photos','personnel_vehicle_asset_checks','personnel_vehicle_checklist_history'] as $table){ if(!pvas_table($table)) pvas_fail('ساختار اطلاعات خودرو/موتورسیکلت نصب نشده است؛ ابتدا مهاجرت دیتابیس مربوطه را اجرا کنید.',503); } }
function pvas_auth(): array { global $CONFIG; $token=Http::bearer(); $payload=$token?Jwt::verify($token,$CONFIG['jwt_secret']):null; if(!$payload||empty($payload['sub'])) pvas_fail('توکن نامعتبر یا منقضی است',401); $u=Db::one("SELECT u.id,u.is_active,u.is_admin,u.role_id,r.title role_title FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$payload['sub']]); if(!$u||!(int)$u['is_active']) pvas_fail('کاربر نامعتبر است',401); return $u; }
function pvas_role_kind(string $title,$check=false){ $t=pvas_norm($title); $senior=(mb_strpos($t,'ارشد')!==false && (mb_strpos($t,'بازرس')!==false || mb_strpos($t,'سربازرس')!==false)); if($check)return $senior; if(mb_strpos($t,'گشت موتوری')!==false)return 'motorcycle'; if(mb_strpos($t,'گشت خودرویی')!==false)return 'car'; if(mb_strpos($t,'سربازرس')!==false)return 'car'; return false; }
function pvas_check_authorized(array $u): bool { return (bool)((int)($u['is_admin']??0)||pvas_role_kind((string)($u['role_title']??''),true)); }
function pvas_admin_allowed(array $u): bool { return pvas_check_authorized($u); }
function pvas_years(): array { $year=(int)date('Y')-621; $out=[]; for($y=$year;$y>=1390;$y--)$out[]=$y; return $out; }
function pvas_asset(int $id): ?array { return Db::one('SELECT * FROM personnel_vehicle_assets WHERE id=? LIMIT 1',[$id]); }
function pvas_history(int $id): array { $hasJson=pvas_col('personnel_vehicle_checklist_history','checks_json'); $json=$hasJson?',h.checks_json':''; return Db::all("SELECT h.id,h.result,h.note{$json},h.checked_at,h.checker_id,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) checker_name FROM personnel_vehicle_checklist_history h LEFT JOIN users u ON u.id=h.checker_id WHERE h.asset_id=? ORDER BY h.checked_at DESC,h.id DESC",[$id]); }
function pvas_photo_keys(string $type): array { return $type==='motorcycle'?['motor_front','motor_back','motor_right','motor_left','motor_card_front','motor_card_back','green_card','insurance','license_front','license_back']:['car_front','car_back','car_right','car_left','license_front','license_back','vehicle_card_front','vehicle_card_back','technical_inspection','insurance','green_card']; }
function pvas_check_keys(string $type): array { return $type==='motorcycle'?['identity','plate','license','insurance','photos','numbers']:['identity','plate','license','insurance','technical','photos','equipment','numbers']; }
function pvas_load(int $id,bool $photos=true): ?array { $a=pvas_asset($id); if(!$a)return null; if($photos)$a['photos']=Db::all('SELECT photo_key,data_uri,crop_json,created_at,updated_at FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$id]); else $a['photo_keys']=array_column(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$id]),'photo_key'); $a['checks']=Db::all('SELECT check_key,check_value,note,checker_id,updated_at FROM personnel_vehicle_asset_checks WHERE asset_id=? ORDER BY check_key',[$id]); $a['checklist_history']=pvas_history($id); return $a; }
function pvas_national_sql(): string { return pvas_col('users','national_code')?'u.national_code':'NULL'; }
function pvas_plate(array $r): string { if(($r['asset_type']??'')==='motorcycle')return trim(($r['motorcycle_plate_top']??'').' / '.($r['motorcycle_plate_bottom']??'')); return trim(($r['plate_part_right']??'').' '.($r['plate_letter']??'').' '.($r['plate_part_left']??'').' ایران '.($r['plate_iran']??'')); }
function pvas_image_bytes($data): string { $s=(string)$data; $p=strpos($s,'base64,'); if($p!==false)$s=substr($s,$p+7); $s=preg_replace('/\s+/','',$s)??$s; $b=base64_decode($s,true); return $b===false?'':$b; }
function pvas_list(): array { $national=pvas_national_sql(); return Db::all("SELECT a.*,u.first_name,u.last_name,u.username,u.phone,{$national} national_code,r.title role_title FROM personnel_vehicle_assets a JOIN users u ON u.id=a.user_id LEFT JOIN roles r ON r.id=u.role_id ORDER BY CASE WHEN a.status='pending' THEN 0 WHEN a.status='needs_correction' THEN 1 ELSE 2 END,a.updated_at DESC,a.id DESC"); }
function pvas_update_photos(int $id,string $type,array $photos): void { $allowed=array_flip(pvas_photo_keys($type)); foreach($photos as $photo){$key=trim((string)($photo['photo_key']??''));$data=(string)($photo['data_uri']??'');if($key===''||!isset($allowed[$key])||$data==='')continue;if(strlen($data)>8000000)pvas_fail('حجم یکی از تصاویر بیش از حد مجاز است');$crop=json_encode($photo['crop_meta']??null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);Db::run("INSERT INTO personnel_vehicle_asset_photos(asset_id,photo_key,data_uri,crop_json) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE data_uri=VALUES(data_uri),crop_json=VALUES(crop_json),updated_at=CURRENT_TIMESTAMP",[$id,$key,$data,$crop]);} }

try {
  pvas_require_schema();
  $u=pvas_auth(); $op=(string)($_GET['op']??'access');
  if($op==='access'){ $kind=pvas_role_kind((string)($u['role_title']??'')); pvas_json(['ok'=>true,'allowed'=>$kind!==false,'asset_type'=>$kind===true?'car':$kind,'checklist_allowed'=>pvas_check_authorized($u),'role_title'=>$u['role_title']??'','years'=>pvas_years()]); }
  if($op==='mine'){ $kind=pvas_role_kind((string)($u['role_title']??'')); $type=(string)($_GET['type']??$kind); if(!in_array($type,['car','motorcycle'],true)||$kind!==$type)pvas_fail('این بخش برای سمت شما فعال نیست',403); $a=Db::one('SELECT id FROM personnel_vehicle_assets WHERE user_id=? AND asset_type=? LIMIT 1',[$u['id'],$type]); pvas_json(['ok'=>true,'asset'=>$a?pvas_load((int)$a['id'],true):null]); }
  if($op==='list'||$op==='checklist-list'){ if(!pvas_admin_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403); pvas_json(['ok'=>true,'items'=>pvas_list()]); }
  if($op==='detail'){ if(!pvas_admin_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403); $id=(int)($_GET['id']??0);$a=pvas_load($id,true);if(!$a)pvas_fail('وسیله یافت نشد',404);pvas_json(['ok'=>true,'asset'=>$a]); }
  if($op==='save'){
    $kind=pvas_role_kind((string)($u['role_title']??''));$b=pvas_body();$type=(string)($b['asset_type']??'');if(!in_array($type,['car','motorcycle'],true)||$kind!==$type)pvas_fail('دسترسی ثبت وسیله برای سمت شما مجاز نیست',403);
    $year=(int)pvas_norm($b['model_year']??0);if($year<1390||$year>(int)date('Y')-621)pvas_fail('سال ساخت/مدل نامعتبر است');
    $fields=['plate_part_right','plate_letter','plate_part_left','plate_iran','motorcycle_plate_top','motorcycle_plate_bottom','vehicle_type','fuel_type','color','model_year','chassis_number','engine_number','vin','motorcycle_usage','motorcycle_system','motorcycle_type','cylinders','license_number','license_issue_date','license_expiry_date','insurance_number','insurance_company','insurance_issue_date','insurance_expiry_date','technical_inspection_number','technical_inspection_issue_date','technical_inspection_expiry_date','fixed_beacon','mobile_beacon','heating_ok','cooling_ok','amplifier'];
    $existing=Db::one('SELECT id FROM personnel_vehicle_assets WHERE user_id=? AND asset_type=? LIMIT 1',[$u['id'],$type]);
    $values=[];foreach($fields as $f){$v=$b[$f]??null;if(is_string($v))$v=pvas_norm($v);$values[$f]=$v===''?null:$v;}
    Db::pdo()->beginTransaction();try{
      if($existing){$id=(int)$existing['id'];$set=[];$params=[];foreach($fields as $f){$set[]="$f=?";$params[]=$values[$f];}$params[]=$id;Db::run('UPDATE personnel_vehicle_assets SET '.implode(',',$set).",status='pending',verified_by=NULL,verified_at=NULL WHERE id=?",$params);}
      else{$cols=['user_id','asset_type'];$marks=['?','?'];$params=[$u['id'],$type];foreach($fields as $f){$cols[]=$f;$marks[]='?';$params[]=$values[$f];} $id=Db::insert('INSERT INTO personnel_vehicle_assets('.implode(',',$cols).') VALUES('.implode(',',$marks).')',$params);}
      if(isset($b['photos'])&&is_array($b['photos']))pvas_update_photos($id,$type,$b['photos']);Db::pdo()->commit();
    }catch(Throwable $e){if(Db::pdo()->inTransaction())Db::pdo()->rollBack();throw $e;}
    pvas_json(['ok'=>true,'asset'=>pvas_load($id,true)]);
  }
  if($op==='checklist-verify'){
    if(!pvas_check_authorized($u))pvas_fail('فقط سربازرس ارشد یا مدیر سامانه دسترسی دارد',403);$b=pvas_body();$id=(int)($b['asset_id']??0);$asset=pvas_asset($id);if(!$asset)pvas_fail('وسیله یافت نشد',404);$keys=pvas_check_keys((string)$asset['asset_type']);$incoming=is_array($b['checks']??null)?$b['checks']:[];$checks=[];$missing=[];foreach($keys as $k){if(!array_key_exists($k,$incoming)){$missing[]=$k;continue;}$v=is_array($incoming[$k])?$incoming[$k]:['value'=>$incoming[$k]];$checks[$k]=['value'=>!empty($v['value']),'note'=>pvas_norm($v['note']??'')];}if($missing)pvas_fail('همه موارد چک‌لیست باید تعیین تکلیف شوند: '.implode(', ',$missing));
    $approved=!empty($b['approved']);if($approved){$wanted=array_flip(pvas_photo_keys((string)$asset['asset_type']));$have=array_flip(array_column(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=?',[$id]),'photo_key'));if(array_diff_key($wanted,$have))pvas_fail('برای تأیید نهایی همه تصاویر مدارک باید ثبت شده باشند.');}
    $status=$approved?'verified':'needs_correction';$note=pvas_norm($b['note']??'');Db::pdo()->beginTransaction();try{foreach($checks as $k=>$v)Db::run("INSERT INTO personnel_vehicle_asset_checks(asset_id,checker_id,check_key,check_value,note) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE check_value=VALUES(check_value),note=VALUES(note),updated_at=CURRENT_TIMESTAMP",[$id,$u['id'],$k,$v['value']?1:0,$v['note']]);$historyJson=json_encode($checks,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(pvas_col('personnel_vehicle_checklist_history','checks_json'))Db::run("INSERT INTO personnel_vehicle_checklist_history(asset_id,checker_id,result,note,checks_json,checked_at) VALUES(?,?,?,?,?,NOW())",[$id,$u['id'],$status,$note,$historyJson]);else Db::run("INSERT INTO personnel_vehicle_checklist_history(asset_id,checker_id,result,note,checked_at) VALUES(?,?,?,?,NOW())",[$id,$u['id'],$status,$note]);Db::run('UPDATE personnel_vehicle_assets SET status=?,verified_by=?,verified_at=NOW(),checklist_note=? WHERE id=?',[$status,$u['id'],$note,$id]);Db::pdo()->commit();}catch(Throwable $e){if(Db::pdo()->inTransaction())Db::pdo()->rollBack();throw $e;}pvas_json(['ok'=>true,'status'=>$status,'checked_at'=>date('Y-m-d H:i:s')]);
  }
  if($op==='export'){
    if(!pvas_admin_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403);$national=pvas_national_sql();$rows=Db::all("SELECT a.*,u.first_name,u.last_name,u.username,u.phone,{$national} national_code,r.title role_title FROM personnel_vehicle_assets a JOIN users u ON u.id=a.user_id LEFT JOIN roles r ON r.id=u.role_id ORDER BY u.last_name,u.first_name,a.asset_type");$photoKeys=[];foreach($rows as $r)foreach(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=?',[$r['id']]) as $p){$k=(string)$p['photo_key'];if($k!==''&&!in_array($k,$photoKeys,true))$photoKeys[]=$k;}$head=['شناسه','نام','نام خانوادگی','نام کاربری','سمت','موبایل','کد ملی','نوع وسیله','پلاک','نوع خودرو','سوخت','رنگ','سال ساخت','شماره شاسی/تنه','شماره موتور','VIN','سیستم موتور','تیپ موتور','کاربری موتور','سیلندر','شماره گواهینامه','صدور گواهینامه','انقضای گواهینامه','شماره بیمه','شرکت بیمه','صدور بیمه','انقضای بیمه','شماره معاینه فنی','صدور معاینه','انقضای معاینه','چراغگردان ثابت','چراغگردان متحرک','گرمایش','سرمایش','آمپلی‌فایر','وضعیت بررسی','اولین تاریخ چک‌لیست','آخرین تاریخ چک‌لیست','تاریخچه کامل چک‌لیست'];foreach($photoKeys as $k)$head[]='تصویر '.$k;$x=new XlsxWriter($head);foreach($rows as $r){$hist=pvas_history((int)$r['id']);$dates=array_column($hist,'checked_at');$cells=[$r['id'],$r['first_name'],$r['last_name'],$r['username'],$r['role_title'],$r['phone'],$r['national_code'],$r['asset_type']==='car'?'خودرو':'موتورسیکلت',pvas_plate($r),$r['vehicle_type'],$r['fuel_type'],$r['color'],$r['model_year'],$r['chassis_number'],$r['engine_number'],$r['vin'],$r['motorcycle_system'],$r['motorcycle_type'],$r['motorcycle_usage'],$r['cylinders'],$r['license_number'],$r['license_issue_date'],$r['license_expiry_date'],$r['insurance_number'],$r['insurance_company'],$r['insurance_issue_date'],$r['insurance_expiry_date'],$r['technical_inspection_number'],$r['technical_inspection_issue_date'],$r['technical_inspection_expiry_date'],((int)$r['fixed_beacon']?'بله':'خیر'),((int)$r['mobile_beacon']?'بله':'خیر'),((int)$r['heating_ok']?'بله':'خیر'),((int)$r['cooling_ok']?'بله':'خیر'),((int)$r['amplifier']?'بله':'خیر'),$r['status'],$dates?end($dates):null,$dates?$dates[0]:null,$dates?implode(' | ',$dates):null];$by=[];foreach(Db::all('SELECT photo_key,data_uri FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$r['id']]) as $p)$by[(string)$p['photo_key']=$p;$start=count($cells);foreach($photoKeys as $k)$cells[]='';$row=$x->addRow($cells);foreach($photoKeys as $i=>$k){$bytes=pvas_image_bytes($by[$k]['data_uri']??'');if($bytes!==''){$x->setImage($row,$start+$i,$bytes,110);$x->setColWidth($start+$i,18);}}}$x->output('personnel_vehicle_assets.xlsx','خودرو و موتورسیکلت');exit;
  }
  pvas_fail('عملیات نامعتبر',404);
}catch(Throwable $e){error_log('personnel-vehicle-assets-safe: '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());pvas_fail('خطای داخلی سرویس اطلاعات خودرو و موتورسیکلت',500);}
