<?php
/* خطیار — API خودرو/موتورسیکلت پرسنل، بدون تغییر ساختار دیتابیس در زمان درخواست */
declare(strict_types=1);
ini_set('display_errors','0'); date_default_timezone_set('Asia/Tehran');
$ROOT=__DIR__.'/../../'; require "$ROOT/lib/Db.php"; require "$ROOT/lib/Jwt.php"; require "$ROOT/lib/Http.php"; require "$ROOT/lib/XlsxWriter.php"; $CONFIG=require "$ROOT/config.php";
function pvas_json($d,int $s=200):void{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function pvas_fail(string $m,int $s=400):void{pvas_json(['ok'=>false,'error'=>$m],$s);}
function pvas_body():array{static$b=null;if($b===null){$b=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($b))$b=[];}return$b;}
function pvas_norm($v):string{$s=trim((string)$v);$s=strtr($s,['ي'=>'ی','ى'=>'ی','ك'=>'ک','ۀ'=>'ه','ة'=>'ه','۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);return trim(preg_replace('/\s+/u',' ',$s)??$s);}
function pvas_table(string$t):bool{static$c=[];if(array_key_exists($t,$c))return$c[$t];try{$r=Db::one("SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? LIMIT 1",[$t]);}catch(Throwable$e){$r=null;}return$c[$t]=$r!==null;}
function pvas_col(string$t,string$c):bool{static$x=[];$k="$t.$c";if(array_key_exists($k,$x))return$x[$k];if(!pvas_table($t))return$x[$k]=false;try{$r=Db::one("SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=? LIMIT 1",[$t,$c]);}catch(Throwable$e){$r=null;}return$x[$k]=$r!==null;}
function pvas_schema():void{foreach(['personnel_vehicle_assets','personnel_vehicle_asset_photos','personnel_vehicle_asset_checks','personnel_vehicle_checklist_history']as$t)if(!pvas_table($t))pvas_fail('ساختار اطلاعات خودرو/موتورسیکلت نصب نشده است؛ ابتدا مهاجرت دیتابیس مربوطه را اجرا کنید.',503);}
function pvas_auth():array{global$CONFIG;$t=Http::bearer();$p=$t?Jwt::verify($t,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))pvas_fail('توکن نامعتبر یا منقضی است',401);$u=Db::one("SELECT u.id,u.is_active,u.is_admin,u.role_id,r.title role_title FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])pvas_fail('کاربر نامعتبر است',401);return$u;}
function pvas_kind(string$t,$check=false){$t=pvas_norm($t);$senior=mb_strpos($t,'ارشد')!==false&&(mb_strpos($t,'بازرس')!==false||mb_strpos($t,'سربازرس')!==false);if($check)return$senior;if(mb_strpos($t,'گشت موتوری')!==false)return'motorcycle';if(mb_strpos($t,'گشت خودرویی')!==false)return'car';if(mb_strpos($t,'سربازرس')!==false)return'car';return false;}
function pvas_allowed(array$u):bool{return(bool)((int)($u['is_admin']??0)||pvas_kind((string)($u['role_title']??''),true));}
function pvas_years():array{$y=(int)date('Y')-621;$a=[];for(;$y>=1390;$y--)$a[]=$y;return$a;}
function pvas_asset(int$id):?array{return Db::one('SELECT * FROM personnel_vehicle_assets WHERE id=? LIMIT 1',[$id]);}
function pvas_history(int$id):array{$j=pvas_col('personnel_vehicle_checklist_history','checks_json')?',h.checks_json':'';return Db::all("SELECT h.id,h.result,h.note{$j},h.checked_at,h.checker_id,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) checker_name FROM personnel_vehicle_checklist_history h LEFT JOIN users u ON u.id=h.checker_id WHERE h.asset_id=? ORDER BY h.checked_at DESC,h.id DESC",[$id]);}
function pvas_photos(string$t):array{return$t==='motorcycle'?['motor_front','motor_back','motor_right','motor_left','motor_card_front','motor_card_back','green_card','insurance','license_front','license_back']:['car_front','car_back','car_right','car_left','license_front','license_back','vehicle_card_front','vehicle_card_back','technical_inspection','insurance','green_card'];}
function pvas_checks(string$t):array{return$t==='motorcycle'?['identity','plate','license','insurance','photos','numbers']:['identity','plate','license','insurance','technical','photos','equipment','numbers'];}
function pvas_load(int$id,bool$photos=true):?array{$a=pvas_asset($id);if(!$a)return null;if($photos)$a['photos']=Db::all('SELECT photo_key,data_uri,crop_json,created_at,updated_at FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$id]);else$a['photo_keys']=array_column(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$id]),'photo_key');$a['checks']=Db::all('SELECT check_key,check_value,note,checker_id,updated_at FROM personnel_vehicle_asset_checks WHERE asset_id=? ORDER BY check_key',[$id]);$a['checklist_history']=pvas_history($id);return$a;}
function pvas_plate(array$r):string{if(($r['asset_type']??'')==='motorcycle')return trim(($r['motorcycle_plate_top']??'').' / '.($r['motorcycle_plate_bottom']??''));return trim(($r['plate_part_right']??'').' '.($r['plate_letter']??'').' '.($r['plate_part_left']??'').' ایران '.($r['plate_iran']??''));}
function pvas_national():string{return pvas_col('users','national_code')?'u.national_code':'NULL';}
function pvas_image($d):string{$s=(string)$d;$p=strpos($s,'base64,');if($p!==false)$s=substr($s,$p+7);$b=base64_decode(preg_replace('/\s+/','',$s)??$s,true);return$b===false?'':$b;}
try{pvas_schema();$u=pvas_auth();$op=(string)($_GET['op']??'access');
if($op==='access'){$k=pvas_kind((string)($u['role_title']??''));pvas_json(['ok'=>true,'allowed'=>$k!==false,'asset_type'=>$k===true?'car':$k,'checklist_allowed'=>pvas_allowed($u),'role_title'=>$u['role_title']??'','years'=>pvas_years()]);}
if($op==='mine'){$k=pvas_kind((string)($u['role_title']??''));$type=(string)($_GET['type']??$k);if(!in_array($type,['car','motorcycle'],true)||$k!==$type)pvas_fail('این بخش برای سمت شما فعال نیست',403);$a=Db::one('SELECT id FROM personnel_vehicle_assets WHERE user_id=? AND asset_type=? LIMIT 1',[$u['id'],$type]);pvas_json(['ok'=>true,'asset'=>$a?pvas_load((int)$a['id']):null]);}
if($op==='list'||$op==='checklist-list'){if(!pvas_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403);$n=pvas_national();pvas_json(['ok'=>true,'items'=>Db::all("SELECT a.*,u.first_name,u.last_name,u.username,u.phone,{$n} national_code,r.title role_title FROM personnel_vehicle_assets a JOIN users u ON u.id=a.user_id LEFT JOIN roles r ON r.id=u.role_id ORDER BY CASE WHEN a.status='pending' THEN 0 WHEN a.status='needs_correction' THEN 1 ELSE 2 END,a.updated_at DESC,a.id DESC")]);}
if($op==='detail'){if(!pvas_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403);$a=pvas_load((int)($_GET['id']??0));if(!$a)pvas_fail('وسیله یافت نشد',404);pvas_json(['ok'=>true,'asset'=>$a]);}
if($op==='save'){$k=pvas_kind((string)($u['role_title']??''));$b=pvas_body();$type=(string)($b['asset_type']??'');if(!in_array($type,['car','motorcycle'],true)||$k!==$type)pvas_fail('دسترسی ثبت وسیله برای سمت شما مجاز نیست',403);$year=(int)pvas_norm($b['model_year']??0);if($year<1390||$year>(int)date('Y')-621)pvas_fail('سال ساخت/مدل نامعتبر است');$fields=['plate_part_right','plate_letter','plate_part_left','plate_iran','motorcycle_plate_top','motorcycle_plate_bottom','vehicle_type','fuel_type','color','model_year','chassis_number','engine_number','vin','motorcycle_usage','motorcycle_system','motorcycle_type','cylinders','license_number','license_issue_date','license_expiry_date','insurance_number','insurance_company','insurance_issue_date','insurance_expiry_date','technical_inspection_number','technical_inspection_issue_date','technical_inspection_expiry_date','fixed_beacon','mobile_beacon','heating_ok','cooling_ok','amplifier'];$e=Db::one('SELECT id FROM personnel_vehicle_assets WHERE user_id=? AND asset_type=? LIMIT 1',[$u['id'],$type]);$v=[];foreach($fields as$f){$z=$b[$f]??null;if(is_string($z))$z=pvas_norm($z);$v[$f]=$z===''?null:$z;}Db::pdo()->beginTransaction();try{if($e){$id=(int)$e['id'];$set=[];$p=[];foreach($fields as$f){$set[]="$f=?";$p[]=$v[$f];}$p[]=$id;Db::run('UPDATE personnel_vehicle_assets SET '.implode(',',$set).",status='pending',verified_by=NULL,verified_at=NULL WHERE id=?",$p);}else{$cols=['user_id','asset_type'];$marks=['?','?'];$p=[$u['id'],$type];foreach($fields as$f){$cols[]=$f;$marks[]='?';$p[]=$v[$f];}$id=Db::insert('INSERT INTO personnel_vehicle_assets('.implode(',',$cols).') VALUES('.implode(',',$marks).')',$p);}if(isset($b['photos'])&&is_array($b['photos'])){$allowed=array_flip(pvas_photos($type));foreach($b['photos']as$ph){$key=trim((string)($ph['photo_key']??''));$data=(string)($ph['data_uri']??'');if($key===''||!isset($allowed[$key])||$data==='')continue;if(strlen($data)>8000000)pvas_fail('حجم یکی از تصاویر بیش از حد مجاز است');$crop=json_encode($ph['crop_meta']??null,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);Db::run("INSERT INTO personnel_vehicle_asset_photos(asset_id,photo_key,data_uri,crop_json) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE data_uri=VALUES(data_uri),crop_json=VALUES(crop_json),updated_at=CURRENT_TIMESTAMP",[$id,$key,$data,$crop]);}}Db::pdo()->commit();}catch(Throwable$e){if(Db::pdo()->inTransaction())Db::pdo()->rollBack();throw$e;}pvas_json(['ok'=>true,'asset'=>pvas_load($id)]);}
if($op==='checklist-verify'){if(!pvas_allowed($u))pvas_fail('فقط سربازرس ارشد یا مدیر سامانه دسترسی دارد',403);$b=pvas_body();$id=(int)($b['asset_id']??0);$a=pvas_asset($id);if(!$a)pvas_fail('وسیله یافت نشد',404);$incoming=is_array($b['checks']??null)?$b['checks']:[];$checks=[];$missing=[];foreach(pvas_checks((string)$a['asset_type'])as$k){if(!array_key_exists($k,$incoming)){$missing[]=$k;continue;}$x=is_array($incoming[$k])?$incoming[$k]:['value'=>$incoming[$k]];$checks[$k]=['value'=>!empty($x['value']),'note'=>pvas_norm($x['note']??'')];}if($missing)pvas_fail('همه موارد چک‌لیست باید تعیین تکلیف شوند: '.implode(', ',$missing));$approved=!empty($b['approved']);if($approved){$wanted=array_flip(pvas_photos((string)$a['asset_type']));$have=array_flip(array_column(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=?',[$id]),'photo_key'));if(array_diff_key($wanted,$have))pvas_fail('برای تأیید نهایی همه تصاویر مدارک باید ثبت شده باشند.');}$status=$approved?'verified':'needs_correction';$note=pvas_norm($b['note']??'');Db::pdo()->beginTransaction();try{foreach($checks as$k=>$x)Db::run("INSERT INTO personnel_vehicle_asset_checks(asset_id,checker_id,check_key,check_value,note) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE check_value=VALUES(check_value),note=VALUES(note),updated_at=CURRENT_TIMESTAMP",[$id,$u['id'],$k,$x['value']?1:0,$x['note']]);$json=json_encode($checks,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(pvas_col('personnel_vehicle_checklist_history','checks_json'))Db::run("INSERT INTO personnel_vehicle_checklist_history(asset_id,checker_id,result,note,checks_json,checked_at) VALUES(?,?,?,?,?,NOW())",[$id,$u['id'],$status,$note,$json]);else Db::run("INSERT INTO personnel_vehicle_checklist_history(asset_id,checker_id,result,note,checked_at) VALUES(?,?,?,?,NOW())",[$id,$u['id'],$status,$note]);Db::run('UPDATE personnel_vehicle_assets SET status=?,verified_by=?,verified_at=NOW(),checklist_note=? WHERE id=?',[$status,$u['id'],$note,$id]);Db::pdo()->commit();}catch(Throwable$e){if(Db::pdo()->inTransaction())Db::pdo()->rollBack();throw$e;}pvas_json(['ok'=>true,'status'=>$status,'checked_at'=>date('Y-m-d H:i:s')]);}
if($op==='export'){if(!pvas_allowed($u))pvas_fail('دسترسی مدیریتی لازم است',403);$n=pvas_national();$rows=Db::all("SELECT a.*,u.first_name,u.last_name,u.username,u.phone,{$n} national_code,r.title role_title FROM personnel_vehicle_assets a JOIN users u ON u.id=a.user_id LEFT JOIN roles r ON r.id=u.role_id ORDER BY u.last_name,u.first_name,a.asset_type");$head=['شناسه','نام','نام خانوادگی','نام کاربری','سمت','موبایل','کد ملی','نوع وسیله','پلاک','نوع خودرو','سوخت','رنگ','سال ساخت','شماره شاسی/تنه','شماره موتور','VIN','سیستم موتور','تیپ موتور','کاربری موتور','سیلندر','شماره گواهینامه','صدور گواهینامه','انقضای گواهینامه','شماره بیمه','شرکت بیمه','صدور بیمه','انقضای بیمه','شماره معاینه فنی','صدور معاینه','انقضای معاینه','چراغگردان ثابت','چراغگردان متحرک','گرمایش','سرمایش','آمپلی‌فایر','وضعیت بررسی','اولین تاریخ چک‌لیست','آخرین تاریخ چک‌لیست','تاریخچه کامل چک‌لیست'];$photoKeys=[];foreach($rows as$r)foreach(Db::all('SELECT photo_key FROM personnel_vehicle_asset_photos WHERE asset_id=?',[$r['id']])as$p){$q=(string)$p['photo_key'];if($q!==''&&!in_array($q,$photoKeys,true))$photoKeys[]=$q;}foreach($photoKeys as$q)$head[]='تصویر '.$q;$x=new XlsxWriter($head);foreach($rows as$r){$h=pvas_history((int)$r['id']);$d=array_column($h,'checked_at');$cells=[$r['id'],$r['first_name'],$r['last_name'],$r['username'],$r['role_title'],$r['phone'],$r['national_code'],$r['asset_type']==='car'?'خودرو':'موتورسیکلت',pvas_plate($r),$r['vehicle_type'],$r['fuel_type'],$r['color'],$r['model_year'],$r['chassis_number'],$r['engine_number'],$r['vin'],$r['motorcycle_system'],$r['motorcycle_type'],$r['motorcycle_usage'],$r['cylinders'],$r['license_number'],$r['license_issue_date'],$r['license_expiry_date'],$r['insurance_number'],$r['insurance_company'],$r['insurance_issue_date'],$r['insurance_expiry_date'],$r['technical_inspection_number'],$r['technical_inspection_issue_date'],$r['technical_inspection_expiry_date'],((int)$r['fixed_beacon']?'بله':'خیر'),((int)$r['mobile_beacon']?'بله':'خیر'),((int)$r['heating_ok']?'بله':'خیر'),((int)$r['cooling_ok']?'بله':'خیر'),((int)$r['amplifier']?'بله':'خیر'),$r['status'],$d?end($d):null,$d?$d[0]:null,$d?implode(' | ',$d):null];$by=[];foreach(Db::all('SELECT photo_key,data_uri FROM personnel_vehicle_asset_photos WHERE asset_id=? ORDER BY id',[$r['id']])as$p)$by[(string)$p['photo_key']]=$p;$start=count($cells);foreach($photoKeys as$q)$cells[]='';$row=$x->addRow($cells);foreach($photoKeys as$i=>$q){$bytes=pvas_image($by[$q]['data_uri']??'');if($bytes!==''){$x->setImage($row,$start+$i,$bytes,110);$x->setColWidth($start+$i,18);}}}$x->output('personnel_vehicle_assets.xlsx','خودرو و موتورسیکلت');exit;}
pvas_fail('عملیات نامعتبر',404);
}catch(Throwable$e){error_log('personnel-vehicle-assets-safe: '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());pvas_fail('خطای داخلی سرویس اطلاعات خودرو و موتورسیکلت',500);}
