<?php
ini_set('display_errors','0');
$ROOT=__DIR__.'/../..';require "$ROOT/lib/Db.php";require "$ROOT/lib/Jwt.php";require "$ROOT/lib/Http.php";$CONFIG=require "$ROOT/config.php";
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store,max-age=0');
function rj($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function re($m,$s=400){rj(['ok'=>false,'error'=>$m],$s);}
function te($t){$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);return (int)($r['c']??0)>0;}function ce($t,$c){$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[$t,$c]);return (int)($r['c']??0)>0;}
function au(){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))re('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.*,r.title role_title,r.level,r.is_admin FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])re('کاربر نامعتبر است',401);if(te('user_sessions')){$dt=$p['dt']??'web';$s=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$admin=!empty($u['is_admin'])||in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);if(!$s||$s['revoked_at']||(!$admin&&(string)$s['device_id']!==(string)($p['device_id']??'')))re('نشست منقضی یا باطل شده است',401);}return $u;}
function rules($id){$a=['regions'=>[],'users'=>[],'roles'=>[]];foreach($a as $k=>$_){$t=['regions'=>'radio_channel_regions','users'=>'radio_channel_users','roles'=>'radio_channel_roles'][$k];if(te($t)){$col=$k==='regions'?'region_id':($k==='users'?'user_id':'role_id');$a[$k]=array_map('intval',array_column(Db::all("SELECT $col v FROM $t WHERE channel_id=?",[$id]),'v'));}}return $a;}
function uregion($u){foreach(['region_id','area_id','zone_id','district_id'] as $c)if(ce('users',$c)&&!empty($u[$c]))return (int)$u[$c];foreach(['user_regions','user_region'] as $t)if(te($t)&&ce($t,'user_id'))foreach(['region_id','area_id','zone_id'] as $c)if(ce($t,$c)){$r=Db::one("SELECT $c v FROM $t WHERE user_id=? LIMIT 1",[$u['id']]);if($r&&$r['v']!==null)return (int)$r['v'];}return 0;}
function allowed($cid,$u){$c=Db::one('SELECT * FROM radio_channels WHERE id=? AND is_active=1',[(int)$cid]);if(!$c)re('کانال بی‌سیم یافت نشد',404);$r=rules($cid);$g=[];if($r['regions'])$g[]=in_array(uregion($u),$r['regions'],true);if($r['roles'])$g[]=in_array((int)$u['role_id'],$r['roles'],true);if($r['users'])$g[]=in_array((int)$u['id'],$r['users'],true);if($g&&(($c['match_mode']??'OR')==='AND'?!in_array(false,$g,true):!in_array(true,$g,true)))re('شما عضو این کانال نیستید',403);return $c;}
$u=au();$cid=(int)($_GET['channel_id']??0);if(!$cid)re('کانال نامعتبر است',400);allowed($cid,$u);$rows=Db::all('SELECT m.id,m.channel_id,m.sender_id,m.sender_name,m.duration_ms,m.bytes_size,m.created_at,r.title role_title FROM radio_messages m JOIN users su ON su.id=m.sender_id LEFT JOIN roles r ON r.id=su.role_id WHERE m.channel_id=? ORDER BY m.id DESC LIMIT 3',[$cid]);foreach($rows as &$r)$r['audio_url']='/api/radio-api-v2.php?op=audio&id='.(int)$r['id'];unset($r);rj(['ok'=>true,'messages'=>$rows]);
