<?php
ini_set('display_errors','0'); error_reporting(E_ALL); header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store');
$ROOT=__DIR__.'/..'; require "$ROOT/lib/Db.php"; require "$ROOT/lib/Jwt.php"; require "$ROOT/lib/Http.php"; require "$ROOT/lib/BaleBot.php"; require "$ROOT/lib/MessengerBot.php"; $CONFIG=require "$ROOT/config.php";
function rb_out($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;} function rb_fail($m,$s=400){rb_out(['error'=>$m],$s);}
function rb_user(){global $CONFIG;$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/Bearer\s+(.+)/i',$h,$m))rb_fail('توکن نامعتبر است',401);$p=Jwt::verify(trim($m[1]),$CONFIG['jwt_secret']);if(!$p)rb_fail('توکن منقضی یا نامعتبر است',401);$u=Db::one("SELECT u.id,u.is_active FROM users u WHERE u.id=?",[$p['sub']]);if(!$u||!$u['is_active'])rb_fail('کاربر نامعتبر',401);return $u;}
function rb_file($data,$name,$index){if(!is_string($data)||!preg_match('#^data:([a-zA-Z0-9.+-]+);base64,(.*)$#s',$data,$m))return null;$mime=strtolower($m[1]);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'];if(!isset($allowed[$mime]))rb_fail('فرمت پیوست مجاز نیست',422);$bin=base64_decode($m[2],true);if($bin===false||strlen($bin)>10*1024*1024)rb_fail('حجم پیوست بیش از ۱۰ مگابایت است',422);$dir=__DIR__.'/../uploads/report-bot/'.date('Y/m');@mkdir($dir,0775,true);$safe=preg_replace('/[^a-zA-Z0-9._-]+/','_',basename((string)$name));$file=$index.'_'.bin2hex(random_bytes(8)).'.'.$allowed[$mime];$abs=$dir.'/'.$file;if(file_put_contents($abs,$bin)===false)rb_fail('ذخیره پیوست انجام نشد',500);$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$base=$https.'://'.($_SERVER['HTTP_HOST']??'localhost');return ['url'=>$base.'/uploads/report-bot/'.date('Y/m').'/'.$file,'mime'=>$mime,'name'=>$safe];}
$u=rb_user();$b=json_decode(file_get_contents('php://input'),true)?:$_POST;$subject=trim((string)($b['subject']??''));$body=trim((string)($b['body']??''));if($subject===''||$body==='')rb_fail('موضوع و متن گزارش الزامی است');$sender=Db::one("SELECT first_name,last_name,phone FROM users WHERE id=?",[$u['id']]);$senderName=trim(($sender['first_name']??'').' '.($sender['last_name']??''));$text="گزارش جدید خطیار\nفرستنده: ".$senderName."\nموضوع: ".$subject."\nمتن گزارش:\n".$body;$attachments=[];foreach(array_slice((array)($b['attachments']??[]),0,5) as $i=>$a){$f=rb_file($a['data']??null,$a['name']??('attachment-'.$i),$i);if($f)$attachments[]=$f;}
$out=[];
try{$chat=BaleBot::findChatForUser((int)$u['id']);if($chat){$out['bale']=['message'=>BaleBot::sendMessage($chat,$text,['target_type'=>'report','target_id'=>$b['report_id']??null])];foreach($attachments as $f){$method=str_starts_with($f['mime'],'image/')?'sendPhoto':'sendDocument';$payload=['chat_id'=>$chat,str_starts_with($f['mime'],'image/')?'photo':'document'=>$f['url'],'caption'=>($f['name']??'پیوست گزارش')];$out['bale']['attachments'][]=BaleBot::request($method,$payload);}}else $out['bale']=['error'=>'not_connected'];}catch(Throwable $e){$out['bale']=['error'=>$e->getMessage()];}
foreach(['telegram','eitaa'] as $platform){try{$sub=Db::one("SELECT chat_id FROM messenger_subscribers WHERE platform=? AND user_id=? AND is_active=1 ORDER BY id DESC LIMIT 1",[$platform,$u['id']]);if(!$sub){$out[$platform]=['error'=>'not_connected'];continue;}$out[$platform]=['message'=>MessengerBot::sendMessage($platform,$sub['chat_id'],$text,['target_type'=>'report','target_id'=>$b['report_id']??null])];foreach($attachments as $f){$method=str_starts_with($f['mime'],'image/')?'sendPhoto':'sendDocument';$payload=['chat_id'=>$sub['chat_id'],str_starts_with($f['mime'],'image/')?'photo':'document'=>$f['url'],'caption'=>($f['name']??'پیوست گزارش')];$out[$platform]['attachments'][]=MessengerBot::request($platform,$method,$payload);}}catch(Throwable $e){$out[$platform]=['error'=>$e->getMessage()];}}
rb_out(['ok'=>true,'sender'=>$senderName,'subject'=>$subject,'attachments'=>count($attachments),'delivery'=>$out]);
