<?php
/** Unified Role App Items source of truth. */
require_once __DIR__ . '/../../lib/Db.php'; require_once __DIR__ . '/../../lib/Jwt.php'; require_once __DIR__ . '/../../lib/Http.php';
$CONFIG=require __DIR__.'/../../config.php'; header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
function kh_table_exists($t){static $c=[];if(isset($c[$t]))return $c[$t];try{$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$t]);return $c[$t]=((int)($r['c']??0)>0);}catch(Throwable $e){return $c[$t]=false;}}
function kh_auth_user(){global $CONFIG;$tok=Http::bearer();$p=$tok?Jwt::verify($tok,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))Http::error('توکن منقضی یا نامعتبر است',401);Http::$currentToken=$tok;$u=Db::one("SELECT u.id,u.username,u.first_name,u.last_name,u.role_id,r.title role_title,r.level,r.is_admin,u.is_active,u.email,u.photo,u.photo_path FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])Http::error('کاربر نامعتبر',401);$dt=$p['dt']??'web';if(kh_table_exists('user_sessions')){$s=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$unlimited=in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true)||!empty($u['is_admin']);if(!$s||$s['revoked_at']||(!$unlimited&&(string)$s['device_id']!==(string)($p['device_id']??'')))Http::error('نشست منقضی یا باطل شده است',401);}return $u;}
function kh_is_admin($u){return !empty($u['is_admin'])||in_array((string)($u['role_title']??''),['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);}
const KH_LINE_LOCATION='LineLocation';const KH_STATION_CAPTURE='StationCapture';const KH_MY_STATIONS='MyStations';const KH_LINE_VISIT='LineVisitProgram';
$allItems=['Dashboard','Search','Driver','Vehicle','Debt','Checklist','Notice','Reports','Sms','BotMessages','Requests','RequestInbox','WorkSummary','SalarySlips','CompanyRequests','Subscription','CheckIn','Forms','Cultural','Welfare','TempDrivers','Notifications','FieldAlerts','ActivityReport','ExpInsurance','ExpTaxi','ExpOplic','TeamReport','InboxReports','ReportDetail','OfficialPresence','Inventory','Messages','Attendance','PastNotices','PastChecklists','DriverSms','MySms','CustomFields','Outage','Profile','ChangePassword','EditProfile','PersonnelVehicleAsset','PersonnelVehicleChecklist','MapSettings','ExpiryNotificationSettings','FieldAlertSettings','ImportTimes','AppLockSettings','CrashReports','LineVisitProgram','LineLocation','MyDailyMission','RoleDashboard','Leaderboard','Radio','Help','StationCapture','MyStations','PresentList'];
function kh_read_config($pdo){try{$r=$pdo->query("SELECT value FROM app_settings WHERE `key`='role_app_items' LIMIT 1")->fetch(PDO::FETCH_ASSOC);$x=$r?json_decode((string)$r['value'],true):[];return is_array($x)?$x:[];}catch(Throwable $e){error_log('role_app_items config: '.$e->getMessage());return [];}}
function kh_roles($pdo){$o=[];try{foreach($pdo->query("SELECT id,title FROM roles ORDER BY id") as $r)$o[]=['id'=>(string)$r['id'],'title'=>(string)$r['title']];}catch(Throwable $e){error_log('role_app_items roles: '.$e->getMessage());}return $o;}
function kh_clean($v){global $allItems;$allowed=array_fill_keys($allItems,true);if(!is_array($v))return []; $o=[];$seen=[];foreach($v as $x){$x=(string)$x;if($x!==''&&isset($allowed[$x])&&!isset($seen[$x])){$seen[$x]=1;$o[]=$x;}}return $o;}
function kh_normalize_config($cfg){global $allItems;$out=[];if(!is_array($cfg))return $out;foreach($cfg as $rid=>$items){$rid=(string)$rid;$raw=is_array($items)?$items:[];$clean=kh_clean($raw);$hadValid=count($clean)>0;$hadExplicitArray=is_array($items); // [] intentionally means no access
    // Legacy/site-only configurations can otherwise lock everyone out. If a role has only
    // obsolete web keys, restore the app default; explicit [] remains "none".
    if($hadExplicitArray && count($raw)>0 && !$hadValid)$clean=$allItems;
    $out[$rid]=$clean;
  }return $out;}
function kh_one_time_migrate($pdo,$cfg){
  try{$norm=kh_normalize_config($cfg);$js=json_encode($norm,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$old=json_encode($cfg,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($js!==$old){$st=$pdo->prepare("INSERT INTO app_settings(`key`,value) VALUES('role_app_items',?) ON DUPLICATE KEY UPDATE value=VALUES(value)");$st->execute([$js]);}
    $st=$pdo->prepare("INSERT INTO app_settings(`key`,value) VALUES('role_app_items_unified_migrated','1') ON DUPLICATE KEY UPDATE value='1'");$st->execute();return $norm;
  }catch(Throwable $e){error_log('role_app_items migration: '.$e->getMessage());return kh_normalize_config($cfg);}
}
try{$u=kh_auth_user();$pdo=Db::pdo();$m=$_SERVER['REQUEST_METHOD']??'GET';$cfg=kh_read_config($pdo);$roles=kh_roles($pdo);$cfg=kh_one_time_migrate($pdo,$cfg);
if($m==='GET'){if(kh_is_admin($u)){echo json_encode(['success'=>true,'roles'=>$roles,'config'=>$cfg,'items'=>$allItems,'default_items'=>$allItems,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}$rid=(string)($u['role_id']??'');$items=!array_key_exists($rid,$cfg)||!is_array($cfg[$rid])?$allItems:kh_clean($cfg[$rid]);echo json_encode(['success'=>true,'items'=>$items,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($m==='POST'){if(!kh_is_admin($u))Http::error('دسترسی غیرمجاز',403);$in=Http::body();if(!isset($in['config'])||!is_array($in['config']))Http::error('تنظیمات آیتم‌های اپ نامعتبر است',422);$new=[];foreach($in['config'] as $rid=>$items)$new[(string)$rid]=is_array($items)?kh_clean($items):$allItems;$js=json_encode($new,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$st=$pdo->prepare("INSERT INTO app_settings(`key`,value) VALUES('role_app_items',?) ON DUPLICATE KEY UPDATE value=VALUES(value)");$st->execute([$js]);echo json_encode(['success'=>true,'ok'=>true,'config'=>$new,'items'=>$allItems,'roles'=>$roles,'default_items'=>$allItems,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}Http::error('Method not allowed',405);}catch(Throwable $e){error_log('unified-role-app-items fatal: '.$e->getMessage());http_response_code(500);echo json_encode(['success'=>false,'error'=>'خطای داخلی در بارگذاری تنظیمات سمت‌ها و آیتم‌های اپ'],JSON_UNESCAPED_UNICODE);}
