<?php
/** Unified Role App Items source of truth. */
require_once __DIR__ . '/../../lib/Db.php';
require_once __DIR__ . '/../../lib/Jwt.php';
require_once __DIR__ . '/../../lib/Http.php';
$CONFIG=require __DIR__.'/../../config.php';
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
function kh_table_exists($table){static $c=[];if(isset($c[$table]))return $c[$table];try{$r=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",[$table]);return $c[$table]=((int)($r['c']??0)>0);}catch(Throwable $e){return $c[$table]=false;}}
function kh_auth_user(){global $CONFIG;$token=Http::bearer();$p=$token?Jwt::verify($token,$CONFIG['jwt_secret']):null;if(!$p||empty($p['sub']))Http::error('توکن منقضی یا نامعتبر است',401);Http::$currentToken=$token;$u=Db::one("SELECT u.id,u.username,u.first_name,u.last_name,u.role_id,r.title role_title,r.level,r.is_admin,u.is_active,u.email,u.photo,u.photo_path FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=? LIMIT 1",[$p['sub']]);if(!$u||!(int)$u['is_active'])Http::error('کاربر نامعتبر',401);$dt=$p['dt']??'web';if(kh_table_exists('user_sessions')){$s=Db::one("SELECT device_id,revoked_at FROM user_sessions WHERE user_id=? AND device_type=? ORDER BY id DESC LIMIT 1",[$u['id'],$dt]);$unlimited=in_array((string)$u['role_title'],['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true)||!empty($u['is_admin']);if(!$s||$s['revoked_at']||(!$unlimited&&(string)$s['device_id']!==(string)($p['device_id']??'')))Http::error('نشست منقضی یا باطل شده است',401);}$u['device_id']=$p['device_id']??null;$u['device_type']=$dt;return $u;}
function kh_is_admin($u){return !empty($u['is_admin'])||in_array((string)($u['role_title']??''),['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد','admin','superadmin'],true);}
const KH_LINE_LOCATION='LineLocation'; const KH_STATION_CAPTURE='StationCapture'; const KH_MY_STATIONS='MyStations';
$allItems=['Search','PresentList','Reports','CheckIn','Requests','RequestInbox','WorkSummary','SalarySlips','CompanyRequests','Subscription','Sms','BotMessages','MySms','Forms','Cultural','Welfare','OfficialPresence','Inventory','MyDailyMission','LineVisitProgram',KH_LINE_LOCATION,KH_STATION_CAPTURE,KH_MY_STATIONS,'RoleDashboard','Leaderboard','ActivityReport','ExpInsurance','ExpTaxi','ExpOplic','TeamReport','TempDrivers','Outage'];
function kh_read_config($pdo){try{$r=$pdo->query("SELECT value FROM app_settings WHERE `key`='role_app_items' LIMIT 1")->fetch(PDO::FETCH_ASSOC);if(!$r)return []; $x=json_decode((string)$r['value'],true);return is_array($x)?$x:[];}catch(Throwable $e){error_log('role_app_items config: '.$e->getMessage());return [];}}
function kh_roles($pdo){$out=[];try{foreach($pdo->query("SELECT id,title FROM roles ORDER BY id") as $r)$out[]=['id'=>(string)$r['id'],'title'=>(string)$r['title']];}catch(Throwable $e){error_log('role_app_items roles: '.$e->getMessage());}return $out;}
function kh_clean($v){if(!is_array($v))return []; $seen=[];$o=[];foreach($v as $x){$x=(string)$x;if($x!==''&&!isset($seen[$x])){$seen[$x]=1;$o[]=$x;}}return $o;}
/* Existing role selections are preserved. Only the newly unified line items are appended when absent. */
function kh_effective_config($cfg,$roles,$allItems){$out=[];foreach($roles as $r){$id=(string)$r['id'];if(!array_key_exists($id,$cfg))continue;if(!is_array($cfg[$id])){$out[$id]=$allItems;continue;}$x=kh_clean($cfg[$id]);foreach([KH_LINE_LOCATION,KH_STATION_CAPTURE,KH_MY_STATIONS,'LineVisitProgram'] as $new){if(!in_array($new,$x,true))$x[]=$new;}$out[$id]=$x;}return $out;}
function kh_save_config($cfg,$roles,$allItems){$out=[];foreach($roles as $r){$id=(string)$r['id'];if(!array_key_exists($id,$cfg))continue;$v=$cfg[$id];$out[$id]=is_array($v)?kh_clean($v):$allItems;}return $out;}
try{$u=kh_auth_user();$pdo=Db::pdo();$m=$_SERVER['REQUEST_METHOD']??'GET';$cfg=kh_read_config($pdo);$roles=kh_roles($pdo);$effective=kh_effective_config($cfg,$roles,$allItems);
if($m==='GET'){if(kh_is_admin($u)){echo json_encode(['success'=>true,'roles'=>$roles,'config'=>$effective,'items'=>$allItems,'default_items'=>$allItems,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}$rid=(string)($u['role_id']??'');$items=!array_key_exists($rid,$effective)||!is_array($effective[$rid])?$allItems:kh_clean($effective[$rid]);echo json_encode(['success'=>true,'items'=>$items,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($m==='POST'){if(!kh_is_admin($u))Http::error('دسترسی غیرمجاز',403);$in=Http::body();if(!isset($in['config'])||!is_array($in['config']))Http::error('تنظیمات آیتم‌های اپ نامعتبر است',422);$new=kh_save_config($in['config'],$roles,$allItems);$js=json_encode($new,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$st=$pdo->prepare("INSERT INTO app_settings(`key`,`value`) VALUES('role_app_items',?) ON DUPLICATE KEY UPDATE value=VALUES(value)");$st->execute([$js]);echo json_encode(['success'=>true,'ok'=>true,'config'=>kh_effective_config($new,$roles,$allItems),'items'=>$allItems,'roles'=>$roles,'source'=>'role_app_items'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}Http::error('Method not allowed',405);}catch(Throwable $e){error_log('unified-role-app-items fatal: '.$e->getMessage());http_response_code(500);echo json_encode(['success'=>false,'error'=>'خطای داخلی در بارگذاری تنظیمات سمت‌ها و آیتم‌های اپ'],JSON_UNESCAPED_UNICODE);}
