<?php
class IranCalendar {
    private const ENDPOINT='https://api.time.ir/v1/event/fa/events/calendar';
    private static $cache=[];
    private static $dayCache=[];
    private static $manualCache=[];
    private static $manualLoaded=[];
    private static $wd=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];
    private static function env($n,$d=null){$v=getenv($n);return $v===false||trim((string)$v)===''?$d:trim($v);}
    public static function normalize($x){$x=trim(strtr((string)$x,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']));$x=str_replace(['/','.'],'-',$x);if(!preg_match('/^(\d{4})-(\d{1,2})-(\d{1,2})$/',$x,$m))return null;$y=(int)$m[1];$mo=(int)$m[2];$d=(int)$m[3];if($mo<1||$mo>12||$d<1||$d>self::monthLength($y,$mo))return null;return sprintf('%04d-%02d-%02d',$y,$mo,$d);}
    private static function leap($y){return in_array($y%33,[1,5,9,13,17,22,26,30],true);}
    public static function monthLength($y,$m){if($m<=6)return 31;if($m<=11)return 30;return self::leap($y)?30:29;}
    public static function toGregorian($jy,$jm,$jd){$j=$jy-979;$m=$jm-1;$n=365*$j+intdiv($j,33)*8+intdiv(($j%33)+3,4)+($m<6?$m*31:$m*30+6)+$jd-1+79;$gy=1600+400*intdiv($n,146097);$n%=146097;$lp=true;if($n>=36525){$n--;$gy+=100*intdiv($n,36524);$n%=36524;if($n>=365)$n++;else$lp=false;}$gy+=4*intdiv($n,1461);$n%=1461;if($n>=366){$lp=false;$n--;$gy+=intdiv($n,365);$n%=365;}$gd=$n+1;$md=[31,$lp?29:28,31,30,31,30,31,31,30,31,30,31];$gm=1;foreach($md as $z){if($gd<=$z)break;$gd-=$z;$gm++;}return[$gy,$gm,$gd];}
    public static function weekdayIndex($j){$j=self::normalize($j);if(!$j)return null;[$y,$m,$d]=array_map('intval',explode('-',$j));[$gy,$gm,$gd]=self::toGregorian($y,$m,$d);return((int)date('w',mktime(12,0,0,$gm,$gd,$gy))+1)%7;}
    public static function weekday($j){$i=self::weekdayIndex($j);return$i===null?null:self::$wd[$i];}
    private static function file($y){$d=__DIR__.'/../cache/calendar';if(!is_dir($d))@mkdir($d,0775,true);return$d.'/'.$y.'.json';}
    private static function json($url){$t=(int)self::env('KHATYAR_CALENDAR_TIMEOUT',8);$key=self::env('TIME_IR_API_KEY',self::env('KHATYAR_TIME_IR_API_KEY',null));$h=['Accept: application/json','User-Agent: KhatYar-Calendar/1.0'];if($key)$h[]='X-API-Key: '.$key;if(function_exists('curl_init')){$c=curl_init($url);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>1,CURLOPT_FOLLOWLOCATION=>1,CURLOPT_CONNECTTIMEOUT=>$t,CURLOPT_TIMEOUT=>$t,CURLOPT_HTTPHEADER=>$h,CURLOPT_SSL_VERIFYPEER=>1,CURLOPT_SSL_VERIFYHOST=>2]);$b=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);if($b!==false&&$s>=200&&$s<300){$j=json_decode($b,true);if(is_array($j))return$j;}}return null;}
    private static function title($e){foreach(['title','event_name','eventName','text','description','occasion','name']as$k)if(isset($e[$k])&&is_scalar($e[$k])&&trim((string)$e[$k])!=='')return trim((string)$e[$k]);return'مناسبت';}
    private static function dateOf($e,$y){foreach(['jDate','jdate','jalali_date','date','persian_date']as$k){if(!isset($e[$k]))continue;$v=$e[$k];if(is_array($v)){if(isset($v['date']))$v=$v['date'];elseif(isset($v['year'],$v['month'],$v['day']))$v=sprintf('%04d-%02d-%02d',$v['year'],$v['month'],$v['day']);elseif(isset($v[0],$v[1],$v[2]))$v=implode('-',$v);} $d=self::normalize($v);if($d&&(int)substr($d,0,4)===$y)return$d;}return null;}
    private static function isHoliday($e){foreach(['isHoliday','is_holiday','holiday']as$k)if(array_key_exists($k,$e)){if(is_bool($e[$k]))return$e[$k];return in_array(strtolower(trim((string)$e[$k])),['1','true','yes','holiday','تعطیل'],true);}return mb_strpos(mb_strtolower(self::title($e),'UTF-8'),'تعطیل')!==false;}
    private static function walk($x,$y,&$out){if(!is_array($x))return;if(isset($x['events'])&&is_array($x['events']))foreach($x['events']as$e)self::walk($e,$y,$out);$d=self::dateOf($x,$y);if($d)$out[$d.'|'.self::title($x)]=['jdate'=>$d,'title'=>self::title($x),'is_holiday'=>self::isHoliday($x),'source'=>'official'];foreach($x as$v)if(is_array($v))self::walk($v,$y,$out);}
    private static function fallbackEvents($y){$sets=[1404=>[['01','01','آغاز نوروز'],['01','02','شهادت حضرت علی (ع) و عید نوروز'],['01','03','عید نوروز'],['01','04','عید نوروز'],['01','11','عید سعید فطر'],['01','12','تعطیل به مناسبت عید سعید فطر و روز جمهوری اسلامی ایران'],['01','13','روز طبیعت'],['02','04','شهادت امام جعفر صادق (ع)'],['03','14','رحلت امام خمینی (ره)'],['03','15','قیام ۱۵ خرداد'],['03','16','عید سعید قربان'],['03','24','عید سعید غدیر خم'],['04','14','تاسوعای حسینی'],['04','15','عاشورای حسینی'],['05','23','اربعین حسینی'],['05','31','رحلت حضرت رسول اکرم (ص) و شهادت امام حسن مجتبی (ع)'],['06','02','شهادت امام رضا (ع)'],['06','10','شهادت امام حسن عسکری (ع) و آغاز امامت حضرت ولیعصر (عج)'],['06','19','میلاد حضرت رسول اکرم (ص) و میلاد امام جعفر صادق (ع)'],['09','03','شهادت حضرت فاطمه زهرا (س)'],['10','13','ولادت امام علی (ع) و روز پدر'],['10','27','مبعث حضرت رسول اکرم (ص)'],['11','15','ولادت حضرت قائم (عج)'],['11','22','پیروزی انقلاب اسلامی ایران'],['12','20','شهادت حضرت علی (ع)'],['12','29','روز ملی شدن صنعت نفت ایران']],1405=>[['01','01','عید سعید فطر و آغاز نوروز'],['01','02','تعطیل به مناسبت عید سعید فطر و عید نوروز'],['01','03','عید نوروز'],['01','04','عید نوروز'],['01','12','روز جمهوری اسلامی ایران'],['01','13','روز طبیعت'],['01','25','شهادت امام جعفر صادق (ع)'],['03','06','عید سعید قربان'],['03','14','عید سعید غدیر خم و رحلت امام خمینی (ره)'],['03','15','قیام ۱۵ خرداد'],['04','03','تاسوعای حسینی'],['04','04','عاشورای حسینی'],['05','13','اربعین حسینی'],['05','21','رحلت حضرت رسول اکرم (ص) و شهادت امام حسن مجتبی (ع)'],['05','22','شهادت امام رضا (ع)'],['05','30','شهادت امام حسن عسکری (ع) و آغاز امامت حضرت ولیعصر (عج)'],['06','08','ولادت حضرت رسول اکرم (ص) و ولادت امام جعفر صادق (ع)'],['08','22','شهادت حضرت فاطمه زهرا (س)'],['10','02','ولادت حضرت امام علی (ع) و روز پدر'],['10','16','مبعث حضرت رسول اکرم (ص)'],['11','04','ولادت حضرت قائم (عج)'],['11','22','پیروزی انقلاب اسلامی ایران'],['12','09','شهادت حضرت امام علی (ع)'],['12','19','عید سعید فطر'],['12','20','تعطیل به مناسبت عید سعید فطر'],['12','29','روز ملی شدن صنعت نفت ایران']]];$a=$sets[(int)$y]??[];$o=[];foreach($a as$e){$j=sprintf('%04d-%02d-%02d',$y,(int)$e[0],(int)$e[1]);$o[$j.'|'.$e[2]]=['jdate'=>$j,'title'=>$e[2],'is_holiday'=>true,'source'=>'official-reference'];}return$o;}
    public static function syncYear($y,$force=false){$y=(int)$y;if(!$force&&isset(self::$cache[$y]))return true;$ref=self::fallbackEvents($y);if($ref){$c=['year'=>$y,'source'=>'official-reference','synced_at'=>date('c'),'events'=>array_values($ref)];$f=self::file($y);if($force||!is_file($f))@file_put_contents($f,json_encode($c,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);self::$cache[$y]=$c;return true;}$f=self::file($y);$c=is_file($f)?json_decode((string)@file_get_contents($f),true):null;if(!$force&&is_array($c)&&isset($c['synced_at'])&&time()-strtotime($c['synced_at'])<86400){self::$cache[$y]=$c;return true;}$ep=self::env('KHATYAR_CALENDAR_ENDPOINT',self::ENDPOINT);$sep=strpos($ep,'?')===false?'?':'&';$all=[];for($m=0;$m<=12;$m++){$j=self::json($ep.$sep.'year='.$y.($m?'&month='.$m:''));if($j)self::walk($j,$y,$all);}if(!$all&&!empty($c['events'])){$c['source']=$c['source']??'official-cache';self::$cache[$y]=$c;return true;}if(!$all)return false;$c=['year'=>$y,'source'=>'official-service','synced_at'=>date('c'),'events'=>array_values($all)];@file_put_contents($f,json_encode($c,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);self::$cache[$y]=$c;return true;}
    public static function events($y,$force=false){$y=(int)$y;if(!$force&&isset(self::$cache[$y]['days']))return self::$cache[$y]['days'];self::syncYear($y,$force);$c=self::$cache[$y]??null;$days=[];for($m=1;$m<=12;$m++)for($d=1;$d<=self::monthLength($y,$m);$d++){$j=sprintf('%04d-%02d-%02d',$y,$m,$d);$days[$j]=['jdate'=>$j,'weekday_index'=>self::weekdayIndex($j),'weekday'=>self::weekday($j),'is_holiday'=>false,'title'=>null,'source'=>'calculated'];}foreach(($c['events']??[])as$e){$j=self::normalize($e['jdate']??'');if(!$j||!isset($days[$j]))continue;if(!empty($e['is_holiday']))$days[$j]['is_holiday']=true;$days[$j]['title']=$days[$j]['title']?($days[$j]['title'].' | '.$e['title']):$e['title'];$days[$j]['source']=$e['source']??'official';}self::$cache[$y]['days']=$days;return$days;}
    private static function loadManualYear($y){$y=(int)$y;if(isset(self::$manualLoaded[$y])||!class_exists('Db'))return;self::$manualLoaded[$y]=true;try{$rows=Db::all('SELECT jdate,title FROM holidays WHERE jdate LIKE ? OR jdate LIKE ?',[$y.'-%',$y.'/%%']);foreach($rows as$r){$j=self::normalize($r['jdate']??'');if($j)self::$manualCache[$j]=trim((string)($r['title']??''));}}catch(Throwable$e){}}
    public static function manualTitle($j){$j=self::normalize($j);if(!$j||!class_exists('Db'))return null;if(array_key_exists($j,self::$manualCache))return self::$manualCache[$j];self::loadManualYear((int)substr($j,0,4));return array_key_exists($j,self::$manualCache)?self::$manualCache[$j]:null;}
    public static function isManualHoliday($j){return self::manualTitle($j)!==null;}
    public static function holidays($y){$o=[];foreach(self::events($y)as$j=>$e){$m=self::manualTitle($j);if(!empty($e['is_holiday'])||$m!==null)$o[$j]=implode(' | ',array_unique(array_filter([$e['title']??null,$m])))?:'تعطیل';}ksort($o);return$o;}
    public static function isOfficialHoliday($j){return!empty(self::day($j)['is_official_holiday']);}
    public static function day($j){$j=self::normalize($j);if(!$j)return['is_official_holiday'=>false,'is_manual_holiday'=>false,'is_holiday'=>false,'title'=>null,'source'=>null,'weekday'=>null,'weekday_index'=>null];if(isset(self::$dayCache[$j]))return self::$dayCache[$j];$e=self::events((int)substr($j,0,4))[$j]??[];$m=self::manualTitle($j);$of=!empty($e['is_holiday']);$man=$m!==null;$t=array_filter([$e['title']??null,$m]);return self::$dayCache[$j]=['is_official_holiday'=>$of,'is_manual_holiday'=>$man,'is_holiday'=>$of||$man,'title'=>implode(' | ',array_unique($t))?:null,'source'=>$of&&$man?'official+manual':($of?($e['source']??'official'):($man?'manual':null)),'weekday'=>$e['weekday']??self::weekday($j),'weekday_index'=>$e['weekday_index']??self::weekdayIndex($j)];}
}