<?php
/** Khatyar - ثبت موقعیت و تصویر خطوط تاکسیرانی */
function _ll_ensure_schema(){
  $stmts=[
    "CREATE TABLE IF NOT EXISTS line_location_permissions (id INT AUTO_INCREMENT PRIMARY KEY, role_id INT NOT NULL, can_capture TINYINT(1) NOT NULL DEFAULT 0, can_view TINYINT(1) NOT NULL DEFAULT 0, can_manage TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_llp_role(role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS line_station_locations (id BIGINT AUTO_INCREMENT PRIMARY KEY, line_id INT NOT NULL, station_name VARCHAR(190) NULL, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, accuracy_m DECIMAL(10,2) NULL, location_photo_path VARCHAR(500) NULL, sign_photo_path VARCHAR(500) NULL, captured_by INT NOT NULL, captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_lsl_line(line_id), INDEX idx_lsl_captured(captured_by,captured_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
  ];
  foreach($stmts as $s){ try{Db::run($s);}catch(Throwable $e){error_log('line-location schema: '.$e->getMessage());} }
  foreach(['latitude DECIMAL(10,7) NULL','longitude DECIMAL(10,7) NULL','location_accuracy_m DECIMAL(10,2) NULL','location_photo_path VARCHAR(500) NULL','station_sign_photo_path VARCHAR(500) NULL','location_updated_by INT NULL','location_updated_at DATETIME NULL'] as $def){
    try{ $col=strtok($def,' '); $n=Db::one("SELECT COUNT(*) c FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='lines' AND COLUMN_NAME=?",[$col]); if(!(int)($n['c']??0)) Db::run("ALTER TABLE `lines` ADD COLUMN `$col` ".substr($def,strlen($col))); }catch(Throwable $e){error_log('line-location column: '.$e->getMessage());}
  }
}
function _ll_can($u,$what){
  if(!$u) return false;
  if(!empty($u['is_admin']) || in_array($u['role_title']??'', ['مدیر کل','رییس اداره بازرسی','نیروی اداری ارشد'],true)) return true;
  _ll_ensure_schema(); $p=Db::one("SELECT can_capture,can_view,can_manage FROM line_location_permissions WHERE role_id=?",[(int)$u['role_id']]);
  return !empty($p[$what]);
}
function _ll_upload($field,$prefix){
  if(empty($_FILES[$field]) || ($_FILES[$field]['error']??1)!==UPLOAD_ERR_OK) return null;
  $f=$_FILES[$field]; if((int)$f['size']>8*1024*1024) Http::error('حجم تصویر بیش از ۸ مگابایت است',400);
  $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']); $ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null; if(!$ext) Http::error('فرمت تصویر مجاز نیست',400);
  $rel='/uploads/line-locations/'.date('Y/m').'/'; $dir=__DIR__.'/../public'.$rel; @mkdir($dir,0775,true); $name=$prefix.'_'.bin2hex(random_bytes(8)).'.'.$ext;
  if(!move_uploaded_file($f['tmp_name'],$dir.$name)) Http::error('ذخیره تصویر ناموفق بود',500); return $rel.$name;
}
function _ll_json_photo($value,$prefix){
  if(!$value || !preg_match('#^data:image/(jpeg|png|webp);base64,#i',$value,$m)) return null; $bin=base64_decode(substr($value,strpos($value,',')+1),true); if($bin===false || strlen($bin)>8*1024*1024)return null;
  $ext=strtolower($m[1]); if($ext==='jpeg')$ext='jpg'; $rel='/uploads/line-locations/'.date('Y/m').'/'; $dir=__DIR__.'/../public'.$rel; @mkdir($dir,0775,true); $name=$prefix.'_'.bin2hex(random_bytes(8)).'.'.$ext; if(file_put_contents($dir.$name,$bin)===false)return null; return $rel.$name;
}
route('GET','/api/line-location/permission',function($p,$b,$u){_ll_ensure_schema();return ['allowed'=>_ll_can($u,'can_capture'),'can_view'=>_ll_can($u,'can_view'),'can_manage'=>_ll_can($u,'can_manage'),'role_id'=>(int)$u['role_id']];});
route('GET','/api/line-location/lines',function($p,$b,$u){if(!_ll_can($u,'can_capture')&&!_ll_can($u,'can_view'))Http::error('دسترسی ثبت موقعیت خطوط ندارید',403);_ll_ensure_schema();$ids=user_line_ids($u);$where='';$args=[];if(is_array($ids)){if(!$ids)return[];$in=implode(',',array_fill(0,count($ids),'?'));$where=" WHERE l.id IN($in)";$args=$ids;}return Db::all("SELECT l.id,l.code,l.origin,l.destination,l.status,l.latitude,l.longitude,l.location_accuracy_m,l.location_photo_path,l.station_sign_photo_path,l.location_updated_at FROM `lines` l $where ORDER BY l.code",$args);});
route('GET','/api/line-location/roles',function($p,$b,$u){if(!_ll_can($u,'can_manage'))Http::error('دسترسی مدیریت مجوزها ندارید',403);_ll_ensure_schema();return Db::all("SELECT r.id,r.title,r.level,COALESCE(p.can_capture,0) can_capture,COALESCE(p.can_view,0) can_view,COALESCE(p.can_manage,0) can_manage FROM roles r LEFT JOIN line_location_permissions p ON p.role_id=r.id ORDER BY r.level,r.title");});
route('POST','/api/line-location/roles',function($p,$b,$u){if(!_ll_can($u,'can_manage'))Http::error('دسترسی مدیریت مجوزها ندارید',403);_ll_ensure_schema();$rid=(int)($b['role_id']??0);if($rid<1)Http::error('سمت نامعتبر است',400);Db::run("INSERT INTO line_location_permissions(role_id,can_capture,can_view,can_manage) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE can_capture=VALUES(can_capture),can_view=VALUES(can_view),can_manage=VALUES(can_manage)",[$rid,!empty($b['can_capture'])?1:0,!empty($b['can_view'])?1:0,!empty($b['can_manage'])?1:0]);return['ok'=>true];},false,3);
route('POST','/api/line-location/capture',function($p,$b,$u){if(!_ll_can($u,'can_capture'))Http::error('دسترسی ثبت موقعیت خطوط ندارید',403);_ll_ensure_schema();$lineId=(int)($b['line_id']??0);$line=Db::one("SELECT id,code FROM `lines` WHERE id=?",[$lineId]);if(!$line)Http::error('خط انتخاب‌شده وجود ندارد',404);$ids=user_line_ids($u);if(is_array($ids)&&!in_array($lineId,$ids,true))Http::error('این خط در محدوده دسترسی شما نیست',403);$lat=$b['latitude']??null;$lng=$b['longitude']??null;if(!is_numeric($lat)||!is_numeric($lng)||$lat<-90||$lat>90||$lng<-180||$lng>180)Http::error('مختصات نامعتبر است',400);$acc=is_numeric($b['accuracy_m']??null)?(float)$b['accuracy_m']:null;$photo=_ll_upload('location_photo','line');$sign=_ll_upload('sign_photo','sign');$photo=$photo?:_ll_json_photo($b['location_photo']??null,'line');$sign=$sign?:_ll_json_photo($b['sign_photo']??null,'sign');if(!$photo||!$sign)Http::error('هر دو تصویر محل خط و تابلو ایستگاه الزامی است',400);$now=date('Y-m-d H:i:s');Db::run("INSERT INTO line_station_locations(line_id,station_name,latitude,longitude,accuracy_m,location_photo_path,sign_photo_path,captured_by,captured_at) VALUES(?,?,?,?,?,?,?,?,?)",[$lineId,trim((string)($b['station_name']??''))?:null,$lat,$lng,$acc,$photo,$sign,$u['id'],$now]);$id=(int)Db::pdo()->lastInsertId();Db::run("UPDATE `lines` SET latitude=?,longitude=?,location_accuracy_m=?,location_photo_path=?,station_sign_photo_path=?,location_updated_by=?,location_updated_at=? WHERE id=?",[$lat,$lng,$acc,$photo,$sign,$u['id'],$now,$lineId]);return['ok'=>true,'id'=>$id,'line_id'=>$lineId,'line_code'=>$line['code'],'latitude'=>(float)$lat,'longitude'=>(float)$lng,'accuracy_m'=>$acc,'location_photo'=>$photo,'sign_photo'=>$sign,'updated_at'=>$now];});
route('GET','/api/line-location/history/{lineId}',function($p,$b,$u){if(!_ll_can($u,'can_view'))Http::error('دسترسی مشاهده موقعیت خطوط ندارید',403);_ll_ensure_schema();$lineId=(int)$p['lineId'];return Db::all("SELECT s.*,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) captured_by_name FROM line_station_locations s LEFT JOIN users u ON u.id=s.captured_by WHERE s.line_id=? ORDER BY s.captured_at DESC LIMIT 100",[$lineId]);});
