<?php
route('GET','/api/school-service/dashboard',function($p,$b,$u){
 _ssv_need($u,'view');_ssv_tables();$district=_ssv_norm($_GET['district']??'');$company=(int)($_GET['company_id']??0);$w=['1=1'];$a=[];if($district!==''){$w[]='i.educational_district=?';$a[]=$district;}if($company){$w[]='i.company_id=?';$a[]=$company;}$where=implode(' AND ',$w);
 $total=(int)(Db::one("SELECT COUNT(*) n FROM school_service_inspections i WHERE $where",$a)['n']??0);$viol=(int)(Db::one("SELECT COUNT(*) n FROM school_service_inspection_violations x JOIN school_service_inspections i ON i.id=x.inspection_id WHERE $where",$a)['n']??0);
 return ['total_inspections'=>$total,'total_violations'=>$viol,'by_district'=>Db::all("SELECT i.educational_district label,COUNT(*) n FROM school_service_inspections i WHERE $where GROUP BY i.educational_district ORDER BY n DESC",$a),'by_company'=>Db::all("SELECT COALESCE(c.name,'نامشخص') label,COUNT(*) n FROM school_service_inspections i LEFT JOIN school_service_companies c ON c.id=i.company_id WHERE $where GROUP BY i.company_id,c.name ORDER BY n DESC LIMIT 20",$a),'by_violation'=>Db::all("SELECT v.title label,COUNT(*) n FROM school_service_inspection_violations x JOIN school_service_violation_types v ON v.id=x.violation_type_id JOIN school_service_inspections i ON i.id=x.inspection_id WHERE $where GROUP BY v.id,v.title ORDER BY n DESC",$a),'by_school'=>Db::all("SELECT COALESCE(s.name,'نامشخص') label,COUNT(*) n FROM school_service_inspections i LEFT JOIN school_service_schools s ON s.id=i.school_id WHERE $where GROUP BY i.school_id,s.name ORDER BY n DESC LIMIT 20",$a)];
});
route('GET','/api/school-service/inspections/{id}',function($p,$b,$u){
 _ssv_need($u,'view');_ssv_tables();$id=(int)$p['id'];$r=Db::one("SELECT i.*,s.name school_name,s.code school_code,c.name company_name,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) inspector_name FROM school_service_inspections i LEFT JOIN school_service_schools s ON s.id=i.school_id LEFT JOIN school_service_companies c ON c.id=i.company_id LEFT JOIN users u ON u.id=i.inspector_user_id WHERE i.id=?",[$id]);if(!$r)Http::error('بازدید پیدا نشد',404);$r['violations']=Db::all("SELECT v.id,v.title FROM school_service_inspection_violations x JOIN school_service_violation_types v ON v.id=x.violation_type_id WHERE x.inspection_id=? ORDER BY v.sort_order,v.id",[$id]);$r['plate']=trim(($r['plate_three']??'').' '.($r['plate_letter']??'').' '.($r['plate_two']??'').' ایران');return $r;
});
route('PUT','/api/school-service/inspections/{id}',function($p,$b,$u){
 _ssv_need($u,'edit');_ssv_tables();$id=(int)$p['id'];if(!Db::one("SELECT id FROM school_service_inspections WHERE id=?",[$id]))Http::error('بازدید پیدا نشد',404);[$a,$l,$c]=_ssv_plate($b);$viol=$b['violation_ids']??[];if(is_string($viol))$viol=json_decode($viol,true)?:[];$viol=array_values(array_unique(array_map('intval',(array)$viol)));[$lat,$lng]=validGeo($b['latitude']??null,$b['longitude']??null);$g=in_array($b['school_gender']??'',['دخترانه','پسرانه','نامشخص'],true)?$b['school_gender']:'نامشخص';$dg=in_array($b['driver_gender']??'',['خانم','آقا','نامشخص'],true)?$b['driver_gender']:'نامشخص';$cert=in_array($b['certificate_status']??'',['معتبر','نامعتبر','ارائه نشد'],true)?$b['certificate_status']:'ارائه نشد';$date=_ssv_en($b['violation_date']??'');if($date!==''&&!preg_match('/^14\d{2}[\/-]\d{1,2}[\/-]\d{1,2}$/',$date))Http::error('تاریخ ثبت تخلف نامعتبر است.',422);$time=trim((string)($b['violation_time']??''));if($time!==''&&!preg_match('/^(?:[01]?\d|2[0-3]):[0-5]\d$/',$time))Http::error('ساعت ثبت تخلف نامعتبر است.',422);_ssv_school_company_validate(!empty($b['school_id'])?(int)$b['school_id']:0,!empty($b['company_id'])?(int)$b['company_id']:0,_ssv_norm($b['educational_district']??''));
 Db::run("UPDATE school_service_inspections SET educational_district=?,company_id=?,school_id=?,school_gender=?,plate_three=?,plate_letter=?,plate_two=?,vehicle_type=?,vehicle_color=?,passenger_count=?,driver_gender=?,certificate_status=?,violation_date=?,violation_time=?,location_text=?,latitude=?,longitude=?,description=? WHERE id=?",[_ssv_norm($b['educational_district']??''),!empty($b['company_id'])?(int)$b['company_id']:null,!empty($b['school_id'])?(int)$b['school_id']:null,$g,$a,$l,$c,_ssv_norm($b['vehicle_type']??''),_ssv_norm($b['vehicle_color']??''),max(0,(int)($b['passenger_count']??0)),$dg,$cert,$date?:null,trim((string)($b['violation_time']??''))?:null,_ssv_norm($b['location_text']??'')?:null,$lat,$lng,trim((string)($b['description']??''))?:null,$id]);Db::run("DELETE FROM school_service_inspection_violations WHERE inspection_id=?",[$id]);foreach($viol as $vid)if(Db::one("SELECT id FROM school_service_violation_types WHERE id=? AND is_active=1",[$vid]))Db::run("INSERT IGNORE INTO school_service_inspection_violations(inspection_id,violation_type_id) VALUES(?,?)",[$id,$vid]);return ['ok'=>true,'id'=>$id];
});
route('DELETE','/api/school-service/inspections/{id}',function($p,$b,$u){_ssv_need($u,'delete');_ssv_tables();$id=(int)$p['id'];if(!Db::one("SELECT id FROM school_service_inspections WHERE id=?",[$id]))Http::error('بازدید پیدا نشد',404);Db::run("DELETE FROM school_service_inspections WHERE id=?",[$id]);return ['ok'=>true];});
route('POST','/api/school-service/import-preview',function($p,$b,$u){
 _ssv_need($u,'import');_ssv_tables();$sheets=_ssv_xlsx_rows($_FILES['file']??null);$records=[];$sheetCounts=[];foreach($sheets as $name=>$rows){$rs=_ssv_sheet_records($rows);$sheetCounts[$name]=count($rs);$records=array_merge($records,$rs);}$companies=[];$schools=[];$maps=[];$errors=[];$duplicateRows=0;$newCompanies=[];$existingCompanies=[];$newSchools=[];$existingSchools=[];$newMappings=[];$existingMappings=[];foreach($records as $i=>$r){$cn=_ssv_norm($r['company']);$sn=_ssv_norm($r['school']);if($cn){$companies[$cn]=1;$co=Db::one("SELECT id FROM school_service_companies WHERE name=?",[$cn]);if($co)$existingCompanies[$cn]=1;else$newCompanies[$cn]=1;}if($sn){$schools[$sn]=1;$school=null;if(_ssv_norm($r['code'])!=='')$school=Db::one("SELECT id FROM school_service_schools WHERE code=?",[_ssv_norm($r['code'])]);if(!$school)$school=Db::one("SELECT id FROM school_service_schools WHERE name=? AND educational_district=?",[$sn,_ssv_norm($r['district'])]);if($school)$existingSchools[$sn]=1;else$newSchools[$sn]=1;}if($cn&&$sn){$key=$sn.'|'.$cn;if(isset($maps[$key])){$duplicateRows++;}else{$maps[$key]=1;$co=$cn?Db::one("SELECT id FROM school_service_companies WHERE name=?",[$cn]):null;$sch=null;if(_ssv_norm($r['code'])!=='')$sch=Db::one("SELECT id FROM school_service_schools WHERE code=?",[_ssv_norm($r['code'])]);if(!$sch)$sch=Db::one("SELECT id FROM school_service_schools WHERE name=? AND educational_district=?",[$sn,_ssv_norm($r['district'])]);if($co&&$sch){$existingMap=Db::one("SELECT company_id FROM school_service_school_companies WHERE school_id=?",[(int)$sch['id']]);if($existingMap&&(int)$existingMap['company_id']===(int)$co['id'])$existingMappings[$key]=1;else$newMappings[$key]=1;}else$newMappings[$key]=1;}}else $errors[]='ردیف '.($i+2).' نام مدرسه یا شرکت ندارد';if(count($errors)>=100)break;}return ['ok'=>true,'rows'=>count($records),'companies_count'=>count($companies),'schools_count'=>count($schools),'mappings_count'=>count($maps),'new_companies'=>count($newCompanies),'existing_companies'=>count($existingCompanies),'new_schools'=>count($newSchools),'existing_schools'=>count($existingSchools),'new_mappings'=>count($newMappings),'existing_mappings'=>count($existingMappings),'duplicate_rows'=>$duplicateRows,'errors'=>$errors,'sheets'=>$sheetCounts];
},false,99);
route('GET','/api/school-service/export-filtered',function($p,$b,$u){
 _ssv_need($u,'report');_ssv_tables();$q=_ssv_norm($_GET['search']??'');$district=_ssv_norm($_GET['district']??'');$company=(int)($_GET['company_id']??0);$w=['1=1'];$a=[];if($q!==''){$w[]='(s.name LIKE ? OR c.name LIKE ? OR i.location_text LIKE ? OR CONCAT(i.plate_three,i.plate_letter,i.plate_two) LIKE ?)';array_push($a,'%'.$q.'%','%'.$q.'%','%'.$q.'%','%'.$q.'%');}if($district!==''){$w[]='i.educational_district=?';$a[]=$district;}if($company){$w[]='i.company_id=?';$a[]=$company;}
 $rows=Db::all("SELECT i.*,s.name school_name,c.name company_name,TRIM(CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,''))) inspector_name FROM school_service_inspections i LEFT JOIN school_service_schools s ON s.id=i.school_id LEFT JOIN school_service_companies c ON c.id=i.company_id LEFT JOIN users u ON u.id=i.inspector_user_id WHERE ".implode(' AND ',$w)." ORDER BY i.id DESC LIMIT 20000",$a);$head=['ردیف','ناحیه','شرکت','نوع مدرسه','مدرسه','پلاک','نوع خودرو','رنگ خودرو','تخلفات','تعداد سرنشین بدون راننده','نوع راننده','وضعیت گواهی صلاحیت','تاریخ','ساعت','محل ثبت تخلف','توضیحات','بازرس'];$out=[];foreach($rows as $i=>$r){$vs=Db::all("SELECT v.title FROM school_service_inspection_violations x JOIN school_service_violation_types v ON v.id=x.violation_type_id WHERE x.inspection_id=?",[(int)$r['id']]);$out[]=[$i+1,$r['educational_district'],$r['company_name'],$r['school_gender'],$r['school_name'],trim(($r['plate_three']??'').' '.($r['plate_letter']??'').' '.($r['plate_two']??'').' ایران'),$r['vehicle_type'],$r['vehicle_color'],implode('، ',array_column($vs,'title')),$r['passenger_count'],$r['driver_gender'],$r['certificate_status'],$r['violation_date'],$r['violation_time'],$r['location_text'],$r['description'],$r['inspector_name']];}$xw=new XlsxWriter($head);foreach($out as $row)$xw->addRow($row);$xw->output('سرویس_مدارس_بازدیدهای_فیلترشده.xlsx','بازدیدها');
},false,99);
