import React,{createContext,useContext,useEffect,useMemo,useRef,useState}from'react';
import{Alert,AppState}from'react-native';import AsyncStorage from'@react-native-async-storage/async-storage';import * as SecureStore from'expo-secure-store';import * as FileSystem from'expo-file-system/legacy';import{createAudioPlayer,useAudioPlayer,useAudioRecorder,setAudioModeAsync}from'expo-audio';import{request,uploadFile}from'../api';import{apiBase}from'../config';import{useAuth}from'../auth';
const RadioContext=createContext(null);const KEY_ENABLED='khatyar.radio.enabled';const KEY_CHANNEL='khatyar.radio.channel';const MAX_TALK_MS=25000;
const RECORDING_OPTIONS={extension:'.m4a',sampleRate:16000,numberOfChannels:1,bitRate:24000,android:{extension:'.m4a',outputFormat:'mpeg4',audioEncoder:'aac',sampleRate:16000,numberOfChannels:1,bitRate:24000},ios:{extension:'.m4a',outputFormat:'mpeg4aac',audioQuality:0,linearPCMBitDepth:16,linearPCMIsBigEndian:false,linearPCMIsFloat:false,sampleRate:16000,numberOfChannels:1,bitRate:24000},web:{mimeType:'audio/webm',bitsPerSecond:24000}};
export function RadioProvider({children}){const{user}=useAuth();const[enabled,setEnabledState]=useState(true),[channels,setChannels]=useState([]),[channelId,setChannelIdState]=useState(0),[busy,setBusy]=useState(false),[speaker,setSpeaker]=useState(null),[recording,setRecording]=useState(false),[status,setStatus]=useState(''),[lastMessage,setLastMessage]=useState(null);const enabledRef=useRef(true),channelRef=useRef(0),lastIdRef=useRef(0),pollingRef=useRef(false),mountedRef=useRef(true),recordingRef=useRef(false);const recorder=useAudioRecorder(RECORDING_OPTIONS);const startEffect=useAudioPlayer(require('../../assets/sounds/message_new.mp3'));const endEffect=useAudioPlayer(require('../../assets/sounds/notification_new.mp3'));useEffect(()=>{enabledRef.current=enabled},[enabled]);useEffect(()=>{channelRef.current=channelId},[channelId]);useEffect(()=>()=>{mountedRef.current=false},[]);
const load=async()=>{if(!user?.id)return;try{const savedE=await AsyncStorage.getItem(KEY_ENABLED);const savedC=await AsyncStorage.getItem(KEY_CHANNEL);const r=await request('/radio-api.php?op=channels',{noStore:true});if(!mountedRef.current)return;setChannels(r.channels||[]);const cid=Number(savedC||r.channel_id||r.channels?.[0]?.id||0);setChannelIdState(cid);channelRef.current=cid;const en=savedE===null?(r.enabled!==false):savedE==='1';setEnabledState(en);enabledRef.current=en;}catch(e){}};
useEffect(()=>{if(!user?.id){setChannels([]);setChannelIdState(0);setRecording(false);return}load();return()=>{try{recorder.stop()}catch(e){}}},[user?.id]);
const setEnabled=async v=>{const next=!!v;setEnabledState(next);enabledRef.current=next;await AsyncStorage.setItem(KEY_ENABLED,next?'1':'0');try{await request('/radio-api.php?op=settings',{method:'POST',body:{enabled:next,channel_id:channelRef.current}})}catch(e){}};
const setChannel=async id=>{const cid=Number(id);setChannelIdState(cid);channelRef.current=cid;lastIdRef.current=0;await AsyncStorage.setItem(KEY_CHANNEL,String(cid));try{await request('/radio-api.php?op=settings',{method:'POST',body:{enabled:enabledRef.current,channel_id:cid}})}catch(e){}};
const playFile=async message=>{try{const token=await SecureStore.getItemAsync('access');const url=message.audio_url?.startsWith('http')?message.audio_url:(apiBase().replace(/\/api$/,'')+message.audio_url);const target=(FileSystem.cacheDirectory||FileSystem.documentDirectory)+`radio-${message.id}.m4a`;await FileSystem.downloadAsync(url,target,{headers:token?{Authorization:`Bearer ${token}`}:{}});startEffect.seekTo(0);startEffect.play();await new Promise(r=>setTimeout(r,180));const p=createAudioPlayer(target);p.play();const duration=Math.max(800,Number(message.duration_ms||0)+400);setTimeout(()=>{try{p.release()}catch(e){}try{endEffect.seekTo(0);endEffect.play()}catch(e){}},duration);if(mountedRef.current)setLastMessage(message)}catch(e){}};
const poll=async()=>{if(!user?.id||!enabledRef.current||pollingRef.current||!channelRef.current)return;pollingRef.current=true;try{const r=await request(`/radio-api.php?op=poll&channel_id=${channelRef.current}&after=${lastIdRef.current}`,{noStore:true});if(!mountedRef.current)return;setBusy(!!r.busy);setSpeaker(r.speaker_id?{id:Number(r.speaker_id),name:r.speaker_name||'کاربر در حال صحبت'}:null);for(const m of(r.messages||[])){lastIdRef.current=Math.max(lastIdRef.current,Number(m.id));if(Number(m.sender_id)!==Number(user.id))await playFile(m)}}catch(e){}finally{pollingRef.current=false}};
useEffect(()=>{if(!user?.id||!enabled)return;poll();const t=setInterval(poll,1800);const sub=AppState.addEventListener('change',s=>{if(s==='active')poll()});return()=>{clearInterval(t);try{sub.remove()}catch(e){}}},[user?.id,enabled,channelId]);
const startTalk=async()=>{if(recordingRef.current)return;try{if(!channelRef.current){Alert.alert('بی‌سیم','ابتدا یک کانال انتخاب کنید.');return}const r=await request('/radio-api.php?op=take',{method:'POST',body:{channel_id:channelRef.current}});if(!r.ok)throw new Error(r.error);await setAudioModeAsync({playsInSilentMode:true,allowsRecording:true,interruptionMode:'doNotMix'});await recorder.prepareToRecordAsync();recorder.record();recordingRef.current=true;setRecording(true);setStatus('در حال صحبت… حداکثر ۲۵ ثانیه');startEffect.seekTo(0);startEffect.play();setTimeout(()=>{if(recordingRef.current)stopTalk()},MAX_TALK_MS)}catch(e){setStatus('');Alert.alert('بی‌سیم',String(e.message||'').includes('استفاده')?'کانال در حال استفاده است.':(e.message||'امکان صحبت وجود ندارد.'))}};
const stopTalk=async()=>{if(!recordingRef.current)return;recordingRef.current=false;setRecording(false);setStatus('در حال ارسال…');try{await recorder.stop();const uri=recorder.uri;if(!uri)throw new Error('فایل صوتی ساخته نشد.');const duration=Math.min(MAX_TALK_MS,Math.round((recorder.currentTime||0)*1000));await uploadFile('/radio-api.php?op=send',{channel_id:channelRef.current,duration_ms:duration},'audio',uri,`radio-${Date.now()}.m4a`,'audio/mp4');endEffect.seekTo(0);endEffect.play();setStatus('');poll()}catch(e){try{await request('/radio-api.php?op=release',{method:'POST',body:{channel_id:channelRef.current}})}catch(_){ }setStatus('');Alert.alert('بی‌سیم',e.message||'ارسال پیام صوتی ناموفق بود.')}};
const value=useMemo(()=>({enabled,channels,channelId,busy,speaker,recording,status,lastMessage,setEnabled,setChannel,startTalk,stopTalk}),[enabled,channels,channelId,busy,speaker,recording,status,lastMessage]);return <RadioContext.Provider value={value}>{children}</RadioContext.Provider>}
export const useRadio=()=>useContext(RadioContext);
