import React,{createContext,useContext,useEffect,useMemo,useRef,useState}from'react';import{Alert,AppState,DeviceEventEmitter,NativeModules}from'react-native';import AsyncStorage from'@react-native-async-storage/async-storage';import * as SecureStore from'expo-secure-store';import * as FileSystem from'expo-file-system/legacy';import{createAudioPlayer,useAudioPlayer,useAudioRecorder,setAudioModeAsync,getRecordingPermissionsAsync,requestRecordingPermissionsAsync}from'expo-audio';import * as Notifications from'expo-notifications';import{request}from'../api';import{apiBase}from'../config';import{useAuth}from'../auth';
const RadioContext=createContext(null),KEY_ENABLED='khatyar.radio.enabled',KEY_CHANNEL='khatyar.radio.channel',DEFAULT_TALK_MS=25000,PTT_RELEASE_GRACE_MS=500,MIN_TALK_MS=1500,NATIVE=NativeModules?.KhatyarRadio;
const RECORDING_OPTIONS={extension:'.m4a',sampleRate:8000,numberOfChannels:1,bitRate:12000,android:{extension:'.m4a',outputFormat:'mpeg4',audioEncoder:'aac',sampleRate:8000,numberOfChannels:1,bitRate:12000},ios:{extension:'.m4a',outputFormat:'mpeg4aac',audioQuality:0,linearPCMBitDepth:16,linearPCMIsBigEndian:false,linearPCMIsFloat:false,sampleRate:8000,bitRate:12000},web:{mimeType:'audio/webm',bitsPerSecond:12000}};
const extractChannels=r=>{const a=Array.isArray(r)?r:(Array.isArray(r?.channels)?r.channels:Array.isArray(r?.data?.channels)?r.data.channels:Array.isArray(r?.items)?r.items:Array.isArray(r?.data?.items)?r.data.items:[]);return a.filter(x=>x&&x.id!=null).map(x=>({...x,id:Number(x.id)}));};
export function RadioProvider({children}){const{user}=useAuth();const[enabled,setEnabledState]=useState(true),[channels,setChannels]=useState([]),[channelId,setChannelIdState]=useState(0),[busy,setBusy]=useState(false),[speaker,setSpeaker]=useState(null),[recording,setRecording]=useState(false),[status,setStatus]=useState(''),[lastMessage,setLastMessage]=useState(null),[recentMessages,setRecentMessages]=useState([]),[playingMessageId,setPlayingMessageId]=useState(0),[maxTalkMs,setMaxTalkMs]=useState(DEFAULT_TALK_MS),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState(''),[listenAll,setListenAllState]=useState(false),[listenAllAllowed,setListenAllAllowed]=useState(false);const enabledRef=useRef(true),channelRef=useRef(0),lastIdRef=useRef(0),pollingRef=useRef(false),recentLoadingRef=useRef(false),recentRequestIdRef=useRef(0),mountedRef=useRef(true),recordingRef=useRef(false),limitRef=useRef(DEFAULT_TALK_MS),talkStartRef=useRef(0),autoStoppedRef=useRef(false),pttReleaseTimerRef=useRef(null),pttDownRef=useRef(false),talkGenerationRef=useRef(0),pttInputGenerationRef=useRef(0),listenAllRef=useRef(false),listenAllLastIdRef=useRef(0),pollAllRef=useRef(false);const recorder=useAudioRecorder(RECORDING_OPTIONS);
const botPlayer=useAudioPlayer(require('../../assets/sounds/radio_bot.wav')),rogerPlayer=useAudioPlayer(require('../../assets/sounds/radio_roger_beep.wav')),eotPlayer=useAudioPlayer(require('../../assets/sounds/radio_eot.wav')),squelchPlayer=useAudioPlayer(require('../../assets/sounds/radio_squelch.wav')),courtesyPlayer=useAudioPlayer(require('../../assets/sounds/radio_courtesy_beep.wav'));const playSfx=p=>{try{p.seekTo(0);p.play()}catch(e){}};const playSquelch=()=>{playSfx(squelchPlayer)};useEffect(()=>{enabledRef.current=enabled},[enabled]);useEffect(()=>{channelRef.current=channelId},[channelId]);useEffect(()=>()=>{mountedRef.current=false;if(pttReleaseTimerRef.current)clearTimeout(pttReleaseTimerRef.current)},[]);
const syncNative=async(overrides={})=>{if(!NATIVE||!user?.id)return;try{const token=await SecureStore.getItemAsync('access');const cid=Number(overrides.channelId??channelRef.current);const ch=channels.find(x=>Number(x.id)===cid);const lastMessageId=overrides.lastMessageId??Number(ch?.last_message_id??lastIdRef.current??0);await NATIVE.configure(token||'',apiBase(),Number(user.id),cid,overrides.enabled??enabledRef.current,lastMessageId)}catch(e){}};
const sortRecentMessages=list=>{const map=new Map();for(const m of(Array.isArray(list)?list:[])){if(m&&m.id!=null)map.set(String(m.id),m)}return Array.from(map.values()).sort((a,b)=>Number(b?.id||0)-Number(a?.id||0)).slice(0,3)};
const loadRecentMessages=async()=>{if(!user?.id||!channelRef.current||recentLoadingRef.current)return;const requestId=++recentRequestIdRef.current;const requestedChannel=Number(channelRef.current);recentLoadingRef.current=true;try{const r=await request(`/radio-api-v2.php?op=poll&channel_id=${requestedChannel}&after=${Math.max(0,Number(lastIdRef.current||0)-20)}`,{noStore:true});if(!mountedRef.current||requestId!==recentRequestIdRef.current||requestedChannel!==Number(channelRef.current))return;const list=Array.isArray(r?.messages)?r.messages:[];if(!list.length)return;const latest=sortRecentMessages(list);lastIdRef.current=Math.max(lastIdRef.current,...latest.map(m=>Number(m?.id||0)));setRecentMessages(prev=>sortRecentMessages([...(Array.isArray(prev)?prev:[]),...latest]))}catch(e){}finally{if(requestId===recentRequestIdRef.current)recentLoadingRef.current=false}};
const apply=async(r,savedC,savedE)=>{const list=extractChannels(r);setChannels(list);const cid=Number(savedC||r?.channel_id||r?.data?.channel_id||list?.[0]?.id||0),chosen=list.find(x=>Number(x.id)===cid)||list[0],actual=Number(chosen?.id||0);recentRequestIdRef.current+=1;setRecentMessages([]);setChannelIdState(actual);channelRef.current=actual;lastIdRef.current=Number(chosen?.last_message_id||0);const limit=Number(chosen?.max_talk_ms||DEFAULT_TALK_MS);setMaxTalkMs(limit);limitRef.current=limit;const en=savedE===null?((r?.enabled??r?.data?.enabled)!==false):savedE==='1';setEnabledState(en);enabledRef.current=en;const allowed=!!(r?.listen_all_allowed);setListenAllAllowed(allowed);const la=allowed&&!!(r?.listen_all);setListenAllState(la);listenAllRef.current=la;if(la)listenAllLastIdRef.current=Math.max(0,...list.map(x=>Number(x.last_message_id||0)));return list};
const load=async()=>{if(!user?.id)return;setLoading(true);setLoadError('');try{const savedE=await AsyncStorage.getItem(KEY_ENABLED),savedC=await AsyncStorage.getItem(KEY_CHANNEL);const r=await request('/radio-api-v2.php?op=channels',{noStore:true});if(!mountedRef.current)return;const list=await apply(r,savedC,savedE);if(!list.length)setLoadError('هیچ کانال مجازی برای حساب شما دریافت نشد.');else if(mountedRef.current)setTimeout(()=>loadRecentMessages(),0);}catch(e){if(mountedRef.current)setLoadError(e.message||'دریافت کانال‌های بی‌سیم ناموفق بود.')}finally{if(mountedRef.current)setLoading(false)}};
useEffect(()=>{if(!user?.id){setChannels([]);setChannelIdState(0);setRecording(false);setRecentMessages([]);setLoadError('');if(NATIVE)NATIVE.stop().catch(()=>{});return}load();return()=>{try{recorder.stop()}catch(e){}}},[user?.id]);
useEffect(()=>{if(!user?.id||!NATIVE)return;syncNative();},[user?.id,enabled,channelId]);
const setEnabled=async v=>{const next=!!v;setEnabledState(next);enabledRef.current=next;await AsyncStorage.setItem(KEY_ENABLED,next?'1':'0');try{await request('/radio-api-v2.php?op=settings',{method:'POST',body:{enabled:next,channel_id:channelRef.current}})}catch(e){}if(NATIVE)syncNative({enabled:next})};
const setListenAll=async v=>{if(!listenAllAllowed)return;const next=!!v;setListenAllState(next);listenAllRef.current=next;if(next)listenAllLastIdRef.current=Math.max(lastIdRef.current,...channels.map(x=>Number(x.last_message_id||0)));try{await request('/radio-api-v2.php?op=settings',{method:'POST',body:{enabled:enabledRef.current,channel_id:channelRef.current,listen_all:next}})}catch(e){}};
const setChannel=async id=>{const cid=Number(id),c=channels.find(x=>Number(x.id)===cid);if(!c)return;setChannelIdState(cid);channelRef.current=cid;recentRequestIdRef.current+=1;setRecentMessages([]);
  /* خطیار: last_message_id داخل آرایهٔ channels ممکن است قدیمی باشد (مثلاً از لحظهٔ باز شدن اپ، پیش از این‌که
     کاربر مدتی روی کانال دیگری بماند). اگر همان مقدار کهنه را مبنای شروع شنود کانال جدید بگیریم، هر پیامی که
     در این فاصله در کانال جدید ارسال شده (ولی قدیمی است، نه واقعاً زنده) به‌عنوان «پیام تازه» شناسایی و پخش می‌شود —
     دقیقاً همان پخش مجددِ پیام‌های قبلیِ کانال هنگام تعویض. پس همین لحظه یک بار مقدار واقعی و به‌روز را از سرور می‌گیریم. */
  let freshLastId=Number(c.last_message_id||0);
  try{const r=await request('/radio-api-v2.php?op=channels',{noStore:true});const list=extractChannels(r);const fresh=list.find(x=>Number(x.id)===cid);if(fresh)freshLastId=Number(fresh.last_message_id||freshLastId);}catch(e){}
  if(cid!==Number(channelRef.current))return; // کاربر تا قبل از رسیدن پاسخ، دوباره کانال را عوض کرده است
  lastIdRef.current=freshLastId;const limit=Number(c.max_talk_ms||DEFAULT_TALK_MS);setMaxTalkMs(limit);limitRef.current=limit;await AsyncStorage.setItem(KEY_CHANNEL,String(cid));try{await request('/radio-api-v2.php?op=settings',{method:'POST',body:{enabled:enabledRef.current,channel_id:cid}})}catch(e){}
  if(NATIVE)syncNative({channelId:cid,lastMessageId:freshLastId});loadRecentMessages()};
const playFile=message=>new Promise(resolve=>{(async()=>{const target=(FileSystem.cacheDirectory||FileSystem.documentDirectory)+`radio-${message.id}.m4a`;try{const token=await SecureStore.getItemAsync('access'),url=message.audio_url?.startsWith('http')?message.audio_url:(apiBase().replace(/\/api$/,'')+message.audio_url);await FileSystem.downloadAsync(url,target,{headers:token?{Authorization:`Bearer ${token}`}:{}});playSquelch();await new Promise(r=>setTimeout(r,220));const p=createAudioPlayer(target);p.play();if(mountedRef.current){setLastMessage(message);setPlayingMessageId(Number(message.id)||0)}setTimeout(()=>{try{p.release()}catch(e){}try{FileSystem.deleteAsync(target,{idempotent:true})}catch(e){}if(mountedRef.current)setPlayingMessageId(0);playSfx(courtesyPlayer);resolve()},Math.max(600,Number(message.duration_ms||0)+350))}catch(e){try{FileSystem.deleteAsync(target,{idempotent:true})}catch(_){}resolve()}})()});
const pollFailRef=useRef(0);
const poll=async()=>{if(!user?.id||!enabledRef.current||pollingRef.current||!channelRef.current)return;pollingRef.current=true;const requestedChannel=Number(channelRef.current);try{const r=await request(`/radio-api-v2.php?op=poll&channel_id=${requestedChannel}&after=${lastIdRef.current}`,{noStore:true});if(!mountedRef.current||requestedChannel!==Number(channelRef.current))return;pollFailRef.current=0;setLoadError('');setBusy(!!r.busy);setSpeaker(r.speaker_id?{id:Number(r.speaker_id),name:r.speaker_name||'کاربر در حال صحبت',role:r.speaker_role||''}:null);const newMessages=Array.isArray(r?.messages)?r.messages:[];if(newMessages.length){for(const m of newMessages){/* خطیار: اگر کاربر حین پخشِ صف پیام‌های این کانال، کانال را عوض کند، این حلقه نباید ادامه بدهد
   وگرنه پیام‌های کانال قبلی پشت سر هم برای کانال جدید پخش می‌شوند و lastIdRef هم با شناسهٔ پیام‌های کانال قبلی آلوده می‌شود. */if(!mountedRef.current||requestedChannel!==Number(channelRef.current))break;lastIdRef.current=Math.max(lastIdRef.current,Number(m.id||0));if(AppState.currentState==='active'&&Number(m.sender_id)!==Number(user.id))await playFile(m)}if(mountedRef.current&&requestedChannel===Number(channelRef.current))setRecentMessages(prev=>sortRecentMessages([...(Array.isArray(prev)?prev:[]),...newMessages]))}}catch(e){pollFailRef.current+=1;if(mountedRef.current&&pollFailRef.current>=3)setLoadError(e?.message||'دریافت پیام‌های بی‌سیم چند بار پیاپی ناموفق بود؛ اتصال اینترنت را بررسی کنید.')}finally{pollingRef.current=false}};
const pollAll=async()=>{if(!user?.id||!enabledRef.current||!listenAllRef.current||pollAllRef.current)return;pollAllRef.current=true;try{const r=await request(`/radio-api-v2.php?op=poll-all&after=${listenAllLastIdRef.current}`,{noStore:true});if(!mountedRef.current||!listenAllRef.current)return;const msgs=Array.isArray(r?.messages)?r.messages:[];for(const m of msgs){if(!mountedRef.current||!listenAllRef.current)break;listenAllLastIdRef.current=Math.max(listenAllLastIdRef.current,Number(m.id||0));if(AppState.currentState==='active'&&Number(m.sender_id)!==Number(user.id))await playFile(m)}}catch(e){}finally{pollAllRef.current=false}};
const presence=async()=>{if(!user?.id||!enabledRef.current||!channelRef.current)return;try{await request('/radio-api-v2.php?op=presence',{method:'POST',body:{channel_id:channelRef.current}})}catch(e){}};
const resyncToLive=async()=>{if(!channelRef.current)return;try{const r=await request('/radio-api-v2.php?op=channels',{noStore:true});const list=extractChannels(r),c=list.find(x=>Number(x.id)===Number(channelRef.current));if(c)lastIdRef.current=Number(c.last_message_id||lastIdRef.current)}catch(e){}};
useEffect(()=>{if(!user?.id||!enabled||!channelRef.current)return;const tick=()=>{if(listenAllRef.current)pollAll();else poll();presence()};tick();loadRecentMessages();const t=setInterval(tick,1800),sub=AppState.addEventListener('change',s=>{if(s==='active'){resyncToLive().then(tick)}});return()=>{clearInterval(t);try{sub.remove()}catch(e){}}},[user?.id,enabled,channelId]);
/* خطیار: سرویس نیتیو بی‌سیم برای این‌که بداند «جاوااسکریپت الان دارد پیام‌ها را پخش می‌کند یا نه» به یک ضربان قلب دقیق از همین‌جا نیاز دارد
   (به‌جای حدس‌زدن از روی اهمیت پردازه که همیشه غلط از آب درمی‌آمد، چون خودِ سرویس هم روی همین پردازه اجرا می‌شود).
   با هر تغییر AppState فوراً، و تا وقتی اپ واقعاً «باز و در پیش‌زمینه» است هر ۲ ثانیه یک‌بار، این وضعیت را برای نیتیو می‌فرستیم. */
useEffect(()=>{if(!NATIVE)return;const send=v=>{try{NATIVE.setForegroundState(v)}catch(e){}};send(AppState.currentState==='active');const sub=AppState.addEventListener('change',s=>send(s==='active'));const hb=setInterval(()=>{if(AppState.currentState==='active')send(true)},2000);return()=>{try{sub.remove()}catch(e){}clearInterval(hb);send(false)}},[]);
const releaseTake=async()=>{try{await request('/radio-api-v2.php?op=release',{method:'POST',body:{channel_id:channelRef.current}})}catch(_){} };
const startTalk=async()=>{if(pttReleaseTimerRef.current){clearTimeout(pttReleaseTimerRef.current);pttReleaseTimerRef.current=null}const inputGeneration=++pttInputGenerationRef.current;pttDownRef.current=true;if(recordingRef.current)return;try{if(!channelRef.current){pttDownRef.current=false;Alert.alert('بی‌سیم',channels.length?'ابتدا یک کانال انتخاب کنید.':'هیچ کانال مجازی برای شما در دسترس نیست.');return}let mic=await getRecordingPermissionsAsync().catch(()=>({granted:false}));if(!mic?.granted)mic=await requestRecordingPermissionsAsync().catch(()=>({granted:false}));if(!mic?.granted){pttDownRef.current=false;return}if(!pttDownRef.current||inputGeneration!==pttInputGenerationRef.current)return;const r=await request('/radio-api-v2.php?op=take',{method:'POST',body:{channel_id:channelRef.current}});if(!r.ok)throw new Error(r.error);if(!pttDownRef.current||inputGeneration!==pttInputGenerationRef.current){await releaseTake();return}const limit=Math.max(5000,Number(r.lease_ms||limitRef.current||DEFAULT_TALK_MS));limitRef.current=limit;setMaxTalkMs(limit);await setAudioModeAsync({playsInSilentMode:true,allowsRecording:true,interruptionMode:'doNotMix'});if(!pttDownRef.current||inputGeneration!==pttInputGenerationRef.current){await releaseTake();return}await recorder.prepareToRecordAsync();if(!pttDownRef.current||inputGeneration!==pttInputGenerationRef.current){await releaseTake();return}recorder.record();talkStartRef.current=Date.now();autoStoppedRef.current=false;recordingRef.current=true;talkGenerationRef.current+=1;playSfx(botPlayer);setRecording(true);setStatus(`در حال صحبت… حداکثر ${Math.round(limit/1000)} ثانیه`);setTimeout(()=>{if(recordingRef.current){autoStoppedRef.current=true;stopTalk({immediate:true})}},limit)}catch(e){pttDownRef.current=false;setStatus('');try{await releaseTake()}catch(_){}Alert.alert('بی‌سیم',String(e.message||'').includes('استفاده')?'کانال در حال استفاده است.':(e.message||'امکان صحبت وجود ندارد.'))}};
const sendAudio=async(uri,duration)=>{if(Number(duration)<MIN_TALK_MS)return null;const token=await SecureStore.getItemAsync('access');const res=await FileSystem.uploadAsync(`${apiBase()}/radio-api-v2.php?op=send`,uri,{httpMethod:'POST',uploadType:FileSystem.FileSystemUploadType.MULTIPART,fieldName:'audio',mimeType:'audio/mp4',parameters:{channel_id:String(channelRef.current),duration_ms:String(Math.min(duration,limitRef.current))},headers:token?{Authorization:`Bearer ${token}`}:{}});let data={};try{data=JSON.parse(res.body)}catch(e){}if(res.status<200||res.status>=300||!data.ok)throw new Error(data.error||`ارسال پیام صوتی ناموفق بود (${res.status})`);return data};
const finishTalk=async generation=>{if(!recordingRef.current||generation!==talkGenerationRef.current)return;recordingRef.current=false;pttDownRef.current=false;setRecording(false);setStatus('در حال تکمیل ضبط و ارسال…');try{await recorder.stop();const uri=recorder.uri;if(!uri)throw new Error('فایل صوتی ساخته نشد.');const duration=Math.max(300,Math.min(limitRef.current,Date.now()-(talkStartRef.current||Date.now())));if(duration<MIN_TALK_MS){try{await FileSystem.deleteAsync(uri,{idempotent:true})}catch(_){}await releaseTake();setStatus('');return}await sendAudio(uri,duration);try{await FileSystem.deleteAsync(uri,{idempotent:true})}catch(_){}playSfx(autoStoppedRef.current?eotPlayer:rogerPlayer);setStatus('');loadRecentMessages();poll()}catch(e){await releaseTake();setStatus('');Alert.alert('بی‌سیم',e.message||'ارسال پیام صوتی ناموفق بود.')}};
const stopTalk=async({immediate=false}={})=>{++pttInputGenerationRef.current;if(!recordingRef.current){pttDownRef.current=false;return}if(immediate){if(pttReleaseTimerRef.current){clearTimeout(pttReleaseTimerRef.current);pttReleaseTimerRef.current=null}return finishTalk(talkGenerationRef.current)}pttDownRef.current=false;if(pttReleaseTimerRef.current)clearTimeout(pttReleaseTimerRef.current);const generation=talkGenerationRef.current;setStatus('در حال تکمیل ضبط…');pttReleaseTimerRef.current=setTimeout(()=>{pttReleaseTimerRef.current=null;if(!pttDownRef.current)finishTalk(generation)},PTT_RELEASE_GRACE_MS)};
useEffect(()=>{if(!NATIVE)return;const sub=DeviceEventEmitter.addListener('khatyarRadioPTT',event=>{if(event?.down)startTalk();else stopTalk()});return()=>{try{sub.remove()}catch(_){}}},[NATIVE,startTalk,stopTalk]);
const value=useMemo(()=>({enabled,channels,channelId,busy,speaker,recording,status,lastMessage,recentMessages,playingMessageId,maxTalkMs,loading,loadError,listenAll,listenAllAllowed,setListenAll,setEnabled,setChannel,startTalk,stopTalk,reloadChannels:load,playRecentMessage:async message=>{if(message?.audio_url)await playFile(message)},backgroundRadio:!!NATIVE}),[enabled,channels,channelId,busy,speaker,recording,status,lastMessage,recentMessages,playingMessageId,maxTalkMs,loading,loadError,listenAll,listenAllAllowed]);return <RadioContext.Provider value={value}>{children}</RadioContext.Provider>};export const useRadio=()=>useContext(RadioContext);