import React from 'react';
import { I18nManager, View, TouchableOpacity, Text, AppState, KeyboardAvoidingView, Platform } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { NavigationContainer, createNavigationContainerRef, DrawerActions } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createDrawerNavigator } from '@react-navigation/drawer';
import * as Font from 'expo-font';
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { AuthProvider, useAuth } from './src/auth';
import { RadioProvider } from './src/radio/RadioContext';
import StartupPermissions from './src/StartupPermissions';
import FirstSetupScreen from './src/FirstSetupScreen';
import PeriodicRenewScreen from './src/PeriodicRenewScreen';
import { loadApiBase } from './src/config';
import { C, FONT } from './src/theme';
import OfflineBanner from './src/OfflineBanner';
import { FontScaleProvider } from './src/fontscale';
import { ThemeProvider } from './src/themeContext';
import ErrorBoundary from './src/ErrorBoundary';
import GpsGuard from './src/GpsGuard';
import MaintenanceGuard from './src/MaintenanceGuard';
import SecurityGuard from './src/SecurityGuard';
import BatteryOptimizationGate from './src/BatteryOptimization';
import ShiftTrackingGate from './src/ShiftTrackingGate';
import PermissionGuard from './src/PermissionGuard';
import ActivityIndicator from './src/components/PulseLoadingIndicator';
import StartupGate from './src/StartupGate';
import PresenceGate from './src/PresenceGate';
import CovertSelfie from './src/CovertSelfie';
import CovertScreenshot from './src/covertScreenshot';
import UpdateScreen from './src/screens/UpdateScreen';
import { checkVersion } from './src/update';
import { request } from './src/api';
import LoginScreen from './src/screens/LoginScreen';
import DashboardScreen from './src/screens/DashboardScreen';
import CustomFieldsScreen from './src/screens/CustomFieldsScreen';
import OutageScreen from './src/screens/OutageScreen';
import SearchScreen from './src/screens/SearchScreen';
import DriverScreen from './src/screens/DriverScreen';
import DebtScreen from './src/screens/DebtScreen';
import ChecklistScreen from './src/screens/ChecklistScreen';
import NoticeScreen from './src/screens/NoticeScreen';
import ReportsScreen from './src/screens/ReportsScreen';
import SmsScreen from './src/screens/SmsScreen';
import BotMessageScreen from './src/screens/BotMessageScreen';
import RequestsScreen from './src/screens/RequestsScreen';
import { RequestInboxScreen, WorkSummaryScreen, SalarySlipsScreen } from './src/screens/RequestScreens';
import CheckInScreen from './src/screens/CheckInScreen';
import FormsScreen from './src/screens/FormsScreen';
import CulturalScreen from './src/screens/CulturalScreen';
import WelfareScreen from './src/screens/WelfareScreen';
import TempDriversScreen from './src/screens/TempDriversScreen';
import NotificationsScreen from './src/screens/NotificationsScreen';
import FieldAlertsScreen from './src/screens/FieldAlertsScreen';
import OfficialPresenceScreen from './src/screens/OfficialPresenceScreen';
import MessagesScreen from './src/screens/MessagesScreen';
import { AttendanceScreen, PastNoticesScreen, PastChecklistsScreen, DriverSmsScreen, MySmsScreen, VehicleScreen } from './src/screens/ListScreens';
import { ActivityReportScreen, ExpInsuranceScreen, ExpTaxiScreen, ExpOplicScreen, TeamReportScreen } from './src/screens/ReportListsScreens';
import { InboxReportsScreen, ReportDetailScreen } from './src/screens/InboxScreen';
import PresentListScreen from './src/screens/ListScreens';
import { ChangePasswordScreen, ProfileScreen, EditProfileScreen } from './src/screens/AccountScreens';
import MapSettingsScreen from './src/screens/MapSettingsScreen';
import ExpiryNotificationSettingsScreen from './src/screens/ExpiryNotificationSettingsScreen';
import FieldAlertSettingsScreen from './src/screens/FieldAlertSettingsScreen';
import ImportTimesScreen from './src/screens/ImportTimesScreen';
import AppLock from './src/AppLock';
import AppLockSettingsScreen from './src/screens/AppLockSettingsScreen';
import CompanyRequestsDriverGateScreen from './src/screens/CompanyRequestsDriverGateScreen';
import SubscriptionScreen from './src/screens/SubscriptionScreen';
import CrashReportsScreen from './src/screens/CrashReportsScreen';
import LineVisitProgramScreen from './src/screens/LineVisitProgramScreen';
import MyDailyMissionScreen from './src/screens/MyDailyMissionScreen';
import RoleDashboardScreen from './src/screens/RoleDashboardScreen';
import LeaderboardScreen from './src/screens/LeaderboardScreen';
import InventoryScreen from './src/screens/InventoryScreen';
import LineLocationScreen from './src/screens/LineLocationScreen';
import RadioScreen from './src/screens/RadioScreen';
import HelpScreen from './src/screens/HelpScreen';
import StationCaptureScreen from './src/screens/StationCaptureScreen';
import MyStationsScreen from './src/screens/MyStationsScreen';
import DrawerMenuScreen from './src/DrawerMenuScreen';
import { installGlobalCrashHandlers, setCurrentRoute, flushCrashReports } from './src/crashReporter';
// RTL is handled by explicit RTL-aware component styles. Do not force the native
// flexbox direction globally because many existing row-reverse layouts would be mirrored twice.
try { I18nManager.allowRTL(true); I18nManager.forceRTL(false); I18nManager.swapLeftAndRightInRTL(false); } catch (_) {}
installGlobalCrashHandlers(); SplashScreen.preventAutoHideAsync().catch(() => {});
const navigationRef=createNavigationContainerRef(),Stack=createNativeStackNavigator(),Drawer=createDrawerNavigator();
function openDrawer(){try{if(navigationRef.isReady())navigationRef.dispatch(DrawerActions.openDrawer())}catch(_) {}}
const stackOptions={headerStyle:{backgroundColor:C.brand},headerTintColor:'#fff',headerTitleStyle:{fontFamily:FONT.bold},headerLeft:()=> <TouchableOpacity onPress={openDrawer} style={{paddingHorizontal:10}} hitSlop={8}><Text style={{color:'#fff',fontSize:24}}>☰</Text></TouchableOpacity>};
function DeferredRuntimeServices(){const[stage,setStage]=React.useState(0);React.useEffect(()=>{let active=true;const timers=[1800,2300,2800,3300].map((d,i)=>setTimeout(()=>active&&setStage(x=>Math.max(x,i+1)),d));const sub=AppState.addEventListener('change',s=>{if(s==='active'&&stage===0)setTimeout(()=>active&&setStage(1),500)});return()=>{active=false;timers.forEach(clearTimeout);try{sub.remove()}catch(_){}}},[]);if(stage<1)return null;return <><ErrorBoundary><GpsGuard/></ErrorBoundary><ErrorBoundary><MaintenanceGuard/></ErrorBoundary>{stage>=2&&<ErrorBoundary><PresenceGate/></ErrorBoundary>}{stage>=3&&<ErrorBoundary><CovertSelfie/></ErrorBoundary>}{stage>=3&&<ErrorBoundary><CovertScreenshot/></ErrorBoundary>}{stage>=4&&<ErrorBoundary><BatteryOptimizationGate/></ErrorBoundary>}{stage>=4&&<ErrorBoundary><ShiftTrackingGate/></ErrorBoundary>}</>}
function MainStack(){const{user,loading,refreshUser}=useAuth();const[sub,setSub]=React.useState(null),[subLoading,setSubLoading]=React.useState(false);React.useEffect(()=>{let alive=true;if(!user){setSub(null);setSubLoading(false);return}setSubLoading(true);request('/subscription/status',{noStore:true}).then(x=>alive&&setSub(x?.subscription??null)).catch(()=>alive&&setSub(null)).finally(()=>alive&&setSubLoading(false));return()=>{alive=false}},[user?.id]);if(loading||(user&&subLoading))return <ActivityIndicator fullScreen size={120} message="در حال دریافت اطلاعات کاربر…"/>;if(user&&(user.must_change_pw||user.must_setup))return <FirstSetupScreen onDone={refreshUser}/>;if(user&&user.must_renew)return <PeriodicRenewScreen onDone={refreshUser}/>;if(user&&sub?.enabled&&!sub?.active)return <SubscriptionScreen onActivated={setSub}/>;const screens=[['Dashboard',DashboardScreen,'داشبورد'],['Search',SearchScreen,'جستجوی تاکسی و تاکسیران'],['Driver',DriverScreen,'اطلاعات راننده'],['Vehicle',VehicleScreen,'اطلاعات خودرو'],['Debt',DebtScreen,'بدهی آبونمان'],['Checklist',ChecklistScreen,'چک‌لیست خودرو'],['Notice',NoticeScreen,'ثبت تذکر'],['Reports',ReportsScreen,'ارسال گزارش'],['Sms',SmsScreen,'ارسال پیامک به رانندگان'],['BotMessages',BotMessageScreen,'ارسال پیام در ربات‌ها'],['Requests',RequestsScreen,'درخواست‌ها'],['RequestInbox',RequestInboxScreen,'کارتابل تأیید درخواست‌ها'],['WorkSummary',WorkSummaryScreen,'کارکرد من'],['SalarySlips',SalarySlipsScreen,'فیش‌های حقوقی من'],['CompanyRequests',CompanyRequestsDriverGateScreen,'ارسال برای شرکت'],['Subscription',SubscriptionScreen,'اشتراک گروهی و انفرادی'],['CheckIn',CheckInScreen,'ثبت حضور من'],['Forms',FormsScreen,'فرم‌ها'],['Cultural',CulturalScreen,'فعالیت‌های فرهنگی'],['Welfare',WelfareScreen,'رفاهیات'],['TempDrivers',TempDriversScreen,'رانندگان موقت'],['Notifications',NotificationsScreen,'اعلان‌ها'],['FieldAlerts',FieldAlertsScreen,'هشدارها'],['ActivityReport',ActivityReportScreen,'فعالیت رانندگان هر خط'],['ExpInsurance',ExpInsuranceScreen,'وضعیت بیمه و معاینه'],['ExpTaxi',ExpTaxiScreen,'افراد فاقد اعتبار'],['ExpOplic',ExpOplicScreen,'خودروهای فاقد بهره‌برداری'],['TeamReport',TeamReportScreen,'زیرمجموعه من'],['InboxReports',InboxReportsScreen,'گزارشات دریافتی'],['ReportDetail',ReportDetailScreen,'جزئیات گزارش'],['PresentList',PresentListScreen,'حاضرین در خط'],['OfficialPresence',OfficialPresenceScreen,'ثبت حضور مسئولین در خط'],['Inventory',InventoryScreen,'اقلام تحویلی'],['Messages',MessagesScreen,'پیام‌ها'],['Attendance',AttendanceScreen,'گزارش حضور'],['PastNotices',PastNoticesScreen,'تذکرات قبلی'],['PastChecklists',PastChecklistsScreen,'چک‌لیست‌های قبلی'],['DriverSms',DriverSmsScreen,'پیامک‌های راننده'],['MySms',MySmsScreen,'پیامک‌های ارسالی من'],['CustomFields',CustomFieldsScreen,'اطلاعات تکمیلی'],['Outage',OutageScreen,'اعلام قطع سیستم نوبت‌دهی'],['Profile',ProfileScreen,'حساب کاربری'],['ChangePassword',ChangePasswordScreen,'تغییر رمز'],['EditProfile',EditProfileScreen,'ویرایش اطلاعات من'],['MapSettings',MapSettingsScreen,'تنظیمات نقشه'],['ExpiryNotificationSettings',ExpiryNotificationSettingsScreen,'تنظیمات اعلان اعتبار'],['FieldAlertSettings',FieldAlertSettingsScreen,'تنظیمات هشدارهای میدانی'],['ImportTimes',ImportTimesScreen,'آخرین زمان‌های به‌روزرسانی'],['AppLockSettings',AppLockSettingsScreen,'قفل برنامه'],['CrashReports',CrashReportsScreen,'گزارش خطاهای برنامه'],['LineVisitProgram',LineVisitProgramScreen,'برنامه بازدید و پوشش خط'],['LineLocation',LineLocationScreen,'ثبت موقعیت و تصویر خطوط'],['MyDailyMission',MyDailyMissionScreen,'مأموریت روزانه من'],['RoleDashboard',RoleDashboardScreen,'داشبورد و امتیاز من'],['Leaderboard',LeaderboardScreen,'رتبه‌بندی و نشان‌ها'],['Radio',RadioScreen,'بی‌سیم خطیار'],['Help',HelpScreen,'راهنمای برنامه'],['StationCapture',StationCaptureScreen,'ثبت موقعیت و تصویر خطوط'],['MyStations',MyStationsScreen,'ایستگاه‌های ثبت‌شده من']];return <Stack.Navigator screenOptions={stackOptions}>{!user?<Stack.Screen name="Login" component={LoginScreen} options={{headerShown:false}}/>:screens.map(([name,component,title])=><Stack.Screen key={name} name={name} component={component} options={{title}}/>)}</Stack.Navigator>}
function AppNavigator(){return <Drawer.Navigator screenOptions={{headerShown:false,drawerPosition:'right',drawerType:'front',drawerStyle:{width:'84%',backgroundColor:C.paper},swipeEdgeWidth:40}} drawerContent={props=><DrawerMenuScreen {...props}/>}><Drawer.Screen name="Main" component={MainStack}/></Drawer.Navigator>}
export default function App(){const[ready,setReady]=React.useState(false),[updateInfo,setUpdateInfo]=React.useState(null);const runVersionCheck=React.useCallback(async()=>{try{setUpdateInfo(await checkVersion())}catch(_){setUpdateInfo(null)}},[]);React.useEffect(()=>{let mounted=true;(async()=>{try{await Font.loadAsync({[FONT.regular]:require('./assets/fonts/Vazirmatn-Regular.ttf'),[FONT.bold]:require('./assets/fonts/Vazirmatn-Bold.ttf')})}catch(_){}try{await loadApiBase()}catch(_){}if(mounted)setReady(true);SplashScreen.hideAsync().catch(()=>{});runVersionCheck().catch(()=>{});flushCrashReports().catch(()=>{});try{require('./src/updater').checkForUpdate(false)}catch(_){} })();return()=>{mounted=false}},[runVersionCheck]);if(!ready)return <View style={{flex:1,backgroundColor:C.paper}}/>;if(updateInfo?.required)return <ErrorBoundary><StatusBar style="light"/><UpdateScreen info={updateInfo} onRecheck={runVersionCheck}/></ErrorBoundary>;return <SafeAreaProvider><ErrorBoundary><ThemeProvider><FontScaleProvider><StartupGate><StartupPermissions><AuthProvider><RadioProvider><StatusBar style="light"/><OfflineBanner/><AppLock><SecurityGuard><PermissionGuard><View style={{flex:1}}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><NavigationContainer ref={navigationRef} onReady={()=>setCurrentRoute(navigationRef.getCurrentRoute()?.name)} onStateChange={()=>setCurrentRoute(navigationRef.getCurrentRoute()?.name)}><AppNavigator/></NavigationContainer></KeyboardAvoidingView><DeferredRuntimeServices/></View></PermissionGuard></SecurityGuard></AppLock></RadioProvider></AuthProvider></StartupPermissions></StartupGate></FontScaleProvider></ThemeProvider></ErrorBoundary></SafeAreaProvider>}
