// تنظیمات build اپ. مقادیر پیش‌فرض از .env خوانده می‌شوند.
try { require('dotenv').config(); } catch (e) {}
let hasLocalAuth = false;
try { require.resolve('expo-local-authentication'); hasLocalAuth = true; } catch (e) { hasLocalAuth = false; }
module.exports = ({ config }) => ({
  ...config,
  name: process.env.APP_NAME || 'خطیار', slug: 'khatyar-mobile', version: process.env.ANDROID_VERSION_NAME || '1.3.79', orientation: 'portrait', newArchEnabled: true, icon: './assets/icon.png', userInterfaceStyle: 'light', assetBundlePatterns: ['**/*'],
  android: {package: process.env.ANDROID_PACKAGE || 'ir.mashhad.taxicontrol',versionCode: Number(process.env.ANDROID_VERSION_CODE || 10379),softwareKeyboardLayoutMode: 'resize',adaptiveIcon:{foregroundImage:'./assets/adaptive-icon.png',backgroundColor:'#0d7a5f'},permissions:['ACCESS_FINE_LOCATION','ACCESS_COARSE_LOCATION','ACCESS_BACKGROUND_LOCATION','CAMERA','RECORD_AUDIO','INTERNET','ACCESS_NETWORK_STATE','FOREGROUND_SERVICE','FOREGROUND_SERVICE_LOCATION','FOREGROUND_SERVICE_MEDIA_PLAYBACK','FOREGROUND_SERVICE_MICROPHONE','RECEIVE_BOOT_COMPLETED','VIBRATE','WAKE_LOCK','REQUEST_IGNORE_BATTERY_OPTIMIZATIONS','POST_NOTIFICATIONS']},
  plugins:[['expo-splash-screen',{image:'./assets/splash-icon.png',resizeMode:'contain',backgroundColor:'#0d7a5f',android:{image:'./assets/splash-icon.png',resizeMode:'contain',backgroundColor:'#0d7a5f'}}],['expo-secure-store',{configureAndroidBackup:false}],...(hasLocalAuth?[['expo-local-authentication',{faceIDPermission:'برای باز کردن برنامه از احراز هویت بیومتریک استفاده می‌شود.'}]]:[]),['expo-location',{isAndroidBackgroundLocationEnabled:true,locationAlwaysAndWhenInUsePermission:'برای ثبت تردد، برنامه به موقعیت در پس‌زمینه نیاز دارد.',foregroundService:{notificationTitle:'خطیار',notificationBody:'نرم‌افزار خطیار فعال و به سرور متصل است',notificationColor:'#0d7a5f'}}],['expo-audio',{microphonePermission:'برای استفاده از بی‌سیم خطیار، دسترسی میکروفون لازم است.',recordAudioAndroid:true,enableBackgroundPlayback:true,enableBackgroundRecording:false}],'expo-camera',['expo-notifications',{icon:'./assets/notification-icon.png',color:'#0d7a5f',sounds:['./assets/sounds/presence_validation_alert.mp3','./assets/sounds/notification_new.mp3','./assets/sounds/message_new.mp3','./assets/sounds/report_received.mp3','./assets/sounds/report_sent_success.mp3','./assets/sounds/presence_success.mp3','./assets/sounds/presence_selfie.mp3','./assets/sounds/presence_station_photo.mp3','./assets/sounds/radio_call_alert.wav']}],['expo-build-properties',{android:{minSdkVersion:24,compileSdkVersion:36,targetSdkVersion:36,buildToolsVersion:'36.0.0',enableProguardInReleaseBuilds:false,enableShrinkResourcesInReleaseBuilds:false,ndkVersion:process.env.ANDROID_NDK_VERSION||'27.1.12297006'}}],'./plugins/withGradle9Syntax','./plugins/withAndroidMavenMirrors','./plugins/withUtf8GradleEncoding','./plugins/withReleaseHardening','./plugins/withLocationJobCrashGuard','./plugins/withProguardKeep','./plugins/withReactNativeArchitectures','./plugins/withKhatyarRadio'],
  extra:{defaultApiBase:process.env.API_BASE||'https://app.yousefipour.ir/api',enableBgTracking:(process.env.ENABLE_BG_TRACKING||'true')==='true',app_version:process.env.ANDROID_VERSION_NAME||'1.3.79',eas:{projectId:process.env.EAS_PROJECT_ID||''}},
});
