import React,{useEffect,useMemo,useState}from'react';
import{View,Text,StyleSheet,TouchableOpacity,LayoutAnimation,Platform,UIManager}from'react-native';
import*as Location from'expo-location';
import{request}from'../api';import{FONT}from'../theme';import{faNum}from'../num';import{tehranTimeToEpochMs}from'../jdate';
const fmt=sec=>{sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;if(h)return`${faNum(h)} ساعت و ${faNum(m)} دقیقه`;if(m)return`${faNum(m)} دقیقه و ${faNum(s)} ثانیه`;return`${faNum(s)} ثانیه`};const toMs=value=>tehranTimeToEpochMs(value);
function StatusRow({bad,title,since,now,fix}){const elapsed=bad&&since?fmt((now-since)/1000):null;return <View style={[s.row,bad?s.rowBad:s.rowOk]}><View style={s.rowTextWrap}><Text style={[s.rowTitle,bad?s.badText:s.okText]}>{title}</Text><Text style={[s.rowState,bad?s.badText:s.okText]}>{bad?`مدت وضعیت: ${elapsed||'در حال محاسبه'}`:'وضعیت عادی است'}</Text>{bad&&fix?<Text style={s.fix}>{fix}</Text>:null}</View><Text style={s.icon}>{bad?'⚠️':'✅'}</Text></View>}
if(Platform.OS==='android'&&UIManager.setLayoutAnimationEnabledExperimental)UIManager.setLayoutAnimationEnabledExperimental(true);
export default function FieldStatusBanner(){const[data,setData]=useState(null),[error,setError]=useState(false),[now,setNow]=useState(Date.now()),[refreshing,setRefreshing]=useState(false),[expanded,setExpanded]=useState(false),[localGps,setLocalGps]=useState(null),[localGpsSince,setLocalGpsSince]=useState(null);
 const load=async()=>{setRefreshing(true);try{const result=await request('/my/field-status');setData(result||{});setError(false)}catch{setError(true)}finally{setRefreshing(false)}};
 const checkLocalGps=async()=>{try{const enabled=await Location.hasServicesEnabledAsync();if(enabled){setLocalGps(true);setLocalGpsSince(null)}else{setLocalGps(false);setLocalGpsSince(v=>v||Date.now())}}catch{setLocalGps(null)}};
 useEffect(()=>{let alive=true;const safe=async()=>{if(alive)await load()};safe();const poll=setInterval(safe,30000);return()=>{alive=false;clearInterval(poll)}},[]);
 useEffect(()=>{let alive=true;const safe=async()=>{if(alive)await checkLocalGps()};safe();const poll=setInterval(safe,5000);return()=>{alive=false;clearInterval(poll)}},[]);
 const status=useMemo(()=>({vpnBad:!!data?.vpn_on,vpnSince:toMs(data?.vpn_since),gpsBad:localGps===false?true:localGps===true?false:!!data?.gps_off,gpsSince:localGps===false?(localGpsSince||toMs(data?.gps_since)):null,stationBad:!!data?.outside_station,stationSince:toMs(data?.outside_since)}),[data,localGps,localGpsSince]);
 const hasAlert=status.vpnBad||status.gpsBad||status.stationBad;
 useEffect(()=>{if(hasAlert)setExpanded(true)},[hasAlert]);useEffect(()=>{if(!hasAlert)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[hasAlert]);
 const toggle=()=>{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);setExpanded(v=>!v)};
 return <View style={[s.box,hasAlert&&s.boxAlert]}><TouchableOpacity onPress={toggle} activeOpacity={.8} style={s.header}><Text style={[s.chevron,expanded&&s.chevronOpen]}>⌄</Text><View style={s.headerText}><Text style={s.title}>وضعیت ایمنی و موقعیت دستگاه</Text><Text style={s.sub}>{hasAlert?'هشدار فعال است؛ برای مشاهده جزئیات کادر باز شده است.':'وضعیت عادی است؛ برای مشاهده جزئیات عنوان را لمس کنید.'}</Text></View><Text style={s.summaryIcon}>{hasAlert?'⚠️':'✅'}</Text></TouchableOpacity>{expanded?<TouchableOpacity onPress={load} disabled={refreshing} style={s.refreshBtn}><Text style={s.refreshTxt}>{refreshing?'در حال بررسی…':'بررسی مجدد'}</Text></TouchableOpacity>:null}{expanded&&(error&&!data?<View style={s.errorBox}><Text style={s.errorText}>دریافت وضعیت از سرور ناموفق بود. اینترنت را بررسی و «بررسی مجدد» را لمس کنید.</Text></View>:<><StatusRow bad={status.vpnBad} title="VPN / فیلترشکن" since={status.vpnSince} now={now} fix="VPN را خاموش کنید و سپس وضعیت را دوباره بررسی کنید."/><StatusRow bad={status.gpsBad} title="موقعیت‌یابی GPS" since={status.gpsSince} now={now} fix="GPS دستگاه را روشن کنید و مجوز موقعیت را فعال نگه دارید."/><StatusRow bad={status.stationBad} title="محدوده ایستگاه" since={status.stationSince} now={now} fix="به محدوده مجاز ایستگاه بازگردید و موقعیت دستگاه را تازه‌سازی کنید."/></>)}</View>}
const s=StyleSheet.create({box:{backgroundColor:'#fff',borderColor:'#e2b100',borderWidth:1,padding:12,marginHorizontal:12,marginTop:12,marginBottom:4,borderRadius:14,elevation:2},boxAlert:{borderColor:'#d64545',backgroundColor:'#fffafa'},header:{width:'100%',flexDirection:'row-reverse',alignItems:'center',gap:10},headerText:{flex:1,minWidth:0,alignSelf:'stretch',alignItems:'flex-end',justifyContent:'center'},chevron:{fontSize:24,color:'#6f6250',textAlign:'center',width:28},chevronOpen:{transform:[{rotate:'180deg'}]},summaryIcon:{fontSize:20,textAlign:'center',width:28},title:{width:'100%',alignSelf:'stretch',fontFamily:FONT.bold,color:'#493a00',textAlign:'right',writingDirection:'rtl',fontSize:15},sub:{width:'100%',alignSelf:'stretch',fontFamily:FONT.regular,color:'#6f6250',textAlign:'right',writingDirection:'rtl',fontSize:11,marginTop:2},refreshBtn:{alignSelf:'flex-end',backgroundColor:'#f7c600',paddingHorizontal:10,paddingVertical:7,borderRadius:9,marginTop:10},refreshTxt:{fontFamily:FONT.bold,color:'#3d3200',fontSize:11,textAlign:'right',writingDirection:'rtl'},row:{width:'100%',flexDirection:'row-reverse',alignItems:'center',borderRadius:10,padding:10,marginTop:7,borderWidth:1},rowOk:{backgroundColor:'#eefaf3',borderColor:'#b9e3c9'},rowBad:{backgroundColor:'#fff0f1',borderColor:'#efb2b8'},rowTextWrap:{flex:1,minWidth:0,alignSelf:'stretch',alignItems:'flex-end'},rowTitle:{width:'100%',fontFamily:FONT.bold,textAlign:'right',writingDirection:'rtl',fontSize:13},rowState:{width:'100%',fontFamily:FONT.regular,textAlign:'right',writingDirection:'rtl',marginTop:3,fontSize:12},okText:{color:'#176b3a'},badText:{color:'#a01826'},fix:{width:'100%',fontFamily:FONT.bold,color:'#8d1a25',textAlign:'right',writingDirection:'rtl',marginTop:5,fontSize:11},icon:{fontSize:20,marginRight:8,textAlign:'center',width:28},errorBox:{backgroundColor:'#fff3cd',borderColor:'#e0a800',borderWidth:1,padding:10,borderRadius:9},errorText:{fontFamily:FONT.regular,color:'#7a5600',textAlign:'right',writingDirection:'rtl',fontSize:12,width:'100%'}});