-- v177: checklist compatibility and report subjects
CREATE TABLE IF NOT EXISTS report_subjects (
 id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_report_subject_title (title)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @c1=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='checklist_items' AND COLUMN_NAME='options');
SET @q1=IF(@c1=0,'ALTER TABLE checklist_items ADD COLUMN options TEXT NULL','SELECT 1'); PREPARE s1 FROM @q1; EXECUTE s1; DEALLOCATE PREPARE s1;
SET @c2=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='checklist_items' AND COLUMN_NAME='answer_type');
SET @q2=IF(@c2=0,"ALTER TABLE checklist_items ADD COLUMN answer_type VARCHAR(20) NOT NULL DEFAULT 'single'",'SELECT 1'); PREPARE s2 FROM @q2; EXECUTE s2; DEALLOCATE PREPARE s2;
