import React,{useState,useEffect,useRef,useCallback}from'react';
import{View,Text,TouchableOpacity,TextInput,StyleSheet,AppState,Vibration,PanResponder}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import*as SecureStore from'expo-secure-store';
import{C as CC,FONT}from'./theme';
import{faNum}from'./num';
const CFG_KEY='app_lock_cfg',SECRET_KEY='app_lock_secret',FAIL_KEY='app_lock_fail_state';
const DEFAULT_CFG={enabled:false,type:'pin4',timeoutMin:1,useBiometric:true};
export async function getLockConfig(){try{const x=await AsyncStorage.getItem(CFG_KEY);const c=x?{...DEFAULT_CFG,...JSON.parse(x)}:DEFAULT_CFG;if(c.type==='pin')c.type='pin4';return c}catch{return DEFAULT_CFG}}
export async function setLockConfig(c){await AsyncStorage.setItem(CFG_KEY,JSON.stringify({...DEFAULT_CFG,...c}))}
export async function setLockSecret(v){await SecureStore.setItemAsync(SECRET_KEY,String(v),{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY})}
export async function getLockSecret(){try{return await SecureStore.getItemAsync(SECRET_KEY)}catch{return null}}
export async function clearLockSecret(){try{await SecureStore.deleteItemAsync(SECRET_KEY)}catch{}}
async function failures(){try{return JSON.parse(await SecureStore.getItemAsync(FAIL_KEY)||'{}')}catch{return{}}}
async function failed(){const f=await failures(),count=Number(f.count||0)+1,ms=count>=8?300000:count>=5?30000:count>=3?5000:0,s={count,until:ms?Date.now()+ms:0};try{await SecureStore.setItemAsync(FAIL_KEY,JSON.stringify(s))}catch{}return s}
async function clearFailures(){try{await SecureStore.deleteItemAsync(FAIL_KEY)}catch{}}
export const LOCK_TYPES={pin4:{label:'پین ۴ رقمی',min:4,max:4},numeric:{label:'رمز عددی',min:5,max:16},password:{label:'رمز حروفی و عددی',min:6,max:32},pattern:{label:'الگوی حرکتی',min:4,max:9}};
export function validateLockSecret(type,v){const s=String(v||'');if(type==='pattern'){const p=s.split('-').filter(Boolean);return p.length<4?'الگو باید حداقل ۴ نقطه داشته باشد.':new Set(p).size!==p.length?'نقاط الگو نباید تکراری باشند.':''}const t=LOCK_TYPES[type];if(!t)return'نوع قفل نامعتبر است.';if(s.length<t.min||s.length>t.max)return`طول ${t.label} باید بین ${faNum(t.min)} تا ${faNum(t.max)} کاراکتر باشد.`;if(type==='pin4'&&!/^\d{4}$/.test(s))return'پین باید دقیقاً ۴ رقم باشد.';if(type==='numeric'&&!/^\d+$/.test(s))return'رمز عددی فقط شامل رقم باشد.';if(type==='password'&&!/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]+$/.test(s))return'رمز باید حداقل یک حرف انگلیسی و یک عدد داشته باشد.';if(/^(.)\1+$/.test(s)||['1234','12345','123456','0000','1111','111111','12345678'].includes(s))return'این رمز بیش از حد ساده است.';return''}
export default function AppLock({children}){const[cfg,setCfg]=useState(null),[locked,setLocked]=useState(false),bg=useRef(null);const load=useCallback(async()=>{const c=await getLockConfig();setCfg(c);if(c.enabled)setLocked(true)},[]);useEffect(()=>{load()},[load]);useEffect(()=>{let last=AppState.currentState;const sub=AppState.addEventListener('change',async st=>{const c=await getLockConfig();if(!c.enabled){last=st;return}if(global.__APPLOCK_SUPPRESS__){last=st;return}if(st==='background')bg.current=Date.now();else if(st==='active'&&last==='background'){const mins=bg.current?(Date.now()-bg.current)/60000:0;if(Number(c.timeoutMin)===0||mins>=Number(c.timeoutMin))setLocked(true);bg.current=null}last=st});return()=>sub.remove()},[]);if(!cfg||!cfg.enabled||!locked)return<>{children}</>;return<LockScreen cfg={cfg} unlock={async()=>{await clearFailures();setLocked(false)}}/>}
function LockScreen({cfg,unlock}){const[value,setValue]=useState(''),[pattern,setPattern]=useState([]),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[cool,setCool]=useState(0);useEffect(()=>{if(cfg.useBiometric)bio()},[]);useEffect(()=>{if(!cool)return;const t=setInterval(()=>setCool(x=>Math.max(0,x-1)),1000);return()=>clearInterval(t)},[cool]);const fail=async()=>{const f=await failed();setValue('');setPattern([]);setCool(f.until>Date.now()?Math.ceil((f.until-Date.now())/1000):0);setErr(f.count>=3?`تلاش ناموفق ${faNum(f.count)} بار.`:'رمز واردشده صحیح نیست.');Vibration.vibrate([0,80,70,80])};async function bio(){if(busy||cool)return;try{setBusy(true);global.__APPLOCK_SUPPRESS__=true;const A=require('expo-local-authentication'),has=await A.hasHardwareAsync(),en=await A.isEnrolledAsync();if(!has||!en){setErr('اثر انگشت یا احراز هویت بیومتریک روی دستگاه فعال نیست.');return}const r=await A.authenticateAsync({promptMessage:'برای باز کردن خطیار احراز هویت کنید',cancelLabel:'استفاده از رمز',disableDeviceFallback:false});if(r.success)await unlock()}catch{}finally{setBusy(false);setTimeout(()=>{global.__APPLOCK_SUPPRESS__=false},700)}}async function check(v){if(busy||cool||!v)return;setBusy(true);setErr('');const secret=await getLockSecret();const ok=secret&&(String(v)===String(secret)||(cfg.type==='pattern'&&String(v).replace(/-/g,'')===String(secret)));if(ok)await unlock();else await fail();setBusy(false)}const add=async d=>{if(busy||cool)return;setErr('');if(d==='del'){setValue(v=>v.slice(0,-1));return}const max=cfg.type==='pin4'?4:16,n=(value+d).slice(0,max);setValue(n);if(cfg.type==='pin4'&&n.length===4)await check(n)};if(cfg.type==='pattern')return<Pattern selected={pattern}setSelected={setPattern}onComplete={p=>{setPattern(p);check(p.join('-'))}}bio={cfg.useBiometric?bio:null}err={err}cool={cool}/>;if(cfg.type==='password')return<Password value={value}setValue={setValue}check={check}bio={cfg.useBiometric?bio:null}err={err}cool={cool}/>;const keys=['1','2','3','4','5','6','7','8','9','bio','0','del'];return<View style={s.wrap}><Icon/><Text style={s.title}>خطیار قفل است</Text><Text style={s.sub}>{cfg.type==='numeric'?'رمز عددی خود را وارد کنید':'پین ۴ رقمی خود را وارد کنید'}</Text><View style={s.dots}>{Array.from({length:cfg.type==='pin4'?4:Math.max(4,value.length)}).map((_,i)=><View key={i}style={[s.dot,i<value.length&&s.on]}/>)}</View>{err&&<Text style={s.err}>{err}</Text>}{cool>0&&<Text style={s.cool}>لطفاً {faNum(cool)} ثانیه صبر کنید</Text>}<View style={s.pad}>{keys.map(k=><TouchableOpacity key={k}disabled={!!cool}style={s.key}onPress={()=>k==='bio'?bio():add(k)}><Text style={s.keyText}>{k==='del'?'⌫':k==='bio'?'♙':faNum(k)}</Text></TouchableOpacity>)}</View></View>}
function Icon(){return<View style={s.icon}><Text style={{fontSize:32}}>🔒</Text></View>}
function Password({value,setValue,check,bio,err,cool}){return<View style={s.wrap}><Icon/><Text style={s.title}>خطیار قفل است</Text><Text style={s.sub}>رمز عبور حروفی و عددی خود را وارد کنید</Text><TextInput autoFocus value={value}onChangeText={v=>setValue(v.slice(0,32))}secureTextEntry style={s.input}placeholder="رمز عبور"placeholderTextColor="#77869b"autoCapitalize="none"autoCorrect={false}onSubmitEditing={()=>check(value)}editable={!cool}/>{err&&<Text style={s.err}>{err}</Text>}{cool>0&&<Text style={s.cool}>لطفاً {faNum(cool)} ثانیه صبر کنید</Text>}<View style={s.row}><TouchableOpacity style={s.btn}onPress={()=>check(value)}><Text style={s.btnText}>ورود</Text></TouchableOpacity><TouchableOpacity style={s.btn}onPress={()=>setValue('')}><Text style={s.btnText}>پاک کردن</Text></TouchableOpacity></View>{bio&&<TouchableOpacity style={s.bio}onPress={bio}><Text style={s.btnText}>اثر انگشت / احراز هویت</Text></TouchableOpacity>}</View>}
function Pattern({selected,setSelected,onComplete,bio,err,cool}){const ref=useRef([]);const add=n=>{if(!ref.current.includes(n)){ref.current=[...ref.current,n];setSelected([...ref.current])}};const point=e=>{const x=e.nativeEvent.locationX,y=e.nativeEvent.locationY,col=Math.max(0,Math.min(2,Math.floor(x/70))),row=Math.max(0,Math.min(2,Math.floor(y/70)));return row*3+col+1};const pan=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>add(point(e)),onPanResponderMove:e=>add(point(e)),onPanResponderRelease:()=>{const p=ref.current.slice();if(p.length>=4)onComplete(p);else{Vibration.vibrate(80);ref.current=[];setSelected([])}}})).current;return<View style={s.wrap}><Icon/><Text style={s.title}>الگوی قفل را رسم کنید</Text><Text style={s.sub}>حداقل ۴ نقطه را با کشیدن انگشت به هم متصل کنید</Text>{err&&<Text style={s.err}>{err}</Text>}{cool>0&&<Text style={s.cool}>لطفاً {faNum(cool)} ثانیه صبر کنید</Text>}<View style={s.pattern}{...pan.panHandlers}>{Array.from({length:8}).map((_,i)=>{const a=selected[i],b=selected[i+1];if(!a||!b)return null;const ax=((a-1)%3)*70+35,ay=Math.floor((a-1)/3)*70+35,bx=((b-1)%3)*70+35,by=Math.floor((b-1)/3)*70+35,len=Math.hypot(bx-ax,by-ay),ang=Math.atan2(by-ay,bx-ax)*180/Math.PI;return<View key={'l'+i}pointerEvents="none"style={[s.line,{left:ax,top:ay,width:len,transform:[{rotate:`${ang}deg`}]}]}/>})}{Array.from({length:9}).map((_,i)=>{const n=i+1,x=(i%3)*70,y=Math.floor(i/3)*70;return<View key={n}pointerEvents="none"style={[s.node,{left:x,top:y},selected.includes(n)&&s.nodeOn]}><View style={s.core}/></View>})}</View><View style={s.row}><TouchableOpacity style={s.btn}onPress={()=>{ref.current=[];setSelected([])}}><Text style={s.btnText}>پاک کردن</Text></TouchableOpacity>{bio&&<TouchableOpacity style={s.btn}onPress={bio}><Text style={s.btnText}>اثر انگشت</Text></TouchableOpacity>}</View></View>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#0b1220',alignItems:'center',justifyContent:'center',padding:24},icon:{width:68,height:68,borderRadius:22,backgroundColor:'#17243a',alignItems:'center',justifyContent:'center',marginBottom:12},title:{fontFamily:FONT.bold,color:'#fff',fontSize:21},sub:{fontFamily:FONT.regular,color:'#a7b4c7',fontSize:13,marginTop:8,marginBottom:16,textAlign:'center'},dots:{flexDirection:'row',gap:13,marginBottom:10},dot:{width:15,height:15,borderRadius:8,borderWidth:2,borderColor:'#506078'},on:{backgroundColor:CC.brand,borderColor:CC.brand},err:{color:'#ff8080',fontFamily:FONT.regular,fontSize:13,marginVertical:8,textAlign:'center'},cool:{color:'#ffd166',fontFamily:FONT.bold,fontSize:13,marginVertical:7},pad:{width:285,flexDirection:'row-reverse',flexWrap:'wrap',justifyContent:'center',gap:13,marginTop:10},key:{width:78,height:68,borderRadius:34,backgroundColor:'#18263b',alignItems:'center',justifyContent:'center'},keyText:{color:'#fff',fontFamily:FONT.bold,fontSize:23},input:{width:300,borderRadius:14,backgroundColor:'#17243a',borderWidth:1,borderColor:'#33445d',padding:15,color:'#fff',fontFamily:FONT.regular,textAlign:'right',fontSize:17},row:{flexDirection:'row-reverse',gap:10,marginTop:14},btn:{backgroundColor:CC.brand,borderRadius:12,paddingVertical:12,paddingHorizontal:20,minWidth:100,alignItems:'center'},btnText:{color:'#fff',fontFamily:FONT.bold},bio:{backgroundColor:'#253754',borderRadius:12,padding:13,marginTop:12,minWidth:230,alignItems:'center'},pattern:{width:210,height:210,position:'relative',marginVertical:18},node:{position:'absolute',width:48,height:48,borderRadius:24,borderWidth:2,borderColor:'#53647d',alignItems:'center',justifyContent:'center'},nodeOn:{borderColor:CC.brand,backgroundColor:'#17365c'},core:{width:12,height:12,borderRadius:6,backgroundColor:'#8291a8'},line:{position:'absolute',height:4,backgroundColor:CC.brand,borderRadius:2,transformOrigin:'left center'}});