import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';
import Constants from 'expo-constants';
import { postOrQueue, request } from './api';
import { isVpnOn, vpnStatus } from './device';
import { getBatteryInfo } from './battery';
import { FEATURES } from './config';
import { isInShift } from './shiftCheck';
import { requestBackgroundLocationCompat } from './androidCompat';
export const BG_TASK='taxi-bg-location';
export async function getAccuratePosition({samples=2,timeoutMs=7000,desiredAccuracy=20,maxAccuracy=80}={}){let best=null;for(let i=0;i<samples;i++){try{const p=await Promise.race([Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High,mayShowUserSettingsDialog:true}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),timeoutMs))]);if(p?.coords){const a=p.coords.accuracy??9999;if(!best||a<(best.coords.accuracy??9999))best=p;if(a<=desiredAccuracy)break;}}catch{}}const a=best?.coords?.accuracy??9999;return best&&a<=maxAccuracy?best:null;}
export async function getFastPosition({maxAgeMs=30000,timeoutMs=5000,maxAccuracy=100}={}){try{const last=await Location.getLastKnownPositionAsync({maxAge:maxAgeMs,requiredAccuracy:maxAccuracy});if(last?.coords){Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High,mayShowUserSettingsDialog:true}).catch(()=>{});return last;}}catch{}try{const p=await Promise.race([Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced,mayShowUserSettingsDialog:true}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),timeoutMs))]);const a=p?.coords?.accuracy??9999;if(p?.coords&&a<=maxAccuracy)return p;}catch{}return null;}
export async function getGsmPosition({timeoutMs=5000,maxAccuracy=100}={}){try{const p=await Promise.race([Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Lowest}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),timeoutMs))]);const a=p?.coords?.accuracy??9999;if(p?.coords&&a<=maxAccuracy)return{coords:p.coords,timestamp:p.timestamp,viaGsm:true};}catch{}return null;}
export async function getTrackingPosition(){const fast=await getFastPosition();if(fast?.coords)return{lat:fast.coords.latitude,lng:fast.coords.longitude,acc:fast.coords.accuracy,viaGsm:false,ts:fast.timestamp};const gps=await getAccuratePosition({samples:2,timeoutMs:7000,desiredAccuracy:25,maxAccuracy:100});if(gps?.coords)return{lat:gps.coords.latitude,lng:gps.coords.longitude,acc:gps.coords.accuracy,viaGsm:false,ts:gps.timestamp};const gsm=await getGsmPosition({timeoutMs:5000,maxAccuracy:150});if(gsm?.coords)return{lat:gsm.coords.latitude,lng:gsm.coords.longitude,acc:gsm.coords.accuracy,viaGsm:true,ts:gsm.timestamp};return null;}
const IS_EXPO_GO=Constants.appOwnership==='expo'||Constants.executionEnvironment==='storeClient';
try{TaskManager.defineTask(BG_TASK,async({data,error})=>{if(error||!data)return;const{locations}=data;if(!locations?.length)return;const ok=await isInShift().catch(()=>true);if(!ok)return;const pings=locations.map(l=>({lat:l.coords.latitude,lng:l.coords.longitude,captured_at:new Date(l.timestamp).toISOString(),mocked:!!(l.mocked||l.coords.mocked)}));let vpn=false,vpnCountry=null;try{const v=await vpnStatus();vpn=v.on;vpnCountry=v.country}catch{}let battery=null;try{battery=await getBatteryInfo()}catch{}await postOrQueue('/locations',{vpn_on:vpn,vpn_country:vpnCountry,battery,pings}).catch(()=>{});});}catch{}
let fgWatcher=null,networkFallbackInterval=null,trackingStartPromise=null;
export async function startTracking(){if(trackingStartPromise)return trackingStartPromise;trackingStartPromise=(async()=>{let fg;try{fg=await Location.requestForegroundPermissionsAsync()}catch{return}if(!fg?.granted)return;let intervalMs=60000;try{const c=await request('/app/version',{auth:false});const sec=parseInt(c?.location_interval_sec,10);if(sec&&sec>=5)intervalMs=sec*1000}catch{}try{const b=await getBatteryInfo();if(b&&!b.charging){if(b.level<=10)intervalMs=Math.round(intervalMs*3);else if(b.level<=20)intervalMs=Math.round(intervalMs*1.75)}}catch{}try{fgWatcher?.remove?.()}catch{}try{fgWatcher=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:Math.max(8000,Math.floor(intervalMs/2)),distanceInterval:20,mayShowUserSettingsDialog:true},async p=>{let vpn=false;try{vpn=await isVpnOn()}catch{}postOrQueue('/locations',{vpn_on:vpn,pings:[{lat:p.coords.latitude,lng:p.coords.longitude,captured_at:new Date(p.timestamp).toISOString(),mocked:!!(p.mocked||p.coords.mocked),accuracy:p.coords.accuracy,via_gsm:(p.coords.accuracy||0)>80,provider:(p.coords.accuracy||0)>80?'network':'gps'}]}).catch(()=>{})});}catch{}try{clearInterval(networkFallbackInterval)}catch{}networkFallbackInterval=setInterval(async()=>{try{const ok=await isInShift().catch(()=>true);if(!ok)return;const p=await getTrackingPosition();if(!p)return;postOrQueue('/locations',{vpn_on:false,pings:[{lat:p.lat,lng:p.lng,captured_at:new Date(p.ts||Date.now()).toISOString(),via_gsm:p.viaGsm,accuracy:p.acc,provider:p.viaGsm?'network':'gps'}]}).catch(()=>{})}catch{}},Math.max(120000,intervalMs));if(FEATURES.bgTracking&&!IS_EXPO_GO){try{const bg=await requestBackgroundLocationCompat(Location);if(bg.granted){const running=await Location.hasStartedLocationUpdatesAsync(BG_TASK).catch(()=>false);if(running)await Location.stopLocationUpdatesAsync(BG_TASK).catch(()=>{});await Location.startLocationUpdatesAsync(BG_TASK,{accuracy:Location.Accuracy.High,timeInterval:intervalMs,distanceInterval:25,pausesUpdatesAutomatically:false,activityType:Location.ActivityType.AutomotiveNavigation,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:'خطیار',notificationBody:'نرم افزار خطیار فعال و به سرور متصل است',notificationColor:'#0d7a5f',killServiceOnDestroy:false}})}}catch{}}})();try{return await trackingStartPromise}finally{trackingStartPromise=null}}
export async function isTrackingActive(){if(IS_EXPO_GO)return!!fgWatcher;try{return await Location.hasStartedLocationUpdatesAsync(BG_TASK).catch(()=>false)}catch{return false}}
export async function stopTracking(){try{fgWatcher?.remove?.();fgWatcher=null}catch{}try{clearInterval(networkFallbackInterval);networkFallbackInterval=null}catch{}if(IS_EXPO_GO)return;try{if(await Location.hasStartedLocationUpdatesAsync(BG_TASK).catch(()=>false))await Location.stopLocationUpdatesAsync(BG_TASK)}catch{}}
