import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Network from 'expo-network';
const KEY='offline_queue_v2';let flushPromise=null;
function uuid(){return'q_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,10)}
function normalizeQueue(value){const source=Array.isArray(value)?value:[];let changed=!Array.isArray(value);const normalized=source.filter(x=>x&&typeof x==='object'&&x.path).map(item=>{if(typeof item.client_uuid==='string'&&item.client_uuid.trim())return item;changed=true;return{...item,client_uuid:uuid()}});return{normalized,changed}}
export async function enqueue(item={}){if(!item?.path)return null;const queue=await pending();const clientUuid=typeof item.client_uuid==='string'&&item.client_uuid.trim()?item.client_uuid:uuid();if(queue.some(x=>String(x.client_uuid||'')===String(clientUuid)))return clientUuid;queue.push({...item,client_uuid:clientUuid,type:item.type||item.path||'unknown',queued_at:Number(item.queued_at||Date.now()),attempts:Number(item.attempts||0)});await AsyncStorage.setItem(KEY,JSON.stringify(queue));return clientUuid}
export async function pending(){const raw=await AsyncStorage.getItem(KEY);if(!raw)return[];try{const parsed=JSON.parse(raw);const{normalized,changed}=normalizeQueue(parsed);if(changed)await AsyncStorage.setItem(KEY,JSON.stringify(normalized));return normalized}catch(_){await AsyncStorage.removeItem(KEY);return[]}}
export async function clearQueue(){await AsyncStorage.removeItem(KEY)}
export async function removeSynced(ids=[]){const idSet=new Set((ids||[]).map(String));const queue=await pending();const remaining=queue.filter(item=>!idSet.has(String(item.client_uuid||'')));await AsyncStorage.setItem(KEY,JSON.stringify(remaining));return queue.length-remaining.length}
async function updateItem(item,patch){const queue=await pending();const i=queue.findIndex(x=>String(x.client_uuid||'')===String(item.client_uuid||''));if(i<0)return;queue[i]={...queue[i],...patch};await AsyncStorage.setItem(KEY,JSON.stringify(queue))}
export async function flush(send){if(flushPromise)return flushPromise;flushPromise=(async()=>{let net;try{net=await Network.getNetworkStateAsync()}catch(_){net={isInternetReachable:true}}if(net.isInternetReachable!==true)return 0;const queue=await pending();if(!queue.length)return 0;let synced=0;for(const item of queue){const attempts=Number(item.attempts||0),last=Number(item.last_attempt_at||0);if(last&&Date.now()-last<Math.min(15*60*1000,Math.max(30*1000,attempts*30*1000)))continue;try{const res=await send(item);if(res?.queued)continue;await removeSynced([item.client_uuid]);synced++}catch(e){await updateItem(item,{attempts:attempts+1,last_attempt_at:Date.now(),last_error:String(e?.message||e).slice(0,500)});continue}}return synced})();try{return await flushPromise}finally{flushPromise=null}}
