import React,{useState,useEffect,useRef}from'react';
import{AppState,StyleSheet,View}from'react-native';import AsyncStorage from'@react-native-async-storage/async-storage';import{request}from'./api';import{notify}from'./notify';import{useAuth}from'./auth';import PresenceCheckModal from'./PresenceCheckModal';import{startPresenceAlarm,stopPresenceAlarm}from'./presenceAlarm';import*as Notifications from'expo-notifications';import{tehranGregorianParts}from'./jdate';
function tehranNow(){const p=tehranGregorianParts(new Date());if(!p){const d=new Date();return{day:d.toISOString().slice(0,10),minutes:d.getHours()*60+d.getMinutes()};}return{day:`${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`,minutes:p.hour*60+p.minute};}
function slotToMinutes(s){const m=/^(\d{2}):(\d{2})$/.exec(s);return m?(+m[1])*60+(+m[2]):-1;}
function notificationData(raw){if(!raw)return{};if(typeof raw==='string'){try{return JSON.parse(raw)}catch(e){return{}}}return raw?.data&&typeof raw.data==='object'?raw.data:raw;}
export default function PresenceGate(){const{user}=useAuth();const[due,setDue]=useState(null);const cfgRef=useRef(null);const pollRef=useRef(null);const mountedRef=useRef(false);
useEffect(()=>{mountedRef.current=true;return()=>{mountedRef.current=false}},[]);
useEffect(()=>{if(!user)return;let alive=true;const check=async()=>{try{const cfg=await request('/my/presence-config',{auth:true,noStore:true});if(!alive)return;cfgRef.current=cfg;if(!cfg.enabled||!cfg.required||!(cfg.slots||[]).length){setDue(null);return;}if(due)return;const now=tehranNow();const win=Math.max(1,Number(cfg.window_minutes||1));for(const sl of cfg.slots){const sm=slotToMinutes(sl);if(sm<0||now.minutes<sm||now.minutes>=sm+win)continue;const key=`presence_done:${now.day}:${sl}`,expiredKey=`presence_expired:${now.day}:${sl}`;if(await AsyncStorage.getItem(key)||await AsyncStorage.getItem(expiredKey))continue;const notifKey=`presence_notified:${now.day}:${sl}`;if(!await AsyncStorage.getItem(notifKey)){await AsyncStorage.setItem(notifKey,'1');notify('صحت‌سنجی حضور',`لطفاً ظرف ${win} دقیقه سلفی و عکس خودروهای خط را ارسال کنید.`,{type:'presence_check',slot:sl,window_minutes:win});}if(alive)setDue({slot:sl,windowMinutes:win,day:now.day,key,expiredKey});return;}}catch(e){}};check();pollRef.current=setInterval(check,20000);return()=>{alive=false;clearInterval(pollRef.current);};},[user,due]);
useEffect(()=>{if(!user)return;let alive=true;const openFromNotification=async(raw={})=>{const data=notificationData(raw);if(data?.type!=='presence_check')return;const immediate=data.immediate===true||data.immediate==='true'||data.immediate===1||data.immediate==='1';let cfg=cfgRef.current||{};if(!cfgRef.current){try{cfg=await request('/my/presence-config',{auth:true,noStore:true});cfgRef.current=cfg}catch(e){cfg={}}}const now=tehranNow();const sl=data.slot||((cfg.slots||[])[0])||`${String(Math.floor(now.minutes/60)).padStart(2,'0')}:${String(now.minutes%60).padStart(2,'0')}`;const key=immediate?`presence_immediate_done:${now.day}:${data.request_id||Date.now()}`:`presence_done:${now.day}:${sl}`,expiredKey=`presence_expired:${now.day}:${sl}`;if(!immediate&&(await AsyncStorage.getItem(key)||await AsyncStorage.getItem(expiredKey)))return;if(alive)setDue({slot:sl,windowMinutes:Math.max(1,Number(data.window_minutes||cfg.window_minutes||1)),day:now.day,key,expiredKey,immediate});};
const handleResponse=r=>openFromNotification(r?.notification?.request?.content?.data||{}).catch(()=>{});const handleReceived=n=>openFromNotification(n?.request?.content?.data||{}).catch(()=>{});
const r1=Notifications.addNotificationReceivedListener(handleReceived);const r2=Notifications.addNotificationResponseReceivedListener(handleResponse);let appSub=null;try{appSub=AppState.addEventListener('change',state=>{if(state==='active')Notifications.getLastNotificationResponseAsync().then(r=>{if(r)handleResponse(r)}).catch(()=>{})})}catch(e){}
Notifications.getLastNotificationResponseAsync().then(r=>{if(r)handleResponse(r)}).catch(()=>{});
return()=>{alive=false;try{r1.remove()}catch(e){}try{r2.remove()}catch(e){}try{appSub?.remove()}catch(e){}};},[user]);
useEffect(()=>{const alarmOn=cfgRef.current?cfgRef.current.alarm!==false:true;if(due&&alarmOn)startPresenceAlarm().catch(()=>{});else stopPresenceAlarm().catch(()=>{});return()=>{stopPresenceAlarm().catch(()=>{})}},[due]);
if(!due)return null;const finish=async(success=true)=>{try{await stopPresenceAlarm()}catch(e){}if(success){try{await AsyncStorage.setItem(due.key,'1')}catch(e){}}else if(due.expiredKey&&!due.immediate){try{await AsyncStorage.setItem(due.expiredKey,'1')}catch(e){}}setDue(null);};
return <View style={s.overlay} pointerEvents="box-none"><View style={s.surface}><PresenceCheckModal slot={due.slot} windowMinutes={due.windowMinutes} onDone={()=>finish(true)} onExpire={()=>finish(false)} onStart={()=>stopPresenceAlarm().catch(()=>{})}/></View></View>;}
const s=StyleSheet.create({overlay:{...StyleSheet.absoluteFillObject,zIndex:100000,elevation:100000,backgroundColor:'#fff'},surface:{...StyleSheet.absoluteFillObject,width:'100%',height:'100%',minWidth:'100%',minHeight:'100%',backgroundColor:'#fff'}});
