import React, { useState, useRef, useEffect } from 'react';
import { faNum } from './num';
import { View, Text, TouchableOpacity, StyleSheet, Image, ScrollView } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as Location from 'expo-location';
import { captureRef } from 'react-native-view-shot';
import { C, FONT } from './theme';
import { fjDateTime } from './jdate';
import ActivityIndicator from './components/PulseLoadingIndicator';
import { getImageConfig, compressToDataUri } from './img';
import { getAppConfig } from './appconfig';

export default function VehiclesPhotoCapture({ onCapture, onCancel, station = null }) {
  const [perm, requestPerm] = useCameraPermissions(); const camRef=useRef(null), shotRef=useRef(null);
  const [busy,setBusy]=useState(false),[shot,setShot]=useState(null),[stamp,setStamp]=useState({date:'',coords:'',street:'',dist:''}),[coords,setCoords]=useState(null);
  useEffect(()=>{getAppConfig(true).catch(()=>{});if(perm&&!perm.granted)requestPerm();},[perm?.granted]);
  if(!perm)return <View style={s.center}><ActivityIndicator color={C.brand}/></View>;
  if(!perm.granted)return <View style={s.center}><Text style={s.hint}>برای گرفتن عکس، اجازهٔ دوربین لازم است.</Text><TouchableOpacity style={s.btn} onPress={requestPerm}><Text style={s.btnTxt}>اجازهٔ دوربین</Text></TouchableOpacity></View>;
  function haversine(a,b,c,d){const R=6371000,t=Math.PI/180,dl=(c-a)*t,do_=(d-b)*t,x=Math.sin(dl/2)**2+Math.cos(a*t)*Math.cos(c*t)*Math.sin(do_/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(x)));}
  async function snap(){if(!camRef.current||busy)return;setBusy(true);try{let lat=null,lng=null;try{const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Highest});lat=p.coords.latitude;lng=p.coords.longitude;}catch(e){}setCoords({lat,lng});let street='';if(lat!=null){try{const p=await Location.reverseGeocodeAsync({latitude:lat,longitude:lng});if(p?.[0])street=[p[0].street,p[0].name,p[0].district].filter(Boolean).slice(0,2).join('، ');}catch(e){}}let dist='';if(lat!=null&&station?.center_lat!=null&&station?.center_lng!=null){try{const d=haversine(lat,lng,+station.center_lat,+station.center_lng),edge=station.radius_m?Math.max(0,d-(+station.radius_m)):d;dist=`فاصله تا ایستگاه: ${faNum(Math.round(edge))} متر`;}catch(e){}}setStamp({date:fjDateTime(new Date()),coords:lat!=null?`${lat.toFixed(5)}, ${lng.toFixed(5)}`:'موقعیت نامشخص',street:street?('خیابان: '+street):'',dist});const p=await camRef.current.takePictureAsync({quality:getImageConfig().quality/100,exif:false,skipProcessing:false});if(!p?.uri)throw new Error('camera_empty_result');setShot(p.uri);}catch(e){}finally{setBusy(false);}}
  async function confirm(){if(!shot||busy)return;setBusy(true);try{const stamped=await captureRef(shotRef,{format:'jpg',quality:1});const data=await compressToDataUri(stamped,{maxW:getImageConfig().maxWidth,quality:getImageConfig().quality});if(!data)throw new Error('image_compression_failed');onCapture(data,coords);}catch(e){try{const data=await compressToDataUri(shot,{maxW:getImageConfig().maxWidth,quality:getImageConfig().quality});if(!data)throw e;onCapture(data,coords);}catch(err){onCapture(null,coords);}}finally{setBusy(false);}}
  if(shot)return <View style={s.previewWrap}><ScrollView persistentScrollbar={true} style={s.previewScroll} contentContainerStyle={s.previewContent} showsVerticalScrollIndicator={false} bounces={false}><Text style={s.title}>تأیید عکس خودروهای خط</Text><View ref={shotRef} collapsable={false} style={s.shotBox}><Image source={{uri:shot}} style={s.shotImg} resizeMode="contain"/><View style={s.stampBox}><Text style={s.stampTxt}>{stamp.date}</Text><Text style={s.stampTxt}>📍 {stamp.coords}</Text>{stamp.street?<Text style={s.stampTxt}>{stamp.street}</Text>:null}{stamp.dist?<Text style={s.stampTxt}>{stamp.dist}</Text>:null}<Text style={s.stampBrand}>سامانه خطیار</Text></View></View><Text style={s.previewNote}>تصویر و اطلاعات موقعیت را بررسی کنید و سپس تأیید و ارسال را بزنید.</Text><View style={s.rowBtns}><TouchableOpacity style={[s.btn,s.outline]} onPress={()=>setShot(null)}><Text style={[s.btnTxt,{color:C.brand}]}>دوباره</Text></TouchableOpacity><TouchableOpacity style={s.btn} onPress={confirm} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.btnTxt}>تأیید و ارسال</Text>}</TouchableOpacity></View></ScrollView></View>;
  return <View style={s.camWrap}><CameraView ref={camRef} style={s.cam} facing="back" mode="picture" active/><View style={s.bottom}><Text style={s.hint}>با دوربین پشت، از خودروهای حاضر در خط عکس بگیرید. تاریخ، ساعت و موقعیت به‌صورت خودکار روی عکس درج می‌شود.</Text><TouchableOpacity style={s.shutter} onPress={snap} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<View style={s.shutterInner/>}</TouchableOpacity>{onCancel?<TouchableOpacity onPress={onCancel}><Text style={s.cancel}>انصراف</Text></TouchableOpacity>:null}<Text style={s.cameraOnly}>ثبت تصویر فقط با دوربین پشت گوشی انجام می‌شود و انتخاب از گالری در این مرحله وجود ندارد.</Text></View></View>;
}
const s=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:'#000'},camWrap:{flex:1,backgroundColor:'#000'},cam:{flex:1},bottom:{position:'absolute',bottom:0,left:0,right:0,padding:18,alignItems:'center',backgroundColor:'rgba(0,0,0,0.45)'},hint:{color:'#fff',fontFamily:FONT.regular,fontSize:13,marginBottom:12,textAlign:'center',lineHeight:21},shutter:{width:72,height:72,borderRadius:36,borderWidth:4,borderColor:'#fff',alignItems:'center',justifyContent:'center'},shutterInner:{width:54,height:54,borderRadius:27,backgroundColor:'#fff'},cancel:{color:'#fff',marginTop:12,fontFamily:FONT.regular,fontSize:13},cameraOnly:{color:'rgba(255,255,255,0.72)',fontFamily:FONT.regular,fontSize:11,textAlign:'center',marginTop:8},previewWrap:{flex:1,width:'100%',minHeight:0,backgroundColor:C.paper},previewScroll:{flex:1,width:'100%'},previewContent:{width:'100%',alignItems:'center',paddingHorizontal:16,paddingTop:12,paddingBottom:24},title:{fontFamily:FONT.bold,fontSize:18,color:C.ink,marginVertical:10,textAlign:'center'},shotBox:{width:'100%',aspectRatio:4/3,borderRadius:14,overflow:'hidden',backgroundColor:'#000',alignItems:'center',justifyContent:'center'},shotImg:{width:'100%',height:'100%'},stampBox:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'rgba(0,0,0,0.5)',padding:8},stampTxt:{color:'#fff',fontFamily:FONT.bold,fontSize:12,textAlign:'right'},stampBrand:{color:C.taxi,fontFamily:FONT.bold,fontSize:10,textAlign:'right',marginTop:2},previewNote:{fontFamily:FONT.regular,color:C.muted,fontSize:12,textAlign:'center',lineHeight:20,marginTop:10},rowBtns:{flexDirection:'row-reverse',gap:12,marginTop:14,width:'100%',justifyContent:'center'},btn:{flex:1,backgroundColor:C.brand,borderRadius:12,paddingVertical:12,paddingHorizontal:18,alignItems:'center',justifyContent:'center'},outline:{backgroundColor:'#fff',borderWidth:1,borderColor:C.brand},btnTxt:{color:'#fff',fontFamily:FONT.bold,fontSize:14}});
