import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import CompanyRequestsScreen from'./CompanyRequestsScreen';
import{request}from'../api';
import{C,FONT}from'../theme';
import ActivityIndicator from'../components/PulseLoadingIndicator';
const fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const en=v=>String(v??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
export default function CompanyRequestsDriverGateScreen(){
 const[driver,setDriver]=useState(null),[candidate,setCandidate]=useState(null),[nid,setNid]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!driver)return;const original=global.fetch;global.fetch=async(input,init={})=>{const url=typeof input==='string'?input:String(input?.url||'');const method=String(init?.method||'GET').toUpperCase();if(method==='POST'&&/\/company-request\/create(?:\?|$)/.test(url)&&init?.body){try{const body=JSON.parse(String(init.body));body.driver_id=Number(driver.id||0)||body.driver_id;body.driver_name=driver.name||driver.full_name||body.driver_name;body.driver_national_id=String(driver.national_id||driver.national_code||body.driver_national_id||'');body.driver_mobile=String(driver.mobile||driver.phone||body.driver_mobile||'');body.driver_vehicle_id=driver.vehicle_id?Number(driver.vehicle_id):body.driver_vehicle_id;body.driver_vehicle_plate=driver.vehicles?.[0]?.plate||driver.plate||body.driver_vehicle_plate;init={...init,body:JSON.stringify(body)}}catch(_){}}const res=await original(input,init);if(method==='POST'&&/\/company-request\/create(?:\?|$)/.test(url)){try{const clone=res.clone(),j=await clone.json();if(j?.id)original('/api/company-request-support.php?op=notify-new',{method:'POST',headers:{'content-type':'application/json',...(init.headers||{})},body:JSON.stringify({request_id:j.id})}).catch(()=>{})}catch(_){}}return res};return()=>{global.fetch=original}},[driver]);
 async function find(){const n=en(nid).replace(/\D/g,'');if(n.length!==10){Alert.alert('کد ملی','کد ملی راننده را ۱۰ رقم وارد کنید.');return}setBusy(true);setCandidate(null);try{const r=await request('/company-request-support.php?op=driver-search&national_id='+encodeURIComponent(n),{noStore:true});if(!r?.driver)throw Error('راننده یافت نشد');setCandidate(r.driver)}catch(e){Alert.alert('راننده یافت نشد',e.message||'راننده‌ای با این کد ملی پیدا نشد.')}finally{setBusy(false)}}
 if(driver)return <CompanyRequestsScreen/>;
 return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.card}><Text style={s.title}>ارسال مدارک برای شرکت</Text><Text style={s.step}>مرحله ۱ — انتخاب راننده</Text><Text style={s.muted}>کد ملی راننده را وارد کنید، مشخصات فرد را از بانک اطلاعاتی بررسی کنید و سپس همان راننده را انتخاب کنید. اطلاعات انتخاب‌شده به‌صورت خودکار همراه درخواست ارسال می‌شود.</Text></View><View style={s.card}><Text style={s.label}>کد ملی راننده</Text><TextInput value={nid} onChangeText={setNid} keyboardType="numeric" maxLength={10} placeholder="مثلاً ۰۰۱۲۳۴۵۶۷۸" placeholderTextColor={C.muted} style={s.input}/><TouchableOpacity style={s.btn} onPress={find} disabled={busy}>{busy?<ActivityIndicator size={32}/>:<Text style={s.btnTxt}>جستجوی راننده</Text>}</TouchableOpacity></View>{candidate&&<View style={s.card}><Text style={s.step}>راننده یافت شد</Text><Text style={s.driverName}>{candidate.name||'—'}</Text><Text style={s.info}>کد ملی: {fa(candidate.national_id||nid)}</Text>{candidate.mobile?<Text style={s.info}>موبایل: {fa(candidate.mobile)}</Text>:null}{candidate.vehicles?.length?<Text style={s.info}>خودرو: {candidate.vehicles.map(v=>v.plate).filter(Boolean).join('، ')}</Text>:null}<TouchableOpacity style={s.selectBtn} onPress={()=>setDriver(candidate)}><Text style={s.btnTxt}>✓ انتخاب این راننده و ادامه</Text></TouchableOpacity></View>}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:40},card:{backgroundColor:C.card||'#fff',borderRadius:16,padding:16,marginBottom:14,borderWidth:1,borderColor:C.line||'#e5e7eb'},title:{fontFamily:FONT.bold,fontSize:20,color:C.text,marginBottom:8,textAlign:'right'},step:{fontFamily:FONT.bold,fontSize:15,color:C.brand,marginBottom:10,textAlign:'right'},muted:{fontFamily:FONT.regular,fontSize:13,color:C.muted,lineHeight:22,textAlign:'right'},label:{fontFamily:FONT.bold,fontSize:13,color:C.text,marginBottom:7,textAlign:'right'},input:{fontFamily:FONT.regular,fontSize:17,color:C.text,borderWidth:1,borderColor:C.line||'#ddd',borderRadius:12,paddingHorizontal:14,paddingVertical:12,textAlign:'center',letterSpacing:2,marginBottom:12},btn:{backgroundColor:C.brand,borderRadius:12,minHeight:50,alignItems:'center',justifyContent:'center'},selectBtn:{backgroundColor:C.brand,borderRadius:12,minHeight:50,alignItems:'center',justifyContent:'center',marginTop:14},btnTxt:{fontFamily:FONT.bold,color:'#fff',fontSize:15},driverName:{fontFamily:FONT.bold,fontSize:21,color:C.text,textAlign:'right',marginBottom:8},info:{fontFamily:FONT.regular,fontSize:14,color:C.text,textAlign:'right',marginTop:5}});
