import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import CompanyRequestsScreen from'./CompanyRequestsScreen';
import{request}from'../api';
import{C,FONT}from'../theme';
import ActivityIndicator from'../components/PulseLoadingIndicator';
const fa=n=>String(n??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const en=v=>String(v??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
export default function CompanyRequestsDriverGateScreen(){
 const[driver,setDriver]=useState(null),[nid,setNid]=useState(''),[busy,setBusy]=useState(false),[boot,setBoot]=useState(true);
 useEffect(()=>{let alive=true;request('/company-request-support.php?op=driver-search&national_id=0000000000',{noStore:true}).catch(()=>{}).finally(()=>alive&&setBoot(false));return()=>{alive=false}},[]);
 useEffect(()=>{if(!driver)return;const original=global.fetch;global.fetch=async(input,init={})=>{const url=typeof input==='string'?input:String(input?.url||'');const method=String(init?.method||'GET').toUpperCase();if(method==='POST'&&/\/company-request\/create(?:\?|$)/.test(url)&&init?.body){try{const body=JSON.parse(String(init.body));if(!body.driver_id){body.driver_id=driver.id;body.driver_name=driver.name;body.driver_national_id=driver.national_id;init={...init,body:JSON.stringify(body)};}}catch(_){}}const res=await original(input,init);if(method==='POST'&&/\/company-request\/create(?:\?|$)/.test(url)){try{const clone=res.clone();const j=await clone.json();if(j?.id){original('/api/company-request-support.php?op=notify-new',{method:'POST',headers:{'content-type':'application/json',...(init.headers||{})},body:JSON.stringify({request_id:j.id})}).catch(()=>{});}}catch(_){}}return res};return()=>{global.fetch=original};},[driver]);
 async function find(){const n=en(nid).replace(/\D/g,'');if(n.length!==10){Alert.alert('کد ملی','کد ملی راننده را ۱۰ رقم وارد کنید.');return}setBusy(true);try{const r=await request('/company-request-support.php?op=driver-search&national_id='+encodeURIComponent(n),{noStore:true});if(!r?.driver)throw Error('راننده یافت نشد');setDriver(r.driver)}catch(e){setDriver(null);Alert.alert('راننده یافت نشد',e.message||'راننده‌ای با این کد ملی پیدا نشد.')}finally{setBusy(false)}}
 if(driver)return <CompanyRequestsScreen/>;
 return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.card}><Text style={s.title}>ارسال مدارک برای شرکت</Text><Text style={s.step}>مرحله ۱ — انتخاب راننده</Text><Text style={s.muted}>ابتدا کد ملی راننده را وارد کنید. پس از یافتن راننده، مشخصات او را بررسی و انتخاب کنید؛ سپس مراحل ارسال مدارک نمایش داده می‌شود.</Text></View><View style={s.card}><Text style={s.label}>کد ملی راننده</Text><TextInput value={nid} onChangeText={setNid} keyboardType="numeric" maxLength={10} placeholder="مثلاً ۰۰۱۲۳۴۵۶۷۸" placeholderTextColor={C.muted} style={s.input}/><TouchableOpacity style={s.btn} onPress={find} disabled={busy}>{busy?<ActivityIndicator size={32}/>:<Text style={s.btnTxt}>جستجوی راننده</Text>}</TouchableOpacity></View>{boot&&<Text style={s.muted}>در حال آماده‌سازی…</Text>}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:40},card:{backgroundColor:C.card||'#fff',borderRadius:16,padding:16,marginBottom:14,borderWidth:1,borderColor:C.line||'#e5e7eb'},title:{fontFamily:FONT.bold,fontSize:20,color:C.text,marginBottom:8,textAlign:'right'},step:{fontFamily:FONT.bold,fontSize:15,color:C.brand,marginBottom:10,textAlign:'right'},muted:{fontFamily:FONT.regular,fontSize:13,color:C.muted,lineHeight:22,textAlign:'right'},label:{fontFamily:FONT.bold,fontSize:13,color:C.text,marginBottom:7,textAlign:'right'},input:{fontFamily:FONT.regular,fontSize:17,color:C.text,borderWidth:1,borderColor:C.line||'#ddd',borderRadius:12,paddingHorizontal:14,paddingVertical:12,textAlign:'center',letterSpacing:2,marginBottom:12},btn:{backgroundColor:C.brand,borderRadius:12,minHeight:50,alignItems:'center',justifyContent:'center'},btnTxt:{fontFamily:FONT.bold,color:'#fff',fontSize:15}});
