import React, { useEffect, useLayoutEffect, useState } from 'react';
import { DrawerActions } from '@react-navigation/native';
import { Alert, Image, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View, useWindowDimensions } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Device from 'expo-device';
import { Platform } from 'react-native';
import { useAuth } from '../auth';
import { request, swr, imageSource, flushQueuedRequests } from '../api';
import { registerPush } from '../push';
import { faNum } from '../num';
import { C, FONT } from '../theme';
import { todayFaLong } from '../jdate';
import FieldStatusBanner from '../components/FieldStatusBanner';
import { useRadio } from '../radio/RadioContext';

function RadioHeaderToggle({ navigation }) {
  const { enabled, busy } = useRadio();
  return <TouchableOpacity onPress={() => navigation.navigate('Radio')} style={s.headerIcon} hitSlop={6}><Text style={s.headerIconText}>{enabled ? (busy ? '📻' : '📡') : '📻̸'}</Text></TouchableOpacity>;
}

const MENU_TABS = [['all', 'همه'], ['general', 'عمومی'], ['field', 'عملیات میدانی'], ['work', 'اداری'], ['messages', 'ارتباطات'], ['personal', 'شخصی']];
const ICON3D = {
  search: require('../../assets/icons3d/search-taxi.png'), present: require('../../assets/icons3d/present-people.png'), sendReport: require('../../assets/icons3d/send-report-plane.png'), checkin: require('../../assets/icons3d/checkin-fingerprint.png'), requests: require('../../assets/icons3d/request-box.png'), approvals: require('../../assets/icons3d/approve-stamp.png'), performance: require('../../assets/icons3d/my-performance.png'), salary: require('../../assets/icons3d/salary-money.png'), company: require('../../assets/icons3d/company-send.png'), subscription: require('../../assets/icons3d/subscription-card.png'), sms: require('../../assets/icons3d/sms-bubble.png'), bot: require('../../assets/icons3d/bot-message.png'), sent: require('../../assets/icons3d/sent-folder.png'), forms: require('../../assets/icons3d/form-document.png'), cultural: require('../../assets/icons3d/cultural-lamp.png'), welfare: require('../../assets/icons3d/welfare-heart.png'), official: require('../../assets/icons3d/official-presence.png'), activity: require('../../assets/icons3d/activity-wave.png'), insurance: require('../../assets/icons3d/insurance-shield.png'), invalid: require('../../assets/icons3d/invalid-warning.png'), operation: require('../../assets/icons3d/operation-tools.png'), team: require('../../assets/icons3d/team-people.png'), temporary: require('../../assets/icons3d/temp-driver.png'), outage: require('../../assets/icons3d/outage-bolt.png')
};
const MENU = [
  { glyph: '📻', t: 'بی‌سیم', r: 'Radio', bg: '#e8f6f0', always: true }, { icon3d: ICON3D.search, t: 'جستجوی تاکسی و تاکسیران', r: 'Search', bg: '#e8f3ff' }, { icon3d: ICON3D.present, t: 'حاضرین در خط', r: 'PresentList', bg: '#e9f7f0' }, { icon3d: ICON3D.sendReport, t: 'ارسال گزارش', r: 'Reports', bg: '#fff3e6' }, { icon3d: ICON3D.checkin, t: 'ثبت حضور من', r: 'CheckIn', bg: '#e7f3ee' }, { icon3d: ICON3D.requests, t: 'درخواست‌ها', r: 'Requests', bg: '#eef2fb' }, { icon3d: ICON3D.approvals, t: 'تأیید درخواست‌ها', r: 'RequestInbox', bg: '#fff3e6' }, { icon3d: ICON3D.performance, t: 'کارکرد من', r: 'WorkSummary', bg: '#f0eefb' }, { icon3d: ICON3D.salary, t: 'فیش حقوقی', r: 'SalarySlips', bg: '#fff7e6' }, { icon3d: ICON3D.company, t: 'ارسال برای شرکت', r: 'CompanyRequests', bg: '#e8f7f4', always: true }, { icon3d: ICON3D.subscription, t: 'اشتراک برنامه', r: 'Subscription', bg: '#fff4d6', always: true }, { icon3d: ICON3D.sms, t: 'ارسال پیامک', r: 'Sms', bg: '#e7f3ee' }, { icon3d: ICON3D.bot, t: 'ارسال پیام در ربات‌ها', r: 'BotMessages', bg: '#eef7ff' }, { icon3d: ICON3D.sent, t: 'پیامک‌های ارسالی من', r: 'MySms', bg: '#eef4ff' }, { icon3d: ICON3D.forms, t: 'تکمیل فرم‌ها', r: 'Forms', bg: '#f0ecff' }, { icon3d: ICON3D.cultural, t: 'فعالیت‌های فرهنگی', r: 'Cultural', bg: '#fdeef7', needs: 'cultural' }, { icon3d: ICON3D.welfare, t: 'ثبت رفاهیات', r: 'Welfare', bg: '#fef3f8', needs: 'welfare' }, { icon3d: ICON3D.official, t: 'حضور مسئولین در خط', r: 'OfficialPresence', bg: '#eafaf3' }, { icon3d: ICON3D.requests, t: 'اقلام تحویلی', r: 'Inventory', bg: '#f0ecff' }, { icon3d: ICON3D.activity, t: 'مأموریت روزانه من', r: 'MyDailyMission', bg: '#fff4d8', always: true }, { icon3d: ICON3D.activity, t: 'برنامه بازدید و پوشش خط', r: 'LineVisitProgram', bg: '#e8f3ff', always: true }, { glyph: '📍', t: 'ثبت موقعیت و تصویر خطوط', r: 'StationCapture', bg: '#e8f3ff' }, { glyph: '🗺️', t: 'ایستگاه‌های ثبت‌شده من', r: 'MyStations', bg: '#eafaf3' }, { icon3d: ICON3D.activity, t: 'داشبورد و امتیاز من', r: 'RoleDashboard', bg: '#eafaf3', always: true }, { icon3d: ICON3D.activity, t: 'رتبه‌بندی و نشان‌ها', r: 'Leaderboard', bg: '#fff4d8', always: true }, { icon3d: ICON3D.activity, t: 'پرکار/کم‌کار هر خط', r: 'ActivityReport', bg: '#eef4ff' }, { icon3d: ICON3D.insurance, t: 'بیمه و معاینه خودروها', r: 'ExpInsurance', bg: '#e9f7f0' }, { icon3d: ICON3D.invalid, t: 'افراد فاقد اعتبار', r: 'ExpTaxi', bg: '#fdeef0' }, { icon3d: ICON3D.operation, t: 'خودرو فاقد بهره‌برداری', r: 'ExpOplic', bg: '#fff7e0' }, { icon3d: ICON3D.team, t: 'زیرمجموعهٔ من', r: 'TeamReport', bg: '#f0ecff' }, { icon3d: ICON3D.temporary, t: 'رانندگان موقت خطوط ویژه', r: 'TempDrivers', bg: '#eef7ff', needs: 'temp' }, { icon3d: ICON3D.outage, t: 'اعلام قطع سیستم نوبت‌دهی', r: 'Outage', bg: '#fdeef0' }
];
const categoryOf = (r) => ['CheckIn', 'OfficialPresence', 'LineVisitProgram', 'StationCapture', 'MyStations', 'RoleDashboard', 'Leaderboard', 'PresentList', 'ActivityReport', 'ExpInsurance', 'ExpTaxi', 'ExpOplic'].includes(r) ? 'field' : ['Reports', 'Requests', 'RequestInbox', 'Forms', 'CompanyRequests', 'Outage'].includes(r) ? 'work' : ['Sms', 'BotMessages', 'MySms', 'Messages', 'Notifications'].includes(r) ? 'messages' : ['WorkSummary', 'SalarySlips', 'Subscription', 'Welfare', 'Cultural'].includes(r) ? 'personal' : 'general';

export default function DashboardScreen({ navigation }) {
  const { user } = useAuth();
  const { width } = useWindowDimensions();
  const cols = width >= 760 ? 4 : width >= 540 ? 3 : 2;
  const cardW = `${100 / cols - 2}%`;
  const [stats, setStats] = useState({ today: 0, checklists: 0, notices: 0, reports: 0, unread: 0 });
  const [myStats, setMyStats] = useState({ drivers: 0, vehicles: 0 });
  const [allowed, setAllowed] = useState(null);
  const [access, setAccess] = useState({ welfare: false, cultural: false, temp: false });
  const [myPhoto, setMyPhoto] = useState(user?.photo || null);
  const [menuTab, setMenuTab] = useState('all');
  const [syncing, setSyncing] = useState(false);
  const [syncDetail, setSyncDetail] = useState('');
  const [pop, setPop] = useState(null);

  const starsFor = (role) => { if (!role) return ''; const r = String(role); if (r.includes('سربازرس')) return '★★★★'; if (r.includes('بازرس')) return '★★'; if (r.includes('ناظر خط') || r.includes('اپراتور')) return '★'; return ''; };
  const stars = user?.rank_stars !== null && user?.rank_stars !== undefined ? '★'.repeat(Math.max(0, Math.min(5, Number(user.rank_stars) || 0))) : starsFor(user?.role);

  useEffect(() => {
    if (!user) return;
    request('/me/full-profile').then((p) => { if (p?.photo) setMyPhoto(p.photo); }).catch(() => {});
    const isAdmin = !!(user.is_admin || (user.level || 0) >= 3);
    request('/my/app-config').then((c) => setAccess({ welfare: isAdmin || !!c?.can_welfare, cultural: isAdmin || !!c?.can_cultural, temp: isAdmin || !!c?.can_manage_temp_drivers })).catch(() => setAccess({ welfare: isAdmin, cultural: isAdmin, temp: isAdmin }));
  }, [user?.id]);

  useEffect(() => {
    if (!user) return;
    request('/my/device-info', { method: 'POST', body: { device_model: [Device.manufacturer, Device.modelName].filter(Boolean).join(' ') || Device.deviceName || '', android_version: Platform.OS === 'android' ? `Android ${Device.osVersion || ''}` : Device.osVersion || '', app_version: require('expo-constants').default?.expoConfig?.version || '' } }).catch(() => {});
  }, [user?.id]);

  const load = () => { swr('/my/dashboard', setStats); swr('/my/stats', setMyStats); swr('/my/app-items', (r) => setAllowed(Array.isArray(r?.items) ? r.items : null)); };
  useEffect(() => { flushQueuedRequests(); registerPush(); load(); const unsub = navigation.addListener('focus', load); return unsub; }, [navigation]);

  const manualSync = async () => {
    if (syncing) return;
    setSyncing(true);
    try { setSyncDetail('پاک‌سازی کش و ارسال داده‌های آفلاین…'); const keys = await AsyncStorage.getAllKeys(); const cacheKeys = keys.filter((k) => String(k).startsWith('cache:')); if (cacheKeys.length) await AsyncStorage.multiRemove(cacheKeys); const n = await flushQueuedRequests().catch(() => 0); load(); Alert.alert('بروزرسانی شد', n > 0 ? `${n} مورد آفلاین ارسال شد.` : 'کش و اطلاعات برنامه بروزرسانی شد.'); } catch (e) { Alert.alert('خطا', 'بروزرسانی کش و اطلاعات ناموفق بود.'); } finally { setSyncDetail(''); setSyncing(false); }
  };

  useLayoutEffect(() => {
    navigation.setOptions({ headerShown: true, headerBackVisible: false, headerLeft: () => <View style={s.headerBar}><View style={s.headerActions}><TouchableOpacity onPress={manualSync} disabled={syncing} style={s.headerIcon} hitSlop={8}><Text style={s.headerIconText}>{syncing ? '⏳' : '↻'}</Text></TouchableOpacity><RadioHeaderToggle navigation={navigation} /><TouchableOpacity onPress={() => navigation.navigate('Notifications')} style={s.headerIcon} hitSlop={8}><View style={s.bellWrap}><Text style={s.headerIconText}>🔔</Text>{stats.unread > 0 ? <View style={s.unreadBadge}><Text style={s.unreadBadgeText}>{stats.unread > 99 ? '+۹۹' : faNum(Number(stats.unread))}</Text></View> : null}</View></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate('InboxReports')} style={s.headerIcon} hitSlop={8}><Text style={s.headerIconText}>📥</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate('Messages')} style={s.headerIcon} hitSlop={8}><Text style={s.headerIconText}>💬</Text></TouchableOpacity></View><TouchableOpacity onPress={() => navigation.dispatch(DrawerActions.openDrawer())} style={s.headerMenuButton} hitSlop={8}><Text style={s.headerMenuText}>☰</Text></TouchableOpacity></View>, headerRight: undefined });
  }, [navigation, stats.unread, syncing]);

  const canShow = (m) => { if (m.r === 'Help') return false; if (m.always) return true; if (m.needs && !access[m.needs]) return false; if (allowed === null) return true; if (m.r === 'StationCapture' || m.r === 'MyStations') return ['StationCapture', 'MyStations', 'LineLocation'].some((k) => allowed.includes(k)); return allowed.includes(m.r); };
  const visibleMenu = MENU.filter((m) => (m.r !== 'Sms' && m.r !== 'MySms' && m.r !== 'BotMessages') || !!user?.can_send_sms || m.r === 'BotMessages').filter(canShow).filter((m) => menuTab === 'all' || categoryOf(m.r) === menuTab);
  const KPIS = [['رانندگان خطوط شما', myStats.drivers], ['خودروهای خطوط شما', myStats.vehicles], ['حضور امروز', stats.today], ['چک‌لیست این ماه', stats.checklists]];

  return <ScrollView style={s.page} contentContainerStyle={s.pageContent}><View style={s.rtlRoot}>{syncing && syncDetail ? <View style={s.syncBanner}><Text style={s.syncText}>{syncDetail}</Text></View> : null}<View style={s.top}><View style={s.topInfo}><Text style={s.hi}>روز بخیر،</Text><View style={s.nameRow}>{stars ? <Text style={s.stars}>{stars}</Text> : null}<Text style={s.nm}>{user?.name || '—'}</Text></View><Text style={s.todayTxt}>{todayFaLong()}</Text>{user?.role ? <View style={s.roleChip}><Text style={s.roleTxt}>{user.role}</Text></View> : null}</View>{myPhoto ? <Image source={imageSource(myPhoto)} style={s.avatar} /> : <View style={s.avatarPh}><Text style={s.avatarTxt}>{(user?.name || '؟')[0]}</Text></View>}</View><View style={s.kpis}>{KPIS.map(([l, n], i) => <View style={[s.kpi, { width: cardW }]} key={i}><Text style={s.kpiN}>{faNum(Number(n))}</Text><Text style={s.kpiL}>{l}</Text></View>)}</View><FieldStatusBanner /><Text style={s.sectionTitle}>دسترسی سریع</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.menuTabs}>{MENU_TABS.map(([k, l]) => <TouchableOpacity key={k} style={[s.menuTab, menuTab === k && s.menuTabOn]} onPress={() => setMenuTab(k)}><Text style={[s.menuTabTxt, menuTab === k && s.menuTabTxtOn]}>{l}</Text></TouchableOpacity>)}</ScrollView><View style={s.grid}>{visibleMenu.map((m, i) => <TouchableOpacity key={i} style={[s.card, { width: cardW }]} activeOpacity={0.85} onPress={() => navigation.navigate(m.r)}><View style={[s.iconWrap, { backgroundColor: m.bg }]}>{m.glyph ? <Text style={s.glyph}>{m.glyph}</Text> : <Image source={m.icon3d} style={s.icon3d} resizeMode="contain" />}</View><View style={s.cardTxtWrap}><Text style={s.cardTxt} numberOfLines={2}>{m.t}</Text></View></TouchableOpacity>)}</View><Modal visible={!!pop} transparent animationType="fade" onRequestClose={() => setPop(null)}><TouchableOpacity style={s.popBg} activeOpacity={1} onPress={() => setPop(null)}><View style={s.popCard}><TouchableOpacity style={s.popBtn} onPress={() => setPop(null)}><Text style={s.popBtnTxt}>بستن</Text></TouchableOpacity></View></TouchableOpacity></Modal></View></ScrollView>;
}

const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: C.paper }, pageContent: { paddingBottom: 24 }, rtlRoot: { width: '100%', alignSelf: 'stretch' },
  syncBanner: { backgroundColor: '#1b3a6b', padding: 10 }, syncText: { color: '#fff', fontFamily: FONT.regular, fontSize: 12, textAlign: 'right', writingDirection: 'rtl' },
  headerBar: { height: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', width: 214 }, headerActions: { height: 44, flexDirection: 'row', alignItems: 'center' }, headerIcon: { width: 34, height: 44, alignItems: 'center', justifyContent: 'center' }, headerIconText: { color: '#fff', fontSize: 18, textAlign: 'center' }, headerMenuButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, headerMenuText: { color: '#fff', fontSize: 24, textAlign: 'center' },
  bellWrap: { width: 34, height: 40, alignItems: 'center', justifyContent: 'center', position: 'relative' }, unreadBadge: { position: 'absolute', top: -2, right: -3, minWidth: 19, height: 19, paddingHorizontal: 4, borderRadius: 10, backgroundColor: '#e53935', borderWidth: 2, borderColor: C.brand, alignItems: 'center', justifyContent: 'center' }, unreadBadgeText: { color: '#fff', fontFamily: FONT.bold, fontSize: 8, lineHeight: 10, textAlign: 'center' },
  top: { backgroundColor: C.brand, padding: 20, paddingTop: 28, paddingBottom: 22, borderBottomLeftRadius: 22, borderBottomRightRadius: 22, flexDirection: 'row-reverse', alignItems: 'center' }, topInfo: { flex: 1, minWidth: 0, alignSelf: 'stretch', alignItems: 'flex-end' }, hi: { width: '100%', color: '#fff', opacity: 0.85, fontFamily: FONT.regular, textAlign: 'right', writingDirection: 'rtl', fontSize: 13 }, nameRow: { width: '100%', flexDirection: 'row-reverse', alignItems: 'center' }, nm: { flex: 1, color: '#fff', fontFamily: FONT.bold, fontSize: 19, textAlign: 'right', writingDirection: 'rtl' }, stars: { color: '#ffd24a', fontSize: 15, textAlign: 'right', writingDirection: 'rtl', marginLeft: 6 }, todayTxt: { width: '100%', color: '#fff', opacity: 0.9, fontFamily: FONT.regular, fontSize: 12, textAlign: 'right', writingDirection: 'rtl', marginTop: 4 }, avatar: { width: 74, height: 74, borderRadius: 37, borderWidth: 2, borderColor: 'rgba(255,255,255,.6)', marginLeft: 12 }, avatarPh: { width: 74, height: 74, borderRadius: 37, backgroundColor: 'rgba(255,255,255,.25)', alignItems: 'center', justifyContent: 'center', marginLeft: 12 }, avatarTxt: { color: '#fff', fontFamily: FONT.bold, fontSize: 28 }, roleChip: { alignSelf: 'flex-end', backgroundColor: 'rgba(255,255,255,.18)', borderRadius: 8, paddingVertical: 3, paddingHorizontal: 10, marginTop: 8 }, roleTxt: { color: '#fff', fontFamily: FONT.bold, fontSize: 12, textAlign: 'right', writingDirection: 'rtl' },
  kpis: { flexDirection: 'row-reverse', flexWrap: 'wrap', paddingHorizontal: 12, paddingTop: 14 }, kpi: { backgroundColor: '#fff', borderColor: C.line, borderWidth: 1, borderRadius: 16, padding: 14, marginLeft: 5, marginRight: 5, marginBottom: 10 }, kpiN: { fontFamily: FONT.bold, fontSize: 22, color: C.brand, textAlign: 'right', writingDirection: 'rtl' }, kpiL: { fontFamily: FONT.regular, fontSize: 12, color: C.muted, textAlign: 'right', writingDirection: 'rtl', marginTop: 2 },
  sectionTitle: { fontFamily: FONT.bold, color: C.ink, fontSize: 15, textAlign: 'right', writingDirection: 'rtl', marginHorizontal: 16, marginTop: 18, marginBottom: 8 }, menuTabs: { paddingHorizontal: 12, paddingBottom: 10, flexDirection: 'row-reverse' }, menuTab: { paddingVertical: 8, paddingHorizontal: 14, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: C.line, marginLeft: 4, marginRight: 4 }, menuTabOn: { backgroundColor: C.brand, borderColor: C.brand }, menuTabTxt: { fontFamily: FONT.bold, color: C.muted, fontSize: 12, textAlign: 'center', writingDirection: 'rtl' }, menuTabTxtOn: { color: '#fff' },
  grid: { flexDirection: 'row-reverse', flexWrap: 'wrap', paddingHorizontal: 12 }, card: { backgroundColor: '#fff', borderColor: C.line, borderWidth: 1, borderRadius: 16, padding: 14, marginLeft: 5, marginRight: 5, marginBottom: 10 }, iconWrap: { width: 44, height: 44, borderRadius: 13, alignSelf: 'flex-end', alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, icon3d: { width: 46, height: 46 }, glyph: { fontSize: 30, textAlign: 'center' }, cardTxtWrap: { width: '100%', alignItems: 'flex-end' }, cardTxt: { width: '100%', fontFamily: FONT.bold, color: C.ink, textAlign: 'right', writingDirection: 'rtl', fontSize: 13, lineHeight: 20 },
  popBg: { flex: 1, backgroundColor: 'rgba(11,27,46,.55)', alignItems: 'center', justifyContent: 'center', padding: 24 }, popCard: { backgroundColor: '#fff', borderRadius: 18, padding: 20, width: '100%', maxWidth: 360 }, popBtn: { backgroundColor: C.brand, borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginTop: 16 }, popBtnTxt: { color: '#fff', fontFamily: FONT.bold, fontSize: 14, textAlign: 'center', writingDirection: 'rtl' }
});
