import React from 'react';
import {ScrollView,View,Text,TouchableOpacity,StyleSheet} from 'react-native';
import {C,FONT} from '../theme';

const sections=[
['شروع کار',['پس از ورود، داشبورد بر اساس نقش و سطح دسترسی شما نمایش داده می‌شود.','در شروع برنامه اطلاعات کش و پیکربندی تازه می‌شود و سپس کنترل‌های امنیتی مرحله‌ای بررسی می‌شوند.']],
['داشبورد',['کارت‌های آماری تعداد رانندگان، خودروها، حضور امروز و چک‌لیست‌های ماه را نشان می‌دهند.','همگام‌سازی اطلاعات آنلاین را تازه و صف آفلاین را پس از اتصال ارسال می‌کند.']],
['عملیات میدانی',['ثبت حضور من برای حضور روزانه است.','حاضرین در خط وضعیت افراد حاضر را نشان می‌دهد.','مأموریت روزانه و برنامه بازدید و پوشش خط برای عملیات میدانی، GPS، تصویر و پوشش استفاده می‌شوند.','ثبت موقعیت و تصویر خطوط برای ثبت موقعیت دقیق ایستگاه و تصاویر محل و تابلوهاست.','ایستگاه‌های ثبت‌شده من سوابق ثبت‌های شما را نمایش می‌دهد.']],
['گزارش و ارتباطات',['ارسال گزارش، فرم‌ها، درخواست‌ها، تأیید درخواست‌ها و ارسال برای شرکت برای عملیات اداری هستند.','ارسال پیامک، پیام‌های ارسالی، ربات‌ها، پیام‌ها و اعلان‌ها برای ارتباطات سامانه هستند.']],
['حساب کاربری',['ویرایش اطلاعات، فیش‌های حقوقی، کارکرد، اشتراک، رفاهیات و فعالیت‌های فرهنگی در حساب کاربری قرار دارند.','تنظیمات نقشه، اعلان، قفل برنامه و تغییر رمز از منوی حساب قابل دسترسی‌اند.']],
['امضای پرسنلی',['در ویرایش اطلاعات داخل کادر امضا با انگشت رسم کنید.','برای ثبت راحت‌تر امضا از گزینه تمام‌صفحه استفاده کنید.','پس از ثبت، امضا در فرم ذخیره می‌شود؛ پاک کردن برای ثبت امضای جدید است.']],
['آفلاین و امنیت',['برخی عملیات هنگام قطع اینترنت در صف می‌مانند و بعد از اتصال ارسال می‌شوند.','اگر برنامه درخواست اصلاح دسترسی یا تنظیم امنیتی کرد، آن را انجام دهید و بررسی مجدد را بزنید.']]
];

export default function HelpScreen({navigation}){return <ScrollView style={s.wrap} contentContainerStyle={s.content}><View style={s.hero}><Text style={s.brand}>خطیار</Text><Text style={s.title}>راهنمای کامل استفاده از نرم‌افزار</Text><Text style={s.sub}>راهنمای ابزارهای موجود در برنامه</Text></View>{sections.map(([h,items])=><View key={h} style={s.card}><Text style={s.section}>{h}</Text>{items.map((x,i)=><View key={i} style={s.item}><Text style={s.dot}>•</Text><Text style={s.text}>{x}</Text></View>)}</View>)}<View style={s.about}><Text style={s.aboutTitle}>اطلاعات برنامه</Text><Text style={s.aboutText}>توسعه‌دهنده: علی یوسفی‌پور</Text><Text style={s.aboutText}>شرکت: مبین شات</Text><Text style={s.aboutText}>نام برنامه: خطیار</Text></View><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Text style={s.backText}>بازگشت</Text></TouchableOpacity></ScrollView>}

const s=StyleSheet.create({wrap:{flex:1,backgroundColor:C.paper},content:{padding:14,paddingBottom:40},hero:{backgroundColor:C.brand,borderRadius:20,padding:20,marginBottom:12},brand:{color:'#fff',fontFamily:FONT.bold,fontSize:24,textAlign:'right'},title:{color:'#fff',fontFamily:FONT.bold,fontSize:17,textAlign:'right',marginTop:8},sub:{color:'#d7eee8',fontFamily:FONT.regular,fontSize:12,textAlign:'right',marginTop:6},card:{backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:'#e4e9f2',padding:14,marginBottom:10},section:{color:C.brand,fontFamily:FONT.bold,fontSize:15,textAlign:'right',marginBottom:8},item:{flexDirection:'row-reverse',alignItems:'flex-start',gap:9,paddingVertical:7},dot:{color:C.brand,fontSize:20,lineHeight:20},text:{flex:1,color:'#344054',fontFamily:FONT.regular,fontSize:12.5,lineHeight:22,textAlign:'right'},about:{backgroundColor:'#102033',borderRadius:15,padding:16},aboutTitle:{color:'#fff',fontFamily:FONT.bold,fontSize:15,textAlign:'right',marginBottom:7},aboutText:{color:'#d7dee9',fontFamily:FONT.regular,fontSize:12,textAlign:'right',lineHeight:23},back:{backgroundColor:C.brand,borderRadius:13,paddingVertical:13,alignItems:'center',marginTop:12},backText:{color:'#fff',fontFamily:FONT.bold,fontSize:14}});
