import React,{useEffect,useState} from 'react';
import {View,Text,ScrollView,TouchableOpacity,StyleSheet,Alert,TextInput,Image,RefreshControl} from 'react-native';
import {request} from '../api';
import {getFastPosition} from '../location';
import {ImagePicker,launchCamera} from '../cameraLock';
import {compressToDataUri} from '../img';
import {C,FONT} from '../theme';
import {faNum} from '../num';
import ActivityIndicator from '../components/PulseLoadingIndicator';

export default function LineVisitProgramScreen(){
 const [data,setData]=useState(null),[selected,setSelected]=useState(null),[actual,setActual]=useState(''),[note,setNote]=useState(''),[photo,setPhoto]=useState(null),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false);
 const load=async()=>{try{const d=await request('/operations/visit-program',{noStore:true});if(d?.warning)Alert.alert('هشدار',d.warning);setData(d);}catch(e){Alert.alert('خطا',e.message||'دریافت برنامه بازدید ناموفق بود');setData({mode:'other',summary:{},lines:[],error:e.message});}};
 useEffect(()=>{load()},[]);
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
 const choose=l=>{setSelected(l);setActual(String(l.present_count||0));setPhoto(null);setNote('');};
 const camera=async()=>{const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted)return Alert.alert('توجه','دسترسی دوربین لازم است');const r=await launchCamera({quality:1});if(!r.canceled)setPhoto(await compressToDataUri(r.assets[0].uri));};
 const pos=async()=>{const p=await getFastPosition({maxAgeMs:5000,timeoutMs:18000,highAccuracy:true});if(!p?.coords)throw new Error('موقعیت مکانی دریافت نشد');if(Number(p.coords.accuracy||0)>150)throw new Error('دقت موقعیت کافی نیست؛ چند لحظه در فضای باز منتظر بمانید.');return p.coords;};
 const start=async()=>{if(!selected)return;setBusy(true);try{const c=await pos();const r=await request('/mission-visits/start',{method:'POST',body:{line_id:selected.line.id,lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,provider:'gps',photo_data:photo}});Alert.alert('شروع شد',r.already_started?'بازدید قبلاً شروع شده بود.':'زمان و موقعیت شروع بازدید ثبت شد.');setSelected(null);await load();}catch(e){Alert.alert('خطا',e.message||'شروع بازدید ناموفق بود')}finally{setBusy(false)}};
 const finish=async()=>{if(!selected?.today_visit?.id)return;if(!photo)return Alert.alert('عکس الزامی است','تصویر پایان بازدید باید مستقیم از دوربین ثبت شود.');if(!note.trim())return Alert.alert('گزارش الزامی است','شرح بازدید را ثبت کنید.');setBusy(true);try{const c=await pos();const r=await request('/mission-visits/finish',{method:'POST',body:{session_id:selected.today_visit.id,actual_present_count:Number(actual)||0,report_text:note,photo_data:photo,lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,provider:'gps'}});Alert.alert(r.validated?'پوشش معتبر ثبت شد':'بازدید ثبت شد',`اعتبار پوشش: ${faNum(Math.round(r.validation_percent||0))}٪\nچک‌لیست این بازدید: ${faNum(r.snapshot?.checked_count||0)}\nاختلاف شمارش: ${faNum(r.difference||0)}`);setSelected(null);await load();}catch(e){Alert.alert('خطا',e.message||'پایان بازدید ناموفق بود')}finally{setBusy(false)}};
 if(!data)return <View style={s.center}><ActivityIndicator color={C.brand}/></View>;
 const summary=data.summary||{};
 return <ScrollView style={s.page} contentContainerStyle={{padding:14,paddingBottom:40}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/> }>
  <View style={s.mode}><Text style={s.modeT}>نوع فعالیت: {modeTitle(data.mode)}</Text><Text style={s.modeS}>پوشش معتبر امروز: {faNum(summary.validated_lines||0)} از {faNum(data.lines?.length||0)} خط</Text></View>
  <Text style={s.h}>برنامه بازدید و پوشش خطوط امروز</Text>{data.error&&<Text style={s.error}>{data.error}</Text>}{!(data.lines||[]).length&&<Text style={s.empty}>هیچ خطی به حساب شما تخصیص داده نشده یا برنامه بازدید قابل دریافت نیست.</Text>}
  {(data.lines||[]).map(x=>{const l=x.line||{},v=x.today_visit;const status=v?.status==='in_progress'?'در حال بازدید':v?.validated?'پوشش معتبر':v?'بازدید ثبت‌شده':'بازدید نشده';return <TouchableOpacity key={l.id} style={[s.card,selected?.line?.id===l.id&&s.sel]} onPress={()=>choose(x)}>
    <View style={s.row}><Text style={s.title}>خط {l.code}</Text><Text style={v?.validated?s.done:v?.status==='in_progress'?s.progress:s.wait}>{status}</Text></View>
    <Text style={s.sub}>{l.origin||''}{l.destination?` ← ${l.destination}`:''}</Text>
    <View style={s.stats}><Stat n={x.total_vehicles} t="کل خودرو"/><Stat n={x.present_count} t="حاضر امروز"/><Stat n={x.checked_count} t="چک‌لیست"/><Stat n={x.notice_count} t="تذکر"/><Stat n={x.expired_present_count} t="اعتبار منقضی"/><Stat n={x.coverage_percent} t="٪ پوشش"/></View>
  </TouchableOpacity>})}
  {selected&&<View style={s.form}><Text style={s.h}>خط {selected.line.code}</Text>{!selected.today_visit||selected.today_visit.status!=='in_progress'?<>
    <Text style={s.help}>برای شروع، در محدوده خط حضور داشته باشید. زمان و GPS ثبت می‌شود.</Text><TouchableOpacity disabled={busy} style={s.start} onPress={start}><Text style={s.btnT}>{busy?'در حال ثبت…':'شروع بازدید خط'}</Text></TouchableOpacity>
  </>:<>
    <Text style={s.help}>بازدید فعال است. پس از انجام عملیات، شمارش واقعی، گزارش و تصویر مستقیم را ثبت کنید.</Text><Text style={s.label}>تعداد واقعی خودروهای حاضر</Text><TextInput keyboardType="numeric" style={s.input} value={actual} onChangeText={setActual}/><Text style={s.compare}>حاضر ثبت‌شده سامانه: {faNum(selected.present_count||0)}</Text><Text style={s.label}>گزارش پایان بازدید</Text><TextInput multiline style={[s.input,{minHeight:90}]} value={note} onChangeText={setNote} placeholder="شرح وضعیت خط، اقدامات انجام‌شده و مغایرت‌ها"/><TouchableOpacity style={s.photoBtn} onPress={camera}><Text style={s.btnT}>{photo?'✓ تعویض تصویر دوربین':'📷 ثبت مستقیم تصویر پایان بازدید'}</Text></TouchableOpacity>{photo&&<Image source={{uri:photo}} style={s.photo}/>}<TouchableOpacity disabled={busy} style={[s.submit,busy&&{opacity:.6}]} onPress={finish}><Text style={s.btnT}>{busy?'در حال ثبت…':'پایان بازدید و اعتبارسنجی پوشش'}</Text></TouchableOpacity>
  </>}</View>}
 </ScrollView>;
}
const Stat=({n,t})=><View style={s.stat}><Text style={s.num}>{faNum(Number(n||0))}</Text><Text style={s.st}>{t}</Text></View>;
const modeTitle=m=>({resident_inspector:'بازرس مقیم',vehicle_patrol:'بازرس گشت خودرویی',motor_patrol:'گشت موتوری',line_supervisor:'ناظر خط',administrative_visit:'سرکشی نیروی اداری',chief_inspector:'سربازرس'}[m]||'بازدید میدانی');
const s=StyleSheet.create({page:{backgroundColor:C.paper},center:{flex:1,alignItems:'center',justifyContent:'center'},mode:{backgroundColor:'#173d69',padding:12,borderRadius:12},modeT:{color:'#fff',fontFamily:FONT.bold,textAlign:'right'},modeS:{color:'#dce8f4',fontFamily:FONT.regular,textAlign:'right',marginTop:5},h:{fontFamily:FONT.bold,color:C.ink,fontSize:16,textAlign:'right',marginVertical:12},card:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:14,padding:12,marginBottom:10},sel:{borderColor:C.brand,borderWidth:2},row:{flexDirection:'row-reverse',justifyContent:'space-between'},title:{fontFamily:FONT.bold,color:C.ink,fontSize:15},sub:{fontFamily:FONT.regular,color:C.muted,textAlign:'right',marginTop:4},done:{fontFamily:FONT.bold,color:'#16875c'},progress:{fontFamily:FONT.bold,color:'#b36a00'},wait:{fontFamily:FONT.bold,color:'#d33'},stats:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7,marginTop:10},stat:{backgroundColor:'#f5f7fa',borderRadius:9,padding:7,minWidth:'30%',alignItems:'center'},num:{fontFamily:FONT.bold,color:C.ink},st:{fontFamily:FONT.regular,color:C.muted,fontSize:10},form:{backgroundColor:'#fff',borderRadius:15,padding:14,borderWidth:1,borderColor:C.line},help:{fontFamily:FONT.regular,color:C.muted,textAlign:'right',lineHeight:22},label:{fontFamily:FONT.bold,color:C.ink,textAlign:'right',marginTop:9,marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:11,padding:11,fontFamily:FONT.regular,textAlign:'right',color:C.ink},compare:{fontFamily:FONT.regular,color:C.muted,textAlign:'right',marginTop:6},photoBtn:{backgroundColor:'#315f8c',padding:13,borderRadius:12,alignItems:'center',marginTop:12},start:{backgroundColor:'#1f7a55',padding:14,borderRadius:12,alignItems:'center',marginTop:12},submit:{backgroundColor:C.brand,padding:14,borderRadius:12,alignItems:'center',marginTop:12},btnT:{color:'#fff',fontFamily:FONT.bold},photo:{width:'100%',height:180,borderRadius:12,marginTop:9},error:{fontFamily:FONT.regular,color:'#b00020',textAlign:'right',backgroundColor:'#fdecec',padding:10,borderRadius:10},empty:{fontFamily:FONT.regular,color:C.muted,textAlign:'center',padding:20}});
