import React from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { C, FONT } from '../theme';
import { request } from '../api';
const V=['عدم اعتبار معاینه فنی','عدم اعتبار بیمه شخص ثالث','سرنشین اضافی','راننده غیر مجاز','داشتن یا نداشتن گواهی صلاحیت معتبر','عدم توجه به فرمان و ایست'];
const en=s=>String(s||'').replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c));
function Select({label,value,items,onChange}){const [open,setOpen]=React.useState(false);return <View style={s.field}><Text style={s.label}>{label}</Text><TouchableOpacity style={s.select} onPress={()=>setOpen(true)}><Text style={s.value}>{value||'انتخاب کنید'}</Text><Text style={s.chev}>⌄</Text></TouchableOpacity><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={s.modal}><ScrollView>{items.map(x=><TouchableOpacity key={String(x)} style={s.option} onPress={()=>{onChange(x);setOpen(false)}}><Text style={s.optionText}>{x}</Text></TouchableOpacity>)}</ScrollView></View></View></Modal></View>}
function Multi({items,selected,onToggle}){return <View style={s.chips}>{items.map(x=><TouchableOpacity key={x.id} style={[s.chip,selected.includes(x.id)&&s.chipOn]} onPress={()=>onToggle(x.id)}><Text style={[s.chipText,selected.includes(x.id)&&s.chipTextOn]}>{x.title}</Text></TouchableOpacity>)}</View>}
export default function SchoolServiceScreen(){const [access,setAccess]=React.useState(null),[meta,setMeta]=React.useState(null),[companies,setCompanies]=React.useState([]),[schools,setSchools]=React.useState([]),[search,setSearch]=React.useState(''),[saving,setSaving]=React.useState(false);
const [f,setF]=React.useState({district:'',company_id:0,school_id:0,school_gender:'',plate_three:'',plate_letter:'',plate_two:'',vehicle_type:'',vehicle_color:'',violations:[],passenger_count:'0',driver_gender:'',certificate_status:'ارائه نشد',date:'',time:'',location:'',description:''});
const [companyName,setCompanyName]=React.useState(''),[schoolName,setSchoolName]=React.useState('');
const set=(k,v)=>setF(x=>({...x,[k]:v}));
React.useEffect(()=>{Promise.all([request('/school-service/access',{noStore:true}),request('/school-service/meta',{noStore:true}),request('/school-service/companies?limit=200',{noStore:true})]).then(([a,m,c])=>{setAccess(a);setMeta(m);setCompanies(c.items||[])}).catch(e=>Alert.alert('خطا',e.message||'دریافت اطلاعات ممکن نشد.'))},[]);
React.useEffect(()=>{const t=setTimeout(()=>{request('/school-service/schools?search='+encodeURIComponent(search)+(f.company_id?'&company_id='+f.company_id:'')+'&limit=200',{noStore:true}).then(x=>setSchools(x.items||[])).catch(()=>{})},250);return()=>clearTimeout(t)},[search,f.company_id]);
const selectedSchool=schools.find(x=>x.id===f.school_id);
const save=async()=>{if(!access?.can_create)return Alert.alert('دسترسی','ثبت بازدید برای شما فعال نیست.');if(!f.district||!f.plate_three||!f.plate_letter||!f.plate_two||!f.vehicle_type||!f.vehicle_color||!f.driver_gender||!f.location)return Alert.alert('اطلاعات ناقص','ناحیه، پلاک، نوع و رنگ خودرو، نوع راننده و محل ثبت تخلف الزامی است.');setSaving(true);try{const r=await request('/school-service/inspections',{method:'POST',body:{educational_district:f.district,company_id:f.company_id||null,school_id:f.school_id||null,school_gender:f.school_gender||'نامشخص',plate_three:en(f.plate_three),plate_letter:f.plate_letter,plate_two:en(f.plate_two),vehicle_type:f.vehicle_type,vehicle_color:f.vehicle_color,violation_ids:f.violations,passenger_count:Math.max(0,parseInt(en(f.passenger_count),10)||0),driver_gender:f.driver_gender,certificate_status:f.certificate_status,violation_date:f.date||'',violation_time:f.time||'',location_text:f.location,description:f.description}});Alert.alert('ثبت شد','بازدید و تخلف با موفقیت ثبت شد.');setF(x=>({...x,violations:[],plate_three:'',plate_letter:'',plate_two:'',passenger_count:'0',location:'',description:''}))}catch(e){Alert.alert('خطا',e.message||'ثبت اطلاعات انجام نشد.')}finally{setSaving(false)}};
if(access&&!access.allowed)return <View style={s.center}><Text style={s.title}>دسترسی به سرویس مدارس برای شما فعال نیست.</Text></View>;
return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.header}>ثبت بازدید سرویس مدارس</Text>
<Select label="ناحیه آموزشی" value={f.district} items={meta?.districts||[]} onChange={v=>set('district',v)}/>
<Select label="شرکت مجری سرویس دانش‌آموزی" value={companies.find(x=>x.id===f.company_id)?.name||'نامشخص'} items={['نامشخص',...companies.map(x=>x.name)]} onChange={v=>{const c=companies.find(x=>x.name===v);set('company_id',c?.id||0);setCompanyName(v)}}/>
<Select label="نوع مدرسه" value={f.school_gender} items={meta?.genders||[]} onChange={v=>set('school_gender',v)}/>
<View style={s.field}><Text style={s.label}>جستجوی مدرسه</Text><TextInput value={search} onChangeText={setSearch} placeholder="نام یا کد مدرسه" placeholderTextColor={C.muted} style={s.input}/>{schools.slice(0,8).map(x=><TouchableOpacity key={x.id} style={[s.schoolRow,f.school_id===x.id&&s.schoolOn]} onPress={()=>{set('school_id',x.id);set('school_gender',x.gender||f.school_gender);setSearch(x.name)}}><Text style={s.schoolName}>{x.name}</Text><Text style={s.schoolMeta}>{x.educational_district||''} {x.company_names?'• '+x.company_names:''}</Text></TouchableOpacity>)}</View>
<Text style={s.section}>پلاک خودرو</Text><View style={s.plate}><TextInput maxLength={3} keyboardType="number-pad" value={f.plate_three} onChangeText={v=>set('plate_three',v)} style={s.plateInput}/><TextInput maxLength={3} value={f.plate_letter} onChangeText={v=>set('plate_letter',v)} style={s.plateInput}/><TextInput maxLength={2} keyboardType="number-pad" value={f.plate_two} onChangeText={v=>set('plate_two',v)} style={s.plateInput}/><View style={s.iran}><Text style={s.iranText}>ایران</Text></View></View>
<Select label="نوع خودرو" value={f.vehicle_type} items={meta?.vehicle_types||[]} onChange={v=>set('vehicle_type',v)}/><Select label="رنگ خودرو" value={f.vehicle_color} items={meta?.vehicle_colors||[]} onChange={v=>set('vehicle_color',v)}/>
<Text style={s.section}>نوع تخلف — امکان انتخاب چند مورد</Text><Multi items={meta?.violations||[]} selected={f.violations} onToggle={id=>set('violations',f.violations.includes(id)?f.violations.filter(x=>x!==id):[...f.violations,id])}/>
<TextInput keyboardType="number-pad" value={f.passenger_count} onChangeText={v=>set('passenger_count',v)} placeholder="تعداد سرنشین بدون راننده" placeholderTextColor={C.muted} style={s.input}/><Select label="نوع راننده" value={f.driver_gender} items={meta?.driver_genders||[]} onChange={v=>set('driver_gender',v)}/><Select label="وضعیت گواهی صلاحیت" value={f.certificate_status} items={['معتبر','نامعتبر','ارائه نشد']} onChange={v=>set('certificate_status',v)}/>
<View style={s.row}><TextInput keyboardType="numbers-and-punctuation" value={f.date} onChangeText={v=>set('date',v)} placeholder="تاریخ شمسی، مثال ۱۴۰۵/۰۶/۰۱" placeholderTextColor={C.muted} style={[s.input,s.half]}/><TextInput value={f.time} onChangeText={v=>set('time',v)} placeholder="ساعت" placeholderTextColor={C.muted} style={[s.input,s.half]}/></View>
<TextInput value={f.location} onChangeText={v=>set('location',v)} placeholder="محل ثبت تخلف" placeholderTextColor={C.muted} style={s.input}/><TextInput value={f.description} onChangeText={v=>set('description',v)} placeholder="توضیحات" placeholderTextColor={C.muted} style={[s.input,s.area]}/>
<TouchableOpacity disabled={saving} onPress={save} style={s.save}><Text style={s.saveText}>{saving?'در حال ثبت…':'ثبت بازدید'}</Text></TouchableOpacity></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.paper},content:{padding:16,paddingBottom:40},header:{fontFamily:FONT.bold,fontSize:21,color:C.ink,textAlign:'right',marginBottom:12},section:{fontFamily:FONT.bold,fontSize:15,color:C.brand,textAlign:'right',marginTop:15,marginBottom:8},field:{marginBottom:10},label:{fontFamily:FONT.bold,fontSize:12,color:C.ink,textAlign:'right',marginBottom:5},select:{minHeight:48,borderWidth:1,borderColor:C.line,borderRadius:12,backgroundColor:'#fff',paddingHorizontal:12,flexDirection:'row-reverse',alignItems:'center'},value:{flex:1,fontFamily:FONT.regular,fontSize:13,color:C.ink,textAlign:'right'},chev:{fontSize:20,color:C.muted},input:{minHeight:48,borderWidth:1,borderColor:C.line,borderRadius:12,backgroundColor:'#fff',paddingHorizontal:12,fontFamily:FONT.regular,fontSize:13,color:C.ink,textAlign:'right',marginBottom:10},row:{flexDirection:'row-reverse',gap:8},half:{flex:1},area:{minHeight:90,textAlignVertical:'top'},plate:{flexDirection:'row-reverse',backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:12,padding:6,marginBottom:10},plateInput:{flex:1,minHeight:44,borderLeftWidth:1,borderColor:C.line,textAlign:'center',fontFamily:FONT.bold,fontSize:17,color:C.ink},iran:{width:58,alignItems:'center',justifyContent:'center'},iranText:{fontFamily:FONT.bold,color:C.ink},chips:{gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:'#fff'},chipOn:{backgroundColor:C.brand,borderColor:C.brand},chipText:{fontFamily:FONT.regular,color:C.ink,fontSize:12,textAlign:'right'},chipTextOn:{color:'#fff'},schoolRow:{backgroundColor:'#fff',borderWidth:1,borderColor:C.line,borderRadius:10,padding:10,marginTop:5},schoolOn:{borderColor:C.brand},schoolName:{fontFamily:FONT.bold,color:C.ink,textAlign:'right'},schoolMeta:{fontFamily:FONT.regular,color:C.muted,fontSize:11,textAlign:'right',marginTop:3},save:{backgroundColor:C.brand,borderRadius:14,minHeight:52,alignItems:'center',justifyContent:'center',marginTop:15},saveText:{fontFamily:FONT.bold,color:'#fff',fontSize:15},center:{flex:1,alignItems:'center',justifyContent:'center',padding:25},title:{fontFamily:FONT.bold,fontSize:17,color:C.ink,textAlign:'center'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.45)',justifyContent:'center',padding:20},modal:{maxHeight:'75%',backgroundColor:'#fff',borderRadius:16,padding:8},option:{padding:14,borderBottomWidth:1,borderBottomColor:C.line},optionText:{fontFamily:FONT.regular,color:C.ink,textAlign:'right'}});