import { Router } from 'express';
import { z } from 'zod';
import { q, pool } from '../db.js';
import { authenticate, requireAdmin } from '../middleware/auth.js';

export const missionRouter = Router();
missionRouter.use(authenticate);

const roleKey = (u) => {
  const t = String(u.role_title || '').replace(/\s+/g, ' ').trim();
  if (/گشت\s*موتوری/.test(t)) return 'motor_patrol';
  if (/سربازرس/.test(t)) return 'chief_inspector';
  if (/ناظر\s*خط/.test(t)) return 'line_supervisor';
  if (/بازرس/.test(t)) return 'inspector_auto';
  if (/نیروی\s*اداری/.test(t)) return 'administrative_visit';
  return 'other';
};
const pct=(n,d)=>d>0?Math.min(100,Math.round((Number(n||0)/Number(d))*10000)/100):0;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const haversine=(a,b,c,d)=>{const R=6371000,rad=x=>x*Math.PI/180,da=rad(c-a),dl=rad(d-b);const x=Math.sin(da/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};

async function resolvedRole(user) {
  const base = roleKey(user);
  if (base !== 'inspector_auto') return base;
  const manual = await q(`SELECT mode FROM inspector_modes WHERE user_id=$1 LIMIT 1`, [user.id]).catch(()=>({rows:[]}));
  if (manual.rows[0]?.mode && manual.rows[0].mode!=='auto') return manual.rows[0].mode;
  const n = await q(`SELECT count(*)::int n FROM user_lines WHERE user_id=$1`, [user.id]);
  return Number(n.rows[0]?.n || 0) <= 1 ? 'resident_inspector' : 'vehicle_patrol';
}

async function effectiveMission(user, period='daily') {
  const ov = await q(`SELECT * FROM user_mission_overrides WHERE user_id=$1 AND period=$2 AND is_active
    AND (effective_from IS NULL OR effective_from<=CURRENT_DATE) AND (effective_to IS NULL OR effective_to>=CURRENT_DATE)
    ORDER BY updated_at DESC LIMIT 1`, [user.id, period]);
  if (ov.rows[0]) {
    const targets = await q(`SELECT t.*,c.title,c.unit,c.description FROM user_mission_override_targets t JOIN mission_metric_catalog c USING(metric_key) WHERE override_id=$1 ORDER BY c.sort_order`, [ov.rows[0].id]);
    return { source:'user_override', role_key:await resolvedRole(user), mission:ov.rows[0], targets:targets.rows };
  }
  const rk = await resolvedRole(user);
  const tpl = await q(`SELECT * FROM mission_templates WHERE role_key=$1 AND period=$2 AND is_active
    AND (effective_from IS NULL OR effective_from<=CURRENT_DATE) AND (effective_to IS NULL OR effective_to>=CURRENT_DATE)
    ORDER BY (zone_id IS NOT NULL AND zone_id=$3) DESC,is_default DESC,updated_at DESC LIMIT 1`, [rk,period,user.zone_id||null]);
  if (!tpl.rows[0]) return { source:'none', role_key:rk, mission:null, targets:[] };
  const targets = await q(`SELECT t.*,c.title,c.unit,c.description FROM mission_template_targets t JOIN mission_metric_catalog c USING(metric_key) WHERE template_id=$1 ORDER BY c.sort_order`, [tpl.rows[0].id]);
  return { source:'role_template', role_key:rk, mission:tpl.rows[0], targets:targets.rows };
}

async function setting(key, fallback){const r=await q(`SELECT setting_value FROM mission_execution_settings WHERE setting_key=$1`,[key]).catch(()=>({rows:[]}));return r.rows[0]?.setting_value??fallback;}
async function lineAllowed(uid,lineId){const r=await q(`SELECT 1 FROM user_lines WHERE user_id=$1 AND line_id=$2`,[uid,lineId]);return !!r.rows[0];}
async function geoAllowed(lineId,lat,lng){
 const extra=Number(await setting('visit_geo_extra_radius_m','75'))||75;
 const {rows}=await q(`SELECT id,name,type,center_lat,center_lng,radius_m,polygon FROM geofences WHERE line_id=$1`,[lineId]).catch(()=>({rows:[]}));
 if(!rows.length) return {ok:true,warning:'برای این خط محدوده جغرافیایی تعریف نشده است'};
 let best=null;
 for(const g of rows){if(g.center_lat!=null&&g.center_lng!=null&&g.radius_m){const dist=haversine(Number(lat),Number(lng),Number(g.center_lat),Number(g.center_lng));if(!best||dist<best.distance_m)best={distance_m:dist,name:g.name,radius_m:Number(g.radius_m)+extra};if(dist<=Number(g.radius_m)+extra)return {ok:true,geofence:g.name,distance_m:Math.round(dist)};}}
 return {ok:false,best};
}
async function lineSnapshot(lineId,userId=null){
 const [line,total,present,checked,notices,expired,debt,visits]=await Promise.all([
  q(`SELECT id,code,origin,destination FROM lines WHERE id=$1`,[lineId]),
  q(`SELECT count(*)::int n FROM vehicles WHERE line_id=$1`,[lineId]),
  q(`SELECT count(DISTINCT driver_id)::int n FROM attendances WHERE line_id=$1 AND created_at::date=CURRENT_DATE`,[lineId]),
  q(`SELECT count(DISTINCT COALESCE(cs.vehicle_id,cs.driver_id))::int n FROM checklist_submissions cs LEFT JOIN vehicles v ON v.id=cs.vehicle_id WHERE cs.created_at::date=CURRENT_DATE AND (v.line_id=$1 OR EXISTS(SELECT 1 FROM attendances a WHERE a.driver_id=cs.driver_id AND a.line_id=$1 AND a.created_at::date=CURRENT_DATE))`,[lineId]),
  q(`SELECT count(*)::int n FROM notices n WHERE n.created_at::date=CURRENT_DATE AND EXISTS(SELECT 1 FROM attendances a WHERE a.driver_id=n.driver_id AND a.line_id=$1 AND a.created_at::date=CURRENT_DATE)`,[lineId]),
  q(`SELECT count(DISTINCT a.driver_id)::int n FROM attendances a JOIN drivers d ON d.id=a.driver_id LEFT JOIN vehicle_drivers vd ON vd.driver_id=d.id LEFT JOIN vehicles v ON v.id=vd.vehicle_id WHERE a.line_id=$1 AND a.created_at::date=CURRENT_DATE AND (COALESCE(d.taxi_lic_status,'') ILIKE '%منقض%' OR COALESCE(d.op_lic_status,'') ILIKE '%منقض%' OR NULLIF(v.tech_inspection_expire,'') IS NOT NULL OR NULLIF(v.insurance_expire,'') IS NOT NULL)`,[lineId]),
  q(`SELECT count(DISTINCT a.driver_id)::int n FROM attendances a JOIN drivers d ON d.id=a.driver_id WHERE a.line_id=$1 AND a.created_at::date=CURRENT_DATE AND EXISTS(SELECT 1 FROM bills b WHERE (b.driver_id=d.id OR b.national_id=d.national_id) AND COALESCE(b.status,'') NOT ILIKE '%پرداخت%')`,[lineId]).catch(()=>({rows:[{n:0}]})),
  userId?q(`SELECT id,status,validated,validation_percent,started_at,finished_at FROM mission_visit_sessions WHERE user_id=$1 AND line_id=$2 AND started_at::date=CURRENT_DATE ORDER BY id DESC LIMIT 1`,[userId,lineId]):Promise.resolve({rows:[]})
 ]);
 return {line:line.rows[0],total_vehicles:Number(total.rows[0]?.n||0),present_count:Number(present.rows[0]?.n||0),checked_count:Number(checked.rows[0]?.n||0),notice_count:Number(notices.rows[0]?.n||0),expired_present_count:Number(expired.rows[0]?.n||0),subscription_debt_present_count:Number(debt.rows[0]?.n||0),coverage_percent:pct(checked.rows[0]?.n,total.rows[0]?.n),today_visit:visits.rows[0]||null};
}
async function subordinateCount(uid){
 const {rows}=await q(`WITH RECURSIVE sub AS (SELECT id FROM users WHERE manager_id=$1 UNION ALL SELECT u.id FROM users u JOIN sub s ON u.manager_id=s.id) SELECT count(DISTINCT id)::int n FROM sub`,[uid]).catch(()=>({rows:[{n:0}]}));return Number(rows[0]?.n||0);
}
async function actualMetrics(user){
 const lines=(await q(`SELECT line_id FROM user_lines WHERE user_id=$1`,[user.id])).rows.map(r=>Number(r.line_id));
 const snaps=await Promise.all(lines.map(id=>lineSnapshot(id,user.id)));
 const presentTotal=snaps.reduce((s,x)=>s+x.present_count,0), totalVehicles=snaps.reduce((s,x)=>s+x.total_vehicles,0), expiredTotal=snaps.reduce((s,x)=>s+x.expired_present_count,0), debtTotal=snaps.reduce((s,x)=>s+x.subscription_debt_present_count,0);
 const [att,checks,notices,expiredNotices,debtNotices,visits,validVisits,reviews,reports]=await Promise.all([
 q(`SELECT count(DISTINCT driver_id)::int n FROM attendances WHERE user_id=$1 AND created_at::date=CURRENT_DATE`,[user.id]),
 q(`SELECT count(DISTINCT COALESCE(vehicle_id,driver_id))::int n FROM checklist_submissions WHERE user_id=$1 AND created_at::date=CURRENT_DATE`,[user.id]),
 q(`SELECT count(*)::int n FROM notices WHERE user_id=$1 AND created_at::date=CURRENT_DATE`,[user.id]),
 q(`SELECT count(*)::int n FROM notices WHERE user_id=$1 AND created_at::date=CURRENT_DATE AND (COALESCE(body,'') ILIKE '%منقض%' OR COALESCE(body,'') ILIKE '%اعتبار%')`,[user.id]),
 q(`SELECT count(*)::int n FROM notices WHERE user_id=$1 AND created_at::date=CURRENT_DATE AND (COALESCE(body,'') ILIKE '%آبونمان%' OR COALESCE(body,'') ILIKE '%بدهکار%')`,[user.id]),
 q(`SELECT count(DISTINCT line_id)::int n FROM mission_visit_sessions WHERE user_id=$1 AND started_at::date=CURRENT_DATE AND status='submitted'`,[user.id]).catch(()=>({rows:[{n:0}]})),
 q(`SELECT count(DISTINCT line_id)::int n FROM mission_visit_sessions WHERE user_id=$1 AND started_at::date=CURRENT_DATE AND validated`,[user.id]).catch(()=>({rows:[{n:0}]})),
 q(`SELECT count(DISTINCT subject_user_id)::int n FROM subordinate_daily_reviews WHERE reviewer_id=$1 AND review_date=CURRENT_DATE`,[user.id]).catch(()=>({rows:[{n:0}]})),
 q(`SELECT count(*)::int n FROM reports WHERE sender_id=$1 AND created_at::date=CURRENT_DATE AND (subject ILIKE '%پایان شیفت%' OR body ILIKE '%پایان شیفت%')`,[user.id])
 ]);
 const subs=await subordinateCount(user.id);
 const denominators={driver_attendance_percent:presentTotal||totalVehicles,vehicle_checklist_percent:presentTotal||totalVehicles,expired_notice_percent:expiredTotal,subscription_debt_notice_percent:debtTotal,assigned_lines_visit_percent:lines.length,subordinate_review_percent:subs,station_visit_percent:lines.length,end_shift_report:1};
 const counts={driver_attendance_percent:Number(att.rows[0]?.n||0),vehicle_checklist_percent:Number(checks.rows[0]?.n||0),expired_notice_percent:Number(expiredNotices.rows[0]?.n||0),subscription_debt_notice_percent:Number(debtNotices.rows[0]?.n||0),assigned_lines_visit_percent:Number(validVisits.rows[0]?.n||0),subordinate_review_percent:Number(reviews.rows[0]?.n||0),station_visit_percent:Number(visits.rows[0]?.n||0),end_shift_report:Number(reports.rows[0]?.n||0)>0?1:0};
 return {lines,snaps,counts,denominators,raw:{present_total:presentTotal,total_vehicles:totalVehicles,notices:Number(notices.rows[0]?.n||0),visited_lines:Number(visits.rows[0]?.n||0),validated_lines:Number(validVisits.rows[0]?.n||0),subordinates:subs}};
}
async function missionProgress(user){
 const eff=await effectiveMission(user,'daily'); const act=await actualMetrics(user); let weightSum=0,scoreSum=0;
 const targets=(eff.targets||[]).map(t=>{const actual=act.counts[t.metric_key]||0,den=act.denominators[t.metric_key]||0,actualPercent=t.metric_key==='end_shift_report'?(actual?100:0):pct(actual,den);const target=Number(t.target_percent||0),achievement=target>0?Math.min(100,actualPercent/target*100):100;const w=Number(t.weight||1);weightSum+=w;scoreSum+=achievement*w;return {...t,actual_count:actual,denominator_count:den,actual_percent:actualPercent,achievement_percent:Math.round(achievement*100)/100,remaining_count:Math.max(0,Math.ceil(den*target/100)-actual)};});
 const weighted=weightSum?Math.round(scoreSum/weightSum*100)/100:0;
 if(eff.mission)await q(`INSERT INTO mission_daily_progress(user_id,progress_date,role_key,mission_source,mission_id,assigned_lines_count,visited_lines_count,validated_lines_count,target_json,actual_json,progress_json,weighted_achievement,updated_at) VALUES($1,CURRENT_DATE,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now()) ON CONFLICT(user_id,progress_date) DO UPDATE SET role_key=EXCLUDED.role_key,mission_source=EXCLUDED.mission_source,mission_id=EXCLUDED.mission_id,assigned_lines_count=EXCLUDED.assigned_lines_count,visited_lines_count=EXCLUDED.visited_lines_count,validated_lines_count=EXCLUDED.validated_lines_count,target_json=EXCLUDED.target_json,actual_json=EXCLUDED.actual_json,progress_json=EXCLUDED.progress_json,weighted_achievement=EXCLUDED.weighted_achievement,updated_at=now()`,[user.id,eff.role_key,eff.source,eff.mission.id,act.lines.length,act.raw.visited_lines,act.raw.validated_lines,JSON.stringify(Object.fromEntries(targets.map(t=>[t.metric_key,t.target_percent]))),JSON.stringify(act.counts),JSON.stringify(Object.fromEntries(targets.map(t=>[t.metric_key,t.achievement_percent]))),weighted]).catch(()=>{});
 return {...eff,assigned_lines:act.lines.length,targets,actual_counts:act.counts,denominators:act.denominators,summary:{...act.raw,weighted_achievement:weighted},lines:act.snaps};
}

missionRouter.get('/my/missions/effective', async (req,res)=> res.json(await effectiveMission(req.user,String(req.query.period||'daily'))));
missionRouter.get('/my/missions/today', async (req,res)=>res.json(await missionProgress(req.user)));
missionRouter.get('/my/visit-program',async(req,res)=>{const p=await missionProgress(req.user);res.json({mode:p.role_key,date:new Date().toISOString().slice(0,10),summary:p.summary,targets:p.targets,lines:p.lines});});
missionRouter.get('/my/mission-timeline',async(req,res)=>{const {rows}=await q(`SELECT e.*,l.code line_code,l.origin,l.destination FROM mission_timeline_events e LEFT JOIN lines l ON l.id=e.line_id WHERE e.user_id=$1 AND e.occurred_at::date=COALESCE($2::date,CURRENT_DATE) ORDER BY e.occurred_at DESC`,[req.user.id,req.query.date||null]);res.json({items:rows});});

const visitStartSchema=z.object({line_id:z.number().int().positive(),lat:z.number(),lng:z.number(),photo_data:z.string().nullable().optional()});
missionRouter.post('/mission-visits/start',async(req,res)=>{const p=visitStartSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'اطلاعات شروع بازدید نامعتبر است'});const d=p.data;if(!await lineAllowed(req.user.id,d.line_id))return res.status(403).json({error:'این خط در محدوده دسترسی شما نیست'});const geo=await geoAllowed(d.line_id,d.lat,d.lng);if(!geo.ok)return res.status(403).json({error:'برای شروع بازدید باید در محدوده خط یا ایستگاه آن حضور داشته باشید',geo});const requirePhoto=String(await setting('visit_require_start_photo','false'))==='true';if(requirePhoto&&!d.photo_data)return res.status(422).json({error:'تصویر شروع بازدید الزامی است'});const rk=await resolvedRole(req.user);const existing=await q(`SELECT id FROM mission_visit_sessions WHERE user_id=$1 AND line_id=$2 AND status='in_progress'`,[req.user.id,d.line_id]);if(existing.rows[0])return res.json({ok:true,id:existing.rows[0].id,already_started:true});const r=await q(`INSERT INTO mission_visit_sessions(user_id,line_id,role_mode,start_lat,start_lng,start_photo_data) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,started_at`,[req.user.id,d.line_id,rk,d.lat,d.lng,d.photo_data||null]);await q(`INSERT INTO mission_timeline_events(user_id,line_id,visit_session_id,event_type,title,details,lat,lng) VALUES($1,$2,$3,'visit_started','شروع بازدید خط',jsonb_build_object('role_mode',$4,'geo',$5::jsonb),$6,$7)`,[req.user.id,d.line_id,r.rows[0].id,rk,JSON.stringify(geo),d.lat,d.lng]);res.status(201).json({ok:true,...r.rows[0],geo});});

const visitFinishSchema=z.object({session_id:z.number().int().positive(),lat:z.number(),lng:z.number(),actual_present_count:z.number().int().min(0).default(0),report_text:z.string().default(''),photo_data:z.string().nullable().optional()});
missionRouter.post('/mission-visits/finish',async(req,res)=>{const p=visitFinishSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'اطلاعات پایان بازدید نامعتبر است'});const d=p.data;const s=(await q(`SELECT * FROM mission_visit_sessions WHERE id=$1 AND user_id=$2 AND status='in_progress'`,[d.session_id,req.user.id])).rows[0];if(!s)return res.status(404).json({error:'بازدید فعال یافت نشد'});const geo=await geoAllowed(s.line_id,d.lat,d.lng);if(!geo.ok)return res.status(403).json({error:'برای پایان بازدید باید در محدوده خط یا ایستگاه آن حضور داشته باشید',geo});const requirePhoto=String(await setting('visit_require_finish_photo','true'))==='true',requireReport=String(await setting('visit_require_end_report','true'))==='true';if(requirePhoto&&!d.photo_data)return res.status(422).json({error:'تصویر مستقیم پایان بازدید الزامی است'});if(requireReport&&!d.report_text.trim())return res.status(422).json({error:'گزارش پایان بازدید الزامی است'});const minDuration=Number(await setting('visit_min_duration_minutes','10'))||10,minChecked=Number(await setting('visit_min_checked_percent','5'))||5;const snap=await lineSnapshot(s.line_id,req.user.id);const duration=Math.max(0,(Date.now()-new Date(s.started_at).getTime())/60000);const checkedPct=pct(snap.checked_count,snap.present_count||snap.total_vehicles);const checks={geo:true,duration:duration>=minDuration,checked:checkedPct>=minChecked,photo:!requirePhoto||!!d.photo_data,report:!requireReport||!!d.report_text.trim()};const pass=Object.values(checks).filter(Boolean).length,validation=Math.round(pass/Object.keys(checks).length*10000)/100,validated=Object.values(checks).every(Boolean);await q(`UPDATE mission_visit_sessions SET finished_at=now(),finish_lat=$1,finish_lng=$2,finish_photo_data=$3,report_text=$4,actual_present_count=$5,status='submitted',validated=$6,validation_percent=$7,validation_details=$8::jsonb,updated_at=now() WHERE id=$9`,[d.lat,d.lng,d.photo_data||null,d.report_text.trim(),d.actual_present_count,validated,validation,JSON.stringify({checks,duration_minutes:Math.round(duration*10)/10,checked_percent:checkedPct,min_duration_minutes:minDuration,min_checked_percent:minChecked,geo}),s.id]);await q(`INSERT INTO mission_timeline_events(user_id,line_id,visit_session_id,event_type,title,details,lat,lng) VALUES($1,$2,$3,'visit_finished','پایان بازدید خط',$4::jsonb,$5,$6)`,[req.user.id,s.line_id,s.id,JSON.stringify({validated,validation_percent:validation,duration_minutes:Math.round(duration*10)/10,actual_present_count:d.actual_present_count}),d.lat,d.lng]);res.json({ok:true,validated,validation_percent:validation,validation_details:{checks,duration_minutes:Math.round(duration*10)/10,checked_percent:checkedPct},snapshot:snap,difference:d.actual_present_count-snap.present_count});});

missionRouter.post('/mission-timeline/event',async(req,res)=>{const p=z.object({event_type:z.string().min(2),title:z.string().min(2),line_id:z.number().int().positive().nullable().optional(),target_type:z.string().nullable().optional(),target_id:z.number().int().nullable().optional(),details:z.any().optional(),lat:z.number().nullable().optional(),lng:z.number().nullable().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'رویداد نامعتبر است'});const d=p.data;const r=await q(`INSERT INTO mission_timeline_events(user_id,line_id,event_type,target_type,target_id,title,details,lat,lng) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) RETURNING id`,[req.user.id,d.line_id||null,d.event_type,d.target_type||null,d.target_id||null,d.title,JSON.stringify(d.details||{}),d.lat||null,d.lng||null]);res.status(201).json({id:r.rows[0].id});});

missionRouter.get('/my/subordinates/daily',async(req,res)=>{const {rows}=await q(`WITH RECURSIVE sub AS (SELECT id,first_name,last_name,role_id,manager_id FROM users WHERE manager_id=$1 UNION ALL SELECT u.id,u.first_name,u.last_name,u.role_id,u.manager_id FROM users u JOIN sub s ON u.manager_id=s.id) SELECT s.id,(s.first_name||' '||s.last_name) name,r.title role_title,COALESCE(m.weighted_achievement,0) weighted_achievement,COALESCE(m.visited_lines_count,0) visited_lines_count,COALESCE(m.validated_lines_count,0) validated_lines_count,rv.total_score review_score FROM sub s LEFT JOIN roles r ON r.id=s.role_id LEFT JOIN mission_daily_progress m ON m.user_id=s.id AND m.progress_date=CURRENT_DATE LEFT JOIN subordinate_daily_reviews rv ON rv.subject_user_id=s.id AND rv.reviewer_id=$1 AND rv.review_date=CURRENT_DATE ORDER BY r.level DESC,s.last_name`,[req.user.id]).catch(()=>({rows:[]}));res.json({items:rows});});
missionRouter.post('/subordinate-daily-reviews',async(req,res)=>{const p=z.object({subject_user_id:z.number().int().positive(),line_id:z.number().int().positive().nullable().optional(),attendance_score:z.number().min(0).max(20),checklist_score:z.number().min(0).max(20),notice_score:z.number().min(0).max(20),coverage_score:z.number().min(0).max(20),quality_score:z.number().min(0).max(20),note:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'ارزیابی نامعتبر است'});const d=p.data,total=d.attendance_score+d.checklist_score+d.notice_score+d.coverage_score+d.quality_score;await q(`INSERT INTO subordinate_daily_reviews(reviewer_id,subject_user_id,review_date,line_id,attendance_score,checklist_score,notice_score,coverage_score,quality_score,total_score,note) VALUES($1,$2,CURRENT_DATE,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(reviewer_id,subject_user_id,review_date) DO UPDATE SET attendance_score=EXCLUDED.attendance_score,checklist_score=EXCLUDED.checklist_score,notice_score=EXCLUDED.notice_score,coverage_score=EXCLUDED.coverage_score,quality_score=EXCLUDED.quality_score,total_score=EXCLUDED.total_score,note=EXCLUDED.note,updated_at=now()`,[req.user.id,d.subject_user_id,d.line_id||null,d.attendance_score,d.checklist_score,d.notice_score,d.coverage_score,d.quality_score,total,d.note||null]);res.json({ok:true,total_score:total});});

missionRouter.get('/admin/mission-daily-performance',requireAdmin,async(req,res)=>{const date=req.query.date||null;const {rows}=await q(`SELECT m.*,u.first_name||' '||u.last_name user_name,r.title role_title FROM mission_daily_progress m JOIN users u ON u.id=m.user_id LEFT JOIN roles r ON r.id=u.role_id WHERE m.progress_date=COALESCE($1::date,CURRENT_DATE) ORDER BY m.weighted_achievement DESC,u.last_name`,[date]);res.json({items:rows});});
missionRouter.get('/admin/mission-visit-report',requireAdmin,async(req,res)=>{const from=req.query.from||null,to=req.query.to||null;const {rows}=await q(`SELECT v.*,u.first_name||' '||u.last_name user_name,r.title role_title,l.code line_code,l.origin,l.destination,EXTRACT(EPOCH FROM (v.finished_at-v.started_at))/60 duration_minutes FROM mission_visit_sessions v JOIN users u ON u.id=v.user_id LEFT JOIN roles r ON r.id=u.role_id JOIN lines l ON l.id=v.line_id WHERE v.started_at::date BETWEEN COALESCE($1::date,CURRENT_DATE) AND COALESCE($2::date,CURRENT_DATE) ORDER BY v.started_at DESC`,[from,to]);res.json({items:rows});});
missionRouter.get('/admin/mission-execution-settings',requireAdmin,async(_req,res)=>res.json({items:(await q(`SELECT * FROM mission_execution_settings ORDER BY setting_key`)).rows}));
missionRouter.put('/admin/mission-execution-settings',requireAdmin,async(req,res)=>{const items=Array.isArray(req.body?.items)?req.body.items:[];const c=await pool.connect();try{await c.query('BEGIN');for(const x of items)await c.query(`INSERT INTO mission_execution_settings(setting_key,setting_value,updated_by,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=now()`,[String(x.setting_key),String(x.setting_value??''),req.user.id]);await c.query('COMMIT');res.json({ok:true});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});

missionRouter.get('/admin/mission-metrics', requireAdmin, async (_req,res)=>res.json((await q(`SELECT * FROM mission_metric_catalog WHERE is_active ORDER BY sort_order`)).rows));
missionRouter.get('/admin/mission-templates', requireAdmin, async (_req,res)=>{const {rows}=await q(`SELECT mt.*,COALESCE(json_agg(json_build_object('metric_key',mtt.metric_key,'target_percent',mtt.target_percent,'weight',mtt.weight,'is_required',mtt.is_required,'minimum_count',mtt.minimum_count) ORDER BY c.sort_order) FILTER(WHERE mtt.id IS NOT NULL),'[]') targets FROM mission_templates mt LEFT JOIN mission_template_targets mtt ON mtt.template_id=mt.id LEFT JOIN mission_metric_catalog c ON c.metric_key=mtt.metric_key GROUP BY mt.id ORDER BY mt.role_key,mt.period,mt.updated_at DESC`); res.json(rows);});
const targetSchema=z.object({metric_key:z.string(),target_percent:z.number().min(0).max(100),weight:z.number().min(0).default(1),is_required:z.boolean().default(true),minimum_count:z.number().int().min(0).nullable().optional()});
const templateSchema=z.object({title:z.string().min(2),role_key:z.enum(['line_supervisor','motor_patrol','vehicle_patrol','resident_inspector','chief_inspector']),period:z.enum(['daily','weekly','monthly']).default('daily'),zone_id:z.number().int().nullable().optional(),is_default:z.boolean().default(true),is_active:z.boolean().default(true),effective_from:z.string().nullable().optional(),effective_to:z.string().nullable().optional(),targets:z.array(targetSchema).min(1)});
missionRouter.post('/admin/mission-templates', requireAdmin, async(req,res)=>{const p=templateSchema.safeParse(req.body); if(!p.success)return res.status(400).json({error:'اطلاعات الگوی مأموریت نامعتبر است',details:p.error.flatten()}); const d=p.data;const client=await pool.connect(); try { await client.query('BEGIN'); const r=await client.query(`INSERT INTO mission_templates(title,role_key,period,zone_id,is_default,is_active,effective_from,effective_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[d.title,d.role_key,d.period,d.zone_id||null,d.is_default,d.is_active,d.effective_from||null,d.effective_to||null,req.user.id]); for(const t of d.targets) await client.query(`INSERT INTO mission_template_targets(template_id,metric_key,target_percent,weight,is_required,minimum_count) VALUES($1,$2,$3,$4,$5,$6)`,[r.rows[0].id,t.metric_key,t.target_percent,t.weight,t.is_required,t.minimum_count??null]); await client.query('COMMIT'); res.status(201).json({id:r.rows[0].id}); } catch(e){await client.query('ROLLBACK'); throw e;} finally {client.release();}});
missionRouter.delete('/admin/mission-templates/:id',requireAdmin,async(req,res)=>{await q(`DELETE FROM mission_templates WHERE id=$1`,[req.params.id]);res.json({ok:true});});
missionRouter.get('/admin/user-mission-overrides',requireAdmin,async(req,res)=>{const params=[];let w='';if(req.query.user_id){params.push(req.query.user_id);w='WHERE o.user_id=$1';}const {rows}=await q(`SELECT o.*,(u.first_name||' '||u.last_name) user_name,COALESCE(json_agg(json_build_object('metric_key',t.metric_key,'target_percent',t.target_percent,'weight',t.weight,'is_required',t.is_required,'minimum_count',t.minimum_count)) FILTER(WHERE t.id IS NOT NULL),'[]') targets FROM user_mission_overrides o JOIN users u ON u.id=o.user_id LEFT JOIN user_mission_override_targets t ON t.override_id=o.id ${w} GROUP BY o.id,u.first_name,u.last_name ORDER BY o.updated_at DESC`,params);res.json(rows);});
missionRouter.put('/admin/user-mission-overrides/:userId',requireAdmin,async(req,res)=>{const p=z.object({period:z.enum(['daily','weekly','monthly']).default('daily'),title:z.string().optional(),is_active:z.boolean().default(true),effective_from:z.string().nullable().optional(),effective_to:z.string().nullable().optional(),targets:z.array(targetSchema).min(1)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'ماموریت اختصاصی نامعتبر است'});const d=p.data;const client=await pool.connect();try{await client.query('BEGIN');const o=await client.query(`INSERT INTO user_mission_overrides(user_id,period,title,is_active,effective_from,effective_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,period) DO UPDATE SET title=EXCLUDED.title,is_active=EXCLUDED.is_active,effective_from=EXCLUDED.effective_from,effective_to=EXCLUDED.effective_to,updated_at=now() RETURNING id`,[req.params.userId,d.period,d.title||null,d.is_active,d.effective_from||null,d.effective_to||null,req.user.id]);await client.query(`DELETE FROM user_mission_override_targets WHERE override_id=$1`,[o.rows[0].id]);for(const t of d.targets)await client.query(`INSERT INTO user_mission_override_targets(override_id,metric_key,target_percent,weight,is_required,minimum_count) VALUES($1,$2,$3,$4,$5,$6)`,[o.rows[0].id,t.metric_key,t.target_percent,t.weight,t.is_required,t.minimum_count??null]);await client.query('COMMIT');res.json({ok:true,id:o.rows[0].id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
missionRouter.delete('/admin/user-mission-overrides/:userId',requireAdmin,async(req,res)=>{await q(`DELETE FROM user_mission_overrides WHERE user_id=$1 AND period=$2`,[req.params.userId,String(req.query.period||'daily')]);res.json({ok:true});});
