{
  "name": "khatyar-mobile",
  "version": "1.3.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "build:apk": "eas build -p android --profile preview",
    "bump": "node bump-version.js",
    "build:release": "node bump-version.js && npx expo prebuild --clean && cd android && gradlew assembleRelease",
    "build:myket": "node scripts/prepare-myket-release.js && npx expo prebuild --platform android --clean && cd android && ./gradlew assembleRelease",
    "build:myket:windows": "node scripts/prepare-myket-release.js && npx expo prebuild --platform android --clean && cd android && gradlew.bat assembleRelease",
    "build:aab": "node scripts/prepare-myket-release.js && npx expo prebuild --platform android --clean && cd android && ./gradlew bundleRelease",
    "prepare:iran": "powershell -ExecutionPolicy Bypass -File .\\prepare-iran-build.ps1",
    "doctor": "npx expo-doctor",
    "build:myket:iran": "powershell -ExecutionPolicy Bypass -File .\\build-myket-release.ps1",
    "check:config-plugin": "node -e \"console.log(require.resolve('@expo/config-plugins')); require('./plugins/withReleaseHardening.js'); console.log('release hardening plugin ok')\"",
    "prebuild:android": "expo prebuild --platform android --clean --no-install"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^2.2.0",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-ml-kit/text-recognition": "^1.5.2",
    "@react-navigation/drawer": "^7.5.0",
    "@react-navigation/native": "^7.1.0",
    "@react-navigation/native-stack": "^7.3.0",
    "dotenv": "^16.4.5",
    "expo": "~57.0.0",
    "expo-application": "latest",
    "expo-battery": "latest",
    "expo-build-properties": "latest",
    "expo-camera": "latest",
    "expo-constants": "latest",
    "expo-device": "latest",
    "expo-font": "latest",
    "expo-image-manipulator": "latest",
    "expo-image-picker": "latest",
    "expo-document-picker": "latest",
    "expo-intent-launcher": "latest",
    "expo-location": "latest",
    "react-native-webview": "^13.16.0",
    "expo-network": "latest",
    "expo-print": "latest",
    "expo-sharing": "latest",
    "expo-notifications": "latest",
    "expo-secure-store": "latest",
    "expo-local-authentication": "latest",
    "expo-av": "latest",
    "expo-status-bar": "latest",
    "expo-task-manager": "latest",
    "react": "19.2.3",
    "react-native": "0.86.0",
    "react-native-gesture-handler": "latest",
    "react-native-reanimated": "latest",
    "react-native-safe-area-context": "latest",
    "react-native-screens": "latest",
    "react-native-view-shot": "3.8.0",
    "expo-file-system": "latest",
    "expo-clipboard": "latest",
    "expo-system-ui": "~57.0.0"
  },
  "devDependencies": {
    "@expo/config-plugins": "~57.0.3"
  }
}
